### ISSUE TITLE
LineSeries with only one or none value not be plotted

### ISSUE THREAD

**Issue by thomasjoscht** [beto-rodriguez/Live-Charts#100]
Hey, I realized that a LineSeries graph will not be (re-) plotted in case that only one or none value exists in collection. This is a little bit messy because in my case wrong (old) graph will be shown after selection of other collection (with only one value). Is it a problem to display a LineSeries graph with only one value?

**Comment by beto-rodriguez** [comment]
But how yo draw a line with only One point?

**Comment by thomasjoscht** [comment]
The simplest solution in my opinion could be for one value a graph with X and Y axes and only one dot at X=0 (labeled) and Y=Value. If no value exists only the X and Y axes (without value labels) will be plotted. Therefore coming from none value, to one value, to two or more values will only enhance graph but not changing the visibility. The graph with axes will be visible all the time.

I've you don't agree also plotting nothing could be fine. But showing old plotted graph after clearing values will not be correct in my opinion. Instead clear graph. Perhaps I will add in my app a property (bool determines values.count>1) for changing visibility of graph and an alternative text like "There is not enough data for graph".

**Comment by beto-rodriguez** [comment]
Ok, I agree with you, I will fix this

**Comment by beto-rodriguez** [comment]
this issue is fixed with multiple comits, now axis are not redrawn every time you change your data, instead the axis are cached and animated the size change, so now the charts should let the axis as tit was drawn before the series has only 1 point. this was done with a large number of commits, practically all of them between version 0.6.5 and 0.6.6
