### ISSUE TITLE
Changing the content of the SeriesCollection on a LineChart does not redraw the chart after first time.

### ISSUE THREAD

**Issue by JRPMike** [beto-rodriguez/Live-Charts#102]
Trying to update the SeriesCollection results in an empty chart after the first time. If I change it to a BarChart and BarSeries, the chart redraws perfectly.

Edit: With the code below, you must resize the window for the chart to show up.

Example below:

```xml
<Window x:Class="LineChartChangingSourceTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="MainWindow" Height="500" Width="525">
    <Grid x:Name="mainGrid">
        <Grid.RowDefinitions>
            <RowDefinition></RowDefinition>
            <RowDefinition Height="25"></RowDefinition>
        </Grid.RowDefinitions>
        <Button Grid.Row="1" Content="go" Click="Button_Click" />
    </Grid>
</Window>
```

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using LiveCharts;

namespace LineChartChangingSourceTest {

  public partial class MainWindow : Window {
    public MainWindow() {
      InitializeComponent();
      Loaded += MainWindow_Loaded;
    }

    LineChart m_chart;
    SeriesCollection m_series;

    void MainWindow_Loaded( object sender, RoutedEventArgs e ) {
      m_chart = new LineChart();
      m_series = new SeriesCollection();
      m_chart.Series = m_series;
      m_chart.AxisY.Title = "Y";
      m_chart.AxisY.MinValue = 0;
      m_chart.AxisY.MaxValue = 1;
      m_chart.AxisX.MinValue = 0;
      m_chart.AxisX.MaxValue = 10;
      m_chart.AxisX.Title = "X";
      mainGrid.Children.Add( m_chart );
    }

    private void Button_Click( object sender, RoutedEventArgs e ) {
      var rand = new Random();
      m_series.Clear();
      for ( int i = 0; i < 10; i++ ) {
        var series = new LineSeries();
        series.Values = new ChartValues<double>();
        for ( int j = 0; j < 10; j++ ) {
          series.Values.Add( rand.NextDouble() );
        }
        m_series.Add( series );
      }
    }
  }
}
```

PS. Sorry... Not sure how to get the formatting on the code blocks right. Also, thank you for this library! It's great!

**Comment by beto-rodriguez** [comment]
Helped you with the format, here is a good article in case you are interested: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

I will investigate the issue soon.

**Comment by beto-rodriguez** [comment]
this bug was only heppening because a simple If I added, IF series.Count == 0 then do not initialize series. I am testing if removing this if brakes something.

**Comment by beto-rodriguez** [comment]
After testing that line was unnecessary and causing this issue.

Added this case to a new debug section 

https://github.com/beto-rodriguez/Live-Charts/tree/master/WPFExamples/z.DebugCases

![untitled](https://cloud.githubusercontent.com/assets/10853349/14393578/5258da4e-fd8d-11e5-8a1c-fe3e7132bdba.png)

**Comment by DLinser** [comment]
I  find another solution. It is try to use chart.Series.Clear(); and chary.Series = your  SeriesCollection; 
Like:
`<lvc:CartesianChart  Name="WENDU"/>

if (WENDU.Series!=null)
            {
                WENDU.Series.Clear();
                WENDU.Series = TempeterSeriesCollection;
            }
`
It is also works.
