### ISSUE TITLE
Default Axes override user axis

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#106]
As said on gitter there are some cases where the default axis created in chart constructor's overrides user defined axis

**Comment by RobMalvern** [comment]
Hi Beto, I believe I have run into this problem - is there a work around known at the moment?

Thanks very much!

**Comment by beto-rodriguez** [comment]
Hi, I am working on this issue today, I hope its fixed soon


El martes, 29 de marzo de 2016, RobMalvern <notifications@github.com>
escribió:

> Hi Beto, I believe I have run into this problem - is there a work around
> known at the moment?
>
> Thanks very much!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/beto-rodriguez/Live-Charts/issues/106#issuecomment-202879230>
>


-- 
Alberto Rodríguez O.

**Comment by RobMalvern** [comment]
Awesome thanks! :+1:

**Comment by beto-rodriguez** [comment]
This should be fixed with last commit https://github.com/beto-rodriguez/Live-Charts/commit/17680c221c605ccf398c817a99c70fcea58bf67e#diff-52175f84455c06cbc258edc68a1348c0R105

Testing and closing when I am completely sure.

**Comment by RobMalvern** [comment]
This is fixed in the most recent version, but the background of the charts always seems to be light green. Is this expected?

**Comment by beto-rodriguez** [comment]
It is fixed, but  0.6.6 is not published yet, the green color just helps me in the debug process, this will be released with 0.6.6 I will publish it here https://github.com/beto-rodriguez/Live-Charts/releases and also you will see the available package in Nuget, it is almost ready
