### ISSUE TITLE
Allow user to control shapes ZIndex

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#107]
The filled line chart seems backwards when viewing the legend.

![croppercapture 3](https://cloud.githubusercontent.com/assets/2676804/14049519/c414ccd4-f283-11e5-9e00-cd0af1459ba6.png)

Looking at the legend, I'd expect that Profit would appear on top in the graph, but since it's drawn first, the effect is that it's on the bottom.  I think this can be resolved by simply reversing the list for the legend.

I don't know if this is a bug or if it should be an option.  I think it would make more sense.

**Comment by gregsdennis** [comment]
Then again, when swapping the series, it seems to look right...

![croppercapture 4](https://cloud.githubusercontent.com/assets/2676804/14049659/a3a076d2-f284-11e5-8387-b2f534bd839e.png)

Here it seems right that the larger number is on top in the legend even though it's in the back.

**Comment by beto-rodriguez** [comment]
I think we can fix this if we pass the series Panel.ZIndex property to the drawn area, this way you  will be able to custom which area is on top, even dynamically. something like:

```xml
<lvc:LineSeries Values="1, 5, 8" Panel.ZIndex="1" />
```

**Comment by gregsdennis** [comment]
I like that idea.

**Comment by beto-rodriguez** [comment]
now you can
```xml
<lvc:LineSeries Values="0, 0, 0" Panel.ZIndex="1" />
<lvc:LineSeries Values="10, 10, 10" Panel.ZIndex="2" />
``

or  change the order

```xml
<lvc:LineSeries Values="0, 0, 0" Panel.ZIndex="2" />
<lvc:LineSeries Values="10, 10, 10" Panel.ZIndex="1" />
``

this should also work dinamically
