### ISSUE TITLE
Line chart not redrawing on series collection reset

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#108]
The canvas clears and the axes are redrawn, but nothing else is.

It looks like the `DrawMargin` canvas isn't being added back to the main Canvas.

**Comment by gregsdennis** [comment]
Add these two lines

    chart.DrawMargin.Children.Clear();
    chart.Canvas.Children.Add(chart.DrawMargin);

here

https://github.com/beto-rodriguez/Live-Charts/blob/master/LiveChartsCore/CoreComponents/Chart.cs#L1152

I don't know what that might break, but it fixes this problem.

**Comment by beto-rodriguez** [comment]
@gregsdennis Ok, I will test
