### ISSUE TITLE
Display series names and colors chart

### ISSUE THREAD

**Issue by lrmills85** [beto-rodriguez/Live-Charts#11]
It would be great if I could name a serie so if I have multiple series it will show the value and the name

**Comment by beto-rodriguez** [comment]
Thats good, and add a chart info control to the project so you can bind series to it. 
![image](https://cloud.githubusercontent.com/assets/10853349/10119947/b54f6368-646b-11e5-8b99-b9262933847f.png)

**Comment by lrmills85** [comment]
Is this live yet?

**Comment by beto-rodriguez** [comment]
yes

**Comment by lrmills85** [comment]
I have 0.3.0 but I am not seeing where I can set this. Can you help?

**Comment by beto-rodriguez** [comment]
This is not included yet, but is an easy one, I will try to commit this in a moment, it is an open source project, you can create pull request too to make this better :)

**Comment by beto-rodriguez** [comment]
Closed with https://github.com/beto-rodriguez/Live-Charts/commit/dd6de35adbb5583fa9c250d4f49b47b5eebabea9, I included an example in the first charts on the wpf test project, it is a simple control.

**Comment by beto-rodriguez** [comment]
![image](https://cloud.githubusercontent.com/assets/10853349/10238027/677987c8-687f-11e5-9f5a-a481b003376c.png)

**Comment by mazvis00** [comment]
How do I add legend in c# not in xaml? I trying to add it in winforms, any pointers how to do it?

**Comment by beto-rodriguez** [comment]
What do you mean with a legend?

**Comment by Trass3r** [comment]
Your "SeriesViewer" is usually called a legend: http://www.mathworks.com/help/matlab/ref/legend.html#bt6ef_q-2_1
"SeriesViewer" really doesn't describe its function very well.

**Comment by beto-rodriguez** [comment]
will rename, thanks
