### ISSUE TITLE
Compatibility with UWP

### ISSUE THREAD

**Issue by Osyrus** [beto-rodriguez/Live-Charts#112]
When installing this on a new UWP project in an updated Visual Stupid Community I got this error: "LiveCharts 0.6.5 is not compatible with UAP,Version=v10.0 (win10-x86-aot).".

**Comment by beto-rodriguez** [comment]
Right now this library only works for wpf and winforms maybe if it gets enough support we can extend it to uwp, Xamarin or even js. Time will tell

**Comment by beto-rodriguez** [comment]
I am not really sure if you can install a wpf control in a uwp project
