### ISSUE TITLE
If series are added to front (series.Values.Insert(0,new ...)), you know the rest

### ISSUE THREAD

**Issue by Umbalas** [beto-rodriguez/Live-Charts#113]
If values are added to front (series.Values.Insert(0,new ...)), you know the rest
0.6.5.0

Really fun drawing magic appears.

**Comment by Umbalas** [comment]
Also, how should your lib support this situation: if values are added not in a row, lets say per x axis - 1,2,3,1 again ! Guess this might not be a real use case, but this might explain that fun drawing bug you were asking about https://github.com/beto-rodriguez/Live-Charts/issues/91

**Comment by beto-rodriguez** [comment]
> if values are added not in a row, lets say per x axis - 1,2,3,1 again

please explain me more, maybe you are seeing the bug and I can't, the library does not tracks by the X value, it tracks in 2 different ways simple and complex, 

simple: when using primitive types, the library tracks by the position of the value in the array, so it means "row, lets say per x axis - 1,2,3,1 " no, no I only track the position of the item so for me they are only "0, 1, 2, 3, 4".

complex: by object reference ID, when you use a class LiveCharts is able to track everything much better and animations should be improved.

> If values are added to front (series.Values.Insert(0,new ...)), you know the rest
0.6.5.0

No I don´t know the rest, please let me know what happens, also you should be using 0.6.5 or less, any not published package is not ready yet.
