### ISSUE TITLE
How to change the color filled in the plot area in the LineChart?

### ISSUE THREAD

**Issue by adwardy** [beto-rodriguez/Live-Charts#114]
The version of the LiveCharts used by me is 0.6.5.1.
The default color of the plot area of LineChart is green.
I wonder how to change the color filled in the plot area in a LineChart.
Changing the background property does not work.
Thank you very much!

**Comment by beto-rodriguez** [comment]
0.6.5.1 is the version I am working with to publish 0.6.6 you should not use it, it is a debug version the green color helps me to debug, please use 0.6.5 when 0.6.6 is ready I will announce it here https://github.com/beto-rodriguez/Live-Charts/releases also you will see it in nuget

**Comment by adwardy** [comment]
OK. Thanks very much!
