### ISSUE TITLE
Measuring Cursor for Chart Axis

### ISSUE THREAD

**Issue by Nick135** [beto-rodriguez/Live-Charts#115]
Is there a cursor for the X- and Y-Axis?
Like the CursorX, CursorY of the MS chart control?

chart1.ChartAreas[0].CursorX.IsUserSelectionEnabled
(The User can set the position of the cursor)

chart1.ChartAreas[0].CursorX.Position
(Actual position of the cursor or set the position of the cursor)

**Comment by beto-rodriguez** [comment]
I am afraid I don't understand what you mean, I have searched for this in MS Charts
 but I have not found what you mean

**Comment by Nick135** [comment]
https://msdn.microsoft.com/de-de/library/system.windows.forms.datavisualization.charting.cursor(v=vs.110).aspx

Hinweise
A cursor is a horizontal or vertical line that defines a position along an axis. A range selection is a range along an axis that is defined by a beginning and end position, and is displayed using a semi-transparent color.
Cursors and range selections are both implemented by the Cursor class, which is exposed as the CursorX and CursorY properties of the ChartArea object. The CursorX object is for the X axis of a chart area, and the CursorY object is for the Y axis. The AxisType property of these objects determines whether the associated axis is primary or secondary.
The only cursor and range selection functionality found outside the Cursor class are the events related to the cursor and range selection that are in the root Chart object.

![image](https://cloud.githubusercontent.com/assets/14072733/14341207/dad4c6c0-fc8f-11e5-85f8-dd5e9a953208.png)

**Comment by pusaken** [comment]
I would like to strongly support that request, with the need of being able to set this cursor by code or mouse click.
In case of mouse click a corresponding event should fire, supplying the reference to the selected data item / location.

**Comment by catacon** [comment]
I agree, this is one of the most useful features of MSCharts.  It can make zooming very natural.

This is a good example with the ability to select a range on the x-axis: http://www.highcharts.com/demo/line-time-series

**Comment by beto-rodriguez** [comment]
Ok definitely I am fixing zooming and panning, for 0.6.7 and I will check how this should be implemented in LiveCharts

**Comment by beto-rodriguez** [comment]
this is already supported, please let me know your opinion I have never used MS Charts

here is an example 

https://github.com/beto-rodriguez/Live-Charts/tree/master/WPFExamples/Line%20Examples/ZoomingPanningAndCursor

All you need to do is `Chart.CursorX.Value = 10` set it to null to delete it.

you can also style the cursor for example `Chart.CursorX.Shape.Fill = Brushes.Red;`

<img src="https://cloud.githubusercontent.com/assets/10853349/14480111/65c18a98-00eb-11e6-8ce2-bc7cf3d0fdfc.gif" />

**Comment by pusaken** [comment]
The cursor is working so far, but the behavior on pan and zoom is a little odd: I think the cursor should either follow the data(point) or it should at least be cleared on pan/zoom...

**Comment by pusaken** [comment]
There already is a way to make the cursor follow:
You can store the Datapoint somewhere globally, and as soon as the the event "LayoutUpdated" of the chart fires, you can readjust the CursorX.Value and the CursorY.Value:

VB code below:
```vb
Private m_CursorPointL1 As LiveCharts.CoreComponents.ChartPoint

Private Sub LCLaser1_DataClick(ByVal obj As LiveCharts.CoreComponents.ChartPoint) Handles LCLaser1.DataClick

	m_CursorPointL1 = obj

End Sub


Private Sub LCLaser1_LayoutUpdated(ByVal sender As Object, ByVal e As System.EventArgs) Handles LCLaser1.LayoutUpdated
        If Not m_CursorPointL1 Is Nothing Then
            LCLaser1.CursorX.Value = m_CursorPointL1.X
            LCLaser1.CursorY.Value = m_CursorPointL1.Y
        End If
End Sub
```

**Comment by beto-rodriguez** [comment]
@pusaken I agree with you, or even better internally the ChartCursor object has a method called Update, I just need to call it when you zoom or pan, so the cursor is updated!

**Comment by beto-rodriguez** [comment]
I am closing this issue, in 0.7.0 now the axis has a new property Axis.Separators, you can actually add as many separators as required, you can highlight range values, or just a simple line as requested here, I called them Separators because they are more than cursors in this library here is an example: (will explain more in the release of 0.6.7)

```xml
<lc:CartesianChart Grid.Row="2" Series="{Binding SeriesCollection}" >
            <lc:CartesianChart.AxisY>
                <lc:Axis>
                    <lc:Axis.Sections>
                        <lc:AxisSection FromValue="8" ToValue="8" StrokeThickness="3" Stroke="red">
                            <lc:AxisSection.Fill>
                                <SolidColorBrush Color="#A3A3FF" Opacity=".4"></SolidColorBrush>
                            </lc:AxisSection.Fill>
                        </lc:AxisSection>
                        <lc:AxisSection FromValue="4" ToValue="8" Label="Good">
                            <lc:AxisSection.Fill>
                                <SolidColorBrush Color="#CDCDCD" Opacity=".4"></SolidColorBrush>
                            </lc:AxisSection.Fill>
                        </lc:AxisSection>
                        <lc:AxisSection FromValue="0" ToValue="4" Label="Bad">
                            <lc:AxisSection.Fill>
                                <SolidColorBrush Color="#FF8585" Opacity=".4"></SolidColorBrush>
                            </lc:AxisSection.Fill>
                        </lc:AxisSection>
                    </lc:Axis.Sections>
                </lc:Axis>
            </lc:CartesianChart.AxisY>
        </lc:CartesianChart>
```


![separators](https://cloud.githubusercontent.com/assets/10853349/15279579/73ad355c-1aeb-11e6-9e4d-c59c5a8f58c8.gif)

**Comment by NeraV** [comment]
I don't see the CursorX and CursorY property on the chart. I really need it... Why is it gone and the example PanningAndZooming changed ?
