### ISSUE TITLE
Zooming and Panning not working

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#117]
Merging #97 and #111, I will try to explain what is going on here, zooming an panning are not working in 0.6.5 and wont work in the future 0.6.6 release

**Why?**

Zooming, Panning and High performance charts are directly related to how the charts are drawn the last releases have been really hard and now as you might see LiveCharts behave much better, all shapes are cached, in previous version everything was redrawn every time, this will improve the performance of the library a lot also improved animations, sadly in previous reelase (0.6.5) I only focused in improving the animations not the features (zooming and panning) because I knew I had to fix #21 and this will drop again the zooming and panning functionality. the good news it that #21 is already supported (will be released with 0.6.6) and I don't see any other feature that could affect zooming and panning again.

**When will zooming and panning work?**

in my experience I have rewritten zooming, panning and high performance too many times that I really don´t want to fix it until all major changes are done,. The good news is that I think we already built all the major enhancements, I would like to tell you that next release will be about fixing these 2 functionalities, but I can't promise that.

**Comment by beto-rodriguez** [comment]
Zooming and panning are now working, here is an example 

https://github.com/beto-rodriguez/Live-Charts/tree/master/WPFExamples/Line%20Examples/ZoomingPanningAndCursor

this is the result

<img src="https://cloud.githubusercontent.com/assets/10853349/14480111/65c18a98-00eb-11e6-8ce2-bc7cf3d0fdfc.gif"/>

**Comment by AchimHaller** [comment]
Hey Beto,
Thank you very much, awesome work. 
I can not find the ZoomingPanningAndCursor example on GitHub and the link above dead, could you please update the link.
Thank you very much!!

**Comment by beto-rodriguez** [comment]
@AchimHaller Hi, I think I renamed the sample to:

https://lvcharts.net/App/examples/v1/wpf/Zooming%20and%20panning

It had suffered some modifications already, the site pulls the samples from the repo

https://raw.githubusercontent.com/beto-rodriguez/Live-Charts/master/Examples/Wpf/CartesianChart/ZoomingAndPanning/ZoomingAndPanning.xaml.cs

**Comment by AchimHaller** [comment]
@beto-rodriguez  Hi, thanks for the quick answer.
Yes I found this sample in Git, what I meant is the Zooming and Panning sample that has the **cursor** function included, this I couldn't find.
Thanks for your help in advanced!

**Comment by hruslowkirill** [comment]
But Zooming doesn't work with Visual Elements. If I zoom, Visual Elements behave very strangely. I'm trying to put a background image under the plot, but it seems that it's not possible with this library
