### ISSUE TITLE
hover popup should have optional timeout

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#118]
I have several charts on a single screen.  The popup should either hide when another shows or have a timeout and hide on its own.  This could be a property on the chart to let the user decide.
![croppercapture 1](https://cloud.githubusercontent.com/assets/2676804/14392024/f0d5dacc-fd84-11e5-8ef7-13a299bf444b.png)

**Comment by beto-rodriguez** [comment]
the popup has its own timer, it should hide by it´s own when the times is ticks, I will take a look, also to #41

**Comment by beto-rodriguez** [comment]
Just added the new property TooltipTimeout:

from code behind:

```c#
myChart.TooltipTimeout = TimeSpan.FromMilliseconds(100);
```

from XAML (in milliseconds)

```xml
<liveCharts:PieChart 
                             Series="{Binding myModel.Series}"
                             TooltipTimeout="10"/>
```

set it to a short interval, so the tool tip will disappear when the user removes the mouse from the data point

**Comment by gregsdennis** [comment]
Is the time configurable?  If not, it should be.

**Comment by yurigaid** [comment]
Hi, I am using the latest version (0.9.7) of LiveCharts (with Geared 1.2.8.2)  and the chart tooltips do not go away by themselves, they stay indefinitely.  I tried using ToolTipTimeout property, but is has no effect.
Any advice how to make the tooltips close automatically?

Thanks,

Yuri
