### ISSUE TITLE
Pie Chart rendering incorrectly

### ISSUE THREAD

**Issue by GorelH** [beto-rodriguez/Live-Charts#123]
![screenshot 1](https://cloud.githubusercontent.com/assets/8646184/14426324/1eb785c2-ffe6-11e5-8c3c-b5c2a64fd40a.png)

version="0.6.6.0"  targetFramework="net461"   windows 10

**Comment by beto-rodriguez** [comment]
Hello, thanks, I need more info about this error, can I please see your code or even better can you create a repo with the error?

Thanks again

**Comment by GorelH** [comment]
Hi i found out it was because of negative value

**Comment by beto-rodriguez** [comment]
Nice, glad you found it
