### ISSUE TITLE
Non-equidistant X-Axis for LineCharts - or - The XY-Plot

### ISSUE THREAD

**Issue by pusaken** [beto-rodriguez/Live-Charts#124]
Hi,

for my charting application I am looking for a way to plot data which is no time based, equidistant series, but a collection of X/Y Points.
As far as I understood Live-Charts, there is currently no way of achieving this.
If so, I'd like to open a feature request for the X/Y plot.

Regards,
Pusaken

**Comment by beto-rodriguez** [comment]
it does, it is the default configuration 

https://github.com/beto-rodriguez/Live-Charts/tree/master/WPFExamples/Line%20Examples/Basic

**Comment by beto-rodriguez** [comment]
LiveCharts should be able to plot anything please let me see what yo have tried, this should be already supported

**Comment by pusaken** [comment]
Wow, OK. My bad.
You ARE great :-). I think I just discovered a new world. From what I understand (now) LineCharts is able to plot whatever object, as long as I provide a mechanism to derive X and Y coordinates from that object. IS THAT TRUE?
You just saved me days of coding...

Thanks!

And BTW Thanks for fixing pan and zoom so quickly :-).

**Comment by beto-rodriguez** [comment]
Yes LiveCharts can plot anything! 

I think I need to improve documentation to explain it better
