### ISSUE TITLE
Old DataLabels don't disappearafter refreshing

### ISSUE THREAD

**Issue by panhans** [beto-rodriguez/Live-Charts#129]
When working with live data, DataLabels won't disappear after updating series values.

![image](https://cloud.githubusercontent.com/assets/4427249/14555249/d4a40dc0-02f1-11e6-84ae-a95348356b21.png)

**Comment by beto-rodriguez** [comment]
Thanks for reporting, sorry about this, many changes happened in previous  versions, fixing asap

**Comment by beto-rodriguez** [comment]
this is fixed now andshow never happen again in 0.7.0 it is design-impossible.
