### ISSUE TITLE
PieChart only works with double values

### ISSUE THREAD

**Issue by panhans** [beto-rodriguez/Live-Charts#130]
PieChart only works with double values. No visualization when using e.g. interger.

`

            //create some series
            var charlesSeries = new PieSeries
            {
                Title = "Charles",
                Values = new ChartValues<int> { 10 }
            };
            var jamesSeries = new PieSeries
            {
                Title = "James",
                Values = new ChartValues<int> { 5 }
            };
            var mariaSeries = new PieSeries
            {
                Title = "James",
                Values = new ChartValues<int> { 7 }
            };

            //add series to SeriesCollection
            this.BarSeries.Add(charlesSeries);
            this.BarSeries.Add(jamesSeries);
            this.BarSeries.Add(mariaSeries);
`

**Comment by gregsdennis** [comment]
I've mentioned this before. We do financial data, so we use decimal.  It's not a big deal to cast to double, but it is a bit confusing when the collection is generic.

**Comment by beto-rodriguez** [comment]
If you configure the series collection to plot integers t will work, for example

```c#
this.BarSeries = new SeriesCollection(new SeriesConfiguration<int>().Y(value => (double) value));

this.BarSeries.Add(charlesSeries);
this.BarSeries.Add(jamesSeries);
this.BarSeries.Add(mariaSeries);
```

because of the confision here, one option could be that default mapper does always this double cast, and in case you need a high performance chart I will add a note to remove this dummy cast

**Comment by beto-rodriguez** [comment]
After thinking about it, this happens because SeriesCollections tries to cast as SeriesConfiguration<T> since T by default is double, and you passed and integer, the cast fails and no mapper is set.

I could actually just just this ugly mapper `new SeriesConfiguration<object>().Y(val => (double) val);` when the cast fails, and also add a note to this behavior.

**Comment by beto-rodriguez** [comment]
@gregsdennis I finally found a way to make livecharts available in more platforms, and I am making a full review of the code, this is what I meant

https://github.com/beto-rodriguez/Live-Charts/commit/4922ca4755fc3285cf2d4a5903241942b5496d23#diff-281d4016347e3e7a546627088ecb9718R55

any help and comments are appreciated

**Comment by beto-rodriguez** [comment]
Now the charts are smart enough to configure, 0.6.x introduced the ability to plot any type, 0.7.0 make this automatically, forget about SeriesConfiguration, the charts will handle it
