### ISSUE TITLE
sometimes when mouse click with no intention, may cause some problem

### ISSUE THREAD

**Issue by xWulitou** [beto-rodriguez/Live-Charts#131]
the error location is in LineChart.cs  line 117. code as below:

if (ShapeHoverBehavior == ShapeHoverBehavior.Dot)
                {
                    sibiling.Shape.Stroke = sibiling.Series.Stroke;
                    sibiling.Shape.Fill = new SolidColorBrush { Color = PointHoverColor };
                }

the property Shape of sibiling is null.

**Comment by beto-rodriguez** [comment]
Hello and thanks for reporting. I am fixing this asap.

Thanks again

**Comment by beto-rodriguez** [comment]
This is already fixed, I am sorry about this error, actually I unlisted 0.6.7 version from nugget because of this dummy bug.
