### ISSUE TITLE
Feature request: allow data points to have different colours

### ISSUE THREAD

**Issue by zelenij** [beto-rodriguez/Live-Charts#135]
It would be nice to be able to have different colours for different points in the same LineSeries.  Maybe an easy way to achieve this would be through enhancing the model of a data point - maybe derriving it from a specific interface.  The same approach probably could be taken to provide other custom things for a point, such as tooltip?

Original SO discussion: http://stackoverflow.com/questions/36770867/how-to-add-per-point-tooltips-in-livecharts-how-to-have-different-colours-for-p/36771023

**Comment by beto-rodriguez** [comment]
I can imagine changing the color of each point, but I am not sure about having more than 1 tooltip in a chart, I think you can achieve this if you change your design a bit.

	
Do you imagine you self having 1,000 points and creating 1,000 tooltips? instead I would recommend you to not plot only double X and Y values, intstead plot a DTO (data transfer object) which can hold all the different properties, and then your tooltip control can display different information according to this DTO that is really easy with WPF if you need some help I am here.

**Comment by zelenij** [comment]
Well, in my particular case I doubt there should be thousands of points.  However, I am happy to use DTO to achieve my goal - do you happen to have some links at hand that demonstrate your approach?

**Comment by beto-rodriguez** [comment]
this can guide you http://lvcharts.net/#/examples/v1/genericline-wpf?path=WPF-Generic if you have any troubles I can help you

**Comment by zelenij** [comment]
Thanks for the link. To be honest, I don't see how I can do what I want based on that.  However, I found an easier solution, which suits me just fine - I display a tooltip on clicking the data point.

My only issue now is that the whole line tooltip is still displayed, and now it's not needed and even obstructive.  Is it possible to disable it?

**Comment by beto-rodriguez** [comment]
Try Chart.Hoverable= false to disable tooltips

**Comment by zelenij** [comment]
This works insofar as disable the tooltip goes.  However, it also prevents the DataClick event from being fired.  Wouldn't you consider it a bug?

**Comment by beto-rodriguez** [comment]
Yes, I will open a new issue based on this, thanks!

**Comment by beto-rodriguez** [comment]
About the issue with DataTooltip and Hoverable, it is fixed in 0.7.0, this version will be released soon, about the multiple colors I will keep track of that issue at #162,

Thanks!
