### ISSUE TITLE
Autosize on chart doesn't seem to work

### ISSUE THREAD

**Issue by lrmills85** [beto-rodriguez/Live-Charts#14]

**Comment by beto-rodriguez** [comment]
Can you please provide more info, like when it happens Thanks!

**Comment by lrmills85** [comment]
If I set the width and height to Auto and no matter what the alignment is, the view always looks like this

![image](https://cloud.githubusercontent.com/assets/14826876/10212796/66b0d6e6-67d2-11e5-9592-e79baf6db915.png)


If I set a minimum width of 300 and minimum height of 125 I get this

![image](https://cloud.githubusercontent.com/assets/14826876/10212819/a897d03c-67d2-11e5-821e-59d322ad5e3c.png)

Also, you will notice the other bug with the labels duplicating

**Comment by beto-rodriguez** [comment]
About the sizing, this library does not modifies any size property, it only inherits from user control, I think it is an error in your code, the labels bug I am not able to reproduce it.

**Comment by lrmills85** [comment]
ok, let me take a look and see what I can find

**Comment by beto-rodriguez** [comment]
did you solve this problem so I can close this issue?

**Comment by beto-rodriguez** [comment]
closing issue since no more info
