### ISSUE TITLE
binding to a serie with twice the same coordinates points fail

### ISSUE THREAD

**Issue by mgth** [beto-rodriguez/Live-Charts#143]
`var config = new SeriesConfiguration<GradientLine>()
                   .Y(g => g.ValueY)
                   .X((g, index) => g.ValueX);`

throws 'NaN;105.6' is not a valid value for 'From' property. 
when two points share the same coordinates.

**Comment by mgth** [comment]
Disallowing animations as a workaround did it.

**Comment by beto-rodriguez** [comment]
Thanks for reporting, will test and fix in next release

**Comment by mgth** [comment]
Ok, thank you for the advice

**Comment by mgth** [comment]
Seems to be fixed in 0.7
