### ISSUE TITLE
LineChart, first point start a bezier line from 0.0

### ISSUE THREAD

**Issue by mgth** [beto-rodriguez/Live-Charts#145]
![chart](https://cloud.githubusercontent.com/assets/2568124/15038753/ea0a722a-12a6-11e6-833b-ce07077a45f8.png)
The chart recover ok when clicking on any point or resizing whole window.

**Comment by beto-rodriguez** [comment]
This is really strange, I will try with 0.7 (in progress version) when it relesaed please let me know if you still face this issue

**Comment by mgth** [comment]
ok, no problem, thanks for helping.

**Comment by IgorTheRussian** [comment]
Does happen to me as well in the latest version !

**Comment by beto-rodriguez** [comment]
@IgorTheRussian Thanks for the feedback, I just disabled 0.6.7 from nuget since it was just a performance release and its kind of buggy, and 0.7 release is really close!

**Comment by mgth** [comment]
Doesn't happen in 0.7 alpha, good job ! 
(but could not find how I can set smoothness to 0 now)
