### ISSUE TITLE
Crash when trying to plot these values

### ISSUE THREAD

**Issue by IgorTheRussian** [beto-rodriguez/Live-Charts#146]
I have this error : 

>  System.ArgumentOutOfRangeException
>  at MS.Utility.FrugalStructList`1.Insert(Int32 index, T value)
>    at System.Windows.Media.PathSegmentCollection.Insert(Int32 index, PathSegment value)
>    at LiveCharts.Cache.LineVisualPoint.Animate(Int32 index, Chart chart, Int32 pathOffset, TimeSpan speed)
>    at LiveCharts.LineSeries.Plot(Boolean animate)
>    at LiveCharts.CoreComponents.Chart.UpdateModifiedDataSeries(Object sender, EventArgs e)

when I try to plot these values (it works if you remove any line!) :
```

Series[0].Values.Add(new Point(1462545105, 54.15));
Series[0].Values.Add(new Point(1462545105, 54.15));
Series[0].Values.Add(new Point(1462545105, 54.15));
Series[0].Values.Add(new Point(1462545105, 54.15));
Series[0].Values.Add(new Point(1462545106, 54.15));
Series[0].Values.Add(new Point(1462545106, 54.15));
Series[0].Values.Add(new Point(1462545192, 54.22));
```

It crashes as well when i put these values in your example IrregularLine.xaml

**Comment by IgorTheRussian** [comment]
Hmm maybe it's similar with #143 ?

**Comment by beto-rodriguez** [comment]
could be, I will test with 0.7 before the release, 0.7 has a new algorithm for line series, it is much more stable and fixed many reported issues

**Comment by beto-rodriguez** [comment]
Yeah, look like is the same as #143 I am closing the issue, 0.7.0 version should never send an invalid value (double.nan) to the view, in this case WPF
