### ISSUE TITLE
Hiding legend

### ISSUE THREAD

**Issue by bad-samaritan** [beto-rodriguez/Live-Charts#148]
Hello,

Is there something we can do with this floating legend considering location on screen - like moving to left when close to edge?

![chartlivebug](https://cloud.githubusercontent.com/assets/5952068/15141997/407af2e2-16a3-11e6-86c0-c11e1cd71f93.png)

**Comment by beto-rodriguez** [comment]
Hello, I guess you are using 0.6.7, that version has a lot of bugs, I actually un listed it in nuget, please try 0.6.6 or even safer 0.6.4, I am reviewing all the code and working in 0.7 version.

**Comment by bad-samaritan** [comment]
Yes, I got mine from NuGet. 
I'm really looking forward to see next versions, can't wait to use StackedBarChart!

**Comment by beto-rodriguez** [comment]
This is already fixed in 0.7.0, this version should be publish today
