### ISSUE TITLE
I have a bar chart with a set width of 300, but hover pop-up comes off the screen

### ISSUE THREAD

**Issue by lrmills85** [beto-rodriguez/Live-Charts#15]
![image](https://cloud.githubusercontent.com/assets/14826876/10212748/a662e0dc-67d1-11e5-88be-fa018b06e4ef.png) - This shows the problem

![image](https://cloud.githubusercontent.com/assets/14826876/10212756/be9ad52e-67d1-11e5-80c4-c496ef92c1d7.png) - This one works

**Comment by beto-rodriguez** [comment]
this should solve the problem, thank for reporting
