### ISSUE TITLE
Setting MinValue, MaxValue of Axis won't work

### ISSUE THREAD

**Issue by mgth** [beto-rodriguez/Live-Charts#153]
Y Axis range is still automatically set.
Actually I need 0-100% range but it is still set to -20 120 after setting MinValue to 0 and MaxValue to 100.

works well for X axis

**Comment by beto-rodriguez** [comment]
You are using 0.7.0 right? I m fixing this now, and facing this issue for zooming and panning, max and min limits are being ignored in 0.7.0

**Comment by beto-rodriguez** [comment]
This should be now fixed, with zooming and pannig commits to 0.7.0 please let me know if you still facing this issue.
