### ISSUE TITLE
Allow labels rotation, and force the chart to display all labels

### ISSUE THREAD

**Issue by rohit3d2003** [beto-rodriguez/Live-Charts#157]
Is there a way to wrap the labels around X-axis or may be rotate them so they show up properly. I have a situation where the labels are overlapping each other since the text is too large for them

**Comment by beto-rodriguez** [comment]
You can use multi line labels, I think is the best option for now, in a future we can try rotating the labels.

use ` Environment.NewLine` in code behind, or with XAML you can `<TextBlock Text="Stuff on line1&#x0a;Stuff on line 2"/>`

**Comment by rohit3d2003** [comment]
It is still not working out completely. The text is always aligned to left instead of appearing in center and when the bar chart have many bars to display in small area, the label only appears for alternate bar. I saw a demo where user can navigate to next bar by clicking on '>' but I am not sure how to do it.

**Comment by beto-rodriguez** [comment]
I see, it happens because the charts tries to optimize the number of labels by default, I think this should be customizable, both rotating the labels, and forcing the chart to display all labels, will add this feature soon.

**Comment by rohit3d2003** [comment]
I tried inverting the bar chart to display full labels but that also didn't work. The labels didn't appear on UI at all. Not sure if there is an interim solution for this else I will try to abbreviate the names

**Comment by beto-rodriguez** [comment]
There is no way to solve this for now, I will fix it soon, Thinking in a property for the axis called DisplayLabelsMode, and the options would be None (hide labels), Auto (the current behavior), ShowAll (will rotate the labels if there is not enough space to display them all).

**Comment by rohit3d2003** [comment]
Appreciate your help! Let me know if I can be of any help.
Hoping to see the next release soon..

**Comment by beto-rodriguez** [comment]
@rohit3d2003 trust me me too! its a huge release, it should be a production-ready release, I hope it is stable enough to build the 1.0 version

**Comment by rohit3d2003** [comment]
This is the only issue that's preventing me from using this library. Is this targeted for next release?

**Comment by beto-rodriguez** [comment]
I can not grant a date, but yes this will be included soon, the library is growing really fast, you must see and try a 0.5.x version (a couple of months ago) to see the difference :smile:

**Comment by beto-rodriguez** [comment]
This is already supported

Force the separator step to 1, so all labels will be always visible,
then set the Axis.LabelsRotateTransform property, you can use any angle, I recommend a small angle (less than 20 degrees).



```xml

<lvc:CartesianChart Grid.Row="2" Series="{Binding SeriesCollection}" 
                            DataClick="Chart_OnDataClick" >
            <lvc:CartesianChart.AxisX>
                <lvc:Axis LabelsRotateTransform="{Binding RotateTransform}" Labels="{Binding Labels}">
                    <lvc:Axis.Separator >
                        <lvc:Separator IsEnabled="False" Step="1"></lvc:Separator>
                    </lvc:Axis.Separator>
                </lvc:Axis>
            </lvc:CartesianChart.AxisX>
        </lvc:CartesianChart>
```

```c#
RotateTransform = new RotateTransform(13);
```

here is the example running in the repo 

https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart/Bar

![rotated](https://cloud.githubusercontent.com/assets/10853349/15623190/d8213c5a-2436-11e6-9b41-5e5c563f6115.png)

**Comment by rohit3d2003** [comment]
This looks cool. Will it be possible to align the text at the center of the bar. Right now it is still confusing since the bar appear at the center of the text whereas the text should start/end at the center of the bar when rotated. For example, in the above scenario, Shea should start at the center of the first bar OR Ferriera should end at the center of the bar.

**Comment by beto-rodriguez** [comment]
Yes it needs an improvement, actually it is not working correctly when you rotate the labels in the Y axis

**Comment by rohit3d2003** [comment]
Are you planning to make it cleaner as part of 0.7.1 release?

**Comment by beto-rodriguez** [comment]
I don't think so, because I had many troubles building the new web site examples with 070, so many of them actually do not work with 070 I need to publish 071 soon, then 072 will surely include this, 071 will be released as soon as I am sure all features are running correctly, I hope today is ready

**Comment by AbhishekVashisth** [comment]
How to show data in Line chart from top to bottom and how to show minor axis like gridlines in the graph?
