### ISSUE TITLE
Data Values are printed next to labels when the value is zero

### ISSUE THREAD

**Issue by rohit3d2003** [beto-rodriguez/Live-Charts#159]
I am using a Bar Chart with Min Value = 0 and show data labels = true. When the bar is drawn, it is showing 0 next to the label instead of showing it over X-Asix

![image](https://cloud.githubusercontent.com/assets/16943885/15339374/cd283ea6-1c49-11e6-8e84-045f0fead2fa.png)

**Comment by beto-rodriguez** [comment]
Hello, which version are you using?

**Comment by rohit3d2003** [comment]
0.6.6.0

**Comment by rohit3d2003** [comment]
I am using 0.6.6.0 with Material Design and MahApps library which is making the bar as borderless

**Comment by beto-rodriguez** [comment]
Already tested this in 0.7.0 and seems fixed, the version should be in nugget today, let me know if the issue is not solved
