### ISSUE TITLE
Enhancement Request: Could we set a bool to a chart that will display a legend for a pie chart?

### ISSUE THREAD

**Issue by lrmills85** [beto-rodriguez/Live-Charts#16]
![image](https://cloud.githubusercontent.com/assets/14826876/10212867/5020e460-67d3-11e5-8c2f-1907d30bbfb9.png) - I would love if I could have a legend on the left or right side of this pie chart if possible

**Comment by beto-rodriguez** [comment]
This should be added to all charts.

**Comment by beto-rodriguez** [comment]
closed becuase this is included in #11
