### ISSUE TITLE
Add polar chart

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#160]
![polar](https://cloud.githubusercontent.com/assets/10853349/15344278/58c91554-1c6b-11e6-9de2-7850479d9aaa.png)

**Comment by beto-rodriguez** [comment]
This chart wont be included in version 1.0, the chart has not enough support and there are some priorities to fix before this, adding the future request label to keep a better track of the priority issues in the library

**Comment by Admin-FSJ** [comment]
Hi Beto-Rodriguez,
Could you please share the code for the above graph.?
