### ISSUE TITLE
Add Heatmap chart

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#161]
![heatmap](https://cloud.githubusercontent.com/assets/10853349/15344287/6a97f462-1c6b-11e6-9643-03fd6a2c6fbb.png)

**Comment by rohit3d2003** [comment]
Are you planning to create a gauge chart as well for release 0.7?

**Comment by beto-rodriguez** [comment]
They are done already, getting ready the final details to publish 0.7.0, I hope today or at least tomorrow  is ready, here is the gauges preview
![gauges](https://cloud.githubusercontent.com/assets/10853349/15369939/6932f970-1cfa-11e6-82ce-fb72b93123b2.gif)

**Comment by rohit3d2003** [comment]
Nice. Looks really good

**Comment by gregsdennis** [comment]
Registering my vote for this (heat map).

**Comment by beto-rodriguez** [comment]
This is already supported, adding a `HeatSeries` to a `CartesianChart`.

**HeatSeries properties**

As any other series in LiveCharts HeatSeries inherits from `LiveCharts.Wpf.Series`, is contains the properties all series do plus:

* `DrawsHeatRange` type `bool`: specifies if the series should draw the heat range (bar to the right)
* `ColdColor` type `Color`: specifies the cold color, cells with the min value in the series will be filled with this color
* `HotColor` type `Color`: specifies the hot color, cells with the max value in the series will be filled with this color

Any value between max and min will be filled with a color resulting from a linear interpolation, if you do not specify Hot and Cold colors the chart will load the defaults as it does with other series

this will be released in 0.7.4

here is an example:

https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart/HeatChart

and the result:

![heatmap](https://cloud.githubusercontent.com/assets/10853349/16281281/3a381fc4-3889-11e6-9886-fa5af3043bfd.gif)
