### ISSUE TITLE
Line chart with different coloring from point to point

### ISSUE THREAD

**Issue by high1** [beto-rodriguez/Live-Charts#162]
I know this is not a usual use case for a charting library, but would it be too complicated to add? Could you point me where should I look, to try to implement it?

**Comment by carlmichaelbenson** [comment]
I have a similar use case, but I was just going to use a separate series for each line chart segment that needs a different color.

**Comment by beto-rodriguez** [comment]
Maybe this more common than what we think, this is the third time I see this request, it should be not hard to implement, thinking about it...

**Comment by beto-rodriguez** [comment]
@high1 @carlmichaelbenson 

I am not sure about this one now...

can you please explain me what are your needs? I mean besides the visual effect, why would this help your users?

This can be easily implemented, but I am not sure about the concept, why is this necessary?

I don't like the ways I see to solve this, and I suspect it is because it is out of design, please illustrate a case to help me to think how to solve this in a better way

**Comment by high1** [comment]
This is a special case in which the color represents additional state that is not part of the information given trough the axis - for example, we have a position of a vehicle described by the percentage of the path as x axis, and time as y axis. The color representation would be an additional information that would represent the state of the vehicle regarding the expected time of the arrival, for example, accurate, late, early etc...

**Comment by gregsdennis** [comment]
@high1 could you post an example?  Also, what is the expected behavior of the color of the line between points?  Some options I can think of:

- Gradient
- Hard change when arriving at next point
- Hard change when leaving current point
- Hard change in center of points

**Comment by princeoffoods** [comment]
Other use cases:

1. Mark points that are outside an allowed range or have state like ok-warning-error for example as green-orange-red in quality control in manufacturing.

2. Mark current/active value. For example when a graph is created in response to selecting an item in a list. The relevant date point is usually not the last point added.

**Comment by beto-rodriguez** [comment]
This is already supported, for a full example see https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart/PointState

The idea is the same, you will map a color for any point also, for example, lets set the fill to red if our value is greater than 200 and yellow if less than 200

            Mapper = Mappers.Xy<ObservableValue>()
                .X((item, index) => index)
                .Y(item => item.Value)
                .Fill(item => item.Value > 200 ? DangerBrush : OkBrush)
                .Stroke(item => Brushes.Transparent);

            OkBrush = new SolidColorBrush(Color.FromRgb(254,192,7));
            DangerBrush = new SolidColorBrush(Color.FromRgb(238,83,80));

I added this Fill and Stroke methods to many mappers, also I extended this to line and bar series

![pointstate](https://cloud.githubusercontent.com/assets/10853349/16845323/186df590-49ae-11e6-9c3a-47fa554b6313.gif)

**Comment by ChrisLawford** [comment]
@beto-rodriguez 
I dont believe you answered @princeoffoods 2nd point;

> Mark current/active value. For example when a graph is created in response to selecting an item in a list. The relevant data point is usually not the last point added.

In my application users will add new points to the graph by specifying the relative movement from the previous point on the chart and i would like the most recent point to be coloured differently to the previous points. This would make it easy for the user to see exactly where they are moving from and then once the new point is created verify that the movement occurred as expected.

I am aware of the example above but I am unsure if i can specify the mapper to fill the point in the way i am requesting as i cannot see how to index the latest point added to my chart values.
![image](https://user-images.githubusercontent.com/34543009/36844319-23fa9aaa-1d4a-11e8-8a0f-2c418187ca72.png)
 In the image you can see the desired functionality using the following code in:
`           Mapper = Mappers.Xy<ObservablePoint>()
                .X(item => item.X)
                .Y(item => item.Y)
                .Fill(item => item.X > 1 ? (item.X > 2 ? DangerBrush : AmberBrush) : null)
                .Stroke(item => item.X > 1 ? (item.X > 2 ? DangerBrush : AmberBrush) : null);
            DangerBrush = new SolidColorBrush(Color.FromRgb(238, 83, 80));
            AmberBrush = new SolidColorBrush(Color.FromRgb(238,200,80));`
It is possible to change this to altering the colour of the last point added to ChartValues<ObservablePoint>.
