### ISSUE TITLE
The "_dateTime" variable of OhlcPoint is often datetime "string", not integer.

### ISSUE THREAD

**Issue by elisechiang** [beto-rodriguez/Live-Charts#163]
The "_dateTime" variable of OhlcPoint is often datetime "string", not integer.

**Comment by beto-rodriguez** [comment]
0.7.0 is not ready yet! I have an issue with datetime!

**Comment by beto-rodriguez** [comment]
This is already fixed, but watch out! DateTime in 0.7.0 is kind of tricky, it is ok for now but I will think about how to implement a better solution.
