### ISSUE TITLE
The OhlcPoints are not displayed correctly at X-Axis.

### ISSUE THREAD

**Issue by elisechiang** [beto-rodriguez/Live-Charts#164]
The OhlcPoints are not displayed correctly at X-Axis. The X-axis labels should be shifted to the right a little.

**Comment by beto-rodriguez** [comment]
Hello, can you please give me and image? so I can see the issue better

**Comment by elisechiang** [comment]
It's okay on the version 0.7.0

**Comment by beto-rodriguez** [comment]
Remember 0.7.0 is alpha, the version is not released yet! some issues you see should disappear when 0.7.0 is released.

When the package is complete you will find it published in [Nuget](https://www.nuget.org/packages/LiveCharts/) also in the [releases section](https://github.com/beto-rodriguez/Live-Charts/releases).

0.7.0 is a huge release! currently from 77,000 lines to 123,000 and counting!
