### ISSUE TITLE
Please think about if it is suitable to use the datetime data type on X-axis of the financial chart.

### ISSUE THREAD

**Issue by elisechiang** [beto-rodriguez/Live-Charts#166]
The stock market is not opened every day and 24 hours, It is closed on weekends. Please think about if it is suitable to use the datetime data type on X-axis of the financial chart. To use the datetime string maybe is more simpler .

**Comment by beto-rodriguez** [comment]
You were right, Updated the `OhclPoint` class,it is now indexed and you must map the labels in the Axis.Labels property, I updated the example.

Please let me know if this does not solves the issue
