### ISSUE TITLE
I don't see the CursorX and CursorY function on version 0.7.0 .

### ISSUE THREAD

**Issue by elisechiang** [beto-rodriguez/Live-Charts#167]
I don't see the CursorX and CursorY function on version 0.7.0 .
Is it no longer supported in the future?

**Comment by beto-rodriguez** [comment]
Consider joining the chart for this kind of comments https://gitter.im/beto-rodriguez/Live-Charts

or reading the issue about it
https://github.com/beto-rodriguez/Live-Charts/issues/115

Again the release is not done yet, when the release is done I will publish the docs too.

This is an open source project and it is maintained by the community so feel free to contribute!
