### ISSUE TITLE
Can't compile. Where is the Charting class?

### ISSUE THREAD

**Issue by elisechiang** [beto-rodriguez/Live-Charts#168]
In the ChartCore class:   

       static ChartCore()
        {
            Configurations = new Charting();
        }

        #endregion

        #region Properties 

        public static Charting Configurations { get; set; }

**Comment by beto-rodriguez** [comment]
Consider joining the chart for this kind of comments, https://gitter.im/beto-rodriguez/Live-Charts

I see it here https://github.com/beto-rodriguez/Live-Charts/blob/a42aa27aef27dd5a55576c63bc2ced4c8ff54044/Core/Charting.cs
