### ISSUE TITLE
While I add the secondry series to the FinancialExample, it isn't displayed. 

### ISSUE THREAD

**Issue by elisechiang** [beto-rodriguez/Live-Charts#169]
While I add the secondry series to the FinancialExample, it isn't displayed. 

            InitializeComponent();

            SeriesCollection = new SeriesCollection
            {
                new OhlcSeries
                {
                    Values = new ChartValues<OhlcPoint>
                    {
                        new OhlcPoint(32, 35, 30, 32),
                        new OhlcPoint(33, 38, 31, 37),
                        new OhlcPoint(35, 42, 30, 40),
                        new OhlcPoint(37, 40, 35, 38),
                        new OhlcPoint(35, 38, 32, 33)
                    }
                },
                new LineSeries
                {
                    Values = new ChartValues<ObservableValue>(),
                    Fill = Brushes.Transparent
                }
            };

            //based on https://github.com/beto-rodriguez/Live-Charts/issues/166 
            //The Ohcl point X property is zero based indexed.
            //this means the first point is 0, second 1, third 2.... and so on
            //then you can use the Axis.Labels properties to map the chart X with a label in the array.
            //for more info see (mapped labels section) 
            //http://lvcharts.net/#/examples/v1/labels-wpf?path=WPF-Components-Labels

            try
            {
                SeriesCollection[1].Values.Insert(2, new ObservableValue(36));
                SeriesCollection[1].Values.Insert(3, new ObservableValue(37));
                SeriesCollection[1].Values.Insert(4, new ObservableValue(35));
            }
            catch
            {

            }

**Comment by beto-rodriguez** [comment]
seems to be working for me, updated the example...

![untitled](https://cloud.githubusercontent.com/assets/10853349/15526729/aee49042-21f9-11e6-842e-be771526b5ef.png)

**Comment by elisechiang** [comment]
In the secondary series, I just want to add 2, 3, 4 chartpoint. So it fails. If I add 0, 1, 2, 3, 4 chartpoint, it's no problem.

**Comment by beto-rodriguez** [comment]
I see, then plot a point, so you can specify the X property too

I am updating docs... to explain why this

    new LineSeries
            {
                Values = new ChartValues<ObservablePoint>
                {
                    //do not add the x=0 point
                    //new ObservablePoint(0,30)
                    new ObservablePoint(1,30),
                    new ObservablePoint(2,32),
                    new ObservablePoint(3,33)
                    new ObservablePoint(4,30)
                },
                Fill = Brushes.Transparent
            }

**Comment by elisechiang** [comment]
How can I dynamic add chartpoint like this?

            SeriesCollection[1].Values.Insert(2, new ObservableValue(36));
            SeriesCollection[1].Values.Insert(3, new ObservableValue(37));
            SeriesCollection[1].Values.Insert(4, new ObservableValue(35));

**Comment by beto-rodriguez** [comment]
I am sorry I dont know what you mean

**Comment by elisechiang** [comment]
Thank you, I see.
I can dynamically add chartpoints like this.

            SeriesCollection[1].Values.Add(new ObservablePoint(2, 36));
            SeriesCollection[1].Values.Add(new ObservablePoint(3, 36));
            SeriesCollection[1].Values.Add(new ObservablePoint(4, 35));

But the hover function does't work at chartpoint 0, 1 .

**Comment by elisechiang** [comment]
I found the problem.
The value of HoverShape.Height should be " Low - High > 10 ? Low - High : 10 ".

            if (HoverShape != null)
            {
                HoverShape.Width = Width;
                HoverShape.Height = Low - High > 10 ? Low - High : 10;
                Canvas.SetLeft(HoverShape, Left);
                Canvas.SetTop(HoverShape, High);
            }

**Comment by beto-rodriguez** [comment]
yeah yeah, that seems to be the problem, fixing asap, thanks!

**Comment by beto-rodriguez** [comment]
I will close this issue since it seems solved, please let me know if I missed something
