### ISSUE TITLE
While the high value is equal to the low value, the height of the HoverShape is zero.

### ISSUE THREAD

**Issue by elisechiang** [beto-rodriguez/Live-Charts#170]
While the high value is equal to the low value, the height of the HoverShape is zero.
The hover function of the chartpoint doesn't work.

In the OhlcPointView.cs:

            if (HoverShape != null)
            {
                HoverShape.Width = Width;
                HoverShape.Height = Math.Abs(High - Low);
                Canvas.SetLeft(HoverShape, Left);
                Canvas.SetTop(HoverShape, High);
            }

**Comment by beto-rodriguez** [comment]
You were right, last commit forces a min height of 10px
