### ISSUE TITLE
Winforms examples

### ISSUE THREAD

**Issue by Zeokat** [beto-rodriguez/Live-Charts#171]
I was checking this library and seems really cool, congrats.

First, im using Winforms and found a little error into documentantion: http://lvcharts.net/#/examples/v1/install-wf?path=WF-Install

```
ElementHost hst = new ElementHost();
host.Dock = DockStyle.Fill;
```

It should be:
```
ElementHost host = new ElementHost();
host.Dock = DockStyle.Fill;
```

And one question, is possible rotate labels? because when you use words as labels, rotate them -45º helps saving space and labels dont overlap. Will be nice have this enhacement :+1:

**Comment by beto-rodriguez** [comment]
Thanks, I will update asap, I actually just commited a native Winforms control, it is just an UserControl that wraps in a element host a wpf chart and espouses the properties. so it is actually changing a bit, I am working now updating the site, will conciser this 

Thank you very much!

**Comment by beto-rodriguez** [comment]
Finally could build a "native" Winforms control there is a new package specialized for Windows Forms, now you should need to add those references, and it must work much better than previous approach.

https://www.nuget.org/packages/LiveCharts.WinForms/

here is the package I am improving docs with this release.

About rotating labels they will be added in future versions there is already an open issue about it #157

**Comment by Zeokat** [comment]
Very nice work @beto-rodriguez , as soon as documentation is ready i will start using WinForms.

Thanks for the hard work.

**Comment by beto-rodriguez** [comment]
new documentation is ready, please let me know if you find any other issue!

Gracias!
