### ISSUE TITLE
Problems loading Visual Studio solution

### ISSUE THREAD

**Issue by Zeokat** [beto-rodriguez/Live-Charts#173]
I just cloned Live-Charts repo into my desktop and then i opened LiveCharts solution `LiveCharts.sln` but Winforms examples refuses to load and Visual Studio returns an error:

`C:\Users\VA\Downloads\Live-Charts-master\WindowsForms\WindowsForms.csproj : error  : No se pudo cargar el archivo del proyecto. No se puede encontrar una parte de la ruta de acceso 'C:\Users\VA\Downloads\Live-Charts-master\WindowsForms\WindowsForms.csproj'.  C:\Users\VA\Downloads\Live-Charts-master\WindowsForms\WindowsForms.csproj``

The error is in spanish but translated to english, it is saying that Visual Studio can't locate the file project at `C:\Users\VA\Downloads\Live-Charts-master\WindowsForms\WindowsForms.csproj`

The project that not load is the WinForms examples. Seems that you used `WindowsForms` name but that directory on GitHub repo is renamed to `WinForms` and moved to another location.

**Comment by beto-rodriguez** [comment]
I just noticed 2 commits were stuck in my pc, now they are here.

Yes I moved the Winforms project to Examples/Winforms, I be more careful next times and will try to place everything in place in my machine before publishing it here... so this wont happen again.

Sadly visual studio is not friendly in this cases, but you have a couple of options

1) forget about your current clone, and clone the library completely again.

2) let visual studio know where the project is located now, select the project that is not loaded (WinForms) then go to properties, and in the project folder property click [...] and browse for the new project location (Examples/Winforms), here is an image, you should see the project in color gray and also you should see the [...] button.

![untitled](https://cloud.githubusercontent.com/assets/10853349/15546265/e3e14342-2264-11e6-964e-809ac48ba496.png)

**Comment by Zeokat** [comment]
Cloned again, now everything works as expected :+1:
