### ISSUE TITLE
The line is broken.

### ISSUE THREAD

**Issue by elisechiang** [beto-rodriguez/Live-Charts#175]
How do I set the ZIndex of the series?
How do I set the panning of the series?

![multiseries](https://cloud.githubusercontent.com/assets/7832743/15606834/35ba1be8-2441-11e6-82c5-2748a7177214.png)

**Comment by beto-rodriguez** [comment]
I have recived some mails and issues about how to do stuff in 0.7, I am updating the docs, the web site will soon include all these features

**Comment by elisechiang** [comment]
Thanks.

**Comment by beto-rodriguez** [comment]
Zindex:

`<lvc: LineSeires Panel.ZIndex="10">`

Panning

Change the Axis.MinValue and Axis.MaxValue properties, the examples will be added to the web site once next release is ready
