### ISSUE TITLE
WinForms and StrokeDashArray property

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#177]
The winforms version is a ElementHost control, that wraps the wpf control, sadly I am not able to create dashed shapes with this method.

I have not found any similar issue in google.

this is the code in WPF
https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart/Customized%20Series

and in Winforms (no dashed lines!)
https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/WinForms/Cartesian/Customized%20Series

Does anyone have a clue about this?

**Comment by JorgeChibante** [comment]
Hello,

I think I have solved it.

![chart](https://cloud.githubusercontent.com/assets/10546083/15658640/bf687782-26b6-11e6-9ac1-796a4a8e6a13.PNG)

Is this it or am I really missing the point? It's the first time I'm using git, how can I contribute?

**Comment by beto-rodriguez** [comment]
Awesome , yes you did, you solved it, just one thing notice the axis should be dashed too according to the code, this is actually the expected result(forget about the background, I already fixed that and will be included in 0.7.1)

http://lvcharts.net/App/Index#/examples/v1/wf/Customizing%20Series

Normally the easier way for you and me, is that you Folk the repo, then fix the issue, and then you create a pull request at this library.

Let me know if you need more help, or you could also just simply let me know how you fixed this and I will include it, but sadly this way you name would not appear in the contributors section.

Thanks for your help!

**Comment by JorgeChibante** [comment]
Ok here's what I changed,

On the file Customized Line Series.cs on line 22 you had:

`StrokeDashArray = new System.Windows.Media.DoubleCollection(20),`
I replaced by:
`StrokeDashArray = new System.Windows.Media.DoubleCollection(new double[] { 2 }),`

and on line 48 where you had:
`StrokeDashArray = new System.Windows.Media.DoubleCollection(2),`
you can replace by 
`StrokeDashArray = new System.Windows.Media.DoubleCollection(new double[] { 2 }),`
and the Y axis becomes dashed.

It's easier this way, I'll try to fork and pull on another opportunity.

**Comment by beto-rodriguez** [comment]
Awesome, thanks!
