### ISSUE TITLE
Exception when hovering over point in linechart with more than one line series

### ISSUE THREAD

**Issue by panhans** [beto-rodriguez/Live-Charts#179]
C#

`var config = Mappers.Xy<WeatherViewModel>();
            config.Y(model => model.Temperature);
            config.X(model => model.DateTime.ToOADate());

            this.LineSeriesCollection= new SeriesCollection()
            {
                new LineSeries
                {
                    Values = new ChartValues<WeatherViewModel>(), DataLabels = true, Configuration = config
                },

                new LineSeries
                {
                    Values = new ChartValues<WeatherViewModel>(), DataLabels = true, Configuration = config
                }
            };

            this.XFormatter = val => DateTime.FromOADate(val).ToString("hh:mm:ss tt");
            this.YFormatter = val => Math.Round(val) + " °";

            Task.Factory.StartNew(() =>
            {
                var r = new Random();

                while (true)
                {
                    foreach (var series in this.LineSeriesCollection)
                    {
                        this.WindowManager.MainWindow.Dispatcher.Invoke(new Action(() =>
                        {
                            if (series.Values.Count > 10)
                            {
                                series.Values.RemoveAt(0);
                            }

                            series.Values.Add(new WeatherViewModel(r.NextDouble() * 30, DateTime.Now));
                        }));
                    }
                    Thread.Sleep(800);
                }
            });`

XAML
`<Wpf:CartesianChart Grid.Row="0" Grid.Column="0" Series="{Binding LineSeriesCollection}">
            <Wpf:CartesianChart.DataTooltip>
                
                <Wpf:DefaultTooltip SelectionMode="SharedYValues"></Wpf:DefaultTooltip>
            </Wpf:CartesianChart.DataTooltip>
   </Wpf:CartesianChart>`

//EDIT: It only apears when adding values in a task.

**Comment by beto-rodriguez** [comment]
I can not force this error, actually I created an example in the repo with this issue and I can't see it, please give me more info, or help me forking, creating the issue and pulling back please!

here is my code and it is working correctly

https://github.com/beto-rodriguez/Live-Charts/issues/179

**Comment by beto-rodriguez** [comment]
closing this issue, I can not force it, and not enough data to reproduce it
