### ISSUE TITLE
Comparing two values using gauge charts and show different color

### ISSUE THREAD

**Issue by rohit3d2003** [beto-rodriguez/Live-Charts#181]
Can we compare two values with the current implementation of gauge chart with a dial showing whether the value is less/greater than expected with the help of colors?
Below is the screenshot for the same

![image](https://cloud.githubusercontent.com/assets/16943885/15686849/a0982baa-2737-11e6-9118-f4181f47c5ed.png)

**Comment by beto-rodriguez** [comment]
This is not supported yet, Will add it in future versions, I don't like at all that line, I am thinking maybe in implementing something different, but I will

**Comment by rohit3d2003** [comment]
Is there a way to set the color if the value exceed the max value?

**Comment by beto-rodriguez** [comment]
Interesting example,  I will add one of those right now that I am building the docs, I am not completely sure if it is possible now, will try and let you know

**Comment by camou23** [comment]
Maybe Something like this? :)
I also need it for a project i am working right now.

![image](https://cloud.githubusercontent.com/assets/4669637/15704749/4f6f4f3c-27ec-11e6-89ec-d355a7cd2299.png)

**Comment by camou23** [comment]
Some news ? :)

**Comment by beto-rodriguez** [comment]
not ready yet :cry:

**Comment by camou23** [comment]
![image](https://cloud.githubusercontent.com/assets/4669637/16455367/501a757c-3e14-11e6-9e06-f8af04e3dcac.png)

I used something like this now.
2 Arc overlayed on top of the GaugeChart

**Comment by eduard-schwenk** [comment]
first of all very nice work rodriguez !
i'm wanted also something like this for my project,
and i've extended the gauge with additional 3 PieSlices and some props for them 

![sample2](https://cloud.githubusercontent.com/assets/20314709/16609995/59130bfa-4358-11e6-87fb-e19b85ecb9db.png)

maybe to have more inspiration :) ...
is also works in 360°
![sample3](https://cloud.githubusercontent.com/assets/20314709/16610058/df2cca28-4358-11e6-9132-430abeb2931d.png)

**Comment by beto-rodriguez** [comment]
I think the best solution for this was crating another gauge, now from 0.7.9 `Gauge` class will be removed, instead we will have a `SolidGauge` (current implementation) and an `AngularGauge`

here is the angular gauge preview

![gauge](https://cloud.githubusercontent.com/assets/10853349/16935874/637c0464-4d28-11e6-87e4-1d941872d435.gif)

**Comment by eduard-schwenk** [comment]
really sad ... if the current gauge will be removed.
In my opinion it's a cool, modern and very expressive component do display a single key value on dashboards, the new style is a good addition, but not a good replacement.
This new style makes it seem outdated, maybe it's cool for automation apps but not for report like dashboards.
(sorry for bad english - if it is so ... :))

**Comment by beto-rodriguez** [comment]
No no it is not removed, we now have 2

**Comment by rohit3d2003** [comment]
Basically, we should be able to set the Start (0), Max/End(15,848,352), Threshold(12191040) and the actual value (11541913) for the above chart to be plotted
