### ISSUE TITLE
Chart Legend Title Is Always "Some Series"

### ISSUE THREAD

**Issue by mbithy** [beto-rodriguez/Live-Charts#182]
When you change the title of the legend from back code the UI does not update. I tried this...
    LiveChart.ChartLegend.Series[0].Title = "New Tilte";
Is there a different Approach?

**Comment by beto-rodriguez** [comment]
When you initialize the series it works for me

http://lvcharts.net/App/Index#/examples/v1/wpf/Stacked%20Area

about changing it at run time, if it is not updating it is a bug, I will try it

**Comment by mbithy** [comment]
Thanks, but until you do, I've discovered during run time you can change the title at the LineSeries that is if your line series was a global variable.
