### ISSUE TITLE
Why the last coordinate axes is closest to the plot area? 

### ISSUE THREAD

**Issue by elisechiang** [beto-rodriguez/Live-Charts#183]
as title

**Comment by beto-rodriguez** [comment]
Can I see a picture so I get a better idea?

**Comment by elisechiang** [comment]
The Green Axis is the last one, but it is close to the right side of the plot area.

            <lc:CartesianChart.AxisY>
                <lc:Axis Foreground="DodgerBlue" Title="Blue Axis"/>
                <lc:Axis Foreground="IndianRed" Title="Red Axis" Position="RightTop" Separator="{x:Static lc:DefaultAxes.CleanSeparator}"/>
                <lc:Axis Foreground="DarkOliveGreen" Title="Green Axis" Position="RightTop" Separator="{x:Static lc:DefaultAxes.CleanSeparator}"/>
            </lc:CartesianChart.AxisY>
![multiaxes](https://cloud.githubusercontent.com/assets/7832743/15738268/1fa6b58c-28dd-11e6-96ca-cafc719a88fe.png)

**Comment by beto-rodriguez** [comment]
What happens here is that they are stacked in the same order in the list, The Red Axis goes first than green axis then it starts the stack to the right, the next element is the green axis, and it is stacked in the second position at right.

I don´t see an issue here, please let me know why inverting the order would not be enough

    <lc:CartesianChart.AxisY>
            <lc:Axis Title="Blue Axis"/>
            <lc:Axis  Title="Green Axis" Position="RightTop"  /> 
            <lc:Axis  Title="Red Axis" Position="RightTop" />  
        </lc:CartesianChart.AxisY>

**Comment by elisechiang** [comment]
In general people want to put the axes to the right side or to the bottom, but maybe they don't want to put the axes in reverse order.
What do you think?
