### ISSUE TITLE
Point Label clipped when Usercontrol is too Small

### ISSUE THREAD

**Issue by camou23** [beto-rodriguez/Live-Charts#185]
![image](https://cloud.githubusercontent.com/assets/4669637/15740207/2b13ddc4-28b4-11e6-8d13-cf368b4e6dba.png)

**Comment by beto-rodriguez** [comment]
My bad, the chart canvas clip to bound is set to true.

https://github.com/beto-rodriguez/Live-Charts/blob/master/WpfView/Charts/Chart/Chart.cs#L42

fixing it in next release

**Comment by beto-rodriguez** [comment]
This should be already solved in latest Nuget package, please let me know if it does no solves your issue
