### ISSUE TITLE
Set Bar Chart to start at zero

### ISSUE THREAD

**Issue by hishaamn** [beto-rodriguez/Live-Charts#187]
Hi,

Can you please help me how to set the bar chart to start at 0? I have a line and the bar chart. Please see screenshot below. I am not able to set the Y-Axis to 0 as I don't require the -10 value.
![chart](https://cloud.githubusercontent.com/assets/14113223/15805080/b681e158-2b2f-11e6-862a-1ba68b6b0504.PNG)

Thanks

**Comment by hishaamn** [comment]
I have been able to fix it. I was missing the MinValue on the AxisY as shown below:

    myBarChart.AxisY.Add(new Axis
    {
          LabelFormatter = value => value.ToString(),
          MinValue = 0
    });   

Thanks

**Comment by beto-rodriguez** [comment]
need to add this to docs!
