### ISSUE TITLE
Column series with no spacing between columns

### ISSUE THREAD

**Issue by alexhelms** [beto-rodriguez/Live-Charts#190]
I am trying to use Live-Charts to make a histogram using a column series. I can't figure out how or if it is even possible to remove the spacing between columns. I am just using the example code a basic column chart. The chart works fine, but how can I remove the padding between the columns? Thanks!

**Comment by beto-rodriguez** [comment]
Not possible for now, this is the result I got:

![image](https://cloud.githubusercontent.com/assets/10853349/15880924/6676dd2a-2cf7-11e6-92d1-d8c6ee4996c3.png)

for now you can increase the columns with using the MaxColWidth property:

                new ColumnSeries
                {
                    Values = //...
                    MaxColumnWidth = double.PositiveInfinity
                }

I will fix the padding issue in next release

**Comment by alexhelms** [comment]
Thanks for the quick feedback!

Next release sounds good. Looking through the code, I found

`const double padding = 5;`

at https://github.com/beto-rodriguez/Live-Charts/blob/master/Core/SeriesAlgorithms/ColumnAlgorithm.cs

Maybe that's the culprit.

**Comment by beto-rodriguez** [comment]
yeah, that is what is wrong, adding  new property `ColumnPadding` 

           new ColumnSeries
            {
                Values = //...
                MaxColumnWidth = double.PositiveInfinity,
                ColumnPadding = 0
            }

then replacing the line you pointed with:

    double padding = ColumnWidth;

should solve the issue

**Comment by beto-rodriguez** [comment]
The previous commit f fixes this for the 4 cases, Columns, Rows, StackedColumns and StackedRows series

Columens and StackedColumns

    new ColumnSeries
        {
            MaxColumnWidth = double.PositiveInfinity,
            ColumnPadding = 0
        }

Rows and StackedRows

    new RowSeries
        {
            Values = //...
            MaxRowHeight = double.PositiveInfinity,
            RowPadding = 0
        }
