### ISSUE TITLE
Floating labels on chart

### ISSUE THREAD

**Issue by lblolz** [beto-rodriguez/Live-Charts#191]
Hi, 

Any edge I wanted to thank you for this great work.

However I have a concern. When I spend my cursor over a graph I the values that appear but I would delete the second column percentages, how can I do?

Can I delete zero values from display ?

![image](https://cloud.githubusercontent.com/assets/13196423/15897496/f40d304c-2d94-11e6-8889-78145a8555b0.png)

Regards,

Loris

**Comment by beto-rodriguez** [comment]
sadly for now the only way to remove them is creating your own tool tip, and setting it to the chart.

here is the source code of how I built the current one 

https://github.com/beto-rodriguez/Live-Charts/blob/master/WpfView/DefaultTooltip.xaml

https://github.com/beto-rodriguez/Live-Charts/blob/master/WpfView/DefaultTooltip.xaml.cs

you should adapt it to your case, this tool tip tries to work for every series and chart in the library
