### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by lblolz** [beto-rodriguez/Live-Charts#192]
Hi, 

I have a concern when I create a pie chart and that it has a negative value. The display is completely bugged.

Would you have a solution?

![image](https://cloud.githubusercontent.com/assets/13196423/15897449/cb1df2a2-2d94-11e6-9a33-e5130cb54693.png)

Best regards, 

Loris

**Comment by beto-rodriguez** [comment]
Hello, and thanks for contributing,

Do you need negative values in a pie chart?

I think it is out of design, I think you should remove them manually

do you agree?

**Comment by lorisb** [comment]
Hi, 

Yes all of my values are important i cannot delete them or take the abs value. I was using Winform Chart and i had this result

![image](https://cloud.githubusercontent.com/assets/13196423/15898054/07c856a0-2d97-11e6-9cdc-b58ac73432b9.png)

**Comment by beto-rodriguez** [comment]
but that is wrong, that doe not represents -0.05, that represents 0, they are forcing negative values to be 0.

I will think about this...

**Comment by camou23** [comment]
Negative values doesn't make any sense in a Piechart.
I dont see this as a Bug.

**Comment by lorisb** [comment]
Thank you for your answers I will think about whether or not I can make negative values to 0
