### ISSUE TITLE
Gauge FromColor and ToColor seems inverted

### ISSUE THREAD

**Issue by courchef** [beto-rodriguez/Live-Charts#195]
If I declare the following:
`<lvc:Gauge Width="200" From="0" FromColor="Red" To="100" ToColor="Green" Value="10">`

I expect the gauge will display a 18 degres (10% of 180 degres) red arc, but the arc is green.

Is it really the expected behavior?

**Comment by beto-rodriguez** [comment]
No it is not, it really seems inverted, thanks for reporting!

**Comment by beto-rodriguez** [comment]
The previous commit fixes this inverted color issue,

0.7.1.8 will include this patch

**Comment by courchef** [comment]
Woa... that was fast.

**Comment by beto-rodriguez** [comment]
Welcome to LiveCharts :smile:
