### ISSUE TITLE
PieChart - Disable tooltip

### ISSUE THREAD

**Issue by courchef** [beto-rodriguez/Live-Charts#197]
I'm using NuGet version 0.7.1.7

The release documention for 0.7.0 (https://github.com/beto-rodriguez/Live-Charts/releases/tag/0.7.0) mentionned that `Hoverable` is now obsolete and we should set `Chart.ToolTip = null` to disable the tooltip.

I tried the following declaration, but the tooltip is always shown when hovering a pie chart
```
<lvc:PieChart Name="lvcTest" Hoverable="False" />
<lvc:PieChart Name="lvcTest" ToolTip="{x:Null}" />

lvcTest.ToolTip = null;
lvcTest.Hoverable = false;
```

I found that we need to set `lvcTest.DataTooltip = null` in order to disable the tooltip for a pie chart.

Is it possible to update the documentation?

**Comment by beto-rodriguez** [comment]
I updated that, thanks for the note!
