### ISSUE TITLE
PieChart - Disabling tooltip also disable the PushOut effect

### ISSUE THREAD

**Issue by courchef** [beto-rodriguez/Live-Charts#198]
NuGet version 0.7.1.7

When setting `Chart.DataTooltip = null` on a PieChart, the push out effect on pie slices is also disabled. 
Is it possible to keep the push out effect while the tooltip is disabled?

**Comment by beto-rodriguez** [comment]
You are right, this should not happen...

**Comment by beto-rodriguez** [comment]
removing the in progress label, it is a bit more complex... will need some time to fix this

**Why**

because when you disable tooltips, hover shapes are not added to the chart, this with the intention to increase performance

A null Tooltip and hoverable effects requieres and adjustment there...

**Comment by beto-rodriguez** [comment]
Hoverable property is back, as in #206 both are required, Hoverable and DataTooltip properties...

to fix this in future release pelase do:

DataTooltip = null;
Hoverable = true;

**Comment by courchef** [comment]
Great!
