### ISSUE TITLE
Feature request: Modify bullet size in DefaultLegend (and also in DefaultTooltip)

### ISSUE THREAD

**Issue by courchef** [beto-rodriguez/Live-Charts#199]
I would like to set the bullet larger in the legend of a chart.

What do you think of the following modifications?

**DefaultLegend.xaml**

```
<Ellipse Width="{Binding BulletSize, RelativeSource={RelativeSource Mode=FindAncestor, AncestorLevel=1, AncestorType={x:Type UserControl}}}"
         Height="{Binding BulletSize, RelativeSource={RelativeSource Mode=FindAncestor, AncestorLevel=1, AncestorType={x:Type UserControl}}}"
         StrokeThickness="{Binding StrokeThickness}" Stroke="{Binding Stroke}" Fill="{Binding Fill}"/>
```

**DefaultLegend.xaml.cs**

```
public static readonly DependencyProperty BulletSizeProperty = DependencyProperty.Register(
            "BulletSize", typeof(int), typeof(DefaultLegend), new PropertyMetadata(11));

public int BulletSize
{
    get { return (int)GetValue(BulletSizeProperty); }
    set { SetValue(BulletSizeProperty, value); }
}
```

**Comment by beto-rodriguez** [comment]
I like this request, will include it in next release

**Comment by beto-rodriguez** [comment]
already included this, thanks for reporting, here is the result with a bullet size of 20 in both

![bullet](https://cloud.githubusercontent.com/assets/10853349/15976006/f61ccca8-2f15-11e6-9b29-91723db700e0.png)

**Comment by courchef** [comment]
I don't want to sound too picky, but I notice incorrect vertical alignment on titles in legend and on count in tooltip.

**Comment by beto-rodriguez** [comment]
Dont worry about it, the more you give me your opinion, the better library we build.

you mean the center issue?, I noticed that too, just fixed it in my local repo

**Comment by beto-rodriguez** [comment]
this should solve it https://github.com/beto-rodriguez/Live-Charts/commit/f8ace17ad1f96bce657965cd9d375c2b1b38ad24

**Comment by courchef** [comment]
Yes, I was the center issue.
This will be looking great!
