### ISSUE TITLE
Feature Request: Support of value "Double.NaN"

### ISSUE THREAD

**Issue by TheCSharpCoder** [beto-rodriguez/Live-Charts#20]
Hello,

it would be great that the plot value "Double.NaN" will be supported and will create a "gap" in the Line Series Plot.
I changed your great library quickly and it works, but it not coded well.

Regards

![nan_plot](https://cloud.githubusercontent.com/assets/14967542/10269863/39e1d1de-6ae2-11e5-9b38-63c3470b2e9f.PNG)

**Comment by beto-rodriguez** [comment]
Thank you for helping, this is a good idea and will be implemented. thanks

**Comment by snellface** [comment]
Hello! You get weird polygon spikes if you use double.nan in lineseries's with fills.
![nan values](https://cloud.githubusercontent.com/assets/6129664/21051044/9ffb9b04-be1e-11e6-8728-27b237e896e6.png)

**Comment by beto-rodriguez** [comment]
the funny part is that seems not to happen always, could please show me your series values?
