### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ko01u** [beto-rodriguez/Live-Charts#200]
wanted to add some more values to a LineSerie. But this seems not possible, it takes really long time.
I tried the example from  http://lvcharts.net/App/examples/v1/wpf/Basics: ( it is also written there "..it also handles performance, feel free to change 1 million points in 1 second..."  )  

public MainWindow()
		{
			var vals = new ChartValues<double>();
			for (double i = 0; i <= 10000; i++)
			{
				vals.Add(i);
			}
			DataContext = this;
			SeriesCollection = new SeriesCollection
			{
		         new LineSeries
			{
				Values = vals
			}
    
			};
			InitializeComponent();
	
        }

**Comment by beto-rodriguez** [comment]
I will remove that note from the article,I am sorry about the confusion, High performance is possible with this library, but it is not built yet.

**Comment by beto-rodriguez** [comment]
Already added a solution for this case.

Please see https://lvcharts.net/App/examples/v1/wpf/Improve%20Performance

Some series are not ready yet, the site explains it better
