### ISSUE TITLE
New LineSeries Stroke Property is nothing/null after adding to SeriesCollection

### ISSUE THREAD

**Issue by pusaken** [beto-rodriguez/Live-Charts#201]
In 0.6.7 the stroke property of a LineSeries was filled with the automatically assigned brush on adding the LineSeries to a SeriesCollection. 
In 0.7.2 I am missing this feature. Is that correct?

Regards,
Pusaken

**Comment by beto-rodriguez** [comment]
Thank you very much for the report.

What happens here is that 0.6 normally updated as soon as the change happened.

What happens in 0.7 is that the design is smarter, and when you add the series, the library is listening for more changes to happen, this with the intention to have high performance chart in a future.

if you try to access the Stroke property, lets say in 1 more second, you will see the color is there, normally the updater runs every time all the series animations finishes, or if animations disabled, they'll run every 10ms.

The updater runs something like...

1) A change happen, updater listener is initialized, and will wait at least an interval of Chart.AnimationsSpeed property.

2) Draw the changes

3) Stop listening for changes.

**Comment by beto-rodriguez** [comment]
Closing this issue, it is directly related with #217
