### ISSUE TITLE
Sections remain visible after .Sections.Clear()

### ISSUE THREAD

**Issue by pusaken** [beto-rodriguez/Live-Charts#202]
v 0.7.2.2:
When calling .Sections.Clear() of an X-Axis the sections remain visible in my LineChart. They detach, however, from the chart and don't move with zoom and pan.

**Comment by beto-rodriguez** [comment]
previous commit fixes this issue and more, also added a unit test, so we are always sure the charts do not hold unnecessary shapes in the canvas, I think I removed a small memory leak in the axis.

https://github.com/beto-rodriguez/Live-Charts/blob/master/UnitTests/MemoryLeaks/DrawnShapes.cs
