### ISSUE TITLE
Lot of points show slowly

### ISSUE THREAD

**Issue by tufeikafei** [beto-rodriguez/Live-Charts#205]
Dear Beto-rodriguez,
I found when I use the LinearGradientBrush,with 10000 points,it moves slowly.
Is there any solution to deal with lots of points?

**Comment by beto-rodriguez** [comment]
High performance is not ready yet, there will be a solution, there is actually a package in Nuget (LiveChats.Optimizations, yes LiveChats, I missed the r), this package used to worj with 0.5 version, then 0.6 improved animations drastically, and now 0.7 makes the library portable, so the package is not updated yet, but the good news is that 0.7 is at least 3 times faster than 0.5.

I hope soon everything is ready. I keep working on it.

**Comment by tufeikafei** [comment]
Really thanks with your work.

**Comment by beto-rodriguez** [comment]
Nothing to thank

**Comment by HereChen** [comment]
Wow... much slow than oxyplot. Maybe, Live-Charts can draw inspiration from oxyplot.

**Comment by beto-rodriguez** [comment]
You will be amazed with the algorithms I am working with

**Comment by beto-rodriguez** [comment]
Line series can plot 25 million points in 3 seconds,  it is in progress will be ready soon

**Comment by HereChen** [comment]
That sounds great!

**Comment by beto-rodriguez** [comment]
Already added a solution for this case.

Please see https://lvcharts.net/App/examples/v1/wpf/Improve%20Performance

Some series are not ready yet, the site explains it better
