### ISSUE TITLE
DataToolTip=nothing causes Lines to grow on mouseover

### ISSUE THREAD

**Issue by pusaken** [beto-rodriguez/Live-Charts#206]
On 0.7.2 when setting the DataTooltip property to nothing (or null) on a LineChart, the Lines will grow (thickness increasing) with every mouseover.

**Comment by beto-rodriguez** [comment]
Hoverable property is back, as in #198  both are required, Hoverable and DataTooltip properties...

to fix this in future release pelase do:

DataTooltip = null;
Hoverable = false;

this will disable both effects

**Comment by beto-rodriguez** [comment]
https://github.com/beto-rodriguez/Live-Charts/commit/e3a7f3c249703480ff2adb154f295fffc3e4e4d0 fixes this issue.

Hoverable property is back, as in #198  both are required, Hoverable and DataTooltip properties...

to fix this in future release pelase do:

DataTooltip = null;
Hoverable = false;

this will disable both effects
