### ISSUE TITLE
Issue with X-Axis Labelling

### ISSUE THREAD

**Issue by hishaamn** [beto-rodriguez/Live-Charts#207]
Hi,

I am currently encountering an issue whereby when I maximized my winform window, the labelling on the X-Axis gets duplicated as shown below:

![labeling](https://cloud.githubusercontent.com/assets/14113223/16044552/fafa3010-3255-11e6-8e2f-dae0f734adfe.PNG)

Normally, when the form first loads, I maximized the window and de-maximized it, it continues to work. My graph is being updated every 10sec. After the graph first update, the above issue happens. Below is the code I am currently using to update the graph

     public async static void UpdateIncidentInOutFlow(CartesianChart incInOutFlowChart)
        {
            var inOutFlowString = APIController.GetIncidentInOutFlow();

            var inOutFlowValues = inOutFlowString.Split('|');

            await Task.Run(() => IncidentHelper.SaveIncInOutFlow(int.Parse(inOutFlowValues[0]), int.Parse(inOutFlowValues[1])));

            incInOutFlowChart.AxisX.Clear();
            incInOutFlowChart.AxisY.Clear();

            GenerateIncidentInOutFlow(incInOutFlowChart);
        }

**Comment by beto-rodriguez** [comment]
Hello

A similar issue was just solved in the last release (0.7.2.2) are you using latest version?

**Comment by hishaamn** [comment]
Hi,
I have just updated the version to 0.7.2.2 and it fixed the issue. Thanks :+1:
