### ISSUE TITLE
Correct spelling for VisualElement VerticalAlingment and HorizontalAlingment

### ISSUE THREAD

**Issue by carlmichaelbenson** [beto-rodriguez/Live-Charts#208]
Correct spelling for VisualElement VerticalAlingment and HorizontalAlingment. It works great though... as long as I misspell them in the WPF.

**Comment by beto-rodriguez** [comment]
Lol, I am sorry about it, fixing it asap

**Comment by beto-rodriguez** [comment]
O can not find the spelling error can you please point me where it is?

**Comment by beto-rodriguez** [comment]
Previous commit fixes this issue, it will be included in next release
