### ISSUE TITLE
Feature Request: Support multiple axes

### ISSUE THREAD

**Issue by TheCSharpCoder** [beto-rodriguez/Live-Charts#21]
Hello,

it would be great to add multiple y axes (primary axes) für the line series plot. So that you can say, line series 1 and 2 will use primary axis 1 and line serie 3 will have the separate primary axis 2.

Regards

**Comment by beto-rodriguez** [comment]
Awesome, this is really good. thanks

**Comment by beto-rodriguez** [comment]
closed with previous comits

**Comment by beto-rodriguez** [comment]
more info at http://lvcharts.net/#/examples/v1/multipleAxes-wpf?path=WPF-MultipleAxes
