### ISSUE TITLE
NRE when calling .Clear() on SeriesCollection with Empty Values

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#211]
From Chat:

I am getting null reference exception randomly when calling Clear on Series Collection which does not have data values as of yet

System.NullReferenceException was unhandled by user code
HResult=-2147467261
Message=Object reference not set to an instance of an object.
Source=LiveCharts.Wpf
StackTrace:
at LiveCharts.Wpf.StackedColumnSeries.Erase()
at LiveCharts.SeriesCollection.OnCollectionChanged(IEnumerable1 oldItems, IEnumerable1 newItems)
at LiveCharts.Helpers.NoisyCollection1.OnCollectionChanged(IEnumerable1 olditems, IEnumerable1 newItems) at LiveCharts.Helpers.NoisyCollection1.Clear()
at Paragon.ViewModels.ExpenseViewModel.CreateExpenseChart() in C:\Projects\Paragon\Paragon\ViewModels\ExpenseViewModel.cs:line 90
at Paragon.ViewModels.ExpenseViewModel.GenerateExpenseChart() in C:\Projects\Paragon\Paragon\ViewModels\ExpenseViewModel.cs:line 84
at Paragon.ViewModels.ExpenseViewModel.<.ctor>b__0_0(ResourcesRetrieved message) in C:\Projects\Paragon\Paragon\ViewModels\ExpenseViewModel.cs:line 24
InnerException:

**Comment by beto-rodriguez** [comment]
This bug was reported in the chat, but I am not able to force it, any help is appreciated @rohit3d2003

**Comment by rohit3d2003** [comment]
I am not able to reproduce it either. I have changed my code to call Clear() only when a Series has an instance of Chart

**Comment by hishaamn** [comment]
Hi,

I keep getting this error when updating the series. My scenario is as follows:

I have 3 tabs and the first 2 tabs contains tables. On the third one, I have my charts. So, when I opened the window, the first tab is loaded and I get the above error since it is also updating the chart. 

The workaround for me is to load the third tab first, that is, the tab containing the charts. This solve the issue.

Can you please check if there is any fix?

Thanks

**Comment by beto-rodriguez** [comment]
@hishaamn are using 0.7.9? I just fixed a similar issue

**Comment by hishaamn** [comment]
Hi,

Yes it does fix the issue. I think I need to perform regular updates :)

Thanks

**Comment by beto-rodriguez** [comment]
@hishaamn at least when you have an issue :smile:

**Comment by emilielalague** [comment]
Hello! I seem to have the same problem in version 0.9.7.0 of the lib. My pie chart is in a tab and I change the data from other tabs. When I make the change after having seen the pie chart, it works fine but if I change the data fisrt, the the app crashes. If I check for the chart not to be null, refreshing the data only when the chart is loaded, it works but as my pie chart are in a tab with contenttemplate, it only works for the first one. What can I do please?

**Comment by Lancelot97** [comment]
Hello guys, 
I've got the same problem with LiveCharts 0.9.7, LiveCharts.WPF 0.9.7 and LiveCharts.Geared 1.2.9 installed.
The problem arises when you add a Series with **null** as values to the SeriesCollection, then you call **SeriesCollection.Clear()**.

Hope this helps someone else.

Keep up the great job!
