### ISSUE TITLE
Could not load file or assembly System.Core, Version=2.0.5.0

### ISSUE THREAD

**Issue by fredericoregateiro** [beto-rodriguez/Live-Charts#212]
I've just got this error, on a app using Live-charts.
I tested on 2 pc's and they both have .net 4.5 installed, this error should only if the .net 4.0 not patched is installed? 

System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'
   at LiveCharts.ChartValues`1.GetLimits()
   at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations)
   at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick()
   at LiveCharts.Wpf.Components.ChartUpdater.<.ctor>b__0_0(Object sender, EventArgs args)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by beto-rodriguez** [comment]
Are you sure both are running .net 4.5? 

I think one of your machines have windows xp, does it?

**Comment by fredericoregateiro** [comment]
No, that's the weird part, one have Windows 8 and the other Windows 10!

**Comment by fredericoregateiro** [comment]
I've notice that the LiveCharts.Core.dll is a portable library, did you choose this type of project over a shared library for any reason?

I just recompile your source code and fix this error, but i created a shared library and reference the wpf view project to the project i create, and the error was gone.

**Comment by beto-rodriguez** [comment]
0.7 is designed to be a cross .net library, and Xamarin says that portable libraries areare the preferred method.

Xamarin is the main target of this library, this technology is growing really fast, LiveCharts need to be there!

https://xamarinhelp.com/portable-class-library-pcl-vs-shared-projects/

**Comment by beto-rodriguez** [comment]
So you first used the Nuget .dll and the error was there? then used the dll you compiled with the source code and it got fixed?

**Comment by fredericoregateiro** [comment]
Yes first i was using the nuget dll's, but to fix the error i created a shared project and copied all the files from the Core project.
So in the end i reference only one dll from my application, and this way produced no errors.
I think that the problem is that the code is compiled on .net 4.0, and System.Core 2.5 doesn't exist in .net 4.0, but in a patch released after KB2468871.
[http://www.hanselman.com/blog/FixingSystemCore205FileLoadExceptionPortableLibrariesAndWindowsXPSupport.aspx](url)

All the pc's i've tested also have .net 4.0 and 4.5 installed, but the patch is not, and because it's a pain to tell all my customers that that have to install a path to continue to use my app, so i preferre not to go that way.

It's great to hear that this project has eyes for the future, that's why i've chosen it over others.
The Shared vs PCL needs to be analysed case by case, in my opinion, they both have advantages and disadvantages.
For me, if i need to share the code with others, then the PCL is the way to go, but if i use it only for refactoring and it's never going to live outside my solution then it's shared project.
[https://docs.xamarin.com/guides/cross-platform/application_fundamentals/building_cross_platform_applications/sharing_code_options/](url)

Other say that the PCL give move pain to the developers 
[http://tirania.org/blog/archive/2016/Jan-22.html](url)

**Comment by fredericoregateiro** [comment]
If you want to take a look in the changes i've made:
[https://1drv.ms/u/s!Ag_dYVHDqujNiTv6OJc0UEHlBYlN](url)

**Comment by beto-rodriguez** [comment]
Thanks!

**Comment by beto-rodriguez** [comment]
@fredericoregateiro I guess I need to definitively remove the .net 4.0 build, because it will be bugged some times, like in your case if last patch is not installed, I will start the builds at 4.0.3, this way you I will force you that the patched is installed in your application, and you will not have these problems with your customers.

Sadly as you said you would need to update their .net framework, but there are many options for this, you could normally specify the min .net version in your installer, setting it to .net 4.0.3 should require your customers to install the last patch automatically.

**Comment by beto-rodriguez** [comment]
I really appreciate the code your shared with me, I added the "help wanted" label in case some one is interested in give us his/hers opinion. 

The problem is totally the patch, portable libraries are only supported in .net 4.0.3 not in 4.0, I need to remove this build since it could fail depending whether the patch is installed in the target machine.

For now I will only stop building for .net 4.0, the build will start at 4.0.3 this way I force your app to have at least [KB2468871](https://www.microsoft.com/en-us/download/details.aspx?id=3556) installed to run LiveCharts.

I now maybe it is hard to notify your customers to install this patch, but this could be done telling your installer that you need at least .net 4.0.3 it should force your customers to install the patch "automatically", at least it should notify them.

**Comment by rohit3d2003** [comment]
I like this approach of automatically forcing the app to install the patch. I believe we should stick with portable libraries since this is what Microsoft is promoting as well for their future app development and a way to go for every developer

**Comment by fredericoregateiro** [comment]
@beto-rodriguez Good to know that this can be fixed easily on your side. On my side i have no problems using .NET 4.0.3.
I will try to change to .NET 4.0.3 on your source code and do some tests

**Comment by beto-rodriguez** [comment]
Officially from 0.7.3.1 to next version support for .net 4.0 was dropped, your app must reference at least 4.0.1.

Added a .bat file to help the building process, the build should be available for everyone now, everything is here to build all the net versions and projects just clicking the LiveCharts.pack.bat file

**Comment by K3v1** [comment]
I am having the same problem despite .net 4.5. (Win7, VS Studio Express 2013)
The exception occurs if I add a CartesianChart to the usercontrol.xaml, but AngularGauge for example works.

Here is the stack trace:
FileNotFoundException: Die Datei oder Assembly "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden
bei LiveCharts.Charts.CartesianChartCore.PrepareAxes()
   bei LiveCharts.ChartUpdater.Update(Boolean restartsAnimations)
   bei LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView)
   bei LiveCharts.Wpf.Components.ChartUpdater.<.ctor>b__0_0(Object sender, EventArgs args)
   bei System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by K3v1** [comment]
![image](https://cloud.githubusercontent.com/assets/20948198/17580339/3318eee4-5f9e-11e6-8755-ee28af41f244.png)

These two components cause the error (the others not!).

**Comment by beto-rodriguez** [comment]
This issue is directly related with  https://www.microsoft.com/en-us/download/details.aspx?id=3556 

If you install that patch you wont have the issue anymore, what scares me the most is the idea that net 4.5 is not patched already!

**Comment by K3v1** [comment]
The installation was not successfull:
![image](https://cloud.githubusercontent.com/assets/20948198/17614143/15eff382-6064-11e6-8a8c-a0cd6f1b40ed.png)
-> KB2468871v2 does not fit or is blocked by another condition on your system.

4.5.1 and 4.5.2 do not solve the issue.

**Comment by beto-rodriguez** [comment]
Are you on windows xp?

**Comment by K3v1** [comment]
No, that is on Windows 7.
Maybe a company specific policy blocks the update. 

I finished my project with WPF Toolkit which is not as pretty as Live-Charts, but I met the deadline.
Thank you for your fast response and these great charts. I will try it in my next project.

**Comment by beto-rodriguez** [comment]
I hope a 1.0 version is ready in your next project, trying to get high performance ready asap

**Comment by GritsenkoSD** [comment]
I can not run the application on Windows XP. Install updates KB2468871.

**Comment by beto-rodriguez** [comment]
What is the error you get?

**Comment by GritsenkoSD** [comment]
Not a valid Win32 application

**Comment by beto-rodriguez** [comment]
How about if you install https://www.microsoft.com/en-us/download/details.aspx?id=29053

**Comment by GritsenkoSD** [comment]
I installed this update

**Comment by GritsenkoSD** [comment]
[http://s019.radikal.ru/i635/1610/6f/8fceb4357260.jpg](url)

**Comment by GritsenkoSD** [comment]
> Also ensure you are compiling in .net 4.0.3
http://s017.radikal.ru/i417/1610/ba/f649ecf7e9b6.png

**Comment by beto-rodriguez** [comment]
I am really not sure what could be wrong, I will reopen this issue, and wait for feed back from users, everyone please let us know if you can use the library in XP

**Comment by GritsenkoSD** [comment]
No application wants to work if it is assembled under 4.0.3 (Windows XP)

**Comment by beto-rodriguez** [comment]
Windows XP SP3 right?

**Comment by GritsenkoSD** [comment]
Yes, Windows XP service pack 3.

**Comment by beto-rodriguez** [comment]
I am done with issue, in the previous commit I added a new project targeting net40, it is just a copy paste of the core project, since it targets 4.0.3, I am sure there should be a way to compile the current code in net 40 since it requires no changes, but for now this works.

Since version 0.8 I will provide both builds in the nuget package

1) Net40
2) Portable class library profile 328 (the current one)

**Comment by GritsenkoSD** [comment]
Thank you! Checked, everything works.
