### ISSUE TITLE
Default Tooltip also shows values of invisible LineSeries

### ISSUE THREAD

**Issue by pusaken** [beto-rodriguez/Live-Charts#215]
V: 0.7.2.2:
When setting LineSeries to invisible their values still show up on the default tooltip.

**Comment by beto-rodriguez** [comment]
This is already fixed and will be included in next release,

here you can find an example

https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart/DynamicVisibility
