### ISSUE TITLE
Graph Type

### ISSUE THREAD

**Issue by hishaamn** [beto-rodriguez/Live-Charts#216]
Hi,

I wanted to know if with your current version of Live-Chart can allow this type of X-Axis as shown below:
![untitled](https://cloud.githubusercontent.com/assets/14113223/16149650/4fb5ddee-34a3-11e6-953a-541b2696b92c.png)

**Comment by beto-rodriguez** [comment]
This is not currently supported, we can add it in a future, I will let this issue open

**Comment by beto-rodriguez** [comment]
For Now I will close this issue, just because this charts is really specific, and for now, and a couple of moths there are some priorities, any ways I am tagging this issue with the "fufure request" label to keep track of it
