### ISSUE TITLE
Tick Marks and Bullet Style

### ISSUE THREAD

**Issue by Billy-Joel** [beto-rodriguez/Live-Charts#218]
Hi Beto,

Good day, I'm really excited to update the control to 7.3.  :)

Just wondering, does the control support tick marks and Bullet Style (Point Style)...
It will be very useful if we can change the points to any shape. The tick marks will also be helpful
to identify the actual point of an axis value specially when there is no axis separator line in the graph.

![tick](https://cloud.githubusercontent.com/assets/18839973/16187985/5bf019ce-36e4-11e6-8f92-09b333487595.PNG)

![bullet](https://cloud.githubusercontent.com/assets/18839973/16187967/4da5508c-36e4-11e6-86a5-5810033e920a.PNG)

Thanks.

Regards,
Billy Joel

**Comment by beto-rodriguez** [comment]
This was fixed with #226, I will explain better in 0.7.4 release

**Comment by Billy-Joel** [comment]
Thank you very much...

Question... Are the tick marks also included in this release? All I can see in the example are bullet Styles.

![tick](https://cloud.githubusercontent.com/assets/18839973/16360460/0c316f50-3b76-11e6-9ea8-a4d7cd001643.PNG)

**Comment by beto-rodriguez** [comment]
need to wait  for 0.7.4

**Comment by Billy-Joel** [comment]
Hi Beto,

Good day, I already updated my control to the latest one and its looking great. I manage to try the bullet style which is the point Shape property which is perfect by the way, but I'm still lost with the Tick mark. Tick Marks by the way is the line under the X Axis (in my example) right before the label indicating the point where the separator should be. But since some of the graphs do not require visible separator and some labels might possibly be long, Tick Marks are useful to identify where the actual x or y axis value should be. 

![tick](https://cloud.githubusercontent.com/assets/18839973/16550857/bb2c93d0-41c1-11e6-8dcd-61fddeab4488.PNG)


Sorry I'm having a problem cloning the repo and cannot view your example. I tried going through it but no luck.

Kindly point me to the right direction please.
Thank you very much.

Regards,
Billy Joel

**Comment by beto-rodriguez** [comment]
Oh I missed that, I am sorry, I misunderstood the issue, you were right, my commit only fixes Bullet Style, not Tick Marks, opening a new issue about it

**Comment by Billy-Joel** [comment]
No problem.... thanks...

**Comment by beto-rodriguez** [comment]
This was accidentally fixed in version 0.9
