### ISSUE TITLE
Axis labels remain visible on Axis.ShowLabels = false when LineSeries bound to that axis

### ISSUE THREAD

**Issue by pusaken** [beto-rodriguez/Live-Charts#219]
With 0.7.3:
The Axis labels can be removed by setting Axis(x).ShowLables = false. But it looks like as soon as there is a LineSeries linked to that Axis, the lables can no longer be removed :-(.

bye,
pusaken

**Comment by beto-rodriguez** [comment]
closed with https://github.com/beto-rodriguez/Live-Charts/commit/c13832a8e0d3918068da9e0443c996ff5ced3ef7 the fix will be included in next release (0.7.4)
