### ISSUE TITLE
Add custom color transition to heat map

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#223]
Currently the heat map supports cold and hot colors and automatically interpolates between the two.

I'd like to have a heat map where I can set a custom gradient brush (like blue-green-yellow-red) and have it use the stops that it defines.

**Comment by beto-rodriguez** [comment]
Guess you are right, updated example to support this feature, by default the gradient only contains 2 colors based on the default colors of the chart, but you can add many stops as required:

https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart/HeatChart

    <lvc:CartesianChart Grid.Row="1">
            <lvc:CartesianChart.Series>
                <lvc:HeatSeries Values="{Binding Values}" DataLabels="True">
                    <lvc:HeatSeries.GradientStopCollection>
                        <GradientStop Offset="0" Color="#99FFFF00"></GradientStop>
                        <GradientStop Offset=".25" Color="#FFFFFF00"></GradientStop>
                        <GradientStop Offset=".50" Color="#990000FF"></GradientStop>
                        <GradientStop Offset=".75" Color="#FF0000FF"></GradientStop>
                        <GradientStop Offset="1" Color="#50505050"></GradientStop>
                    </lvc:HeatSeries.GradientStopCollection>
                </lvc:HeatSeries>
            </lvc:CartesianChart.Series>
            <lvc:CartesianChart.AxisX >
                <lvc:Axis Labels="{Binding SalesMan}" LabelsRotation="-15">
                    <lvc:Axis.Separator>
                        <lvc:Separator Step="1"></lvc:Separator>
                    </lvc:Axis.Separator>
                </lvc:Axis>
            </lvc:CartesianChart.AxisX>
            <lvc:CartesianChart.AxisY>
                <lvc:Axis Labels="{Binding Days}"></lvc:Axis>
            </lvc:CartesianChart.AxisY>
        </lvc:CartesianChart>

![heatmap](https://cloud.githubusercontent.com/assets/10853349/16313609/80698526-393f-11e6-84d8-c5fb8546496c.gif)
