### ISSUE TITLE
ShowGridLine=False, is it possible?

### ISSUE THREAD

**Issue by RiderOfTheli** [beto-rodriguez/Live-Charts#224]
Hi,
I would like to ask, if it's possible to attach GridLineStyle, or ShowGridLines to your solution? Something like:

```
<lvc:CartesianChart.GridLineStyle>
        <Style TargetType="Line">
                <Setter Property="Stroke" Value="Red" />
                <Setter Property="StrokeDashArray" Value="2,4" />
         </Style>
</lvc:CartesianChart.GridLineStyle>
```

Or simply: `ShowGridLines="True"`

It would be great to change the color or disable GridLines for charts.
Thank you very much

**Comment by beto-rodriguez** [comment]
Hello

Please see http://lvcharts.net/App/examples/v1/wpf/About%20Series

in that example I make separators dashed, you can also disable them to make them invisible

    <lvc:CartesianChart.AxisX>
    <lvc:Axis IsMerged="True">
      <lvc:Axis.Separator>
        <lvc:Separator StrokeThickness="1" StrokeDashArray="2" IsEnabled="False"> 
          <lvc:Separator.Stroke>
            <SolidColorBrush Color="#404F56" />
          </lvc:Separator.Stroke>
        </lvc:Separator>
      </lvc:Axis.Separator>
    </lvc:Axis>
  </lvc:CartesianChart.AxisX>

let me know if this solves your issue!
