### ISSUE TITLE
Tooltip is clipped from other Usercontrols

### ISSUE THREAD

**Issue by camou23** [beto-rodriguez/Live-Charts#229]
![image](https://cloud.githubusercontent.com/assets/4669637/16381665/ed302426-3c7d-11e6-91fc-4f4fecb9aa75.png)

Is it maybe possible to give the Tooltip an Zindex of 100 maybe?
So it wouldnt be clipped from other Usercontrols.

I cant find the right place in the code.

**Comment by camou23** [comment]
![image](https://cloud.githubusercontent.com/assets/4669637/16381723/2ea85e50-3c7e-11e6-9033-35fe6bbd4877.png)

It gets also clipped by the Window Boundries

**Comment by camou23** [comment]
#230  should fix this i think

**Comment by camou23** [comment]
https://giphy.com/gifs/3o6gEb20IdgtuEKncI

**Comment by beto-rodriguez** [comment]
You PR was a nice try but it was not going to be enough, pelase see this alternative.

To solve this what we actually need to do is add  tooltip at the chart UI level, so we can always set a higher zindex that all the charts.

My idea was to wrap all the controls you need to force the tooltip to draw over, all the charts in this container must share this tooltip, also notice the tooltip will never go out the container, as you mentioned, it could overflow the window, with this method we also fix that.

For a fill example see https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart/SharedTooltip

Here a code snippet

    <Canvas Name="CanvasContainer">

        

        <lvc:DefaultTooltip Name="CurrentTooltip" Visibility="Hidden" 
                            Panel.ZIndex="100"
                            Canvas.Left="0" Canvas.Top="0"
                            IsWrapped="True">
            
        </lvc:DefaultTooltip>

        <Grid Height="{Binding ActualHeight, ElementName=CanvasContainer}" 
              Width="{Binding ActualWidth, ElementName=CanvasContainer}">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*"></ColumnDefinition>
                <ColumnDefinition Width="*"></ColumnDefinition>
                <ColumnDefinition Width="*"></ColumnDefinition>
            </Grid.ColumnDefinitions>

            <lvc:CartesianChart Grid.Column="0" Background="White"
                            DataTooltip="{Binding ElementName=CurrentTooltip}">
                <lvc:CartesianChart.Series>
                    <lvc:LineSeries Values="1,2,3,4,5" LabelPoint="{Binding LabelPoint}"></lvc:LineSeries>
                </lvc:CartesianChart.Series>
            </lvc:CartesianChart>
            <lvc:CartesianChart Grid.Column="1" Background="White"
                            DataTooltip="{Binding ElementName=CurrentTooltip}">
                <lvc:CartesianChart.Series>
                    <lvc:LineSeries Values="1,2,3,4,5" LabelPoint="{Binding LabelPoint}"></lvc:LineSeries>
                </lvc:CartesianChart.Series>
            </lvc:CartesianChart>
            <lvc:CartesianChart Grid.Column="2" Background="White"
                            DataTooltip="{Binding ElementName=CurrentTooltip}">
                <lvc:CartesianChart.Series>
                    <lvc:LineSeries Values="1,2,3,4,5" LabelPoint="{Binding LabelPoint}" ></lvc:LineSeries>
                </lvc:CartesianChart.Series>
            </lvc:CartesianChart>
        </Grid>
    </Canvas>

**Comment by beto-rodriguez** [comment]
From 0.9.2 and above this scenario is automatically supported, there is no need to wrap the tooltip in a container as it was in the previous versions, if you already did this in your code, your wrapping will be ignored but you code should compile correctly, there is no need to change your code, but I recommend you to do so just because it is now cleaner and this step is not necessary
