### ISSUE TITLE
LineSeries over StackedAreaSeries

### ISSUE THREAD

**Issue by NickSavin** [beto-rodriguez/Live-Charts#231]
Hello!

I have Winforms Chart in my WPF Application
![image](https://cloud.githubusercontent.com/assets/20172765/16391587/7dded404-3cb0-11e6-8b63-83b9b6adb42b.png)

I try to create the same with "LiveCharts" and have some problems:

![image](https://cloud.githubusercontent.com/assets/20172765/16391724/131d059a-3cb1-11e6-9a94-f3387602e42a.png)

1. LineSeries is shown incorrectly. Only point are visible , but a line is invisible.
2. Axis "Visiblity" property is not working
3. PointGeometry property on LineSeries is not available
as in documentation
http://lvcharts.net/App/examples/v1/wpf/Basic%20Line%20Chart

**Comment by NickSavin** [comment]
`<TabItem Header="Chart Awarenes livechart">

                                <lvc:CartesianChart  LegendLocation="Top" >
                                    <lvc:CartesianChart.AxisY>
                                        <lvc:Axis MinValue="0" MaxValue="1" Title="Share" MaxHeight="1"></lvc:Axis>
                                        <lvc:Axis MinValue="0" Title="Reach" MaxValue="1"  LabelFormatter="{Binding YFormatter}" MaxHeight="1" Position="RightTop"></lvc:Axis>
                                    </lvc:CartesianChart.AxisY>
                                    <lvc:CartesianChart.AxisX>
                                        <lvc:Axis MinValue="0" MaxValue="1"  MaxHeight="1"></lvc:Axis>
                                        <lvc:Axis MinValue="0" MaxValue="1"  MaxHeight="1"></lvc:Axis>
                                    </lvc:CartesianChart.AxisX>

                                    <lvc:CartesianChart.Series>

                                        <lvc:LineSeries          ScalesXAt="0"  ScalesYAt="0" Title="Value" Values="{Binding ReachPoints}"  />
                                        <lvc:StackedAreaSeries   ScalesXAt="1"  ScalesYAt="1" Title="Share TV" Values="{Binding ShareTVPoints }"  />
                                        <lvc:StackedAreaSeries   ScalesXAt="1"  ScalesYAt="1" Title="Share Internet" Values="{Binding ShareInternetPoints}"  />
                                    </lvc:CartesianChart.Series>

                                </lvc:CartesianChart>
                                

                            </TabItem>`

**Comment by NickSavin** [comment]
code behinde
`<TabItem Header="Chart Awarenes livechart">

                                <lvc:CartesianChart  LegendLocation="Top" >
                                    <lvc:CartesianChart.AxisY>
                                        <lvc:Axis MinValue="0" MaxValue="1" Title="Share" MaxHeight="1"></lvc:Axis>
                                        <lvc:Axis  MinValue="0" Title="Reach" MaxValue="1"  LabelFormatter="{Binding YFormatter}" MaxHeight="1" Position="RightTop"></lvc:Axis>
                                    </lvc:CartesianChart.AxisY>
                                    <lvc:CartesianChart.AxisX>
                                        <lvc:Axis MinValue="0" MaxValue="1"  MaxHeight="1"></lvc:Axis>
                                        <lvc:Axis Visibility="Hidden" MinValue="0" MaxValue="1"  MaxHeight="1"></lvc:Axis>
                                    </lvc:CartesianChart.AxisX>

                                    <lvc:CartesianChart.Series>

                                        <lvc:LineSeries          ScalesXAt="1"  ScalesYAt="1" Title="Value" Values="{Binding ReachPoints}"  />
                                        <lvc:StackedAreaSeries   ScalesXAt="0"  ScalesYAt="0" Title="Share TV" Values="{Binding ShareTVPoints }"  />
                                        <lvc:StackedAreaSeries   ScalesXAt="0"  ScalesYAt="0" Title="Share Internet" Values="{Binding ShareInternetPoints}"  />
                                    </lvc:CartesianChart.Series>

                                </lvc:CartesianChart>
                                

                            </TabItem>`

**Comment by beto-rodriguez** [comment]
Hello, I will try to answer you your question, this library needs better documentation, I am on it, LiveCharts is useless if it is not documented property.

1) The line is there, but it is behind the areas, use the Panel.ZIndex property to bring it to front.

    System.Windows.Controls.Panel.SetZIndex(myLineSeries, 0);

2) Axis Visibility property is not the one the library uses to hide the axis, use Axis.ShowLabels instead, I agree with you that the visibility property is more intuitive I will see what I can do there

3) Point geometry is only available at 0.7.4 as the web site says at the top of the page, this feature was added a couple of days ago, and its only available in 0.7.4 I am working to publish it asap.

**Comment by NickSavin** [comment]
Big thanks for operative answer! It was very useful

**Comment by NickSavin** [comment]
I have a new problem. Can you help?

![image](https://cloud.githubusercontent.com/assets/20172765/16409469/5b655e72-3d26-11e6-88bc-42636fbbd254.png)

At the TopLeft corner is an artifact. at position (1,0) area is not fill.
But at BottomRignt coner, position (1,0) is all right


`
<TabItem Header="Chart Awarenes livechart">

                                <lvc:CartesianChart   LegendLocation="Top"  Margin="5" Padding="5">

                                    <lvc:CartesianChart.ChartLegend>
                                        <lvc:DefaultLegend Margin="0,0,0,10"/>
                                    </lvc:CartesianChart.ChartLegend>
                                    
                                    <lvc:CartesianChart.AxisY>                                        
                                        
                                        <lvc:Axis MinValue="0" MaxValue="1" Title="Share" MaxHeight="1">
                                            <lvc:Axis.Separator>
                                                <lvc:Separator IsEnabled="False"/>
                                            </lvc:Axis.Separator>
                                        </lvc:Axis>
                                        <lvc:Axis  MinValue="0" Title="Reach" MaxValue="1"  LabelFormatter="{Binding YFormatter}" MaxHeight="1" Position="RightTop" Margin="10">
                                            <lvc:Axis.Separator>
                                                <lvc:Separator IsEnabled="False"/>
                                            </lvc:Axis.Separator>
                                        </lvc:Axis>
                                        
                                    </lvc:CartesianChart.AxisY>
                                    <lvc:CartesianChart.AxisX>
                                        <lvc:Axis MinValue="0" MaxValue="1"  MaxHeight="1" Margin="10" Title="Awareness">
                                            <lvc:Axis.Separator>
                                                <lvc:Separator IsEnabled="False"/>
                                            </lvc:Axis.Separator>
                                        </lvc:Axis>
                                        <lvc:Axis ShowLabels="False"  MinValue="0" MaxValue="1"  MaxHeight="1">
                                            <lvc:Axis.Separator>
                                                <lvc:Separator IsEnabled="False"/>
                                            </lvc:Axis.Separator>
                                        </lvc:Axis>
                                    </lvc:CartesianChart.AxisX>

                                    <lvc:CartesianChart.Series>

                                        <lvc:LineSeries         Panel.ZIndex="4"  PointDiameter="0"  ScalesXAt="1" ScalesYAt="1"  Stroke="DarkMagenta" Fill="Transparent" Title="Value" LineSmoothness="1"
                                                                Values="{Binding ReachPoints}"  />
                                        <lvc:StackedAreaSeries  Panel.ZIndex="2"  ScalesXAt="0" ScalesYAt="0"  Fill="{StaticResource  brush1 }" Title="Share TV" 
                                                                Values="{Binding ShareTVPoints }"  />
                                        <lvc:StackedAreaSeries  Panel.ZIndex="3"  ScalesXAt="0"  ScalesYAt="0" Fill="{StaticResource  brush2 }" Title="Share Internet" 
                                                                Values="{Binding ShareInternetPoints}"  />
                                    </lvc:CartesianChart.Series>

                                </lvc:CartesianChart>
                                

                            </TabItem>
`

**Comment by NickSavin** [comment]
Chart is not paint a first point in binded collection with value (1,0)

**Comment by beto-rodriguez** [comment]
ill test this

**Comment by NickSavin** [comment]
If I delete StackedAreaSeries "Share TV",  the "Share Internet" series is painted properly.

![image](https://cloud.githubusercontent.com/assets/20172765/16443812/76d58408-3de3-11e6-8d2a-1a6cd1ab7bc3.png)

StackedAreaSeries "Share TV" first point is (0,1) end point (1,0)
StackedAreaSeries "Share Internet" first point is (0,0) end point (1,1)

step is 0.01

**Comment by NickSavin** [comment]
is there any solution?

**Comment by beto-rodriguez** [comment]
Please be patient :disappointed:  remember I am the only one supporting the library right now, I could answer you faster if you create a repo with the issue, so I can see the bug runing, other wise you need to wait for me to build and test the example

you can also sen me an email with the bug (already have 5 mails in queue), help me to help you

**Comment by NickSavin** [comment]
Big thanks for your answer, and for your library. I will send you email with bug

**Comment by beto-rodriguez** [comment]
I added a note in the source code to explain this

https://github.com/beto-rodriguez/Live-Charts/blob/34af117fbb37b34edcf1432fba2d843fb8943567/Core/Charts/ChartCore.cs#L545

OK this issue is solved for you case, and for 90% of future developers

the other 10% will need a tricky solution

**What is going on here?**

LiveCharts stacks in both directions left (negatives) and right (positives)

You had a zero, zero is not negative, not positive, so it was actually being stacked with the negative values, instead of positives, where you needed it.

I changed the code so zero will always be stacked with the positives, only because this is what we all developers normally need.

But in a case where you need the zero to stack with the negatives, for now you must not use zeros, instead use a numeric approach, e.g. -0.000000001 it is practically zero, but not zero, now you will force your point to be stacked with the negatives.

**Comment by beto-rodriguez** [comment]
That was the explanation, now to get this fixed for you you must wait for the next release, I hope tomorrow I can release a version.

Or you could also clone the repo, and compile your binaries

Hope this helps you!

**Comment by cyrusd87** [comment]
@beto-rodriguez  I would like to focus the zoom where there are the two stacks, is there a way to make this? 

Actual situation is this
![image](https://cloud.githubusercontent.com/assets/9257354/20887730/2ce9013a-bafc-11e6-9aa2-a8c00ed116ec.png)


I would like to have this result

![image](https://cloud.githubusercontent.com/assets/9257354/20887707/1a01a40a-bafc-11e6-8e89-19814bfd469c.png)
