### ISSUE TITLE
What is the best way to Deep Copy/Clone Live-Charts objects and collections?

### ISSUE THREAD

**Issue by carlmichaelbenson** [beto-rodriguez/Live-Charts#234]
What is the best way to Deep Copy/Clone a CartesianChart, or collections in the chart like SeriesCollection, AxesCollection, VisualElementsCollection, etc.? Thanks.

**Comment by beto-rodriguez** [comment]
This is normally a problem with any .net object, How did you solve this?

When I face this problem, normally serializing, and serializing is enough but I don't think it will work in this case.

**Comment by beto-rodriguez** [comment]
I will close the issue, since this is not a specific issue with the library
