### ISSUE TITLE
How to use binding SeriesCollection at Datatemplate

### ISSUE THREAD

**Issue by Yukimune** [beto-rodriguez/Live-Charts#236]
Hi! 
I'm writing some LineChart(0.7.3.1) in WPF(TargetFramework 4.6.1).
I try to draw multiple CarttesianChart by DataTemplate.
So I'm tring bind to CartesianChart.Series in DataTemplate.
And run it, I can show all items are drawn, but binded seriescollection doesn't well.

xaml code bellow.

    <Grid>
        <StackPanel>
            <ItemsControl ItemsSource="{Binding Items}">
                <ItemsControl.ItemTemplate>
                    <DataTemplate>
                        <StackPanel>
                            <TextBlock Text="{Binding Key}"></TextBlock>
                            <lvc:CartesianChart Series="{Binding Collection}"></lvc:CartesianChart>
                        </StackPanel>
                    </DataTemplate>
                </ItemsControl.ItemTemplate>
            </ItemsControl>
        </StackPanel>
    </Grid>

code behind bellow

    public partial class MainWindow : Window
    {
        public ObservableCollection<SeriesViewModel> Items { get; private set; }
        public MainWindow()
        {
            InitializeComponent();
            Items = new ObservableCollection<SeriesViewModel>();
            for (int i = 0; i < 3; i++)
            {
                Items.Add(new SeriesViewModel(i.ToString("00")));
            }

            DataContext = this;
        }
    }

    public class SeriesViewModel
    {
        public string Key { get; private set; }
        public SeriesCollection Collection { get; private set; } = new SeriesCollection();

        public SeriesViewModel(string name)
        {
            Key = "TextBlock " + name;
            Collection.Add(new LineSeries
            {
                Title ="Title "+ name,
                Values = new ChartValues<double> { 1, 3, 4, 5 }
            });
        }
    }

As result bellow.
![result](https://cloud.githubusercontent.com/assets/5716130/16477036/14ad3cee-3ec9-11e6-9029-0b307e4815c5.png)

Thanks;)

**Comment by NickSavin** [comment]
try to use
`ChartValues<ObservablePoint>`

in

`Collection.Add(new LineSeries
        {
            Title ="Title "+ name,
            Values = new ChartValues<double> { 1, 3, 4, 5 }
        });
`

**Comment by Yukimune** [comment]
I've tryed it, but nothing changed.
code bellow

    public class SeriesViewModel:INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        private static readonly PropertyChangedEventArgs CollectionPropertyChangedEventArgs = new PropertyChangedEventArgs(nameof(Collection));

        private SeriesCollection coll=new SeriesCollection();

        public SeriesCollection Collection
        {
            get { return this.coll=new SeriesCollection(); }
            set
            {
                if (this.coll== value) { return; }
                this.coll= value;
                this.PropertyChanged?.Invoke(this, CollectionPropertyChangedEventArgs);
            }
        }

        public string Key { get; private set; }

        public SeriesViewModel(string name)
        {
            Key = "TextBlock " + name;
            Collection.Add(new LineSeries
            {
                Title = "Title " + Key,
                Values = new ChartValues<double> { 1, 3, 4, 5 }
            });
        }
    }

I found SeriesCollection.CollectinoChanged event has fired when Add().
But SeriesCollection class doesn't implemented System.Collections.Specialized.INotifyCollectionChanged.

**Comment by beto-rodriguez** [comment]
@Yukimune I will test this and let you know, thanks for reporting.

And yes, this library does not use INotifyCollection changed since 0.7.0, since ObservableCollections are only available in WPF and 0.7 was design to be a cross net project, we use our own cross net class NoisyCollection

**Comment by Yukimune** [comment]
@beto-rodriguez Thank you. 
Ok, I stopped write all in DataTemplate, and separated as UserControl.
Finally works well! Thank you.

MainWindow.xaml

    <Grid>
        <StackPanel>
            <ItemsControl ItemsSource="{Binding Items}">
                <ItemsControl.ItemTemplate>
                    <DataTemplate>
                        <ContentControl Content="{Binding}"></ContentControl>
                    </DataTemplate>
                </ItemsControl.ItemTemplate>
            </ItemsControl>
        </StackPanel>
    </Grid>
UserControl1.xaml

    <Grid>
        <StackPanel>
            <TextBlock Text="{Binding Key}"></TextBlock>
            <lvc:CartesianChart Series="{Binding Collection}"></lvc:CartesianChart>
        </StackPanel>
    </Grid>
MainWindow.xaml.cs

    public partial class MainWindow : Window
    {
        public ObservableCollection<UserControl1> Items { get; private set; } = new ObservableCollection<UserControl1>();
        public MainWindow()
        {
            InitializeComponent();
            
            for (int i = 0; i < 3; i++)
            {
                Items.Add(new UserControl1(new SeriesViewModel(i.ToString("00"))));
            }
            DataContext = this;
            var timer = new System.Windows.Threading.DispatcherTimer();
            // testing add dynamically
            timer.Interval = TimeSpan.FromSeconds(2);
            timer.Tick += (s, e) => { Items.Add(new UserControl1(new SeriesViewModel("new added"))); };
            timer.Start();
        }
    }
