### ISSUE TITLE
Cartesian Line Series Always a Straight Line

### ISSUE THREAD

**Issue by mbithy** [beto-rodriguez/Live-Charts#238]
See sublimeted image
![straightline](https://cloud.githubusercontent.com/assets/4972810/16488262/72c67110-3ed8-11e6-9d70-cf8bd6ee0b80.png)
Yet the points have different values...

**Comment by beto-rodriguez** [comment]
I am not able to reproduce this issue, please help me with more info

**Comment by mbithy** [comment]
I am on windows 10 64bit, the observable chart values range from between 1.100000 to about 1.300000 basically the current EURUSD bid price. Chart set up and code behind is like in your examples

**Comment by beto-rodriguez** [comment]
it seems like you fixed the Y Min and Max values, try setting explicitly them to null, or try forcing them to a range is useful in your case, for example AxisY[0].MinValue = 1.1, AxisY[0].MaxValue = 1.3

if they are failing with null then it should be a bug, sadly I can not force it

**Comment by mbithy** [comment]
null works OK.
