### ISSUE TITLE
Simple Question for  Line Chart

### ISSUE THREAD

**Issue by briggsyuk** [beto-rodriguez/Live-Charts#239]
Hello,

I am sure i will immediately be shouted at for using VB.net but can anyone provide me a simple example of how to use a line chart in VB.NET, from there i can probably figure everything else out.

c# > vb converters cant make sense of most examples i see on the website.

I already use the gauges and really want to learn how to use your charts.

Thank you.
Briggsy

**Comment by beto-rodriguez** [comment]
Sadly writing all example in both c# and vb net is impossible right now, I will consider that but only once we have a 1.0 version and this library is at least Xamarin and UWP, that will take months.

I have to say that 3 years ago I knew nothing about c# only vb, you should give it a try to c#, if you really now vb you know c#, they are brothers, most examples in the web are written in c#.

Really if you know vb it will take you 3 days and you will be an expert in c#, it is the same language with some makeup.

**Comment by briggsyuk** [comment]
Hello, Thank you, i will be learning C# in the future but i dont have the time to re-write my project in c# and learn c# at the moment. 

I was just after a very simple example not a whole document so i can finish up my project this week.

Thanks for your time and efforts.
