### ISSUE TITLE
LineSeries PointDiameter missing

### ISSUE THREAD

**Issue by Showmaster3000** [beto-rodriguez/Live-Charts#242]
After upgrading to latest version 0.7.4, the attribute PointDiameter is not available anymore. Can't find the new/changed option. The documentation still lists PointDiameter in examples.

The following code snipset worked in 0.7.3
CC_Chart3.Series.Add(new LineSeries()
{
     Values = GetData(3),
     StrokeThickness = 1,
     PointDiameter = 0    //  <-- this line fails in 0.7.4
 });

**Comment by beto-rodriguez** [comment]
Please see https://github.com/beto-rodriguez/Live-Charts/releases/tag/0.7.4

I always document everything in the Releases section, I renamed that property to match the new PointGeometry property, now you can use any geometry, not only points

**Comment by Showmaster3000** [comment]
Ah, sorry and thank you. Didn't see this page, because the search function didn't list it.
