### ISSUE TITLE
chart.toPNG

### ISSUE THREAD

**Issue by brogine** [beto-rodriguez/Live-Charts#243]
Hi, i was wondering if it's possible to add an option to export all charts to an image format.
I'm planning to use this awesome library to automatize an exorbitant amount of data sources into one application. My final report must be in a plain format, so i'll be needing this feature.

Thanks!

**Comment by eduard-schwenk** [comment]
@brogine, i think this can be done with the **RenderTargetBitmap** directly
a Sample can be found here:
http://stackoverflow.com/questions/2522380/get-a-bitmap-image-from-a-control-view
i used this for other usercontrol but must be work for every wpf controls.

**Comment by beto-rodriguez** [comment]
Yeah I agree with @eduard-schwenk

**Comment by brogine** [comment]
Thank guys. I've ended up using this function:

```c#
public static Bitmap ControlToImage(Visual target, double dpiX, double dpiY)
        {
            if (target == null)
            {
                return null;
            }
            // render control content
            Rect bounds = VisualTreeHelper.GetDescendantBounds(target);
            RenderTargetBitmap rtb = new RenderTargetBitmap((int)(bounds.Width * dpiX / 96.0),
                                                            (int)(bounds.Height * dpiY / 96.0),
                                                            dpiX,
                                                            dpiY,
                                                            PixelFormats.Pbgra32);
            DrawingVisual dv = new DrawingVisual();
            using (DrawingContext ctx = dv.RenderOpen())
            {
                VisualBrush vb = new VisualBrush(target);
                ctx.DrawRectangle(vb, null, new Rect(new System.Windows.Point(), bounds.Size));
            }
            rtb.Render(dv);

            //convert image format
            MemoryStream stream = new MemoryStream();
            BitmapEncoder encoder = new BmpBitmapEncoder();
            encoder.Frames.Add(BitmapFrame.Create(rtb));
            encoder.Save(stream);

            return new Bitmap(stream);
        }
```

**Comment by ceds** [comment]
Hi everyone,

Above is a solution for WPF.  What about winforms?

**Comment by MartinBodocky** [comment]
What about solution which is not using visual components ? Like generate chart pictures directly?
Thanks

**Comment by beto-rodriguez** [comment]
@MartinBodocky @ceds for both cases you can try this sample:

https://github.com/beto-rodriguez/Live-Charts/blob/master/Examples/Wpf/CartesianChart/Chart%20to%20Image/ChartToImageSample.xaml.cs

**Comment by omairzia** [comment]
Hi,
I have followed the above mentioned link to generate an image of live graph in my application and it is working fine locally but when I deploy it on azure it is not doing anything. I am getting an empty image that does not contains graph in it further I have checked in logs no error or exception is being thrown. It seems that it is not working on Azure.

Can anybody help me please?

**Comment by omairzia** [comment]
I can reproduce the issue on my local environment now by just commenting the following line of code:

myChart.Update(true, true); //force chart redraw
viewbox.UpdateLayout();

It seems that control cannot be updated on Azure. I have also tried to update the controls through "Dispatcher" but still getting the same issue on Azure.

Please help me to resolve this issue.
