### ISSUE TITLE
sign.pfx  file not exist

### ISSUE THREAD

**Issue by chucklu** [beto-rodriguez/Live-Charts#245]
1>------ Rebuild All started: Project: WinFormsView, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2884,5): error MSB3322: Unable to get MD5 checksum for the key file "sign.pfx". Could not find file 'D:\SourceCode\GitHub\Live-Charts\WinFormsView\sign.pfx'.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by beto-rodriguez** [comment]
Try pulling the most recent version of this library, it works correctly in the current repo version

or you could just uncheck the "Sing the assembly" option, go to Properties -> Singing then uncheck the option

**Comment by chucklu** [comment]
thank you ,I forgot to merge the origin/master
