### ISSUE TITLE
[bug] NullReferenceException when set DisableAnimations="True"

### ISSUE THREAD

**Issue by vmatkarimov** [beto-rodriguez/Live-Charts#251]
LiveCharts version 0.7.5.1

I have a NullReferenceException when set DisableAnimations="True".

**Comment by beto-rodriguez** [comment]
I am not able to force this issue, can you please give me more info about it, which series are you using? stack trace, or any code snippet would be really useful

**Comment by Yukimune** [comment]
Hi, I've repro.
It's happend at 0.7.5, but 0.7.6 doesn't.

In LiveCharts Example 
I've tested at CustomTooltipAndLegendExample, added `DisableAnimations="True"` like bellow.
CustomTooltipAndLegendExample.xaml:11
`<lvc:CartesianChart LegendLocation="Right" DisableAnimations="True">`

Then run. NullReferenceException has occured at ChartUpdater.cs:63.

Stack Trace:

System.NullReferenceException はハンドルされませんでした。
  HResult=-2147467261
  Message=オブジェクト参照がオブジェクト インスタンスに設定されていません。
  Source=LiveCharts
  StackTrace:
       場所 LiveCharts.ChartUpdater.<Update>b__15_0(ISeriesView s) 場所 D:\Documents\Repos\github\Live-Charts\Core\ChartUpdater.cs:行 63
       場所 LiveCharts.Helpers.Extentions.ForEach[T](IEnumerable`1 source, Action`1 predicate) 場所 D:\Documents\Repos\github\Live-Charts\Core\Helpers\Extentions.cs:行 41
       場所 LiveCharts.ChartUpdater.Update(Boolean restartsAnimations) 場所 D:\Documents\Repos\github\Live-Charts\Core\ChartUpdater.cs:行 63
       場所 LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView) 場所 D:\Documents\Repos\github\Live-Charts\WpfView\Components\ChartUpdater.cs:行 78
       場所 LiveCharts.Wpf.Components.ChartUpdater.<.ctor>b__0_0(Object sender, EventArgs args) 場所 D:\Documents\Repos\github\Live-Charts\WpfView\Components\ChartUpdater.cs:行 39
       場所 System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
       場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       場所 System.Windows.Threading.DispatcherOperation.InvokeImpl()
       場所 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       場所 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       場所 System.Windows.Threading.DispatcherOperation.Invoke()
       場所 System.Windows.Threading.Dispatcher.ProcessQueue()
       場所 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       場所 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       場所 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       場所 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       場所 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       場所 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       場所 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       場所 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       場所 System.Windows.Application.RunDispatcher(Object ignore)
       場所 System.Windows.Application.RunInternal(Window window)
       場所 System.Windows.Application.Run(Window window)
       場所 System.Windows.Application.Run()
       場所 Wpf.App.Main()
       場所 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       場所 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       場所 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       場所 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       場所 System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

I wish it's helpful for you. .;)

**Comment by beto-rodriguez** [comment]
@Yukimune @vmatkarimov Thanks to both I could finally force this issue, with your help and #265

**Comment by beto-rodriguez** [comment]
Last commit should fix this, thanks for reporting, this fix will be publish with 0.7.8 version

**Comment by vmatkarimov** [comment]
Thanks Beto, I'll try it right now.
