### ISSUE TITLE
Cartesian Graph - Winforms (can I do it questions)

### ISSUE THREAD

**Issue by chanbrown007** [beto-rodriguez/Live-Charts#254]
Hi,

Is there a way to perform a check to see if mouse location is over a chartPoint and if so return the chartpoint (similar to Chart.hitTest in winforms)?

Also is there any way to add StripLines (a vertical or horizontal line that spans the entire graph)?

Thank,
Chandler

**Comment by beto-rodriguez** [comment]
Hello

The first question, it is interesting, maybe we need another event in the charts, `ChartPointMouseOver`, currently there is only an event that is called every time a user click on a chartpoint, the `DataClick` event.

About StripLines, yeah, please see http://lvcharts.net/App/examples/v1/wpf/Sections In that exampl I draw a yellow line.

**Comment by chanbrown007** [comment]
On a more general level, is there a way to just do a standard click or mousemove event with the livechart for winform? What could be cool is that both those events in the arguments passed could return if a chartpoint was clicked or hovered over. For example in my use, I had built a tool that was relying on the regular winform chart, but I kept hitting limitations and performance drops and so I now am currently changing the entire implementation to use LiveCharts instead. But one of the main features I was using heavily was the ability to right click on a chart anywhere and get a drop down menu that could vary based off whether a point was selected or not.

**Comment by beto-rodriguez** [comment]
Interesting request, I will se how to solve this

**Comment by beto-rodriguez** [comment]
@chanbrown007 There is already an event when you click any data point 

I added an example to winforms, I think this should solve your issue.

Please let me know if this is not enough

Example here https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/WinForms/Cartesian/BasicLine
