### ISSUE TITLE
Designer NRE on binding Axes

### ISSUE THREAD

**Issue by NickSavin** [beto-rodriguez/Live-Charts#258]
![image](https://cloud.githubusercontent.com/assets/20172765/16851154/ed79cd02-4a0a-11e6-9331-02f9b4ad5e2f.png)

binded collection 
`

        public AxesCollection ChartAxesY { get; set; } = new AxesCollection()
        {
            new LiveCharts.Wpf.Axis() { Title="1111" },
        };
        public AxesCollection ChartAxesX { get; set; } = new AxesCollection()
                    {
            new LiveCharts.Wpf.Axis() { Title="1111" },
        };

`

**Comment by beto-rodriguez** [comment]
should be solved in future versions, thanks for reporting

**Comment by NickSavin** [comment]
Thank you!!!
