### ISSUE TITLE
Default Legend content Allignment

### ISSUE THREAD

**Issue by NickSavin** [beto-rodriguez/Live-Charts#259]
![image](https://cloud.githubusercontent.com/assets/20172765/16853134/cf27ab0e-4a13-11e6-8b9e-6f19405a43f4.png)

Hello!

Default Legend content spaces a not equal Like in Winforms charts.

![image](https://cloud.githubusercontent.com/assets/20172765/16853081/916022ce-4a13-11e6-9887-3c837b4874b5.png)

Using the custom legend is not good solution, because it it a common issue, as i think.

**Comment by beto-rodriguez** [comment]
you are right, just fixed this by default you will get a legend as you require it in future versions
