### ISSUE TITLE
Feature Request: Support adding Text objects to the chart

### ISSUE THREAD

**Issue by carlmichaelbenson** [beto-rodriguez/Live-Charts#26]
Hi,

It would be great to be able to add Text objects, or images, to the chart or series similar to what ZedGraph provides in ZedGraphControl.GraphPane.GraphObjList.Add(text). Thanks.

Cheers

**Comment by beto-rodriguez** [comment]
moved to #32

**Comment by carlmichaelbenson** [comment]
Can this be reopened, since there is no way to add Text objects, images, etc. to the chart in version 0.7.0+

**Comment by beto-rodriguez** [comment]
This is already supported, now it should be more MVVM friendly than previous method, here is an example

https://github.com/beto-rodriguez/Live-Charts/blob/master/Examples/Wpf/CartesianChart/UIElements/UIElementsExample.xaml
