### ISSUE TITLE
Live-charts and ObservableCollection + Linq?

### ISSUE THREAD

**Issue by RiderOfTheli** [beto-rodriguez/Live-Charts#261]
Hi,

I have found this on stackoverflow:
[http://stackoverflow.com/questions/38016190/use-linq-to-populate-live-charts-seriescollection](http://stackoverflow.com/questions/38016190/use-linq-to-populate-live-charts-seriescollection)
And I'm trying to adapt it to latest version of Live-Charts (0.7.6), but I guess I need helping hand here...

thank you for your support

**Comment by beto-rodriguez** [comment]
Hello

Please see http://lvcharts.net/App/examples/v1/wpf/Using%20LINQ

**Comment by RiderOfTheli** [comment]
Thank you, it works for me. I've got a one question - how to implement it to Basic Stacked Columns? Should I split the result into e.g Dates and then add it to StackedColumnSeries?

Thank you
