### ISSUE TITLE
Series color issue

### ISSUE THREAD

**Issue by NickSavin** [beto-rodriguez/Live-Charts#263]
This issue depend on #262 

When i fill my series collection by first call of my method

![image](https://cloud.githubusercontent.com/assets/20172765/16869192/444b5a96-4a84-11e6-80ac-b9fd9ecfefa7.png)

when I call my method second time , it calls seriescollection.clear() and fill it with a new series, but with a new colors =)

![image](https://cloud.githubusercontent.com/assets/20172765/16869269/b677596c-4a84-11e6-82ea-e19ada3be692.png)

![image](https://cloud.githubusercontent.com/assets/20172765/16869312/e12b66a8-4a84-11e6-9c46-5419aa1aad27.png)

Its not good =)

**Comment by beto-rodriguez** [comment]
This is actually the safest way for the library, every time a series is added it increments a counter, that is why you get a new color, this is safe so color never repeat, any ideas to change this is appreciated.

You can always force the colors fo your series as:

    <lvc:LineSeires Stroke="Red" />

**Comment by NickSavin** [comment]
Thank you!
`
<lvc:LineSeires Stroke="Red" /> 
`
 is all right.

But what do you think about to reset counter after calling seriescollection.clear() ?

**Comment by beto-rodriguez** [comment]
I like it, will commit that to close this issue
