### ISSUE TITLE
The same information bind two different Charts will be wrong

### ISSUE THREAD

**Issue by jackswei** [beto-rodriguez/Live-Charts#264]
xaml：
   ```
 <lvc:CartesianChart Grid.Row="1">
            <lvc:CartesianChart.Series>
                <lvc:LineSeries Fill="Transparent"
                                LineSmoothness="1"
                                PointForeround="#222E31"
                                PointGeometrySize="15"
                                Stroke="#1C8FC5"
                                StrokeThickness="2"
                                Values="{Binding TDS}" />
                <lvc:ColumnSeries Configuration="{Binding Mapper}" Values="{Binding TDS}" />
            </lvc:CartesianChart.Series>
        </lvc:CartesianChart>

```
cs:
  ```
 public partial class MainWindow : MetroWindow
    {

        public CartesianMapper<ObservableValue> Mapper { get; set; }
        public ChartValues<ObservableValue> TDS { get; set; }
        private Thread _TcomSend;
        public MainWindow()
        {
            TDS = new ChartValues<ObservableValue>
            {
                new ObservableValue(30),
                new ObservableValue(50),
                new ObservableValue(70),
                new ObservableValue(80),
                new ObservableValue(90),
                new ObservableValue(100)
            };
            Mapper = Mappers.Xy<ObservableValue>()
                .X((item, index) => index )
                .Y(item => item.Value); 
    DataContext = this;
        }

        private void DoSendData()
        {
            Random crandom = new Random();
            while (true)
            {
                Thread.Sleep(2000);   
                foreach (var observable in TDS)
                                {
                    observable.Value = crandom.Next(10, 400);
                   }
            }
        }
    }
}

```

![2](https://cloud.githubusercontent.com/assets/6355204/16894288/46005d40-4b84-11e6-930b-548bb725b916.png)
![3](https://cloud.githubusercontent.com/assets/6355204/16894289/460296c8-4b84-11e6-98b1-039068ddab77.png)

**Comment by beto-rodriguez** [comment]
Thanks for your report, I will fix this with High Performance release since it is related with it

**Comment by beto-rodriguez** [comment]
Notice in this example you don't need to configure ObservableValue, it is already configured globally in the library

**Comment by beto-rodriguez** [comment]
This is now supported and will be released with the next version of the library, now you can:

    var r = new Random();

            var vals = new ChartValues<ComplexModel>
            {
                new ComplexModel { A= r.Next(0,10), B= r.Next(0,10) },
                new ComplexModel { A= r.Next(0,10), B= r.Next(0,10) },
                new ComplexModel { A= r.Next(0,10), B= r.Next(0,10) },
            };

            Series = new SeriesCollection
            {
                new ColumnSeries(Mappers.Xy<ComplexModel>().Y(x => x.A))
                {
                    Values = vals
                },
                new ColumnSeries(Mappers.Xy<ComplexModel>().Y(x => x.B))
                {
                    Values = vals
                }
            };
