### ISSUE TITLE
Legend issue

### ISSUE THREAD

**Issue by NickSavin** [beto-rodriguez/Live-Charts#266]
Hello, Alberto!

legend with a lot of items is out of container panel

![image](https://cloud.githubusercontent.com/assets/20172765/16899912/a5ff3520-4c1c-11e6-872c-efef13b54e16.png)

![image](https://cloud.githubusercontent.com/assets/20172765/16899914/c0884d46-4c1c-11e6-9a48-d43f440f64f9.png)

Its a sample on winforms
![image](https://cloud.githubusercontent.com/assets/20172765/16899930/1e23fb30-4c1d-11e6-9802-9701d2bfefab.png)

**Comment by beto-rodriguez** [comment]
You are being so rude with legends! :smile: 

Will see what I can do here, thanks for reporting

**Comment by NickSavin** [comment]
Your library becomes mach better from version to version =) 
Thank you

**Comment by beto-rodriguez** [comment]
Should be solved with last commit, a test:

![deflegend](https://cloud.githubusercontent.com/assets/10853349/16923197/b43050c6-4cde-11e6-8004-f58a3606a8f8.gif)
