### ISSUE TITLE
Is live-charts could use mvvm pattern binding data and display?

### ISSUE THREAD

**Issue by flyaim** [beto-rodriguez/Live-Charts#27]
Is live-charts could use mvvm pattern binding data and display? If it can，how to use？Thanks！

**Comment by beto-rodriguez** [comment]
Yes it can. it is ready for wpf bindings you could use all you know with wpf to make this work. I currently don't have an example. Maybe and just maybe in a future I will add an exmaple to test project. Please try it if something is not working I can help you. 

Thanks.

**Comment by gregsdennis** [comment]
I had to create an attached property in order to fill in data from my view model in C#.  Is there a pure-XAML solution?

**Comment by beto-rodriguez** [comment]
it should be possible the problem I see is that write the next block of code as Xaml will result complex, I think an IValueConverter could be a good solution

```
LineChart.Series = new ObservableCollection<Serie>
            {
                new LineSerie
                {
                    PrimaryValues = new ObservableCollection<double>
                    {
                        -10, 5, 9, 28, -3, 2, 0, 5, 10, 1, 7, 2
                    }
                }
            };
```

**Comment by gregsdennis** [comment]
@flyaim,

@beto-rodriguez merged in some changes today that should help with your MVVM needs.  Download the latest source and look at the XAML in the second tab for how to bind data.

**Comment by beto-rodriguez** [comment]
I am clsing this issue, now Test project includes an MVVM example for each chart

**Comment by flyaim** [comment]
@beto-rodriguez 
@gregsdennis 
got it，i will try，thank you！
