### ISSUE TITLE
gap between OhlcPoint and axis X separator

### ISSUE THREAD

**Issue by hulihutu9** [beto-rodriguez/Live-Charts#273]
There is a small gap between OhlcPoint and axis X separator. Is it a bug or it is the author want?

![image](https://cloud.githubusercontent.com/assets/20458989/16954895/3b8a0b26-4e05-11e6-8aff-e3f1da0529ac.png)

Deleting the first axis X separator looks better. Anyone agree it?

**Comment by beto-rodriguez** [comment]
Hello and thanks for reporting.

I agree with you that it would loo better, but it would not be true, the separator is being drawn where it should, and moving it to the left would be a lie.

As an alternative you can easily disable X Axis separators

    Separator.IsEnabled = false;

or

    <lvc:CartesianChart >
        <lvc:CartesianChart.AxisX>
            <lvc:Axis Separator="{x:Static lvc:DefaultAxes.CleanSeparator}"><lvc:Axis >
        <lvc:CartesianChart.AxisX> 
    </lvc:CartesianChart>

With your image I saw an issue, I try to explain in the next image, and it was solved with the previous commit

![untitled](https://cloud.githubusercontent.com/assets/10853349/17084660/143cdbca-5189-11e6-9091-8a17af6f0dfc.png)
