### ISSUE TITLE
[Minor] Error on site

### ISSUE THREAD

**Issue by Sadikk** [beto-rodriguez/Live-Charts#274]
At http://lvcharts.net/App/examples/v1/wpf/360%20Gauge this line : 
` <lvc:SolidGauge Grid.Row="1" Uses360Mode="True" From="0" To="1" 
                   Value="{Binding Value}" LabelFormatter="{Binding Formatter}" />`

should be like that 
`<lvc:Gauge Grid.Row="1" Uses360Mode="True" From="0" To="1" 
                   Value="{Binding Value}" LabelFormatter="{Binding Formatter}" />`

otherwise it causes an error because SolidGauge doesn't exist.

**Comment by beto-rodriguez** [comment]
You are right, last commit should fix it, thanks for reporting
