### ISSUE TITLE
Segment color and ToolTip hover

### ISSUE THREAD

**Issue by Choppi** [beto-rodriguez/Live-Charts#279]
Hi

Before starting, I wanted to thank you all of this. You're doing a great job. 

Let's begin ! I'm working on a project that needs to plot a graph but more like a StepLine graph.  And i have 2 questions : 

1) Is it possible to use differents colors for segment ? I mean, i have 4 points with 2 horizontal lines linked by a vertical one, is it possible to use different colors for the 2 horizontal ones ?

2) And can we modify the tooltip to be opened not only when mouse hovers points but when mouse hovers segments and print X.StartingValue and X.EndValue ? 

Thanks in advance ! 

Choppi

**Comment by beto-rodriguez** [comment]
Hello Choppi

This is the second time I see a request of a StepLineSeries so I added one.

please let me know if this is enough to solve your case.

Here is a brief code snippet, it is currently only available cloning or downloading this library, not published yet, it will be included in next release (0.7.11) but I would really appreciate your opinion before release it.

Thanks!

    <lvc:CartesianChart>
            <lvc:CartesianChart.Series>
                <lvc:StepLineSeries Values="1, 4, 2, 5, 6, 8, 2" AlternativeStroke="IndianRed"/>
            </lvc:CartesianChart.Series>
        </lvc:CartesianChart>

![untitled](https://cloud.githubusercontent.com/assets/10853349/17117772/59f5e7e2-5283-11e6-9284-614b20fae0cb.png)

**Comment by Choppi** [comment]
Thanks for your answer ! 

That might be useful but, what i'm looking for is AlternativeStroke on Horizontal Lines. Here we can only change color on Vertical Lines. What I want is to be able to change for example the first horizontal line in green and do not change the other lines ! 

But thank you for your work, i'll look through it to see what can I do to fit my request ! :)

**Comment by beto-rodriguez** [comment]
You can change both, sorry forgot to mention that

    <lvc:CartesianChart>
        <lvc:CartesianChart.Series>
            <lvc:StepLineSeries Values="1, 4, 2, 5, 6, 8, 2" Stroke="Green" AlternativeStroke="IndianRed"/>
        </lvc:CartesianChart.Series>
    </lvc:CartesianChart>

**Comment by Choppi** [comment]
Yeah, i just saw that after looking through it, that was my bad sorry ! 

That's perfect then, thank you for this !!
