### ISSUE TITLE
Shared Tooltip goes invisible when changing the Usercontrol

### ISSUE THREAD

**Issue by camou23** [beto-rodriguez/Live-Charts#280]
I hope the GIF explains what i mean.
When not just write me on gitter.
![animation2](https://cloud.githubusercontent.com/assets/4669637/17094141/a2058398-524d-11e6-9de2-35ba447280f6.gif)

**Comment by camou23** [comment]
Its some sort of a timing problem. 
When i do it slow it works like normal.
But if you do it fast the Tooltip goes invisible.

**Comment by beto-rodriguez** [comment]
Previous commit fixes this, I have to say that I am not 100% convinced about this solution but it works, and I don't see how it could fail

Thanks for reporting again!
