### ISSUE TITLE
Typo in the example on the main page and various other pages

### ISSUE THREAD

**Issue by mrakgr** [beto-rodriguez/Live-Charts#282]
```
//create some labels if necessary
var labels = new string[] {"Jan", "Feb" , "Mar", "Apr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dec"};
myChart.AxixX.Labels = labels;
```

In the above I am decently sure that `AxixX` is supposed to be `AxisX`. The above is on the main Github page. Also, I am not sure the example should go as in above since the `Labels` property is a part of the Axis class while `AxisX` is an `AxesCollection`. It might be better if the example used an explicit CarthesianChart(). 

Also, here are some typos that I found:

[In Basics](http://lvcharts.net/App/examples/v1/wpf/Basics)

`If necessary you can also define your own Tool tips o Legends controls, here is an article about it`

There is typo here. `tips o Legends` should have an `of` or maybe `on` in the middle.

[In On Series](http://lvcharts.net/App/examples/v1/wpf/About%20Series)

`Notice any stacked series (including pie series) will not only change drawn shape visibility property, it will also removed the series from the stacked values, and the chart will be updated as if that series would not exists.`

Typos: “will also remove`d` the series”, “would not exist`s`”.

It should be:

`Notice any stacked series (including pie series) will not only change based on the visibility property, it will also remove the series from the stacked values, and the chart will be updated as if that series had not existed.`

**Comment by beto-rodriguez** [comment]
This helps a lot thank you very much, I will fix it asap

**Comment by mrakgr** [comment]
I forgot one. [In Constant Changes](http://lvcharts.net/App/examples/wpf/Constant%20Changes) there is an errant period at the end. `not waste them!.` should be `not waste them!`

**Comment by beto-rodriguez** [comment]
Thank you very much again for reporting!

All your type errors should be fixed now, please let me know if you find anything else!

thanks!
