### ISSUE TITLE
OHLC & Candle serie issue

### ISSUE THREAD

**Issue by PsykotropyK** [beto-rodriguez/Live-Charts#285]
Hello,

It seems that both the OHLC and Candle series suffer from the same rendering issue depending on how many points are displayed. The width of a candle seems to be constant no matter the amount of point shown, but instead of overlapping two candles when there are too many of them, it transform it into a simple bar (high - low) 

I think the width of a candle (W) should depend on the width of the plotting area (w) the number of candles (n) and a parameter to allow for controlling the final size (p, with 90% as default, or something around this) 

W = w / n * p

**Comment by PsykotropyK** [comment]
11 candles : 
![11](https://cloud.githubusercontent.com/assets/12467463/17277345/1d530276-5741-11e6-8128-75b9bbc981cd.PNG)

12 candles : 
![12](https://cloud.githubusercontent.com/assets/12467463/17277347/21d73cae-5741-11e6-94dd-98c42a5332b6.PNG)

**Comment by PsykotropyK** [comment]
So I found the MaxColumnWidth which should allow me to dynamically set it up, but can you tell me how I can get the width of the plot area (i.e. axis, labels, titles, ... excluded)?

**Comment by beto-rodriguez** [comment]
I have not investigated this issue, but to answer 

> can get the width of the plot area (i.e. axis, labels, titles, ... excluded)?

Instead of accessing the pot area, look for `DrawMargin`

**Comment by PsykotropyK** [comment]
The DrawMargin unit is the same as the MaxColumnWidth?

So basically if I do ToDrawMargin ( value , source , chart , axis ) with the min and max X value currently shown I should get the full extent? I will try it soon (unfortunately i'm lacking time) and post what I found.

Thanks for the answer

**Comment by beto-rodriguez** [comment]
Yeah same units.

**Comment by beto-rodriguez** [comment]
No, MaxColumnWidth is in Pixels

ToDrawMargin takes chart values returns pixels

FromDrawMargin takes pixels, returns chart values

**Comment by PsykotropyK** [comment]
> No, MaxColumnWidth is in Pixels

ToDrawMargin takes chart values returns pixels

So yes. I want pixel to define MaxColumnWidth and I got them from ToDrawMargin. Basically I'll do 
(ToDrawMargin(xmax)-ToDrawMargin(xmin)) / (Nxmax - Nxmin) * 95% with N the index

Only thing is that I didn't find an event for Zoom to catch when it changes. I will try through MouseWheel or smthg.

**Comment by beto-rodriguez** [comment]
My bad, I deleted than **No** then.

I have not tested this, I will investigate this issue tomorrow, but as far as I see this seems like a bug, and it should be fixed inside the code of the library.

I am not sure if this is useful, but zooming and panning just changes the axis limits, Axis.MinValue and Axis.MaxValue, this range determines the visible section in the chart.

also here is where the library handles the zooming, it is actually really simple, since the axis is who handles it.

https://github.com/beto-rodriguez/Live-Charts/blob/master/WpfView/Charts/Base/Chart.cs#L846

**Comment by PsykotropyK** [comment]
if you change something in the core code, make that the candle width is dynamic. Financial series may plot thousands of data and do extensive use of zoom/pan

**Comment by beto-rodriguez** [comment]
I am working with high performance right now, should be ready next week

**Comment by beto-rodriguez** [comment]
You are right, the width of columns was being ignored when the series was crowded, last commit fixes this.
