### ISSUE TITLE
Question: How to bind a collection to PieChart?

### ISSUE THREAD

**Issue by sherry-ummen** [beto-rodriguez/Live-Charts#286]
Basically I want to take whole of the data from the backend and using MVVM. How do I do it? Any example would be helpful.

Thanks

**Comment by beto-rodriguez** [comment]
Hello, with a collection you mean any array in .net? without using SeriesCollection or ChartValues right?

**Comment by sherry-ummen** [comment]
Hmm basically what I am trying to do is that I have a list which I want to bind to pie chart. Since I am mvvm so I cannot access the control directly.

**Comment by beto-rodriguez** [comment]
How about

    pubic class ViewModel
    {
         public SeriesCollection Series { get; set; } = new SeriesCollection 
        { 
            new PieSeries { Values = new ChartValues<double> {3}} },
            new PieSeries { Values = new ChartValues<double> {4}} },
            new PieSeries { Values = new ChartValues<double> {6}} }
        }

Then

    <lvc:CartesianChart Series="{Binding Series}">
            <lvc:CartesianChart.DataContext>
                <ViewModel />
            </lvc:CartesianChart.DataContext>
        </lvc:CartesianChart>

**Comment by beto-rodriguez** [comment]
Just noticed the Doughnut example was not linked correctly, this example was intended to illustrate how to do this, it is already updated.

http://lvcharts.net/App/examples/v1/wpf/Doughnut%20Chart
