### ISSUE TITLE
Milestone on Line Graph

### ISSUE THREAD

**Issue by hishaamn** [beto-rodriguez/Live-Charts#287]
Hi,

Is it possible to have milestone on the Line Graph? 

Thanks

**Comment by beto-rodriguez** [comment]
Hello 

Please see https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart/UIElements

Let me know if this is enough!

**Comment by hishaamn** [comment]
Thanks. 
But it is available only for WPF?

Thanks

**Comment by beto-rodriguez** [comment]
You were right, last commit extends this to wpf, it will be publishes with 0.7.11 here is an exmaple in wf

https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/WinForms/Cartesian/UielementsExample

**Comment by hishaamn** [comment]
Thanks Alberto.

I will give it a try :+1:

**Comment by beto-rodriguez** [comment]
I will upload the example today later, there I added the example to the repo, here is the result:

![image](https://cloud.githubusercontent.com/assets/10853349/17458944/bf762fb6-5beb-11e6-8c8e-934673096680.png)

**Comment by hishaamn** [comment]
Thank you :+1:

**Comment by hishaamn** [comment]
Hey there,

I have tried it and it works as expected :). But can you show me how to set the milestone to vertical instead of horizontal please?

Thanks
