### ISSUE TITLE
Series Collection not Notifying Collection changed

### ISSUE THREAD

**Issue by NickSavin** [beto-rodriguez/Live-Charts#288]
Hello, Beto!

I have a new issue:

I have a  `
public SeriesCollection ChartSeries { get; set; } = new SeriesCollection(); 
`
in my ViewModel

`<lvc:CartesianChart Grid.Row="1" Margin="10"  LegendLocation="Top" Series="{Binding OutputVM.OLVCoverGuide.ChartSeries}" >
`
Its All raight.

But when I try to bind this collection to another control  issue appears. On running application, when I try to access ComboBox  a Null ref Exeption appears.

`<ComboBox  Width="100" Height="20" HorizontalAlignment="Right" Margin="0 10 10 0" ItemsSource="{Binding OutputVM.OLVCoverGuide.ChartSeries}">` 

```
                                   `  <ComboBox.ItemTemplate>
                                        <DataTemplate>
                                            <StackPanel Orientation="Horizontal">
                                                <TextBlock Text="{Binding Title}"/>
                                                <CheckBox IsChecked="{Binding Visibility , Mode=TwoWay , Converter={StaticResource bvc}}"/>
                                            </StackPanel>
                                        </DataTemplate>
                                    </ComboBox.ItemTemplate>
                                </ComboBox>`
```

**Comment by NickSavin** [comment]
if I add a second collection to my ViewModel    typeof   ObservableCollection<Series>

then fill it with series and bind to my combox, its All right.

But this is not solution, because I need to have a two collection of series (ObservableCollection<Series> and SeriesCollection)

**Comment by NickSavin** [comment]
that is what I want. Its working with a two binded collections, but it is not good

![image](https://cloud.githubusercontent.com/assets/20172765/17332413/56c310fe-58d7-11e6-8eb9-30782ced980c.png)

**Comment by beto-rodriguez** [comment]
For the record, as I explained to @NickSavin it seems that `SeriesCollection` needs to notify WPF as `ObservableCollection` does, I will investigate further, a workaround for now is to bind a new and already loaded series collection.

Nick was doing

    public class ViewModel
    {
        public SeriesCollection ChartSeries {get;set;} = new SeriesCollection();

         public void Load()
         {
              ChartSeries.Clear();
             
              //SeriesCollection does not notifes wpf controls that this series was added
              ChartSeries.Add(new LineSeries 
              {
                  Values = //some random values
              });
         }    
    }

And this is a workaround

    public class ViewModel : INotifyPropertyChanged
    {
        public SeriesCollection ChartSeries
        {
            get { return _chartSeries; }
            set
            {
                _chartSeries = value;
                OnPropertyChanged();
            }
        } = new SeriesCollection();

         public void Load()
         {
              var series = new SeriesCollection();

              series.Add(new LineSeries 
              {
                  Values = //some random values
              });

              ChartSeries = series;
         }

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

**Comment by beto-rodriguez** [comment]
I will remove the Bug label from this issue, because since the target of the library is not only to work with WPF, and this is a platform specific issue, the solution to this would be to create a WPF version of the `SeriesCollection` class, which should implement `ICollectionChanged`.

I am not 100% sure about this, this will make SeriesCollection dirty and harder to maintain, we would need a SeriesCollection class for every platform the library support.

**Comment by beto-rodriguez** [comment]
I will close this issue.

`SeriesCollection` will not implement `ICollectionChanged` because it would be hard to maintain, and this has some workarounds.

Thanks for your feedback!

**Comment by beto-rodriguez** [comment]
Actually I was able to fix this issue, I was scared of this because as I said before in the PCL profile 328 I had no access to INotifyCollectionChanged, I decided to use profile 78 instead and now we can access it and implement INCC in the core of the library.

This will be included in the next version fo the library.
