### ISSUE TITLE
DataTooltip issue

### ISSUE THREAD

**Issue by JulFIC** [beto-rodriguez/Live-Charts#295]
Hello,
I have an issue about the datatooltip.
I don't know why but my text (name of series +values) is in black. I want to change that . Do you know a way to do that on the xaml ?
I already try to change the foreground on the defaultTooltip without success....

![livechartissue](https://cloud.githubusercontent.com/assets/20856872/17432643/9d1b7c82-5b00-11e6-922f-7efa99124e69.png)

**Comment by beto-rodriguez** [comment]
Hello, this works for me:

```xml
<lvc:CartesianChart>
           <lvc:CartesianChart.DataTooltip>
               <lvc:DefaultTooltip Foreground="IndianRed"></lvc:DefaultTooltip>
           </lvc:CartesianChart.DataTooltip>
</lvc:CartesianChart>
```

**Comment by JulFIC** [comment]
hey,
I already try this but it doesn't work.
It change only the color of the title on the Data ToolTip.
 
        
![livechartissue2](https://cloud.githubusercontent.com/assets/20856872/17438422/021263e0-5b23-11e6-8591-14bc831010fa.png)
![livechartissuecode](https://cloud.githubusercontent.com/assets/20856872/17438423/021b992e-5b23-11e6-8e31-49b47603fff5.png)

**Comment by beto-rodriguez** [comment]
it seems that an style in your app is overriding the Tooltip labels foreground, I will try to force this issue, could you please let me know if this is true?

**Comment by JulFIC** [comment]
You're write it was the style . when the style of the textblock is already set (specially the foreground) , the override style on your xaml inside a datatemplate is not taken. It's a known bug on wpf.
