### ISSUE TITLE
VerticalStackedSeries

### ISSUE THREAD

**Issue by Stakhmi4** [beto-rodriguez/Live-Charts#299]
Hi. Can i draw this graph?

![1](https://cloud.githubusercontent.com/assets/10836966/17584616/301c3e72-5fc0-11e6-914d-8384f87913b8.png)

with definitioin like in VerticalStackedArea:

    new VerticalStackedAreaSeries
    {
        Values = new ChartValues<ObservableValue>
        {
              new ObservableValue(9),
              new ObservableValue(9),
              new ObservableValue(5)
         },
         DataLabels = true
    },
    new VerticalStackedAreaSeries
    {
        Values = new ChartValues<ObservableValue>
        {
              new ObservableValue(8),
              new ObservableValue(11),
              new ObservableValue(5)
         },
         DataLabels = true
      }
     ...............

**Comment by beto-rodriguez** [comment]
Hello, I  am sorry I don't understand this, what is the issue?
