### ISSUE TITLE
PieCharts disappear

### ISSUE THREAD

**Issue by hkhoi** [beto-rodriguez/Live-Charts#3]
Worked nicely, but there is an issue.

PieChart.Series = new ObservableCollection<Serie>
            {
                //if you add more than one serie to pie chart, they will be overridden
                new PieSerie
                {
                    PrimaryValues = new ObservableCollection<double> { 8 },   // Only one component
                    Labels = standardLabels
                }
            };

=> Then the chart animates and disappears.

**Comment by beto-rodriguez** [comment]
this fixed the problem, but now we got a new issue because I think we should get a full circle not this;

![image](https://cloud.githubusercontent.com/assets/10853349/10043673/8913b4ce-61ba-11e5-871d-3f0972c98cfd.png)

I will let this issue open so we can review that later. thanks

**Comment by beto-rodriguez** [comment]
I will close this since is a opinion based enhancement, and not a primary goal
