### ISSUE TITLE
Piechart 0.4 does not hover

### ISSUE THREAD

**Issue by ambenkhalfa** [beto-rodriguez/Live-Charts#30]
Hello dear Rodriguez
First, I want to thank you for this contribution it's very an easy way to create charts 

Then, In this new release 0.4 the Piechart does not hover (show tooltip) i tried PieChart.Hoverable=true like the older release but it doesn't work.

Thank you

**Comment by beto-rodriguez** [comment]
Yes this is totally intentional, I am working on a production project with this library and the tooltip in a pie chart seems hard to read for a user. The code that shows the tooltop is there (but as a comment, because then we can go back if this is not working). I think this way a pie chart is more usefull for a normal user. It easier to read this way. 0.4 was practically to make pie chart more readable. What do you think?

**Comment by ambenkhalfa** [comment]
Yes I totally agree with you but i think showing percentage of each part isn't enough for final users. In my case i want to show primary values in each part. I used the PieSeriesViewer to show this values + labels but it's not interresting idea. It will be i think, more readable if each part can show either percentage or primary value.

**Comment by beto-rodriguez** [comment]
You are rigth, I just made a commit to fix this. by default pie chart now shows values, then you need to impletment a `Formatter` to display it as percentage. Also included test project shows both cases and extended a bit documentation for `Formatters`.

Thank you very much. I think you will agree with this solution, if you dont please let me know. the commit to fix this was https://github.com/beto-rodriguez/Live-Charts/commit/e0a6bc75e269fb73956288f6960375592b2dab1c, Also if you star this library it helps a lot to bring more traffic and help :).

**Comment by ambenkhalfa** [comment]
Thank you very much It works perfectly you may upload it also in Nuget for future developers. thank you again for this contribution.

**Comment by ambenkhalfa** [comment]
Hi again, And thank you for the new release 0.4.1
i wonder now if enabling hover tooltip  with this configuration will be more interresting. Imagine when hover a part it shows tooltip like that (Label: priamary_value (percentage%) ) 
example: on  hover
Algeria: 2086278,79 (23,5%) Mexico: 862981,22 (12,14%) 

 What do you think ?

**Comment by beto-rodriguez** [comment]
It could be useful for cases where you need to display more data, the problem is that I dont think all developers using this assemby will need that. The good news is that it should be really easy to implement it, overriden `OnDataMouseEnter` in a pie chart. For example:

```c#
public class MyCustomChart : PieChart
    {
        public override void OnDataMouseEnter(object sender, MouseEventArgs e)
        {
            //if you need to display current behavior then call this
            base.OnDataMouseEnter(sender, e);

            //then do what you need to display
            var b = new Border
            {
                BorderThickness = new Thickness(0),
                Background = new SolidColorBrush { Color = Color.FromRgb(30, 30, 30), Opacity = .8 },
                CornerRadius = new CornerRadius(1)
            };
            var sp = new StackPanel
            {
                Orientation = Orientation.Vertical
            };

            var senderShape = HoverableShapes.FirstOrDefault(s => Equals(s.Shape, sender));
            var pieSlice = senderShape?.Shape as PieSlice;
            if (pieSlice == null) return;


            sp.Children.Add(new TextBlock
            {
                Text = senderShape.Label + ": " + senderShape.Value +
                       " (" + (senderShape.Value.Y/PieTotalSum).ToString("P") + ")",
                Margin = new Thickness(5),
                VerticalAlignment = VerticalAlignment.Center,
                FontFamily = new FontFamily("Calibri"),
                FontSize = 11,
                Foreground = Brushes.White
            });

            //if you need to use the current formatter then need to implement something like this
            //in TextBlock text property
            //Text = senderShape.Label + ", " + (SecondaryAxis.LabelFormatter == null
            //        ? senderShape.Value.Y.ToString(CultureInfo.InvariantCulture)
            //        : SecondaryAxis.LabelFormatter(senderShape.Value.Y)),

            b.Child = sp;
            Canvas.Children.Add(b);

            var minDimension = DesiredSize.Width < DesiredSize.Height
               ? DesiredSize.Width : DesiredSize.Height;

            Canvas.SetLeft(b, (DesiredSize.Width - minDimension) / 2 + 10);
            Canvas.SetTop(b, (DesiredSize.Height - minDimension) / 2 + 10);

            CurrentToolTip = b;
        }
    }
```

I really don't know how to add this in docs, but as you can see I built all charts this way, you can get custom behaviors overriden only what you need in your case when mouse is over a Hoverable Shape. 

I currently can't test it because Im making a mess with current code (to build 1.0 with async drawing, should improve performance a lot I hope). But I hope you get the idea and hope this does not throws.

**Comment by beto-rodriguez** [comment]
Actually this would only work if you create this class inside LiveCharts Assembly because `HoverableShapes` is `internal` (I dont know what was I thinking), So I will open a new issue to ensure you can override all methods in `Chart` class and access all properties (plus document it).

**Comment by ambenkhalfa** [comment]
Yes that is the right solution
