### ISSUE TITLE
Real time ploting of Stacked Columns

### ISSUE THREAD

**Issue by dmitrygoldenberg** [beto-rodriguez/Live-Charts#300]
Hi,

I'm working on some project in which I need to plot stacked columns in real time. So I'm trying to integrate the code from two examples (Basic Stacked Columns & Constant Changes examples)
But the problem is that I'm not able to see my stacked columns, but I see that the X,Y axises are changes as needed.

Please take a look at my code:

`public class MeasureModel
    {
        public DateTime DateTime { get; set; }
        public double Value;
    }
`

`
 public Form1()
        {
            InitializeComponent();

            var mapper = Mappers.Xy<MeasureModel>()
                .X(model => model.DateTime.Ticks / TimeSpan.FromMilliseconds(500).Ticks)   //use DateTime.Ticks as X
                .Y(model => model.Value);           //use the value property as Y

            //lets save the mapper globally.
            Charting.For<MeasureModel>(mapper);

            //the ChartValues property will store our values array
            emotion1 = new ChartValues<MeasureModel>();
            emotion2 = new ChartValues<MeasureModel>();

            addSeries(emotion1);
            addSeries(emotion2);

            cartesianChart1.AxisX.Add(new Axis
            {
                DisableAnimations = false,
                //LabelFormatter = value => new System.DateTime((long)(value * TimeSpan.FromMilliseconds(500).Ticks)).ToString("mm:ss"),
                Separator = new Separator
                {
                    Step = TimeSpan.FromSeconds(1).Ticks
                }
            });

            date = new DateTime();
            SetAxisLimits(date);

            //The next code simulates data changes every 500 ms
            Timer = new Timer
            {
                Interval = 500
            };
            Timer.Tick += TimerOnTick;
            R = new Random();
            Timer.Start();
        }

        private void SetAxisLimits(DateTime now)
        {
            cartesianChart1.AxisX[0].MaxValue = now.Ticks + TimeSpan.FromSeconds(1).Ticks; 
            cartesianChart1.AxisX[0].MinValue = now.Ticks - TimeSpan.FromSeconds(8).Ticks; 
        }

        private void addSeries(ChartValues<MeasureModel> seriesValues)
        {
            this.cartesianChart1.Series.Add(new StackedColumnSeries
                {
                    Values = seriesValues,
                    StackMode = StackMode.Values,
                    StrokeThickness = 5
                });
        }
        private void addSeriesValue(ChartValues<MeasureModel> seriesValues, DateTime time)
        {
            seriesValues.Add(new MeasureModel
            {
                DateTime = time,
                Value = R.Next(0, 20)
            });
        }

        private void TimerOnTick(object sender, EventArgs eventArgs)
        {
            date.AddMilliseconds(500);

            addSeriesValue(emotion1, date);
            addSeriesValue(emotion2, date);

            SetAxisLimits(date);

            if (emotion1.Count > 192)
            {
                emotion1.RemoveAt(0);
                emotion2.RemoveAt(0);
            }
        }
`

Is it Some problem with my Code? Also you can found that LabelFormater is in Comments, is it because it causes OutOfRangeError.

Thank you for help

**Comment by beto-rodriguez** [comment]
Hello, please send the not eat the bottom at this article http://lvcharts.net/App/examples/v1/wpf/Date%20Time

Let me know if this solves your issue

**Comment by dmitrygoldenberg** [comment]
Hello,
Thank you for reply but this is not helped me because my interval is milliseconds.
I'm gathering data from external source with X samples per second. Each sample contains Y parameters. So I'm trying to represent each sample with Y parameters at Y different StackedColumnSeries.

At the current code I posted, there are 500 milliseconds of interval for example 

Thanks

**Comment by beto-rodriguez** [comment]
Any bar series width is unitary as explained here

 http://stackoverflow.com/q/38731985/2979430

You have 2 options:

1) set an appropiate Interval to your chart, 500 ms as  far as I can see

    var dayConfig = Mappers.Xy<DateModel>()
      .X(dateModel => dateModel.DateTime.Ticks/TimeSpan.FromMillisecons(500).Ticks)
      .Y(dateModel => dateModel.Value);
    //and the formatter
    Formatter = value => new DateTime((long) (value*TimeSpan.FromMilliseconds(15).Ticks)).ToString("t");

2) maybe you don't really need date time as X you could also index the values in X.

    var dayConfig = Mappers.Xy<DateModel>()
      .X((dateModel, index ) => index)
      .Y(dateModel => dateModel.Value);

Then use the Axis.Labels property to set the date time labels

**Comment by beto-rodriguez** [comment]
I was working in a similar case, then noticed that the easier way for my case was the second option, this is what I did in case it helps you

    GearedValues = v.AsChartValues();
            Mapper = Mappers.Xy<Vm>()
                .X((m, i) => i)
                .Y(m => m.Value);
            Labels = new ObservableCollection<string>(
                v.Select(x => x.DateTime.ToString("dd MMM yyy")));

    <lvc:CartesianChart.Series>
                <lvc:ColumnSeries Name="GearedSeries" Title="GearedValues" 
                                  Values="{Binding GearedValues}"  ColumnPadding="1"
                                  Configuration="{Binding Mapper}"/>
            </lvc:CartesianChart.Series>
            <lvc:CartesianChart.AxisX>
                <lvc:Axis Labels="{Binding Labels}" LabelsRotation="-35">
                </lvc:Axis>
            </lvc:CartesianChart.AxisX>
        </lvc:CartesianChart>
