### ISSUE TITLE
Series Collection Clear issue

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#301]
From SO

http://stackoverflow.com/questions/38986439/wpf-livecharts-the-given-key-was-not-present-in-the-dictionary

**Comment by jrd281** [comment]
I created the SO question, would you like a Stacktrace?

**Comment by beto-rodriguez** [comment]
Please, it would help a lot

**Comment by jrd281** [comment]
[LiveCharts.txt](https://github.com/beto-rodriguez/Live-Charts/files/423275/LiveCharts.txt)

I've attached the StackTrace to this comment.  I've got the output from the Visual Studio "Output Window" and the output from the "Call Stack" window.  Let me know if you need anything else from me.

**Comment by beto-rodriguez** [comment]
Hi, sorry for the late answer, I finally got some time to check this out.

So I see 2 errors in your code

1) from your stack Trace your ChartValues are of type `StickerBreakdownVM`, but in your Linq query you are creating a list of ObservableValue:

    var groupsingsList = stickersBreakdownGroupings.Select(n =>
    {
      var pieSeries = new PieSeries();
      pieSeries.Title = n.BreakdownType;
      pieSeries.DataLabels = true;
      //next line is wrong
      pieSeries.Values = new ChartValues<ObservableValue> {new   ObservableValue(n.Count)};
      //they should also be ChartValues<StickerBreakdownVM> as far as I can see
     return pieSeries;
   }).ToList();

2) well, that was not causing the exception, but what actually is, is that you have not told LiveCharts how to plot `StickerBreakdownVM` class, I will throw a LiveCharts exception when `Configurations[typeof (T)];` fails finding the key, so you get more info about it, to configure your VM you normally need to add the next code when your app starts:

    var mapper = Mappers.XY<StickerBreakdownVM>().Y(vm => vm.MyYProperty)   
    Charting.For<StickerBreakdownVM>(mapper);

For more info see http://lvcharts.net/App/examples/v1/wpf/Types%20and%20Configuration

I will close this issue for now, if this does not solves your issue let me know it.
