### ISSUE TITLE
Positioning of Visual Element

### ISSUE THREAD

**Issue by hishaamn** [beto-rodriguez/Live-Charts#305]
Hi,

I have been trying for hours on how to set the Position of the Text "Release Test" at the top:

![capture](https://cloud.githubusercontent.com/assets/14113223/17826223/9d69de60-667f-11e6-8a0a-1e0378291087.PNG)

Below is the code being used and it is generating the Vertical line dynamically based on values being provided.

    var axisSection = new AxisSection
                    {
                        FromValue = index,
                        ToolTip = "dfsdf",
                        ToValue = index,
                        Stroke = Brushes.YellowGreen,
                        StrokeThickness = 1,
                        StrokeDashArray = new DoubleCollection(new[] { 4d })
                    };

                    chart.VisualElements.Add(new VisualElement
                    {
                        HorizontalAlignment = HorizontalAlignment.Center,
                        VerticalAlignment = VerticalAlignment.Top,
                        UIElement = new TextBlock //notice this property must be a wpf control
                        {
                            Text = journalObj.Title,
                            FontWeight = FontWeights.Bold,
                            Foreground = Brushes.Snow,
                            FontSize = 12,
                            Opacity = 0.6
                        }
                    });

I have try to use the X and Y but when used, the text does not appear.

Thanks

**Comment by beto-rodriguez** [comment]
Hello, the idea is to use X and Y as you stated, what I think is going on is that you are doing

    chart.VisualElements.Add(new VisualElement
                {
                    HorizontalAlignment = HorizontalAlignment.Center,
                    VerticalAlignment = VerticalAlignment.Top,
                    Y = 0.5 
                });

And you should set it to Bottom, since at top it wont be visible

    chart.VisualElements.Add(new VisualElement
                {
                    HorizontalAlignment = HorizontalAlignment.Center,
                    VerticalAlignment = VerticalAlignment.Bottom, //here is the change
                    Y = 0.5 
                });
