### ISSUE TITLE
LiveCharts.WPF DateTimeAxis MinValue

### ISSUE THREAD

**Issue by UBaHbI4** [beto-rodriguez/Live-Charts#306]
I in the project try to use LiveCharts.WPF. It is impossible to establish MinValue, for example **20.08.2016 12:30:30**, to **within seconds**. May I realize somehow it? Generally I need an interval from StartData to EndData with the interval equal (EndData-SartData)/10. And initial and final date have to be to within seconds. Help please. Thanks, Ivan

**Comment by NintendoPlayer** [comment]
How did you solve the issue?
