### ISSUE TITLE
StackedColumnChart Rotation of Data Labels

### ISSUE THREAD

**Issue by FabianHeiss** [beto-rodriguez/Live-Charts#308]
Hello,
im from Germany so excuse my bad english.

is there a way to rotate the Data Labels in a StackedColumnChart?
![stackedcolumnchart](https://cloud.githubusercontent.com/assets/13312735/17889893/d005ef98-6932-11e6-9d0a-331f36aaaaa0.PNG)

Thanks.
Greetings from Germany,
Fabian Heiß

**Comment by beto-rodriguez** [comment]
Hello, not yet, I like this feature, I will keep it open to include it.

Thanks

**Comment by beto-rodriguez** [comment]
0.8.1 will include a fix for this case, thanks for reporting, you can find more info about the solution at #410

**Comment by mauriciocrezende** [comment]
Hello,
is there a way to rotate the Data Labels in a LineSeries? thank you.
![grafico](https://user-images.githubusercontent.com/56925136/90052698-e950de00-dcaf-11ea-872e-4f803a2ce1e5.PNG)
