### ISSUE TITLE
Typo in Constant Changes Example

### ISSUE THREAD

**Issue by EdGrant63** [beto-rodriguez/Live-Charts#309]
First of all, this is a great project, thanks to everyone that has contributed!

I was doing some testing on this example to see if it would work for a graphing project I am working on. I noticed that a few places in the code a variable was named "Values" instead of "Value". Here are the lines of code that I noticed were incorrect for this example.

C#
`Value = new ChartValues<MeasureModel>();`

`public ChartValues<MeasureModel> Value { get; set; }`

`if (Value.Count > 30) Value.RemoveAt(0);`

XAML
`<lvc:LineSeries Values="{Binding Value}" PointGeometrySize="18" StrokeThickness="4" />`

Not quite sure how to make the changes myself as I am pretty new to Git and Development in general, so I figured I would at least post it here.

Thanks,

Ed

**Comment by solarsunspot** [comment]
I thought the same thing when I first started working with the program but the way it is written is actually correct. When ever you see "Value" it is pertaining to the variable within the MeasureModel class.  The "Values" variable is different and is a set of "ChartValues" (x,y) obtained through the MeasureModel class that have the "value" as x and the date as y.

Using the way it is written actually gets the code to run on my end.

**Comment by beto-rodriguez** [comment]
Thanks for the feedback, @solarsunspot  is right, it stands from ChartValues, so to avoid this confusion in the example I renamed Values to ChartValues, this way future readers will not face this confusion, let me know if this is not enough!
