### ISSUE TITLE
WPF example project could trow an exception

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#312]
I just updated to VS2015 update 3 and suddenly the WPF examples project throws an exception that is not related with the library.

![untitled](https://cloud.githubusercontent.com/assets/10853349/17949364/9dcae432-6a1a-11e6-881a-d80c678b54db.png)

A work around is to disable UI Debugging Tools for XAML, ensure this option is not checked at: 

Tools –> Options –> Debugging –> General –> Enable UI Debugging Tools for XAML

Then the examples will not throw anymore...

I already reported as much as I could to the VS team, hope they fix it soon.

**Comment by alexhelms** [comment]
I posted this on gitter but I'll put it here too.

I've been runing VS 2015 update 3 since it was released and did not have any issues with LiveCharts 0.7.11. I'm a similar but difference exception ever since updating to 0.7.12.

Here is the snippet that causes the exception at runtime. I removed the bindings:

`
<lvc:CartesianChart Margin="0,0,3,0"
					DisableAnimations="True"
					LegendLocation="None">
	<lvc:CartesianChart.Series>
		<lvc:LineSeries Title="RA"
						MinWidth="0"
						Fill="#330000ff"
						LineSmoothness="0.35"
						PointGeometry="{x:Null}"
						PointGeometrySize="0"
						Stroke="#0000FF"
						StrokeThickness="2"
						Values="0,1,2" />
		<lvc:LineSeries Title="DEC"
						MinWidth="0"
						Fill="#33FF0000"
						LineSmoothness="0.35"
						PointGeometry="{x:Null}"
						PointGeometrySize="0"
						Stroke="#FF0000"
						StrokeThickness="2"
						Values="2,1,0" />
	</lvc:CartesianChart.Series>
	<lvc:CartesianChart.AxisX>
		<lvc:Axis MaxValue="50"
				  MinValue="0"
				  ShowLabels="False" />
	</lvc:CartesianChart.AxisX>
	<lvc:CartesianChart.AxisY>
		<lvc:Axis MaxValue="1"
				  MinValue="-1"
				  Position="RightTop"
				  ShowLabels="True">
			<lvc:Axis.Separator>
				<lvc:Separator Step="1" />
			</lvc:Axis.Separator>
		</lvc:Axis>
	</lvc:CartesianChart.AxisY>
</lvc:CartesianChart>
`

And here is the exception:

![image](https://cloud.githubusercontent.com/assets/174474/18072850/64611d56-6e16-11e6-9ba3-4aa21d419466.png)

**Comment by beto-rodriguez** [comment]
Well I am pretty sure I found an Issue in VS, for now I fond what caused this issue, and it was removed even the library would behave better with the previous code :cry: 

If anyone at VS team sees this issue, it started at

d7540bc874953060a4e141fb1dd4383ca768251d

And what cased the issue was [this](https://github.com/beto-rodriguez/Live-Charts/commit/1fc1b3e99a278db71059b3bb5350fb0fe243733e)

What happens there, is that I force the chart to update, as the code reaches this point, Otherwise (the alternative I took) the chart waits for the next updater tick to update.
