### ISSUE TITLE
Can't add winform controls to the Toolbox

### ISSUE THREAD

**Issue by wilson212** [beto-rodriguez/Live-Charts#313]
I followed the installation instructions to a T, but I keep getting this error whenever I try to add the components to my Visual Studio 2015.

The error -> http://puu.sh/qNjYi/52d64b0dc9.png

**Comment by beto-rodriguez** [comment]
I have not tested with the last release, but it was 15 days ago, and this is the first report I see about it.

Try cleaning and rebuild, then try again, also closing visual studio and reopen it could help

Could you please let me know your .net version?

**Comment by wilson212** [comment]
My .Net version is 4.6.1. I was able to add the WPF controls just fine, but the winforms ones wont add to the toolbox. I have tried re-closing visual studio. Cleaning my build and re-building did not fix the issue.

**Comment by beto-rodriguez** [comment]
I just tested, and yet is works correctly in .net 4.6.1

Notice there are 3 LiveCharts files ensure you are adding `LiveCharts.Winforms`, also ensure you are in the designer, when adding the control to you toolbox, you should be seeing all the normal controls in the toolbox before trying to add this control.

Hope this helps you.

**Comment by kimboox44** [comment]
Same thing here, can't add controls to toolbox using ver0.9.5 but 0.9.2 ,3, 4  works

**Comment by beto-rodriguez** [comment]
In my experience, Visual Studio is no designed to update the version the controls in your toolbox constantly, I've passed many hours trying to debug this issues, but now I am totally convinced that is issues are from VisualStudio, not from the library, maybe I could help VS making the control more friendly, is anyone aware of an article that explains this? 

Practically every time I'm about to publish a new version, my VS designer crashes for both WPF and WinForms (much more buggy), it seems that VS caches many stuff, so we need to help VS to remove these items from cache.

My personal rule goes:

[1]. (WinForms)
Right click in your toolbox, then Reset Toolbox.

![reset toolbox](https://cloud.githubusercontent.com/assets/10853349/24206634/795393dc-0ee4-11e7-9e8a-f98ca62f6906.png)
 
[1]. (WPF)
Close any XAML file and kill XDesProc.exe using windows Task Manager.

2.
Remove any possible cached item. if possible delete `bin `and `obj `folders from your solution, then Clean, Rebuild.

[3]. (WinForms)
Re-add the control to your toolbox https://lvcharts.net/App/examples/v1/wf/Install
