### ISSUE TITLE
How to draw missing points with DateTimePoint values?

### ISSUE THREAD

**Issue by everystone** [beto-rodriguez/Live-Charts#314]
According to the [examples](http://lvcharts.net/App/examples/v1/wpf/Missing%20Points) you can draw missing points using double.Nan. How do you do this when using DateTimePoint values?

I tried doing
`new DateTimePoint { DateTime = DateTime.Now, Value = double.NaN}` which does hide the value from the chart, but it still shows up in the tooltip: 

![image](http://i.imgur.com/kMJNUNC.png)

**Comment by beto-rodriguez** [comment]
It should be the same way, will test to see what is going on

Thanks for reporting

**Comment by everystone** [comment]
I solved this by creating a custom Tooltip class ( I used xaml from DefaultToolTip) and filtered out the NaN values in Data.

        public TooltipData Data
        {
            get
            {
                return _data;
            }

            set
            {
                value.Points = value.Points.Where(p => !double.IsNaN(p.ChartPoint.Y)).ToList();
                _data = value;
                OnPropertyChanged("Data");
            }
        }
Thanks alot for your work on this project.

**Comment by beto-rodriguez** [comment]
Awesome, glad you figure it out
