### ISSUE TITLE
How to hide one serie on the dataTooltip ?

### ISSUE THREAD

**Issue by JulFIC** [beto-rodriguez/Live-Charts#315]
Hello,
I have three series on my chart.
I want to hide only the information of one serie on the dataTooltip . It is possible ?

**Comment by beto-rodriguez** [comment]
Hi

There is no a built in feature to support this, but you can always build your own tooltip that skips a specific series, Follow this example

http://lvcharts.net/App/examples/v1/wpf/Customizing%20Tooltips

Then you should be able to filter the `Data` property in your tooltip to only display the series you need:

    var filteredPoints = Data.Points.Where(x => x.Series.Title != "my series title to ignore");

**Comment by beto-rodriguez** [comment]
I will close this issue for now, feel free to add any comments or suggestions to this or any other new issue

**Comment by JulFIC** [comment]
It works thanks the datatooltip is empty now for the collection

**Comment by Chris854** [comment]
> Hi
> 
> There is no a built in feature to support this, but you can always build your own tooltip that skips a specific series, Follow this example
> 
> http://lvcharts.net/App/examples/v1/wpf/Customizing%20Tooltips
> 
> Then you should be able to filter the `Data.Points` property in your tooltip to only display the series you need:
> 
> ```
> var filteredPoints = Data.Points.Where(x => x.Series.Title != "my series title to ignore");
> ```

Hey Beto,

can you explain this in some more detail? I hae the following custom Tooltip ("MyTooltip"), and am not sure how to use your comment about filteredPoints

`using System.ComponentModel;
using LiveCharts;
using LiveCharts.Wpf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace _3D_Curve_Editor
{
    public partial class MyTooltip : IChartTooltip
    {
        private TooltipData _data;
        public MyTooltip()
        {
            InitializeComponent();
            DataContext = this;
        }

        public event PropertyChangedEventHandler PropertyChanged;

        public TooltipData Data
        {
            get
            {
                return _data;
            }
            set
            {

                _data = value;
                OnPropertyChanged("Data");
            }
        }

        public TooltipSelectionMode? SelectionMode { get; set; }

        protected virtual void OnPropertyChanged(string propertyName = null)
        {
            PropertyChanged.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}`
