### ISSUE TITLE
Multiple series types on single chart

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#32]
I think it would nice to be able to merge chart types.  For example, have a bar chart with a line on it.

**Comment by beto-rodriguez** [comment]
Hello, thanks for helping, yes it should be good, I actually saw this library in Javascript and I am thinking on impleting a lot of features from it. http://www.highcharts.com/demo/spline-symbols, for example in this link you can see that this chart includes images, to solve this issue, images or #26 I was thinking that your should be able to add an `UiFrameworkElement` at a certain position, so you can draw any WPF element at a certain chart point.

**Comment by beto-rodriguez** [comment]
I have been working in this, and not series are compatible, right now you can only add lines to a bar chart or to a stacked bar chart, do you know nother useful combination of series?

![untitled](https://cloud.githubusercontent.com/assets/10853349/11455219/03d95aa6-9618-11e5-8b7d-2d9ea58aa251.png)

![untitled](https://cloud.githubusercontent.com/assets/10853349/11455221/17ae8376-9618-11e5-9a49-e880a8d9f52a.png)

**Comment by beto-rodriguez** [comment]
Text and any ui elements are supported now, I added an example in test project

<p align="center">
  <img src="https://dl.dropboxusercontent.com/u/40165535/LiveCharts/UiElements.png"/>
</p>

**Comment by gregsdennis** [comment]
I think this is complete.  Any reason to keep open?

**Comment by beto-rodriguez** [comment]
Nope
