### ISSUE TITLE
Clipping of point markers

### ISSUE THREAD

**Issue by Reinski** [beto-rodriguez/Live-Charts#325]
Hi! I am using LiveCharts to visualize a number of events on a time axis, which means my points are (X,Y) where X is a DateTime and Y is an integer >=0.
I definitely want to have the X-axis on the bottom and I want the Y-axis to start at 0 (zero), which is easy to do via the MinValue property.
However, there is a problem with points lying on Y=0, meaning they are located directly on the X-axis at the lower border of the chart area: 
Their markers are only visible partly, because clipping cuts away the part that lies outside the chart area. 
![clipped-markers](https://cloud.githubusercontent.com/assets/4990380/18225171/1ca3fd32-71ed-11e6-9d72-10d4667c16eb.gif)

I have tried to shift the MinValue a little into the negative, so that there is some space to draw the circles. But since I need to do that relatively to the axis value span, it may happen that the chart draws negative value labels.
E.g. I decided to extend the Y-axis by 5%. When I have a MaxValue of 100 and MinValue of 0, this means I set the Y-axis MinValue to -5. Now the circles are fully visible, but the chart will display the lowest Y-label with "-5", which really doesn't make sense for a chart that can only have positive values.
![not-clipped-but-negative](https://cloud.githubusercontent.com/assets/4990380/18225170/1c9f893c-71ed-11e6-9d23-dfdd94128cc2.png)

Is there an easy way to get this solved? Any help is appreciated... ;-)

**Comment by beto-rodriguez** [comment]
Sadly the way the code is implemented makes it hard to solve this.

Clipping is required, and solves many issues, specially when zooming/panning, imagine in your chart that you only need to display (at Y axis) from 10 to 20, clipping the line will make it look correctly, otherwise, the line will be drawn all over your app.

So to solve this scenario I see some alternatives:

1. You could simply remove the point of your line, if that is ok for you `MyLineSeries.PointGeometry = null;`
2. I guess the correct answer for this is to add a new property to specify the value where laves start/end something like `Axis.MinLabelValue`, `Axis.MaxLabelValue`

**Comment by Reinski** [comment]
Hi, thanks for your reply! I see the point, however, I'd expect a logic like "if the point lies in the visible area (or at the edge) then the according point marker is always fully rendered".
Of course, properties like Axis.MinLabelValue and Axis.MaxLabelValue would also be nice to have for such a case.
Do you see any chance to handle this 'manually' via the Labels collection in a reasonable way? I don't have any experience with it so far.

**Comment by Reinski** [comment]
Additional info: I've played around with the Labels property of the AxisY, but without success. As soon as I set any Labels manually, no labels show up at all.
Is there a way to set labels on the Y-axis manually? All examples I've seen so far only use it on the X-axis.

**Comment by beto-rodriguez** [comment]
What do you mean with manually? can I please see a example

The "Basic Row" example sets labels in the Y axis

https://lvcharts.net/App/examples/v1/wpf/Basic%20Row

https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart/Basic%20Bars

**Comment by everystone** [comment]
I found that setting MaxValue to 105, and MinValue to -5 works for me. The chart still displays 0-100, but the values are not clipping that much at 0 and 100.

**Comment by beto-rodriguez** [comment]
I forgot to reference the close of this issue with https://github.com/beto-rodriguez/Live-Charts/pull/435 notice in that PR I fixed this not only at the bottom/top of a chart, I also granted that the first and last points are totally visible always.

It will be included in the next version of the library, you will notice the way the library decides its limits is smarter and cleaner.
