### ISSUE TITLE
Gauge color issue

### ISSUE THREAD

**Issue by qqttrr** [beto-rodriguez/Live-Charts#326]
![2](https://cloud.githubusercontent.com/assets/11064107/18245122/2e9e767c-736c-11e6-8600-a0381130d33d.png)
When binding value exceeds "To" property, the gauge color, as you can see in the attached screenshot, becomes unexpected. Is there any way to fix it? The color is supposed to change from SeaGreen to DarkRed here.

**Comment by FoggyFinder** [comment]
@qqttrr , You can show [MCVE](http://stackoverflow.com/help/MCVE) ?

**Comment by beto-rodriguez** [comment]
Oops, I named wrong the commit, but https://github.com/beto-rodriguez/Live-Charts/commit/292860b02919557e219be57d5dde6ed7bebb93cf fixes this.

Now the interpolation of colors is bounded at Max and Min colors.
