### ISSUE TITLE
LineSeries unexpected triangle

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#328]
From SO

http://stackoverflow.com/questions/39409144/wpf-livecharts-line-series-visibility-bugged

**Comment by drdran** [comment]
I have the same issue with a line seriees too.

**Comment by beto-rodriguez** [comment]
This fix will be included in the next release (0.8)

**Comment by beto-rodriguez** [comment]
Actually this issuer was not completely fixed with 0.8 release, I am building more complex examples for the library and faced this issue, I made a fix already, sadly the fix I applied in 0.8 seems not to be working for all cases, 0.8.1 will include another patch to this issue.

Here is the example to test this issue:

![new](https://cloud.githubusercontent.com/assets/10853349/20472075/68afa2ea-af7c-11e6-95e9-7b4c6eec44e1.gif)
