### ISSUE TITLE
Unable to bind AngularSection FromValue

### ISSUE THREAD

**Issue by RobSmyth** [beto-rodriguez/Live-Charts#329]
#### How to reproduce?

AngularSection.FromValue is not a dependency property. As a result I cannot using binding. I'm using an AngularGauge and the FromValue and ToValues are using binding, but this is not useful if I cannot also bind the sections.

#### Extra notes

I would like these to become dependency properties.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.11.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
This is now supported and will be included since 0.7.14 version

Thank for reporting!
