### ISSUE TITLE
Ability to rotate axis labels

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#33]
I'd like to see the ability to rotate the axis labels so that I can display them veritically or at some arbitrary angle.

**Comment by beto-rodriguez** [comment]
I was trying to fix this, but aftet trying I think the best solution is to create a new charts, for example add a row chart (inverse of column chart), stacked row chart and inverse line and are chart

**Comment by gregsdennis** [comment]
Can you create a branch with your efforts? I'll take a shot at it.

**Comment by beto-rodriguez** [comment]
Sadly I deleted that because I saw no future.

**Comment by gregsdennis** [comment]
Okay.  I'll browse the code and see if I can do it.  It really should be a feature.  Other graphs can do it.

**Comment by beto-rodriguez** [comment]
yes your idea is good, What I didnt liked was my code, thats why I did not save it

**Comment by gregsdennis** [comment]
Usually a good idea.  I'll take a look.  Planning on creating a prop on the series for rotation, then applying a render transform.  There may be a few gotchas, but I'll work through them.

**Comment by beto-rodriguez** [comment]
This is now supported, see exmaples here 
**Bars**
https://github.com/beto-rodriguez/Live-Charts/tree/master/ChartsTest/BarExamples/RotatedBar
**Lines**
https://github.com/beto-rodriguez/Live-Charts/tree/master/ChartsTest/Line%20Examples/RotadedLine
**Stacked Bar**
https://github.com/beto-rodriguez/Live-Charts/tree/master/ChartsTest/StackedBarExamples/StackedBarRotated
