### ISSUE TITLE
NullReferenceException in AxesCollection.Clear()

### ISSUE THREAD

**Issue by grehovm** [beto-rodriguez/Live-Charts#330]
#### How to reproduce?

in view:

``` xaml
<UserControl x:Class="DopCalc.Views.ShewhartView"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:wpf="clr-namespace:LiveCharts.Wpf;assembly=LiveCharts.Wpf"
        xmlns:cal="http://www.caliburnproject.org">
    <Grid >
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*"></ColumnDefinition>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"></RowDefinition>
            <RowDefinition Height="*"></RowDefinition>
        </Grid.RowDefinitions>
        <StackPanel Orientation="Horizontal">
            <DatePicker x:Name="From" MinWidth="100" Margin="2"></DatePicker>
            <DatePicker x:Name="To" MinWidth="100" Margin="2"></DatePicker>
            <ComboBox x:Name="Components" DisplayMemberPath="UserName" SelectedValuePath="Num" MinWidth="200" Margin="2" SelectedValue="{Binding Number}"></ComboBox>
            <Button Content="Показать" cal:Message.Attach="[Event Click] = [Action Show(From.SelectedDate, To.SelectedDate, Components.SelectedValue)]" MinWidth="100" Margin="2"></Button>
        </StackPanel>
        <wpf:CartesianChart Grid.Row="1" Grid.Column="0" Series="{Binding SeriesCollection}" AxisX="{Binding AxesCollection}" Margin="2"></wpf:CartesianChart>
    </Grid>
</UserControl>


```

in viewmodel:

``` csharp
public SeriesCollection SeriesCollection { get; set; } = new SeriesCollection();
public AxesCollection AxesCollection { get; set; } = new AxesCollection();

public void Show(DateTime from, DateTime to, int number)
{
    if (SeriesCollection.Count > 0)
        SeriesCollection.Clear();
    if (AxesCollection.Count > 0)
        AxesCollection.Clear();
    var model = _shewhartService.MakeShewhartMap(from.Date, to.Date.AddSeconds(86400 - 1), number - 1);
    if (model == null)
        return;
    var values = new ChartValues<double>();
    values.AddRange(model.Data.Select(x => x.Value));
    var series = MakeSeries("Data", values);
    series.StrokeDashArray = null;
    SeriesCollection.Add(series);
    SeriesCollection.Add(MakeSeries("m+3s", MakeArray(model.Data.Count, model.Mu + 3 * model.Sigma)));
    SeriesCollection.Add(MakeSeries("m+2s", MakeArray(model.Data.Count, model.Mu + 2 * model.Sigma)));
    SeriesCollection.Add(MakeSeries("m", MakeArray(model.Data.Count, model.Mu)));
    SeriesCollection.Add(MakeSeries("m-2s", MakeArray(model.Data.Count, model.Mu - 2 * model.Sigma)));
    SeriesCollection.Add(MakeSeries("m-3s", MakeArray(model.Data.Count, model.Mu - 3 * model.Sigma)));
    AxesCollection.Add(new Axis { Labels = model.Data.Select(x => x.Key.ToString("dd.MM.yyyy HH:mm:ss")).ToList() });
}
```

When i double click on button to call function i get System.NullReferenceException on calling `AxesCollection.Clear();`:

```
   in LiveCharts.Wpf.Axis.Clean()
   in LiveCharts.Wpf.AxesCollection.OnNoisyCollectionChanged(IEnumerable`1 oldItems, IEnumerable`1 newItems)
   in LiveCharts.Helpers.NoisyCollection`1.OnCollectionChanged(IEnumerable`1 olditems, IEnumerable`1 newItems)
   in LiveCharts.Helpers.NoisyCollection`1.Clear()
   in DopCalc.ViewModels.ShewhartViewModel.Show(DateTime from, DateTime to, Int32 number) in C:\Projects\dcch21\DopCalc\ViewModels\ShewhartViewModel.cs:line 45
```
#### Extra notes

i use caliburnmicro if this is important.
#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.13</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>7</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Hi, thanks for the report, I will try, but you don't normally need o clear/add a new axis, an axis class is smart enough to redar when you change its labels, and that is how you should be using it.

Instead of: 
    AxesCollection.Add(new Axis { Labels =model.Data.Select(x => x.Key.ToString("dd.MM.yyyy HH:mm:ss")).ToList()  });

You only change the labels of your current axis, for example: 
    myChart.AxisX[0].Labels = model.Data.Select(x => x.Key.ToString("dd.MM.yyyy HH:mm:ss")).ToList() ;

**Comment by grehovm** [comment]
In my example, i cleanse completely because the model can be null and an user should not see an old data \ axis. In your example, you need to follow order of axes or to store a pointer to them. Display chart is quite rare (when user click) and not expensive operation (for my part), I went for a simpler way - all clean out and rebuild

**Comment by Bennith** [comment]
I haven't had this issue but added in code behind a step for checking zero count and clear(); so probably not ideal but gets the job done!

//Init Series Collection
STOOverviewSeries = new SeriesCollection { };

//Check count of series
if (STOOverviewSeries.Count == 0)
{
     
     //add stuff...

}else{

     //clear and then redraw/refresh new data
     STOOverviewSeries.Clear();
     STOOverviewSeries = new SeriesCollection { new ColumnSeries
      {
            Title = "Warehouse Location",
             Values = new ChartValues<double> { 1332, 540, 139, 150, 2234, 334, 5567 }
       }
       };

      //etc...
}

**Comment by grehovm** [comment]
Unfortunately, I had to finish the program quickly and I have replaced live-charts with oxyplot.

**Comment by beto-rodriguez** [comment]
This is finally fixed and will be included in the next version of the library, thanks for reporting
