### ISSUE TITLE
VisualElementsCollection.Clear() isn't clearing UIElements

### ISSUE THREAD

**Issue by carlmichaelbenson** [beto-rodriguez/Live-Charts#334]
#### How to reproduce?

In my PressureGraphView.xaml ...

        <lvc:CartesianChart x:Name="TheChart"
                            AnimationsSpeed="{Binding AnimationsSpeedProperty}"
                            AxisX="{Binding AxisXCollectionProperty}"
                            AxisY="{Binding AxisYCollectionProperty}"
                            Background="{DynamicResource ChartBackgroundBrush}"
                            ChartLegend="{Binding ChartLegendProperty}"
                            DataTooltip="{Binding DataTooltipProperty}"
                            DisableAnimations="{Binding DisableAnimationsProperty}"
                            Hoverable="False"
                            LegendLocation="None"
                            Series="{Binding SeriesCollectionProperty}"
                            VisualElements="{Binding VisualElementsCollectionProperty}"
                            Zoom="{Binding ZoomProperty}" />

In my PressureGraphViewModel.cs ...

                // Initialize Chart

                AnimationsSpeedProperty = TimeSpan.FromMilliseconds(80.0);

                ChartLegendProperty = null;

                // Get rid of Chart tooltips
                DataTooltipProperty = null;

                // Disable Zooming
                ZoomProperty = ZoomingOptions.None;

                // Disable Animations
                DisableAnimationsProperty = true;
                
                // Create a Mapper for standard Point type
                var mapper = Mappers.Xy<Point>()
                    .X(value => value.X) //use the X property as X
                    .Y(value => value.Y); //use the Y property as Y

                // Save the mapper globally
                Charting.For<Point>(mapper);

                // Axis Setup
                AxisXCollectionProperty = new AxesCollection();
                AxisYCollectionProperty = new AxesCollection();

                // X Axis Setup
                AxisXCollectionProperty.Add(new Axis
                {
                    LabelFormatter = val => TimeSpan.FromSeconds(val).ToString(@"mm\:ss"),
                    FontFamily = (FontFamily) Application.Current.FindResource("NormalFontFamily"),
                    FontSize = (double) Application.Current.FindResource("Heading2FontSize"),
                    MinValue = MinValueX = 0.0,
                    MaxValue = MaxValueX = 90.0,
                    Separator = new LiveCharts.Wpf.Separator
                    {
                        Step = 10.0,
                        IsEnabled = true,
                        Stroke = (Brush) Application.Current.FindResource("HighlightBrush"),
                        StrokeThickness = 1.0
                    }
                });

                AxisSection m_section = new AxisSection();

                double axisYSeparatorStep = 500.0;

                if (PressureUnits.Equals(Converter.PressureUnitType.psi.ToString(), StringComparison.OrdinalIgnoreCase))
                {
                    CurrentPressureLimit = Converter.ConvertPressure(CurrentPressureLimit, Converter.PressureUnitType.kpa, Converter.PressureUnitType.psi);
                    axisYSeparatorStep = 100.0;
                }
                else if (PressureUnits.Replace('/', '_').Equals(Converter.PressureUnitType.kg_cm2.ToString(), StringComparison.OrdinalIgnoreCase))
                {
                    CurrentPressureLimit = Converter.ConvertPressure(CurrentPressureLimit, Converter.PressureUnitType.kpa, Converter.PressureUnitType.kg_cm2);
                    axisYSeparatorStep = 50000.0;
                }

                // Y Axis Setup - For plotting pressure
                AxisYCollectionProperty.Add(new Axis
                {
                    FontFamily = (FontFamily)Application.Current.FindResource("NormalFontFamily"),
                    FontSize = (double)Application.Current.FindResource("Heading2FontSize"),
                    MinValue = 0.0,
                    MaxValue = CurrentPressureLimit * 1.1,
                    Separator = new LiveCharts.Wpf.Separator
                    {
                        Step = axisYSeparatorStep,
                        IsEnabled = true,
                        Stroke = (Brush)Application.Current.FindResource("HighlightBrush"),
                        StrokeThickness = 1.0
                    }
                });

                // Y Axis Setup - for displaying images... phase start, timed reminders, etc.
                AxisYCollectionProperty.Add(new Axis
                {
                    MinValue = 0.0,
                    MaxValue = 400.0,
                    ShowLabels = false
                });

                // Max Pressure Section
                m_section = new AxisSection();
                m_section.FromValue = CurrentPressureLimit;
                m_section.ToValue = CurrentPressureLimit;
                m_section.Fill = (Brush)Application.Current.FindResource("TransparentBrush");
                m_section.Stroke = (Brush)Application.Current.FindResource("ArmActionBrush");
                m_section.StrokeThickness = 3.0;
                AxisYCollectionProperty[0].Sections.Add(m_section);

                Next = 80.0;

                AxisXCollectionProperty[0].MinValue = 0.0;
                AxisXCollectionProperty[0].MaxValue = 90.0;
                
                MyValues = new ChartValues<Point>();
                
                // Setup the SeriesCollectionPropertySeriesCollectionProperty

                SeriesCollectionProperty = new SeriesCollection();

                // How to set up a SolidColorBrush resource in xaml, and then use findResource in codebehind:
                //
                // In xaml...
                // <SolidColorBrush x:Key="BrushFFXXXXXX">#FF8D8A8A</SolidColorBrush>
                // 
                // In code behind...
                // myTextBox.Background = (Brush)Application.Current.MainWindow.FindResource("BrushFFXXXXXX");
                //

                // CartesianChart Setup
                CurrentLineSeries = new LineSeries();
                MyValues = new ChartValues<Point>();
                MyValues.Add(new Point(0.0, 0.0));
                CurrentLineSeries.Values = MyValues;
                CurrentLineSeries.PointGeometrySize = 1;
                CurrentLineSeries.Fill = (Brush)Application.Current.FindResource("TransparentBrush");
                m_currentLineSeriesStroke =
                    m_currentLineSeriesStrokeHold =
                        CurrentLineSeries.Stroke = (Brush)Application.Current.FindResource("TransparentBrush");
                CurrentLineSeries.StrokeThickness = 3.0;
                SeriesCollectionProperty.Add(CurrentLineSeries);

                // Setup the VisualElementsCollectionProperty
                VisualElementsCollectionProperty = new VisualElementsCollection();
                VisualElement test = new VisualElement();
                test.X = 10.0;
                test.Y = 10.0;
                test.AxisX = 0;
                test.AxisY = 1;
                test.UIElement = new Rectangle { Width = 10.0, Height = 10.0, Fill = Brushes.LimeGreen };
                VisualElementsCollectionProperty.Add(test);

                VisualElementsCollectionProperty.Clear();

#### Extra notes

I expect VisualElementsCollectionProperty.Clear(); to clear the visual elements from the chart.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.13</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>8.1</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
You are right Visual Elements were not responsive, this fixes it.

Now it updates correctly in all cases, Add, Remove, Clear, or even when you change the X or Y properties in the visual element it is animated to its new position. 

This fix will be included in 0.7.14

**Comment by mschindler504** [comment]
> You are right Visual Elements were not responsive, this fixes it.
> 
> Now it updates correctly in all cases, Add, Remove, Clear, or even when you change the X or Y properties in the visual element it is animated to its new position.
> 
> This fix will be included in 0.7.14

Hi, I'm getting a null reference exception "object reference not set to an instance of an object" and I've narrowed it down to the UIElement. I clear the VisualElements, but everytime I try to add more visualelements, it get the error when trying to add. Any help would be greatly appreciated. Thanks

**Comment by visouser2** [comment]
> > You are right Visual Elements were not responsive, this fixes it.
> > Now it updates correctly in all cases, Add, Remove, Clear, or even when you change the X or Y properties in the visual element it is animated to its new position.
> > This fix will be included in 0.7.14
> 
> Hi, I'm getting a null reference exception "object reference not set to an instance of an object" and I've narrowed it down to the UIElement. I clear the VisualElements, but everytime I try to add more visualelements, it get the error when trying to add. Any help would be greatly appreciated. Thanks

@mschindler504 Did you ever fix the issue you had?
