### ISSUE TITLE
ChartValues<decimal> requires explicit casting 

### ISSUE THREAD

**Issue by srv-cjlo** [beto-rodriguez/Live-Charts#335]
#### How to reproduce?

new ChartValues<decimal> { 1.23, 4.54, 5.67 } threw InvalidCastException. I have to cast decimal explicitly: new ChartValues<decimal> { (decimal)1.23, (decimal)4.54, (decimal)5.67} or ChartValues<decimal> { 1.23m, 4.54m, 5.67m }.

#### Extra notes

I would not expect that to happen for typed generics

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.13.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>8.1</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Well after some research this is not a bug, and thanks to the SO community they explained it better.

This explains it  better.

http://stackoverflow.com/questions/39601319/generic-decimal-cant-cast-from-double/39601377?noredirect=1#comment66511336_39601377

So it is actually really simple, when you `new ChartValues { 1.23, 4.54, 5.67 } ` your values are double for the compiler, unless you cast them, or let it know they are decimal as I suggested adding `m` and the end of each value, that is why the object overload is being called, and as explained in the link above

> The reason being that a boxed value can only be unboxed to its real type. In your case your are boxing a double and trying to unbox it to a decimal. That is not allowed.

**Comment by srv-cjlo** [comment]
Thanks you! Will you consider using the new type dynamic, or is it relevant? I have not used this type before, and not sure how expensive it is though.

**Comment by beto-rodriguez** [comment]
No I wont use dynamics, the performance is not what scares me, but using generics and dynamic is a really bad design.

The only way for you to make it work is using decimals. 

P.S. notice any generic collection is not compilable with the syntax you are using

    //this is impossible
    var list = new List<decimal> { 1.23, 1.53, 6.3};
