### ISSUE TITLE
180 / 360 deg guage sizing

### ISSUE THREAD

**Issue by RobSmyth** [beto-rodriguez/Live-Charts#338]
#### How to reproduce?

Place two 180 deg gauges in two grids of the same size. Only difference between the 2 is that one is configures to be a 360 deg gauge. The 360 deg guage fills the grid but the 180 deg gauge has large padding both vertically and horizontally. The 180 deg gauge is only filling about half of the grid I would expect it too.

![capture](https://cloud.githubusercontent.com/assets/6183736/18814092/1533ccae-8353-11e6-9a43-b666d9ecd152.PNG)
#### Extra notes

XAML code fragment:

```
    <Grid Name="root" Margin="0" Style="{DynamicResource GridStyle}">
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>
        <wpf:Gauge Name="guage" Grid.Row="0" Margin="3"
                   Uses360Mode="{Binding Path=Uses360Mode, Mode=OneWay}" 
                   FromColor="{Binding FromColour, Mode=OneWay}" 
                   ToColor="{Binding ToColour, Mode=OneWay}"
                   From="{Binding Minimum, Mode=OneWay}"
                   To="{Binding Maximum, Mode=OneWay}"
                   Value="{Binding Value, Mode=OneWay}" 
                   LabelFormatter="{Binding Formatter}" 
                   Foreground="{DynamicResource ForegroundBrush}"
                   FontSize="{Binding Path=ActualHeight, ElementName=root, Converter={StaticResource doubleConverter}, ConverterParameter=0.07}" />
        <TextBlock Name="label" Grid.Row="1"
                   Style="{DynamicResource TextboxStyle}"
                   HorizontalAlignment="Center" TextAlignment="Center" IsHitTestVisible="False" 
                   FontWeight="Bold" Margin="3,1,3,10" Text="{Binding Label, Mode=OneWay}"
                   FontSize="{Binding Path=ActualHeight, ElementName=root, Converter={StaticResource doubleConverter}, ConverterParameter=0.10}"/>
    </Grid>
```
#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>7.13.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by briggsyuk** [comment]
I have the same issue. you have to play around and have some extreme margins in XMAL to make the gauge fit.

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is already fixed, and will be included in the next version of the library.
