### ISSUE TITLE
DataTooltips keeps displaying on Multiple Charts

### ISSUE THREAD

**Issue by eduard-schwenk** [beto-rodriguez/Live-Charts#340]
#### How to reproduce?

I've made some observations when i display more than 1 Chart on Page:
i have a table with 3 Columns on my page and show 3 different charts with column/bar series,
If i move the mouse from one chart to another to see some data tooltips, the data-tooltips keeps displaying and don't disappears, except the last chart that i leave with mouse to free area,
this one will desappear properly.
Just need to confirm if someone have a similar issue and can it be solved with some workaround? 

#### Extra notes

it seems that whe here is no space between charts, the component don't register that the focus on this control was lost.
![chart_issue01](https://cloud.githubusercontent.com/assets/20314709/18833270/2adba9e4-83f0-11e6-8db7-0d3d368cefde.png)

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.14.3</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.1 (target)</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 7 Pro SP1 (x86)</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Thank, last commit fixes it, this will be included in 0.7.15
