### ISSUE TITLE
Data disappears if value is higher than axis max-value

### ISSUE THREAD

**Issue by eduard-schwenk** [beto-rodriguez/Live-Charts#342]
#### How to reproduce?

Hi i've observed another "little" issue after upgrading one of projects from LiveChart 7.08 to the newer 7.14.3 version:
if i have setted the axis max value and some data is higher than the Axis-MaxValue this data will not be drawn!
In my case i have the YAxis with MAxValue 1.1 and Values : 1.12 0.97 1.06 0.84 1.26
so the first and the last one disappears ...

#### Extra notes

here is screenshot from 7.08 and 7.14.3 versions:of the same chart:
7.08:
![livecharts_7_08](https://cloud.githubusercontent.com/assets/20314709/18879832/066ac37e-84d6-11e6-946a-983ceb4d9b44.png)
7.14.3:
![livecharts_7 14 3](https://cloud.githubusercontent.com/assets/20314709/18879840/0b7564e6-84d6-11e6-8372-2bbc05265f1b.png)

thanks in advance, ... and: Great job!

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>7.14.3</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Win 7 Pro SP1 (x86)</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Las commit fixed it, thanks for the report, this will be included since 0.7.16

thanks again!
