### ISSUE TITLE
Axis Title Position (Delayed Centering)

### ISSUE THREAD

**Issue by Billy-Joel** [beto-rodriguez/Live-Charts#344]
Hi Beto,

Good day, another great release you have here. This tool keeps getting better every update.

I have some concern regarding the title of x & y axis, for some reason it stop from centering on the first update of the values or on the first initialization of the graph.

I didn't change any codes and working fine until  7.12.

First Update (Not centered)
![view1](https://cloud.githubusercontent.com/assets/18839973/18909670/903ea70a-8585-11e6-9522-953cdd763f15.PNG)

2nd update (Centered)
![view2](https://cloud.githubusercontent.com/assets/18839973/18909676/95846682-8585-11e6-819a-f39a53193e1c.PNG)

Is this a bug or do I have to set something to automatically re-position the label on the first run?

<table>
<tr>
    <td>Live-Charts version </td>
    <td>7.15</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Thanks @Billy-Joel for your constant reports, I really appreciate it.

Last commit should fix this issue, this fix will be included in 0.7.16
