### ISSUE TITLE
DateTimePoint instead of Custom MeasureModel in Costant Changes Sample

### ISSUE THREAD

**Issue by drdran** [beto-rodriguez/Live-Charts#345]
#### Extra notes

I think that replace MeasureModel with DateTimePoint in the Costant Changes Sample will improve greatly the performance: I visualize 3 graph with 15 series with 30 point each and using the DateTimePoint model the grpah run fast and the system is much more responsive.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.15</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.61</td>
</tr>
<tr>
    <td>Windows</td>
    <td>7</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Maybe, but the example also helps user to understand how the library works, and that you are not only limited to use the already defined types.

**Comment by beto-rodriguez** [comment]
Hi

I will close this because there is now a better article to explain how to increase performance

https://lvcharts.net/App/examples/v1/wpf/Improve%20Performance
