### ISSUE TITLE
Charts for UWP  plan?

### ISSUE THREAD

**Issue by yanjingenious** [beto-rodriguez/Live-Charts#346]

**Comment by beto-rodriguez** [comment]
Yes and also Xamarin, that is the plan, @AuroraDysis have being working on it.

Of course there are some issues to fix when migrating to another platform I don't know the date but I am sure we will support both in no more than 6 months

**Comment by yanjingenious** [comment]
Thank you very much for your work.
expecting  :-D

**Comment by beto-rodriguez** [comment]
Will close this issue, for future reference please see #186
