### ISSUE TITLE
Series fill not able to be set by data trigger

### ISSUE THREAD

**Issue by Stephen-Ross** [beto-rodriguez/Live-Charts#347]
#### How to reproduce?

If I have a Series setup with a data trigger that will change the fill based on a condition within my ViewModel the fill will not actually change based on the trigger value.

``` xaml
<Style TargetType="{x:Type wpf:ScatterSeries}">
    <Setter Property="MaxPointShapeDiameter" Value="4"/>
    <Setter Property="MinPointShapeDiameter" Value="4"/>
    <Setter Property="Visibility" Value="{Binding Path=Show, Converter={StaticResource BooleanToVisibilityConverter}}"/>
    <Setter Property="Fill" Value="{Binding Path=Color, Converter={StaticResource UintToBrushConverter}}"></Setter>
     <Style.Triggers>
         <DataTrigger Binding="{Binding RelativeSource={RelativeSource AncestorType={x:Type wpf:CartesianChart}}, Path=DataContext.UseSingleColor, Mode=OneWay, UpdateSourceTrigger=PropertyChanged}" Value="True">
             <Setter Property="Fill" Value="{StaticResource AccentColorBrush}"/>
         </DataTrigger>
     </Style.Triggers>
</Style>
```

The Fill is initially set correctly by the Setter of the style but when the data trigger fires the value never changes from the set value.
#### Extra notes

I've looked through the LiveCharts code and I believe this stems from the fact that the `ChartUpdater` will `EnusureElementBelongsToCurrentView` no matter what. And since this method removes the element from the `UIElementCollection` all the properties are set to default so when the Colors are set it uses the default Fill color again.

I have been able to resolve this locally by adding a `ContainsElement` method to the `Chart`:

``` c#
public bool ContainsElement(object element)
{
    var wpfElement = (FrameworkElement)element;
    if (wpfElement == null)
    {
        return false;
    }

    return this.Canvas.Children.Contains(wpfElement);
}
```

Changing the `ChartUpdater.Update` to make use of this method to decide if the element needs to actually be added to the View as:

``` c#
foreach (var series in Chart.View.ActualSeries)
{
    if (Chart.View.ContainsElement(series))
    {
        continue;
    }

    InitializeSeriesView(series);
    series.ActualValues.Initialize(series);
    series.InitializeColors();
    series.DrawSpecializedElements();
}
```
#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.15</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>7</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
I don't see how this could fail, but moving the core of library scares me, I will test before applying your suggestion.

thanks

**Comment by Stephen-Ross** [comment]
I wouldn't say it's 'failing', it's more to do with the code structure that you have, so when the Series attempts to 'Update' itself it will come and and remove the Series from the `UIElementCollection` and then re-add it which will take all the default values as the triggers won't be checked at this point.

It will them attempt to calculate the `Triggers`, which will attempt to update the `UIElementCollection` again, which will start the process over again, and again and on forever.

So effectively you don't want to be re-adding the `Series`, you want to always be using the base object, both for performance and also due to the fact that the `Triggers` will never be calculated correctly.

This is why I didn't create a pull request for this as you obviously know the code better than me and since this part of the code is a high traffic area I didn't want to fix this issue but break something else.

**Comment by beto-rodriguez** [comment]
I tested your solution in some scenarios, it seems to be running properly, personally scares me changing this high traffic zone, but seems to be running correctly, I will merge this, we need to try it to solve this case, this will be included since the next version of the library 0.9.2

**Comment by beto-rodriguez** [comment]
I'll actually I am reverting this, found the first issue, wont include in 0.9.2 I need more testing time to fix this...

**Comment by beto-rodriguez** [comment]
I was able to fix this issue with https://github.com/beto-rodriguez/Live-Charts/commit/536fef74f11db09987d2de93462279ee5a430094 I actually created a small example with this feature, it will be uploaded in the site soon.

Thanks for the report
