### ISSUE TITLE
How to set Formatter on a custom ToolTip

### ISSUE THREAD

**Issue by apresmoi** [beto-rodriguez/Live-Charts#348]
Hello, is there any way to hide some series in the hover tooltip?

I mean, let say that I plot a function with it's error bars. I want the tooltip just to show the values of the function, but not the ones from the error bars.

Can this be done without creating a custom tooltip?

I am using
<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.13.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by apresmoi** [comment]
Answer: https://github.com/beto-rodriguez/Live-Charts/issues/315

**Comment by apresmoi** [comment]
Hello, I have an issue, how can I make the YFormatter work in my custom ToolTip ?

**Comment by beto-rodriguez** [comment]
Hi

Please see the LabelPoint property of the series class

https://lvcharts.net/App/documentation/beta/LiveCharts-Wpf-Series

here is an example https://github.com/beto-rodriguez/Live-Charts/blob/master/Examples/Wpf/PieChart/PieChartExample.xaml.cs

```c#
public partial class PieChartExample : UserControl
    {
        public PieChartExample()
        {
            InitializeComponent();

            PointLabel = chartPoint =>
                string.Format("{0} ({1:P})", chartPoint.Y, chartPoint.Participation);

            DataContext = this;
        }

        public Func<ChartPoint, string> PointLabel { get; set; }
    }
````

```xml
<lvc:PieChart LegendLocation="Bottom">
            <lvc:PieChart.Series>
                <lvc:PieSeries Title="Maria" Values="3" DataLabels="True" PushOut="20" 
                               LabelPoint="{Binding PointLabel}"/>
            </lvc:PieChart.Series>      
</lvc:PieChart>
```

Let me know if this is not enough
