### ISSUE TITLE
Gantt Chart

### ISSUE THREAD

**Issue by RiderOfTheli** [beto-rodriguez/Live-Charts#351]
Hello,

I would like to ask you, if it's possible that in the nearest future you will be able to add Gantt Chart to your library?
#### How to reproduce?

I was trying to achieve this when playing with RowSeries() but I think there should be something like StartPoint for each row or something like that.
#### Extra notes

What I have:

![row](https://cloud.githubusercontent.com/assets/8041023/19233202/580fabe6-8ee4-11e6-92b7-b6bd177c87b8.png)

How it could be:

![gantt](https://cloud.githubusercontent.com/assets/8041023/19233211/648a1a28-8ee4-11e6-83dd-2398489d5419.png)

Thank you for any comment on that :)
#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.15</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
I like your idea, it is simple to implement.

Adding a double property `StartPoint` to Row and column series, and by default it is 0, so you will get the current behavior.

**Comment by beto-rodriguez** [comment]
This is already supported and will be included since version 0.8

for an example please see https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart/GanttChart

The example will be in the Website soon

![new](https://cloud.githubusercontent.com/assets/10853349/19914088/6ea3b286-a06d-11e6-93a2-7dfcb15d3a24.gif)

**Comment by RiderOfTheli** [comment]
Fantastic! 

Thank you!

**Comment by szg1993** [comment]
Hi!

I would like to create a gantt chart, and yours in the example is almost perfect for me.
Could you help me to achieve this mods:

1. Fixed row height to the Task0...11.
2. Remove the space between the rows.
3. Disable the resizing of the chart when I resize the window.

Thank you!

**Comment by szg1993** [comment]
Hi!

I would like to create a gantt chart, and yours in the example is almost perfect for me.
Could you help me to achieve this mods:

1. Fixed row height to the Task0...11.
2. Remove the space between the rows.
3. Disable the resizing of the chart when I resize the window.

Thank you!

**Comment by atjbat** [comment]
Good morning
Someone can help me about possibility to strech gantt row with mouse?
Is there a example where I can start?
thank you
