### ISSUE TITLE
A advanced zooming feature would be great

### ISSUE THREAD

**Issue by helmuteke** [beto-rodriguez/Live-Charts#353]
A advanced zooming feature would be great like this one

![zoom](https://cloud.githubusercontent.com/assets/4700280/19519695/61b24b4c-960d-11e6-8b4c-d3a963b3f654.png)
)

**Comment by beto-rodriguez** [comment]
Check for this example, you don't necessarily need to use the Geared package to make it work.

Getting ready more articles about advanced features, will keep this open while I upload the examples

https://github.com/Live-Charts/GearedExamples/tree/master/Wpf/Scrolling

**Comment by helmuteke** [comment]
hi , normaly i work with forms instead wpf. have to learn wpf.
so i can not rebuild this example. Can you give me a full project file please ?

**Comment by beto-rodriguez** [comment]
The article is not uploaded yet, but the previous link helped you, I am closing this to keep issues clean, again the article will be in the site soon
