### ISSUE TITLE
Axis Labels Don't All Appear

### ISSUE THREAD

**Issue by mdisbrow** [beto-rodriguez/Live-Charts#358]
#### How to reproduce?

Create a chart with an Axis and set the Labels property:
cartesianChart1.AxisX.Add(new Axis
            {
                Title = "",
                FontSize = 15,
                FontWeight =  FontWeights.ExtraBold,
                Labels = chartValues.Select(chart => chart=="0"? "":chart).ToList()
            });
Set the chart to have Dock style of Fill and AutoSize to True

As the chart is adjusted to various sizes the Labels appear/disappear.
#### Extra notes

Chart displayed in larger size
![chart-all-labels](https://cloud.githubusercontent.com/assets/16465420/19805781/fc6ea3cc-9cdb-11e6-8e9c-93d188850778.PNG)

Chart displayed in shorter size
![charl-some-labels](https://cloud.githubusercontent.com/assets/16465420/19805784/02e3e794-9cdc-11e6-86d2-529fa90afeda.PNG)
#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.17.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 7 Enterprise Service Pack 1 64-bit</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Hi, I am not able to reproduce this issue, please let me know more about it, also if you could provide a repository with the issue then I can fix it faster.

The WinForms examples in the library have the Dock property to fill and they work correctly.

![new](https://cloud.githubusercontent.com/assets/10853349/19905369/1035d8c2-a03c-11e6-8ff9-d34c3529bd12.gif)

**Comment by mdisbrow** [comment]
I will look at example again but this is easy for me to reproduce.

**Comment by mdisbrow** [comment]
After looking closer at the examples, I found this was needed to always display the labels:
               Separator = new Separator // force the separator step to 1, so it always display all labels
                {
                    Step = 1,
                    IsEnabled = false //disable it to make it invisible.
                },

**Comment by aozkul** [comment]
WinForm Application code below

            LineSeries row = new LineSeries()
            {
                DataLabels = true,
                FontSize = 16f,
                Foreground = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(55, 71, 79)),
                Values = new ChartValues<int>(),
                StrokeThickness = 3,
                //Fill = System.Windows.Media.Brushes.Transparent,
                LabelPoint = point => "%" + point.Y.ToString()
            };

            LiveCharts.Wpf.Axis ax = new LiveCharts.Wpf.Axis()
            {
                Title = "Tools",
                FontSize = 8,
                Separator = new Separator { Step = 1, IsEnabled = false },
                ShowLabels = true,
                Labels = new List<string>() {"T11","T12", "T13", "T14", "T15", "T16", "T17", "T18", "T19", "T20", "T21" },
            };

            for (int i = 0; i < Tools.Count-1 ; i++)// Tools.Count-1 = 11
            {
                row.Values.Add((int)ToolPerformance[i]);
            }

            cartesianChart1.Series.Add(row);
            cartesianChart1.AxisX.Add(ax);


i tries this code, and  basicly i did not see all the labels. i have 11 values for this but i just saw 3 values and 2 of them are the same.. Do you have any comments?
thanks for replies.
