### ISSUE TITLE
bitmap to chart area background

### ISSUE THREAD

**Issue by BaderTalal** [beto-rodriguez/Live-Charts#359]
#### detailed request

I am trying to plot seismic data to a <b>writeablebitmap</b> then copy this bitmap to fill the chart area and setup the X and Y axes to reflect the actual plot dimensions

more in <b>seismic data</b>:
normally we have thousands of time series and will be plotted vertically ether in Wiggle traces or grey shades, or colored (something like heat map)

the aim of this is to use the very nice design of Axes and chart area of LiveCharts to plot my Data instead of going from zero and try to build a whole charting system, which i cannot do easily :)

**Comment by beto-rodriguez** [comment]
I like what you are trying to do, sadly I am not really sure where you should start.

Feel free to share your work if you succeed and let me know it please
