### ISSUE TITLE
[Low Priorty] Binding error: FontFamily is null by default for Series

### ISSUE THREAD

**Issue by rusanov-vladimir** [beto-rodriguez/Live-Charts#363]
#### How to reproduce?
Run WPF sample in debug and observe output in console. You should notice this message repeated several times:

System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='<null>' BindingExpression:Path=(0); DataItem='PieSeries' (Name=''); target element is 'TextBlock' (Name=''); target property is 'FontFamily' (type 'FontFamily')

#### Extra notes

AFAIK this is caused because `TextBlock` that is created in `Series.BindATextBlock` has this binding:

`tb.SetBinding(TextBlock.FontFamilyProperty, new Binding {Path = new PropertyPath(FontFamilyProperty), Source = this});`
while `Series.FontFamilyProperty`  is defined as following:

        public static readonly DependencyProperty FontFamilyProperty = DependencyProperty.Register(
            "FontFamily", typeof (FontFamily), typeof (Series), 
            new PropertyMetadata(default(FontFamily)));

`default(FontFamily)` is null, so binding fails with with specified error message.

Solutions I could suggest:
1. An easy fixed would be simply to initialize FontFamilyProperty with something like new `new FontFamily("Segoe UI")`.  It's done for FontSizeProperty, for example.
2. More advanced solution could be to trying use FrameworkPropertyMetadataOptions.Inherits to inherit application's FontFamilty.

For 1st solution I could provide a pull request.

**Comment by beto-rodriguez** [comment]
Thanks, I think forcing the font is a good solution considering themes should be ready soon, we can play with this font also in the themes
