### ISSUE TITLE
What is EnsureDouble Method

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#37]
To: @gregsdennis 
I am doing a lot of changes in this library, with the changes you made and the ones i am about to push this 0.5 version will be the best by far (now line charts can draw 1,000,000 points in less than 10 ms). I am just seeing some new methods, that I would like to know what are they for what like this one:

https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/Charts/Chart.cs#L748

thanks

**Comment by gregsdennis** [comment]
As I was making changes to support bindings, some of the calculations were resulting in double.NaN, so I add that to correct that to zero.

 
 
  On Tue, Nov 24, 2015 at 8:26 PM, Alberto Rodriguez<notifications@github.com> wrote:   
To: @gregsdennis 
I am doing a lot of changes in this library, with the changes you made and the ones i am about to push this 0.5 version will be the best by far (now line charts can draw 1,000,000 points in less than 10 ms). I am just facing some new methods what is this method for?

https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/Charts/Chart.cs#L748

thanks

**Comment by beto-rodriguez** [comment]
Thanks

**Comment by gregsdennis** [comment]
There's probably a better way to do handle that, like maybe fixing the calculations to properly handle those specific scenarios, but that seems to be your domain, and I didn't want to muck with it.

**Comment by beto-rodriguez** [comment]
They are probably generated when a chart is small, maybe less that 15 px, this maybe should not happen now since I now it wont draw if plotArea.Width < 10, Ill test and try to remove that method
