### ISSUE TITLE
Changing windows theme causes InvalidCastException in Livecharts.wpf.dll

### ISSUE THREAD

**Issue by everystone** [beto-rodriguez/Live-Charts#372]
#### How to reproduce?

Open control panel -> Appearance and personalization -> presonalization
Change windows theme. (example from default windows theme to High contrast)

#### Extra notes
This was initially triggered by remote desktop software, either Windows Remote Desktop or TeamViewer. I think these types of software usually alters windows theme to use less bandwidth.
#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.17</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10, latest</td>
</tr>
</table>

![live](https://cloud.githubusercontent.com/assets/5428649/19888984/906da240-a032-11e6-9069-8949999e19e9.png)

**Comment by beto-rodriguez** [comment]
Interesting... I can see the issue, I am getting ready the library themes, will fix some bugs there to make it work, I will first get the themes ready, maybe this bug gets fixed when we are done with themes

**Comment by beto-rodriguez** [comment]
This is already fixed and will be included in 0.8.1

Thanks for the report

![new](https://cloud.githubusercontent.com/assets/10853349/21397755/9806caf4-c76a-11e6-8b85-277d8f6371c8.gif)
