### ISSUE TITLE
ZoomIn ZoomOut

### ISSUE THREAD

**Issue by fabolo** [beto-rodriguez/Live-Charts#381]
#### How to reproduce?

I made a CartesianChart with DateTime on X axis and a 0-250 range on Y axis, enabled Zoom="Xy" then used the mouse wheel. The range on Y axis went to extremely high values. Please check ChartCore ZoomIn ZoomOut functions handling of Y Range

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.17</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>7SP1</td>
</tr>
</table>

**Comment by fabolo** [comment]
![zoomin](https://cloud.githubusercontent.com/assets/6189594/20217871/4020cc2a-a822-11e6-9f18-f1e604add704.png)

**Comment by beto-rodriguez** [comment]
That's the issue, you got it fixing it in next release (0.8
)

**Comment by beto-rodriguez** [comment]
This is already fixed, and will be included since 0.8 version

Thanks again!
