### ISSUE TITLE
Does it supports window phone 8 and greater versions

### ISSUE THREAD

**Issue by rspl17** [beto-rodriguez/Live-Charts#39]
I have been finding chart library with zoom and pan supported so I would like to know if your library could be supported for wp8 or not

**Comment by beto-rodriguez** [comment]
I have never worked with wp8, I will try it and let you know

**Comment by rspl17** [comment]
@beto-rodriguez  any news ?

**Comment by beto-rodriguez** [comment]
@rspl17 sorry I have not test it yet, I have never worked with wp8 I tried but with no success yet :( can you please guide me or test it?

**Comment by rspl17** [comment]
@beto-rodriguez  sure I can help but the UI elements of window phone 8 are different than the window 8 or wpf. At these level I could help you writing UI code if needed but I need to understand the logic behind chart and zooming can you explain me ? here or skype or other place you like....

**Comment by beto-rodriguez** [comment]
I will close this, maybe in a future we can reopen it again and try to extend this charts to wp8
