### ISSUE TITLE
Strange behaviour for ColumnSeries

### ISSUE THREAD

**Issue by drdran** [beto-rodriguez/Live-Charts#390]
In the debug output I found this strange message:

Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='<null>' BindingExpression:Path=(0); DataItem='ColumnSeries' (Name=''); target element is 'TextBlock' (Name=''); target property is 'FontFamily' (type 'FontFamily')

#### How to reproduce?

I have a SeriesCollection with some ColumnSeries initialized with this properties:

ColumnSeries TestStats = new ColumnSeries
 {
  Values = new ChartValues<ObservableValue> { new ObservableValue(0) },
  MaxColumnWidth = 250,
  DataLabels = true,
  LabelPoint = point => point.Y.ToString(),
  Title = "Stats " + i.ToString(),
};

#### Extra notes

If I comment the Datalabel and LabelPoint, the message doesn't appear.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.17</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>7</td>
</tr>
</table>

**Comment by rusanov-vladimir** [comment]
This should be already fixed in #363. I think it would become available in next release v 0.8

**Comment by drdran** [comment]
Thnak you @rusanov-vladimir I close this thread as duplicate.
