### ISSUE TITLE
RoutedEventHandler instead of UpdaterTickHandler

### ISSUE THREAD

**Issue by fabolo** [beto-rodriguez/Live-Charts#391]
#### How to reproduce?
I've tried to be notified of the UpdaterTick event of a Chart inside a ViewModel of a MVVM Light project, by using the EventToCommand extension, but Interation.Triggers complain of the signature of the event. It says the handler must be a RoutedEventHandler in order to bind correctly the command.

<i:Interaction.Triggers>
        <i:EventTrigger EventName="UpdaterTick">
           <mvvm:EventToCommand Command="{Binding MyCmd}"/>
        </i:EventTrigger>
     </i:Interaction.Triggers>

#### Extra notes

Could it be possible to change the type of this handler, as it seems to me there would be no side effect in doing that? (or else, does someone know a workaround?)
thank you, really nice work!

file Live-Charts\Wpfview\Charts\Base\Chart.cs line 216

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.17</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>7SP1</td>
</tr>
</table>

**Comment by rusanov-vladimir** [comment]
I've had same issue with DataClick event in PieChart. As a workaround I used this method: I've inherited PieChart into my custom LivePieChart and then in ctor I've subscribed to DataClick event forwarding it to my RoutedEventHandler that I've created. In code it would look like this:

     public class LivePieChart : LiveCharts.Wpf.PieChart {
        public LivePieChart() {
               ((Chart) this).DataClick += LiveBarChart_DataClick;
        }

        public static readonly RoutedEvent DataClickEvent = EventManager.RegisterRoutedEvent(
            "DataClick", RoutingStrategy.Direct, typeof(RoutedEventHandler), typeof(LivePieChart));

        private void LiveBarChart_DataClick(object sender, ChartPoint chartPoint) {
            RaiseDataClickEvent(sender, chartPoint);
        }

        public event RoutedEventHandler DataClick {
            add {
                AddHandler(DataClickEvent, value);
            }
            remove {
                RemoveHandler(DataClickEvent, value);
            }
        }

        private void RaiseDataClickEvent(object sender, ChartPoint chartPoint) {
            var newEventArgs = new DataClickRoutedEventArgs(DataClickEvent, sender);
            newEventArgs.Point = chartPoint;
            RaiseEvent(newEventArgs);
        }
     }

But I agree, that these events should be RoutedEvents instead. At least I can't see any point in not doing them RoutedEvents, but it automatically disables event bindings via commands.

**Comment by beto-rodriguez** [comment]
This is already fixed... sorry for that wrong approach you both were right.

As far as I see this should be already supported, now you can bind all the events, also implemented a better approach to handle events in winforms.

notice this issue is related to #42 

this will be included in the next version of the library (0.9), thanks for your feedback

**Comment by beto-rodriguez** [comment]
oops, referenced wrong the commit, this issue is fixed with https://github.com/beto-rodriguez/Live-Charts/commit/339a4983230862e833ee901e4db8d30e5f90fe1b

**Comment by fabolo** [comment]
I've downloaded 0.9.7 and I have the same problem

the event should satisfy the EventHandler delegate which expects a second parameter EventArgs and ChartUpdated should call Invoke like this

internal void ChartUpdated()
{
      if (UpdaterTick != null) UpdaterTick.Invoke(this, new RoutedEventArgs());
}
