### ISSUE TITLE
Cant use custom styles

### ISSUE THREAD

**Issue by mohitook** [beto-rodriguez/Live-Charts#392]
Instructions: replace text surrounded by '*' with your case, please delete this line.

#### How to reproduce?

Try to use this in wpf application:
https://lvcharts.net/App/examples/v1/wpf/Themes

#### Extra notes

I will modify the size and color of DataLabels!

#### I am using

<Application x:Class="DashBoard02.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:vm="clr-namespace:DashBoard02.ViewModel"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
			 xmlns:ignore="http://www.galasoft.ch/ignore"
             xmlns:lvc="clr-namespace:LiveCharts.Wpf;assembly=LiveCharts.Wpf"
             xmlns:system="clr-namespace:System;assembly=mscorlib"
             StartupUri="MainWindow.xaml"
             mc:Ignorable="d ignore">
    
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Green.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseDark.xaml" />

                

                
                <ResourceDictionary Source="pack://application:,,,/LiveCharts.Wpf;component/Themes/Colors/material.xaml" />
                
                
                
                
                
                
                
                

                

                
                
                
                <ResourceDictionary Source="pack://application:,,,/LiveCharts.Wpf;component/Themes/Size/m.xaml" />
                
                

                
                
                
                
                <ResourceDictionary Source="pack://application:,,,/LiveCharts.Wpf;component/Themes/Weight/normal.xaml" />
                
                

                
                <ResourceDictionary Source="pack://application:,,,/LiveCharts.Wpf;component/Themes/base.xaml" />

            </ResourceDictionary.MergedDictionaries>
            
            <vm:ViewModelLocator x:Key="Locator"
                             d:IsDataSource="True" />
        </ResourceDictionary>
    </Application.Resources>
    
</Application>

The problem is the following(for every resource):
An error occurred while finding the resource dictionary "pack://application:,,,/LiveCharts.Wpf;component/Themes/Colors/material.xaml".

**Comment by beto-rodriguez** [comment]
Sorry for the delay themes will be included in 0.8 version, the version is stuck because of issues with UWP packaging, keep working on it, if I cant make it work in the next 24 hrs, I will publish only the WPF version.

An alternative is using the source code of the library, which is 0.8 version, then you will be able to style your charts.

**Comment by mohitook** [comment]
Thanks for the help!
+1 additionally question if I may:

`<Style TargetType="wpf:Series" x:Key="SeriesStyle">
        <Setter Property="FontFamily" Value="Calibri"></Setter>
        <Setter Property="FontSize" Value="40"></Setter>
        <Setter Property="Foreground" Value="Azure"></Setter>
        <Setter Property="LayoutTransform">
            <Setter.Value>
                <RotateTransform Angle="45"/>
            </Setter.Value>
        </Setter>
        
    </Style>
    <Style TargetType="wpf:ColumnSeries" BasedOn="{StaticResource SeriesStyle}"/>
    <Style TargetType="wpf:StackedColumnSeries" BasedOn="{StaticResource SeriesStyle}"/>`

I am trying to rotate the DataLabels but I don't know the proper way to do it.. eg: I will rotate the StackedColumnSeries's datalabel to normal state... the code above can only change the first 3 setter, but the LayoutTransform doesn't work :(

**Comment by beto-rodriguez** [comment]
Sorry not supported yet 😟, rotation for now is only available with Axis Labels, it is not implemented yet in series.

**Comment by beto-rodriguez** [comment]
I am closing this issue, 0.8 is now published and you should be able to use the defualt Styles, about your second issue I am concidering an improvement there, a future version will include a fix for that.

Feel free to add any comment here or any other issue. Thanks!
