### ISSUE TITLE
OHLC and CandleSeries color

### ISSUE THREAD

**Issue by apresmoi** [beto-rodriguez/Live-Charts#393]
#### How to reproduce?

I can't set the color of a OHLC or Candle series by neither of this paramenters:

Foreground, Fill, Stroke

Which is the correct way to do it?
Thanks.

**Comment by apresmoi** [comment]
Never mind, the parameters are: IncreaseBrush and DecreaseBrush

**Comment by chengy24** [comment]
How do you use it tho ? Are you using mapper?

**Comment by chengy24** [comment]
How do u use it tho? Are you using mapper?
