### ISSUE TITLE
Null reference exception on CartesianChart when VisualElements is null

### ISSUE THREAD

**Issue by rusanov-vladimir** [beto-rodriguez/Live-Charts#399]
#### How to reproduce?

In BasicColumn.xaml add `VisualElements="{x:Null}"` to `CartesianChart` definition. Yes, it makes no sense to explicitly set this collection to null, but it's really a common scenario when databinding to this dependency property.

#### Extra notes

`CartesianChartCore` on each update calls `RunSpecializedChartComponents()`. If VisualElements collection is null, unhandled null reference exception occurs in:

     foreach (var visualElement in cartesianChart.VisualElements)
            {
                visualElement.AddOrMove(this);
            }

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>*0.7.17*</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*4.5.2*</td>
</tr>
<tr>
    <td>Windows</td>
    <td>*8.1*</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
fixed with #400
