### ISSUE TITLE
Still can't bind some properties

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#40]
The XAML is a lot cleaner being able to bind most things as of v0.5.6, but I would like to be able to bind the axis label formatter.  Can this be updated to a Dep Prop?

**Comment by gregsdennis** [comment]
In fact, how about all of the properties be Dep Props?

**Comment by beto-rodriguez** [comment]
this could work, for a label formatter maybe this syntax would be nice, but I am not sure how to implement it http://www.wpf-tutorial.com/data-binding/the-stringformat-property/

**Comment by beto-rodriguez** [comment]
actually we could replace label formatters with `IValueConverters` so they can be set in your `XAML`

**Comment by gregsdennis** [comment]
I actually like the idea of having a StringFormat property on Axis.  Then it would just pass the format into the double.ToString() method.

**Comment by gregsdennis** [comment]
On second thought, binding a formatter function is a bit more powerful.  I like the idea you have in your LabelFormatters class.  This can be applied in XAML like this:

    <Axis LabelFormatter="{x:Static LabelFormatters.Number}"/>
