### ISSUE TITLE
Artifact on changing LineSeries Visibility

### ISSUE THREAD

**Issue by NickSavin** [beto-rodriguez/Live-Charts#403]
#### How to reproduce?

Artifact appears on changing LineSeries Visibility, as shown on GIF

![bug](https://cloud.githubusercontent.com/assets/20172765/20671695/7166f672-b58f-11e6-887a-0dfaf12db87f.gif)

XAML:

`
<lvc:CartesianChart Name="Chart_BudgetToInternet" Grid.Row="1" LegendLocation="Top"  Margin="10" Background="{Binding CurrentApplicationSettings.CurrentAppColor}"
                                                        Series="{Binding OutputVM.BudgetToIntenet.BudgetToIntenetChartSeries}">`

                                        <lvc:CartesianChart.ChartLegend>
                                            <lvc:DefaultLegend Margin="0,0,0,10"/>
                                        </lvc:CartesianChart.ChartLegend>

                                        <lvc:CartesianChart.AxisY>
                                            <lvc:Axis Foreground="Black" MinValue="0" LabelFormatter="{Binding OutputVM.BudgetToIntenet.XFormatter}" >
                                                <lvc:Axis.Separator>
                                                    <lvc:Separator Stroke="DarkGray"/>
                                                </lvc:Axis.Separator>
                                            </lvc:Axis>
                                            <lvc:Axis Title="Effective reach" Position="RightTop" Foreground="Black" MinValue="0" MaxValue="1"
                                                  LabelFormatter="{Binding OutputVM.BudgetToIntenet.YFormatter}">
                                                <lvc:Axis.Separator>
                                                    <lvc:Separator IsEnabled="False"/>
                                                </lvc:Axis.Separator>
                                            </lvc:Axis>
                                        </lvc:CartesianChart.AxisY>

                                        <lvc:CartesianChart.AxisX>

                                            <lvc:Axis Title="Budget to Internet" Foreground="Black" MinValue="0" LabelFormatter="{Binding OutputVM.BudgetToIntenet.XFormatter}">
                                                <lvc:Axis.Separator>
                                                    <lvc:Separator Stroke="DarkGray"/>
                                                </lvc:Axis.Separator>
                                            </lvc:Axis>
                                        </lvc:CartesianChart.AxisX>

                                    </lvc:CartesianChart>`

Code:

` if (BudgetToIntenetChartSeries.Count>0)
            {
                BudgetToIntenetChartSeries.Clear();
            }

            var AdditionalTVReachSeries = new LineSeries() { Title = "Additional TV Reach Point Cost", Values = new ChartValues<ObservablePoint>(), ScalesYAt = 0, PointGeometry = DefaultGeometries.None };
            var CPIIncrementEffectiveReachSeries = new LineSeries() { Title = "Cost per Internet Increment Effective Reach Point", Values = new ChartValues<ObservablePoint>(), ScalesYAt = 0, PointGeometry = DefaultGeometries.None };
            var EffectiveReachSeries = new LineSeries() { Title = "Effective Reach Increment by Internet", Values = new ChartValues<ObservablePoint>(), ScalesYAt = 1, PointGeometry = DefaultGeometries.None };
            var CostPerTvIncrementSeries = new LineSeries() { Title = "Cost Per TV Increment", Values = new ChartValues<ObservablePoint>(), ScalesYAt = 0, PointGeometry = DefaultGeometries.None };

            foreach (var item in _budgetToIntenetModel.Data)
            {
                AdditionalTVReachSeries.Values.Add(new ObservablePoint((double)Math.Round(item.BudgetInternet), (double)Math.Round(item.AdditionalTVReachPointCost)));
                CPIIncrementEffectiveReachSeries.Values.Add(new ObservablePoint((double)Math.Round(item.BudgetInternet), (double)Math.Round(item.CostPerInternetIncrementEffectiveReachPoint)));
                EffectiveReachSeries.Values.Add(new ObservablePoint((double)item.BudgetInternet, item.EffectiveReachIncrementByInternet));
                CostPerTvIncrementSeries.Values.Add(new ObservablePoint((double)item.BudgetInternet, (double)Math.Round(item.CostPerTvIncrementEffectiveReachPoint)));
            }

            BudgetToIntenetChartSeries.Add(AdditionalTVReachSeries);
            BudgetToIntenetChartSeries.Add(CPIIncrementEffectiveReachSeries);
            BudgetToIntenetChartSeries.Add(EffectiveReachSeries);
            BudgetToIntenetChartSeries.Add(CostPerTvIncrementSeries);`

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.17</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>windows 10 x64</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
This should be already fixed using the current source of the repo

https://github.com/beto-rodriguez/Live-Charts/issues/328

In the previous link I faced this issue building this example, and for me it works correctly now.

**Comment by NickSavin** [comment]
Thank You! I will test it, when a new version will be released, and give you feedback

**Comment by beto-rodriguez** [comment]
I'll close this issue for now, I am sure it is fixed, and will be included in 0.8.1 if this is not solved when the version is released, please feel free to reply here or in any other new issue.

Thanks again Nick
