### ISSUE TITLE
LabelFormatter not formating

### ISSUE THREAD

**Issue by R0xtar** [beto-rodriguez/Live-Charts#404]
#### How to reproduce?
Firstly, let me thank you for this amazing job you've done here.  The library is massive and well documented, it's a pleasure to work with.

My problem is, using any chart type form Lvc library I'm not able to apply formatting to my values.

##### View
```xaml 
<lvc:Gauge Grid.Row="1"
           From="0"
           LabelFormatter="{Binding Formatter}"
           To="{Binding SalesLastYearToDate}"
           Uses360Mode="False"
           Value="{Binding SalesYearToDate}" />
```

##### ViewModel

```cs

        private double _salesYearToDate;
        public double SalesYearToDate
        {
            get { return _salesYearToDate; }
            set { Set(() => SalesYearToDate, ref _salesYearToDate, value); }
        }

        private double _salesLastYearToDate;
        public double SalesLastYearToDate
        {
            get { return _salesLastYearToDate; }
            set { Set(() => SalesLastYearToDate, ref _salesLastYearToDate, value); }
        }
        public Func<decimal, string> Formatter { get; set; }

        public RandomViewModel() {
            SalesYearToDate = 10;
            SalesLastYearToDate = 20;
            Formatter = x => x + " CHF";
        }
```
#### Extra notes

Result : [screenshot](http://i.imgur.com/7kFv37u.png)

I also tried with an encapsulated value and a NotifyPropertyChanged on Formatter but the result remains the same, no formatting is applied to my values.

I know there's no other issues with this LabelFormatter so I'm probably missing an obvious detail, I'm trying to resolve this issue since 2 days but still didn't managed to get this work as expected. Thank's in advance for your help. 

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.8.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10.0.14393 Build 14393 (Windows 10 Pro N Anniversary Update</td>
</tr>
</table>

**Comment by rusanov-vladimir** [comment]
There is no issue with the library, there is something wrong in your code. I've checked [Gauge180](https://lvcharts.net/App/examples/v1/wpf/180%20Gauge) example and changed formatter to use ChangeNotifications:

        public Func<double, string> Formatter {
            get {
                return _formatter;
            }
            set {
                _formatter = value;
                OnPropertyChanged("Formatter");
            }
        }

And used MoveOnClick() to change the Formatter value:

        private void MoveOnClick(object sender, RoutedEventArgs e) {
            var val = new Random().Next(50, 100);

            Formatter = x => val.ToString() + "!";
            Value = val;
        }

Formatter is applied correctly as you can see in the [video](http://screencast.com/t/4jMneLnHAjP)

I suggest to close the issue and look for the error in code.

**Comment by R0xtar** [comment]
Hi @rusanov-vladimir,

Thanks for your answer, as I said in my first message `I know there's no other issues with this LabelFormatter so I'm probably missing an obvious detail`.

After launch break here in Switzerland I kept trying again and again. Finally, I've found the "issue" (no misunderstanding here, I'm not telling that this is an issue for the library).

With 

```cs
public Func<double, string> Formatter { get; set; }
```

Instead of 

```cs
public Func<decimal, string> Formatter { get; set; }
```

Everything is working fine. I tried many other combinations, and the only ones which are working are ones where formatter is `public Func<double, string> Formatter { get; set; }`

My example was wrong my values are decimals so I was trying to convert a decimal to string instead of double to string, so, to sum up, it doesn't matter if values types are decimal, int, float, or whatever, the formatter must remain `<double, string>` to get this job done.

Don't now if it's a bug or a feature :trollface:

**Comment by R0xtar** [comment]
Don't know if this issue is closed or not, so I'll let @beto-rodriguez decide 👍 

Thanks again for your help @rusanov-vladimir and @beto-rodriguez for this library.

**Comment by rusanov-vladimir** [comment]
@R0xtar You are welcome. About the `decimal` vs `double` doubt you had. If you will check the LabelFormatter signature you will notice that [it's defined](https://github.com/beto-rodriguez/Live-Charts/blob/master/WpfView/Gauge.cs#L277) as Func<double,string>. So there is no doubt it would not work with decimal, binding mechanism will simply fail with such error:

> System.Windows.Data Error: 1 : Cannot create default converter to perform 'one-way' conversions between types 'System.Func`2[System.Decimal,System.String]' and 'System.Func`2[System.Double,System.String]'. Consider using Converter property of Binding. BindingExpression:Path=Formatter; DataItem='Gauge180' (Name=''); target element is 'Gauge' (Name=''); target property is 'LabelFormatter' (type 'Func`2')

So, 2 tips for the future:
 - Check output for possible binding errors
 - Check signature of members to avoid guessing which types you have to use

**Comment by beto-rodriguez** [comment]
@rusanov-vladimir is totally right, the correct type is `double` instead of `decimal`, thanks @rusanov-vladimir, and thanks @R0xtar for your feedback.

**Comment by R0xtar** [comment]
So I was right with my first statement, I was missing an obvious detail.
Thanks for helping me open my eyes 🤒
