### ISSUE TITLE
Basic stacked chart: Select only a range of value on Y axis

### ISSUE THREAD

**Issue by Koaleo** [beto-rodriguez/Live-Charts#405]
* Hello guys, in my wpf mvvc app i have a basic stacked chart like this:

![image](https://cloud.githubusercontent.com/assets/15799276/20847139/12c600d6-b8cd-11e6-8fb2-30df44a0a7b8.png)

I would like to know if there is a way to view only a certain range of value in the Y axis like a zoom in effect. I want to achieve this for example:

![image](https://cloud.githubusercontent.com/assets/15799276/20878127/469d0484-bacd-11e6-8b37-2c8fe0988e8c.png)

The first value on the Y axis is not 0 anymore.*

Thanks

**Comment by rusanov-vladimir** [comment]
Just set up your AxisY as you want it.
![2016-12-05_1002](https://cloud.githubusercontent.com/assets/3341799/20877517/090f9ad2-bad2-11e6-8023-ba825470bffa.png)

      <lvc:CartesianChart.AxisY>
        <lvc:Axis Title="AxesY" MinValue="50" MaxValue="200">
          <lvc:Axis.Separator>
            <lvc:Separator Step="50"></lvc:Separator>
          </lvc:Axis.Separator>
        </lvc:Axis>
      </lvc:CartesianChart.AxisY>

**Comment by Koaleo** [comment]
Thank you rusanov-vladimir for the answer but the problem is that i am using a StackedChart and this solution is not working, in the other basic column charts it works fine!

I tried your solution also with an easier example 
https://lvcharts.net/App/examples/v1/wpf/Basic%20Stacked
but it doesn't work :( 

any other suggestion?

**Comment by cyrusd87** [comment]
@rusanov-vladimir , @beto-rodriguez I want to make the same thing, any advice??

**Comment by beto-rodriguez** [comment]
I think this is an issue a stacked column, series should always start from 0, will take a look to it

**Comment by cyrusd87** [comment]
@beto-rodriguez  I would like to focus the zoom where there are the two stacks, is there a way to make this? 

Actual situation is this
![image](https://cloud.githubusercontent.com/assets/9257354/20887730/2ce9013a-bafc-11e6-9aa2-a8c00ed116ec.png)


I would like to have this result

![image](https://cloud.githubusercontent.com/assets/9257354/20887707/1a01a40a-bafc-11e6-8e89-19814bfd469c.png)

**Comment by beto-rodriguez** [comment]
I get it now, this is an issue.

**Comment by cyrusd87** [comment]
@beto-rodriguez could you please tell me if you think to make this feature in one of the next releases?

**Comment by beto-rodriguez** [comment]
sure, this week I plan to fix all open issues and make a release

**Comment by beto-rodriguez** [comment]
This is already fixed and will be included since version 0.8.1

Thanks for the report
