### ISSUE TITLE
Hoverable="False" doesn't turn off tool tip.

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#41]
Can't seem to turn this off.  My users are going to expect to be able to click into a specific data point with this feature on.

**Comment by beto-rodriguez** [comment]
I test it and it turns off the tooltip, maybe I misunderstood the issue

**Comment by gregsdennis** [comment]
In my app, it's not turning the tooltip off.  I even tried to change it via Snoop, and saw no change.  The tooltip was always enabled.

This is specifically for a bar chart:

	<lc:BarChart x:Name="Trend" Grid.Column="1" Hoverable="False" Zooming="False" Margin="5">
		<lc:BarChart.Series>
			<lc:BarSeries PrimaryValues="{Binding Data}"/>
		</lc:BarChart.Series>
		<lc:BarChart.PrimaryAxis>
			<lc:Axis MinValue="0"/>
		</lc:BarChart.PrimaryAxis>
		<lc:BarChart.SecondaryAxis>
			<lc:Axis MinValue="0" Labels="{Binding PrimaryAxisLabels}"/>
		</lc:BarChart.SecondaryAxis>
	</lc:BarChart>

**Comment by beto-rodriguez** [comment]
I copy pasted this example and it works

**Comment by gregsdennis** [comment]
Having this issue again with pie charts.  The pie chart is part of a data template.  Not sure if that's relevant.

**Comment by beto-rodriguez** [comment]
@gregsdennis About this I am sorry, it worked for all charts but pie chart, just fixed it with last commit. 

it should work now with this line change

https://github.com/beto-rodriguez/Live-Charts/commit/f66c2db3105dfc4add8d0c59ccf790363fe52d7c#diff-aad6d60d39ee5aaee03742e365e85cfeR162
