### ISSUE TITLE
Cast error using mapping in OhlcSeries

### ISSUE THREAD

**Issue by sstsai** [beto-rodriguez/Live-Charts#411]
constructor for OhlcSeries reads:
 public OhlcSeries(object configuration)
        {
            Model = new ColumnAlgorithm(this);
            Configuration = configuration;
            InitializeDefuaults();
        }
should read:
 public OhlcSeries(object configuration)
        {
            Model = new OhlcAlgorithm(this);
            Configuration = configuration;
            InitializeDefuaults();
        }

**Comment by beto-rodriguez** [comment]
Thanks for the report, this fix will be included in 0.8.1 release
