### ISSUE TITLE
PieChart: Give an option to allow each of the DataLabel (TextBlock) to be rotated to match its PieSlice

### ISSUE THREAD

**Issue by Enigmatrix** [beto-rodriguez/Live-Charts#413]
#### Currently each text box renders its label horizontally only

This takes up quite a bit of space if the labels are of moderate length and if there are many slices.
Allowing the DataLabel to tilt to match its pieslice's rotation would save some space (also give a nice visual effect). This can also be adapted to make small slices' labels to align perpendicular to the slice, so
that pieslices with low participation but long labels can still be rendered without being annoying.

**Comment by beto-rodriguez** [comment]
I think a better or more standard solution would be to add the labels outside the slices, as shown here https://github.com/beto-rodriguez/Live-Charts/issues/296

**Comment by beto-rodriguez** [comment]
I am closing this issue, I really think that the solution proposed in #292 is cleaner, the problem I see with rotating the labels is that the slices with a small share will be messy...

If you disagree or have any other opinion feel free to let me know it.

Thanks fo the report
