### ISSUE TITLE
WPF sample crash on french windows version (with fix)

### ISSUE THREAD

**Issue by jeanluc-martin** [beto-rodriguez/Live-Charts#418]
#### How to reproduce?

Use a French windows version and launch the WPF sample.

#### Exception
Exception in Examples\WPF\CartesianChart\Linq\Database.cs
System.FormatException
Caused by the separator used in the csv file.

#### Fix
Use InvariantCulture :

read.Add(new City
                    {
                        Name = values[0],
                        Population = double.Parse(values[1]**, System.Globalization.CultureInfo.InvariantCulture**),
                        Area = double.Parse(values[2]**, System.Globalization.CultureInfo.InvariantCulture**),
                        Country = values[3]
                    });

Thanks

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.8</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Thank you very much for this report, previous commit applies your fix
