### ISSUE TITLE
Click event for data point

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#42]
Would like to receive a Click event or equivalent when clicking on a data point.  Should indicate which data point was clicked.

**Comment by beto-rodriguez** [comment]
sure this can be easly implemented. I will add it as soon as possible

**Comment by beto-rodriguez** [comment]
This is already supported, right now it is only tested in line charts, but I wrote the code to support it for all charts, here is an example

https://github.com/beto-rodriguez/Live-Charts/tree/master/ChartsTest/Line%20Examples/Custom

**Comment by gregsdennis** [comment]
Awesome!

Now all it needs is a `Command` property to support MVVM. :smile:

**Comment by beto-rodriguez** [comment]
@gregsdennis but `point.Instance` contains the model from MVV**M**, do you really think it is necessary?

**Comment by gregsdennis** [comment]
It's a matter of bindings.  You can't bind to an event.  But a command is set up as a dependency property, so it can take a binding.

**Comment by gregsdennis** [comment]
https://msdn.microsoft.com/en-us/magazine/dn237302.aspx

**Comment by beto-rodriguez** [comment]
Thanks I will take a look then

**Comment by renatop7** [comment]
@gregsdennis Did you manage to work this out? I'm also using MVVM (Prism) and I need to bind the DataClick event... Already tried several solutions but nothing seems to work.

**Comment by gregsdennis** [comment]
I haven't.  Primarily because I've moved off of the project where I was using the library, but also because I've been personally busy.

@beto-rodriguez was taking point on this, I thought.

**Comment by renatop7** [comment]
@gregsdennis Ah ok! Thanks anyway hehe

@beto-rodriguez this guy have some insights on how to bind events to method in wpf
http://www.singulink.com/CodeIndex/post/building-the-ultimate-wpf-event-method-binding-extension
Maybe can help you on this task!
I'll try to get this code to run with LiveCharts, if I can make some progress I let you know

**Comment by beto-rodriguez** [comment]
Thanks, I will reopen this issue so I don't forget it

I guess this question is also related 

http://stackoverflow.com/questions/39976909/binding-custom-events-of-custom-elements-in-mvvm-pattern

**Comment by renatop7** [comment]
@beto-rodriguez yeah... this is my question hehe. I'm working on the helper but no luck so far.
If I get any updates I let you know.

**Comment by ZKRobi** [comment]
@beto-rodriguez I was triing to get this binding work, and found this issue. Is there any chance this will be a feature?

**Comment by beto-rodriguez** [comment]
This is finally supported and will be included in the next version of the library

**Comment by danmoller** [comment]
Any chances of having "DoubleClick" here as well?
