### ISSUE TITLE
[WPF] [Gauge] Chart not filled and from/to labels not process on load

### ISSUE THREAD

**Issue by MarioZG** [beto-rodriguez/Live-Charts#422]
#### How to reproduce?
This is weird one, and very specific. Might be WPF related (?).

You have user control with view model, and child control with gauge charts. Child control inherits datacontex (view model) of parent control.

 On child control, last gauge chart is not filled and from/to labels are not process on initial load. After raising change event on view model all draws ok. All other charts initialize ok.

It is always last gauge added in xaml. If you add one with visibility collapsed, all previous would initialize ok. Tried in grids, different panels. Always last one added to xaml fails on inital load.

<img width="505" alt="uplad" src="https://cloud.githubusercontent.com/assets/10474989/21390455/634ff778-c787-11e6-9024-ae8c1033afb2.png">

#### Extra notes

i have attached solution to reproduce.

[ChartTest.zip](https://github.com/beto-rodriguez/Live-Charts/files/666395/ChartTest.zip)

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>8.0.0.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Win 10

</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
I checked this, this is very strange I had a bed time also understanding your design, something is confusing there and might be causing the issue.

I am sorry I am closing this for now, this issue seem not to be related with the library as you stated, it seems that something is going wrong in your current design, sadly I can't debug it for now.

I hope you understand.

Thanks for the report
