### ISSUE TITLE
LineSeries drawing problem with the first point

### ISSUE THREAD

**Issue by kkokosa** [beto-rodriguez/Live-Charts#425]
#### How to reproduce?

The easiest way is to use my small, just started repository using Live-Charts:
1. git clone https://github.com/kkokosa/EtwVisualizer.git
2. Compile under Visual Studio 2015
3. Run, you will see strange LineSeries drawing:

![image](https://cloud.githubusercontent.com/assets/11159779/21450201/dc8039dc-c8f4-11e6-90be-96229ad1d4a5.png)

#### Extra notes

It may be the very first usage of LiveCharts from within F# project. I had to recompile LiveCharts from the github source because of the namespace naming problem: it is Livecharts instead of LiveCharts, making F# not able to resolve some types. Compiled libs are included in the repository and referenced by the project.

It would be very nice to correct this namespace issue and I would be able to reference nuget packages.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.8.1 (custom build)</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10</td>
</tr>
</table>

**Comment by ilyalozovyy** [comment]
I can confirm that I am seeing the same issue when I try to create a new WPF project and use the documentation from the website to create a simple line chart.
The interesting part is that when I download the repo and run the sample WPF application, I am not seeing the same issue and the line charts show up like they should.

**Comment by beto-rodriguez** [comment]
Please for now use 0.8.0 version, ill try to test, reproduce and make a new build today

**Comment by AnthonyOSX** [comment]
Can confirm 0.8.1 is the issue. Downgrading to 0.8.0 working as expected.

**Comment by ilyalozovyy** [comment]
Awesome, thanks for the quick reply. I'll get the earlier version and
continue playing.

**Comment by kkokosa** [comment]
@beto-rodriguez great! Can you also address the issue with F# consuming LiveCharts.dll? Should I create another issue?

**Comment by FoggyFinder** [comment]
@kkokosa I've used LiveCharts in F# + WPF project, but eventually switched to OxyPlot. There were a few bugs in old version of LiveCharts that is already fixed :)

But I had no problems using LiveCharts from the F# project. What kind of problem with the namespace you talking about?

P. S. Seems, you should join to F# Slack Team:
http://fsharp.org/guides/slack/

**Comment by kkokosa** [comment]
@FoggyFinder I've created a very simple snippet to illustrate this: https://dotnetfiddle.net/0lhCf4

Symptoms are exact the same as in Visual Studio project - LiveCharts.Wpf somehow is not seeing LiveCharts types (see the first error) even I am referencing both LiveCharts and LiveCharts.Wpf packages (both 0.8.0 versions).

**Comment by FoggyFinder** [comment]
yeah....
@beto-rodriguez ^ please note

**Comment by beto-rodriguez** [comment]
Both issues seems to be fixed for me now in version 0.8.1 specially with these commits https://github.com/beto-rodriguez/Live-Charts/commit/2c3f3e5776b86bc073a48aaf27b762c428c3d64b, https://github.com/beto-rodriguez/Live-Charts/commit/e60ecd59753680114441df84d079cf545f40f8b0

Updated the Fiddle, now it complaints about wpf dependencies, not LiveCharts dlls, I think it should work correctly now (Sorry I dont know how to add system dependencies to .Net Fiddle)
https://dotnetfiddle.net/KghA8F

It seems fixed for me, I would appreciate if you could let me know if this is fixed for you.

**Comment by kkokosa** [comment]
Yes, I can confirm both problems are fixed in version 0.8.1.1, thank you!
