### ISSUE TITLE
BoxPlot WPF

### ISSUE THREAD

**Issue by rodrigomocca** [beto-rodriguez/Live-Charts#427]
Hi, sorry for contact you in this way, but I really need to ask you, this tool has BoxPlot diagram?

Thanks.

**Comment by beto-rodriguez** [comment]
Hi, yes it is supported, check out the CandleStick example here https://github.com/beto-rodriguez/Live-Charts/tree/master/Examples/Wpf/CartesianChart/Financial

you can see it running cloning the repo

**Comment by ceds** [comment]
Hi there.  Is it possible to do a box plot as illustrated here:

https://plot.ly/python/box-plots/

Box pots are very nice charts and I use them a lot with Plotly.  However cannot manage to get them right with Livecharts
