### ISSUE TITLE
Value Clear Graphic Bug

### ISSUE THREAD

**Issue by anilozfuttu** [beto-rodriguez/Live-Charts#429]
Hello, I have UI for displaying live data taken from a sensor. Everything is working fine but when I clear data with  `chart1.Series[0].Values.Clear();` I get graphic bug like this

![image](https://cloud.githubusercontent.com/assets/17238960/21595102/48096a04-d13b-11e6-9bae-39348766b018.png)

I don't know how to fix this. Is there any function for clearing screen?

Thank you!

**Comment by beto-rodriguez** [comment]
Hi, are you using version 0.8.1.1? it was released just yesterday with this fix

**Comment by anilozfuttu** [comment]
My program using 0.8.0.0 version how can I upgrade in existing project ?
