### ISSUE TITLE
Tooltip (hover) content could be customizable.

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#43]
Would like the ability to provide my own content for the tooltip or to turn on/off data shown in it.

**Comment by beto-rodriguez** [comment]
you can, its it not documented already, but just create a custom user control and create a new intance of it in DataTooltip Property.

```
myChart.DataTooltip = new MyCustomTooltip();
```

`MyCustomTooltip` DataContext will be one of this view models, (according to chart type) https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/Tooltip/ViewModels.cs,

here you can see some examples with the current used tooltips
https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/Tooltip/IndexedToolTip.xaml
