### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by MarioZG** [beto-rodriguez/Live-Charts#431]
seems like latest official nuget package for livecharts.WPF (8.1.1) doesn't include fix #420. Got exception mentioned in issue when updated to latest package from nuget.org site.

**Comment by beto-rodriguez** [comment]
Well, I really don't see how your commit could not be included, I'll need some time to test and verify it.
Is the issue fixed when you reference this repository instead?

**Comment by MarioZG** [comment]
Initially i did reference my fork with fix, and it worked ok. When i switched to latest official nuget (8.1.1), this error surfaced. I just switched back to my copy of repo. 

Looks like fix is in the master, but i just checked dll from nuget with ilspy (dll compiled on 1/1/2017 18:00) - seems like fix is missing in compiled dll.

**Comment by beto-rodriguez** [comment]
Thanks for the reply, I guess something went wrong in the build process, i'll verify it and come back once I do.

**Comment by beto-rodriguez** [comment]
Being honest I don't know what went wrong here :/

I comited again your solution, thanks again! it will  be included in the next version of the library

**Comment by MarioZG** [comment]
looks like it's solved now. Just updated to latest version and all works perfect!
