### ISSUE TITLE
Changing AxesCollection via binding doesn't remove old axes

### ISSUE THREAD

**Issue by rusanov-vladimir** [beto-rodriguez/Live-Charts#432]
#### How to reproduce?

Bind to AxisX and change the AxesCollection property later.
#### Extra notes

Chart to be updated with new AxesCollection, instead the new axes are drawn over the old ones.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.8.1</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Fixed with #433
