### ISSUE TITLE
Null separator throws exception.

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#44]
Tried to do this:

	<lc:Axis MinValue="0" Labels="{Binding PrimaryAxisLabels}" Separator="{x:Null}"/>

Got a NullReferenceException.

**Comment by beto-rodriguez** [comment]
Separators canot be null, from docs

https://github.com/beto-rodriguez/Live-Charts/wiki/0.2-Live-Charts-Basics

they are necessary for a chart, instead disable it.

<lc:Axis MinValue="0" Labels="{Binding PrimaryAxisLabels}" >
    <lc:Axis.Separator>
       <lc:Separator Enabled="False" />
   <lc:Axis.Separator>
</lc:Axis>

**Comment by gregsdennis** [comment]
The only way to disable the separator is in the code behind or by creating a new disabled separator in XAML.  There should be a way to disable in XAML without creating a new one.

**Comment by beto-rodriguez** [comment]
I like the `Separator="{x:Null}"` syntax, it is intiutive, I will add this to next release, something like:

canging this line https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/Axis.cs#L68

to

```c#
private Separator _separator;

public Separator Separator 
{
  get { return _separator;} 
  set 
  {
      if (value == null) 
     {
        _separator = new Separator { Enabled = false };
        return;
     }
     _separator = value;
  }
}
```

**Comment by gregsdennis** [comment]
I think the better solution would be to allow null in the property then check for null wherever it's used.

Reasoning:  when I set a property to be null, I expect that it's null.  Setting a property to be null, then getting a value out is a bad experience.  Consider this code:

    var myObj = new MyObject { MyProp = new object() };
    ... // do some stuff that may change myObj.MyProp
    if (myObj == null)
    {
        ...
    }

This is perfectly logical code, but if the setter for `MyProp` doesn't actually set the property to null, the contents of that `if` statement will *never* execute.

**Comment by beto-rodriguez** [comment]
the problem is that separator does not only means that line you see, it is a important concept in a chart, the enable property is there to make it invisible, but it is a really importanto calculation to scale a chart I dont think that is possible without changing a huge part of the code

**Comment by gregsdennis** [comment]
In that case, I suggest making the `Axis.Separator` property non-user-settable.  This would require that the user set `Separator` properties like this:

    <lc:Axis MinValue="0" Labels="{Binding PrimaryAxisLabels}" Separator.Enabled="False"/>

See [this SO answer](http://stackoverflow.com/a/602465/878701) as to why this works.

Also, you'll need to make the properties on `Separator` DPs.

As a final note, `Enabled` should be `IsEnabled` to follow in the pattern set forth by MS.

**Comment by gregsdennis** [comment]
Okay... I'll see what alternatives there are.

**Comment by gregsdennis** [comment]
Ideally, I think what you'd want is not to have a public setter on the `Axis.Separator` property.  But then you run into the issue of setting the separator properties in XAML.  You *could* create forwarding properties on `Axis`, but that's not very clean.

I think the best thing to do is to update the `Separator` properties to DPs and give them default values (the defaults you use in the `Axis` constructor would be fine).  This way, the defaults can be overridden in XAML either directly or via styles.

**Comment by gregsdennis** [comment]
As far as the exception when the separator is null, I think it's best to throw an exception if it is required.  However, it should throw `ArgumentNullException` immediately rather than waiting for a dereference attempt.
