### ISSUE TITLE
Powershell use

### ISSUE THREAD

**Issue by KurtDeGreeff** [beto-rodriguez/Live-Charts#440]
Can someone please give me a basic example how I can use these beautiful charts from Powershell?
I can use add-type to load the dll..but are stuck then on creating new objects..

However the website is really fantastic, I'm sysadmin and have no programming experience to directly use the C# examples..but  I know Powershell as a good friend :)
Thanks for helping and sorry for not being an real issue but maybe I can put the solution in the wiki afterwards..
Great day!

**Comment by beto-rodriguez** [comment]
I left this open just in case some one wanted to answer, because being honest I don't have a clue.

I wish I could help you, i am closing this for now.
