### ISSUE TITLE
(0, 0) position and separators are moved out

### ISSUE THREAD

**Issue by NickSavin** [beto-rodriguez/Live-Charts#443]
#### How to reproduce?

![image](https://cloud.githubusercontent.com/assets/20172765/22144976/91a57904-df10-11e6-8e8b-c7fd65cbdb59.png)

![image](https://cloud.githubusercontent.com/assets/20172765/22145232/81c3026c-df11-11e6-99eb-1a861e1555a7.png)

#### Extra notes

in 0.7.17 is all right

![image](https://cloud.githubusercontent.com/assets/20172765/22145017/b052f62e-df10-11e6-9195-8716bf2127c7.png)

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>090</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>461</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Thanks for the report this is now fixed and it is included in v091
