### ISSUE TITLE
NullReferenceException in chart with multiple line series when one point is double.NaN with Geared LineSeries

### ISSUE THREAD

**Issue by Gonzo1976** [beto-rodriguez/Live-Charts#445]
#### How to reproduce?

*Two series of GearedValues<double>, one of them contain NaN values, throw an exception: An unhandled exception of type 'System.NullReferenceException' occurred in LiveCharts.Geared.dll on CartesianChart. The same code (and values) works fine with normal(not geared) LiveCharts version*

#### Extra notes

*Exception is thrown when mouse is over the Chart near/over NaN value*

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>*1.2.0.0*</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*4.5*</td>
</tr>
<tr>
    <td>Windows</td>
    <td>*10*</td>
</tr>
</table>

**Comment by Gonzo1976** [comment]
Sorry mistake, I am using Live-Charts: 0.8.1.1, but LiveCharts.Geared: 1.2.0.0

**Comment by beto-rodriguez** [comment]
Hi, could you please update to LiveCharts 0.9 and geared 1.2.1? and verify if the issue persists

**Comment by Gonzo1976** [comment]
Hi, thank You for the help, the exception is gone after update!

**Comment by Gonzo1976** [comment]
I close the issue now, thank you again for help.
