### ISSUE TITLE
Histogram and Line chart

### ISSUE THREAD

**Issue by vSkullv** [beto-rodriguez/Live-Charts#452]
Hi,

Is it possible to produce Histogram+Line on the same chart using the library.

I can see that you have columnChart but I need something that does not have any gaps between the columns.

Thanks

**Comment by beto-rodriguez** [comment]
It is totally possible please check out this question in SO 

https://stackoverflow.com/questions/38731985/how-customize-column-width-in-column-series

I am closing this for now
If you face any issue let me know

Regards

**Comment by vSkullv** [comment]
This is very useful. Thanks for letting me know.
