### ISSUE TITLE
WPFExample doesn't compile

### ISSUE THREAD

**Issue by SkyQuant** [beto-rodriguez/Live-Charts#46]
A lot of errors on debugging attempt in "WPFExample" project with 0.5.6 library. Does it really works correctly?

**Comment by gregsdennis** [comment]
Are you using VS 2015? A lot of the code uses C# 6 features, and it won't build in 2013 or earlier.

**Comment by SkyQuant** [comment]
Yes, VS 2015 and C# 6. I have seen properties like this :-)
 ```public double MaxColumnWidth { get; set; } = 60;```

**Comment by SkyQuant** [comment]
Problems usually in XAML, for example in this snippet with convertation
```
<liveCharts:ScatterSeries Title="Sin" 
                                         PrimaryValues="0, .7071, 1, .7071, 0, -0.7071, -1, -0.7071, 0"
                                         SecondaryValues="0, 45, 90, 135, 180, 225, 270, 315, 360"/>
```

**Comment by SkyQuant** [comment]
Or unreconized attributes 
```
Stroke="#FFB300" Fill="#AAFFB300" 
 Stroke="#FFA000" Fill="#AAFFA000"
```

**Comment by gregsdennis** [comment]
@beto-rodriguez, it seems there may be a glitch in the project file.  For some reason, the compiler returns a bunch of errors, but the solution builds and runs.  (I'm confused as to how that can happen.)

Regardless, the solution to remove the errors was found [here](http://stackoverflow.com/a/25529024/878701).  Can you do this and commit, please?

**Comment by beto-rodriguez** [comment]
@gregsdennis I will take a look at this

**Comment by beto-rodriguez** [comment]
also I wil try to remove all c#6 sintax.

**Comment by beto-rodriguez** [comment]
What was causing the issue is that binded primary values are not loaded in design mode, so they were null, now PrimaryValues property detects if it is in desing mode, and if it it creates an empty list of values, if this does not works for you please let me know.

this is what solves the issue:
https://github.com/beto-rodriguez/Live-Charts/commit/1d2e2d72243468a4c6e5ea22af711db252bc1c1a#diff-7c12c11b1fbff07aaa27277843014e12L57

**Comment by beto-rodriguez** [comment]
@SkyQuant just released 0.5.7 https://github.com/beto-rodriguez/Live-Charts/releases/tag/0.5.7, its available on nuget too, you said something really important "Does it really works correctly". because of that bug alot of people might think this, so this is a really important release.

Thanks, I hope you find this library useful.

**Comment by SkyQuant** [comment]
Anyway: Exception thrown: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll
in this snippet
```
            <liveCharts:BarChart.Series>
                <liveCharts:BarSeries Title="Maria"    PrimaryValues="20, 40, 45, 60, 55, 60, 65, 70"></liveCharts:BarSeries>
                <liveCharts:BarSeries Title="John"     PrimaryValues="30, 35, 43, 68, 65 ,70, 55, 60"></liveCharts:BarSeries>
                <liveCharts:LineSeries Title="Averge"  PrimaryValues="25, 37.5, 44, 64, 60, 65, 60, 65" AreaOpacity="0"></liveCharts:LineSeries>
            </liveCharts:BarChart.Series>
```

But after XAML commenting and initialization in code it's become ok
```
            Chart.Series.Add(new BarSeries {PrimaryValues = new ObservableCollection<double> { 20, 40, 45, 60, 55, 60, 65, 70 } });
            Chart.Series.Add(new BarSeries {PrimaryValues = new ObservableCollection<double> { 30, 35, 43, 68, 65, 70, 55, 60 } });
            Chart.Series.Add(new BarSeries {PrimaryValues = new ObservableCollection<double> { 25, 37.5, 44, 64, 60, 65, 60, 65 } });
```

**Comment by beto-rodriguez** [comment]
if you already updated to last version try closing all files and opening them again, its a bug in designer mode, if this does not work please let me know, it works for me, @gregsdennis does it works for you?

**Comment by SkyQuant** [comment]
Still the same :-( 
Tried both 0.5.7, with CoreLibrary and binaries from Nuget

**Comment by beto-rodriguez** [comment]
this is what I get.

![image](https://cloud.githubusercontent.com/assets/10853349/11567844/ba3c06a6-99ae-11e5-9854-e33743264584.png)

**Comment by SkyQuant** [comment]
I have the same picture in design mode, but exception on debuging.

**Comment by beto-rodriguez** [comment]
maybe you added and invalid character by error, try to sync witht his repo again. It works for me, actually I just added support for C#5, I opened this project in VS13 and everying works fine.

**Comment by SkyQuant** [comment]
I totaly deleted previous files and updated to clean resent version.

**Comment by beto-rodriguez** [comment]
Also ensure that both projects are targeting same .net framework, It should work I dont know why it does not for you

**Comment by SkyQuant** [comment]
v4.6?

**Comment by beto-rodriguez** [comment]
it works from 4.0 to 4.6, just make sure both projects are targeting the same framwork
