### ISSUE TITLE
Missing  X & Y Axis Separator Lines and out of place x axis label

### ISSUE THREAD

**Issue by Billy-Joel** [beto-rodriguez/Live-Charts#460]
Hi Beto,

Good day, I've been using this control for quite some time now and loving it.
I tried to update the control to the latest version but encountered some sort of a bug. 
Some of the axis separator lines are missing. The code are still the same as the one before but for some reason it stop on painting some lines. Also the x axis seems to extend to the lowest part where the x axis labels were located.

I'm trying to downgrade my version to the last one but failed to do so. 

Thanks.

Regards,
Billy Joel

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.3</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>7</td>
</tr>
</table>

**Comment by Billy-Joel** [comment]
Been trying to add some screenshots but encountering some kind of error

**Comment by beto-rodriguez** [comment]
Hi Billy I am sorry for this issue, i'll try to reproduce with the info you gave me, there are many ways to roll back, from the package manager run these commands in that order:

PM > Uninstall-Package LiveCharts.Wpf
PM > Uninstall-Package LiveCharts
PM > Install-Package LiveCharts.Wpf -version 0.9.2

Hope this helps you

**Comment by Billy-Joel** [comment]
Thanks... 
I really appreciate your reply.

**Comment by beto-rodriguez** [comment]
I rolled back #449 this should now go back to normal with https://github.com/beto-rodriguez/Live-Charts/commit/39bdf10492b6989547ba3d23ab46e31999bb4671

version 0.9.3.1 will be published in a couple of hours with this fix.

Thank you very much Billy for all the reports you've made to the library.
