### ISSUE TITLE
Axis.LabelFormatter not working

### ISSUE THREAD

**Issue by NintendoPlayer** [beto-rodriguez/Live-Charts#461]
Instructions: replace text surrounded by '*' with your case, please delete this line.

#### How to reproduce?

Hi!  I'm trying to use a cartesianchart to show some temperatures between two datetime values.  Everything works correctly except when I try to fill the LabelFormatter.

When I reach this line, val value is  -3000000000.  I don't know how to handle this, because such value fires an exception because is out of DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks.

cartesianChart1.AxisX[0].LabelFormatter = val => (new System.DateTime((long)val).ToString("dd/MM/yyyy HH:mm:ss"));

I tried to turn the number to positive.  Then the chart shows.  It's empty, values are loaded to the serie, but the label shows 01/01/0001 00:50:00.

cartesianChart1.AxisX[0].LabelFormatter = val => (new System.DateTime(System.Math.Abs((long)val)).ToString("dd/MM/yyyy HH:mm:ss"));

I've seen the example on the live charts website, but I really don't understand it.

Some help would be nice.

Thanks

#### Extra info

I'm loading values into serie as DateModel, as suggested in live charts DateTime example

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.2.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10 Pro x64</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Well there is no way to convert -3000000000 to Datetime

The question is How does this value is there???

There are many possible answers, but the most likely is that you are passing a wrong limit to the axis, notice in the site Example I set the limits manually here: https://github.com/beto-rodriguez/Live-Charts/blob/master/Examples/Wpf/CartesianChart/ConstantChanges/ConstantChangesChart.xaml.cs#L119

So your error could be there... When the axis is being drawn, it calls your formatter function with the value it is trying to draw as parameter:

    LabelFormatter = val => ...

Where val is the value the axis is trying to draw

Why is your axis trying to draw a separator at -3000000000?

I don´'t know, please check that you are passing correctly the axis limits, a easy workaround if you don't want many troubles is to return an empty label when your chart is trying to draw this negative labels...

I don't support this solution but it can help you to find the issue:

    cartesianChart1.AxisX[0].LabelFormatter = val => val < 0 
                            ? "???" //lets return this dummy string just to help you find the issue...
                            : (new System.DateTime((long)val).ToString("dd/MM/yyyy HH:mm:ss"));

I am closing this for now I hope my answer helps you to find your issue.
thank you very much for the report.

**Comment by kropotin** [comment]
I have the same problem. This problem goes away when the collection does not yet have points. When the collection already contains points and I open the chart - everything works out normally.
I decided this: Formatter = value => new System.DateTime ((long) ((value < 0)? 0: value)). ToString ("t");
