### ISSUE TITLE
StepLineSeries slow

### ISSUE THREAD

**Issue by Bykiev** [beto-rodriguez/Live-Charts#467]
Hello, I'm using a stepline chart in my WPF project and I have near 2 000 points (I saw you example with 100 000 points but didn't find it in demo app where I can download it?), but when I  move from one point to another all app is freezing. I'm using DateTime on X Axis, so I'm using config and formatter from demo application. If I change StepLineSeries to LineSeries everthing is smooth and app is not freezing. Please, fix it!

Also paning and zooming is slow too even with LineSeries...

**Comment by beto-rodriguez** [comment]
Hello

Please see checkout the [geared](https://lvcharts.net/licensing/pricing) package, you can install it also from nuget

here is a repository, I keep adding samples as I fix issues

https://github.com/Live-Charts/GearedExamples


I hope this helps you I am closing this for now, little by little I am introducing the geared package as it gets more stable... but maybe it can help you too, give it a try
