### ISSUE TITLE
Realtime changes on PieChart

### ISSUE THREAD

**Issue by ruzovvo** [beto-rodriguez/Live-Charts#47]
Hi, I'm trying to use PieChart and I set
PrimaryValues="{Binding VM.Obj.Prop, UpdateSourceTrigger=PropertyChanged, Mode=OneWay}"

VM.Obj.Prop is a property:
public List<double> Prop
{
    get {return _prop;}
    set {
        _prop = value;
        RaisePropertyChanged(() => Prop)
    }
}

So in RaisePropertyChanged() I generate PropertyChanged event but chart doesn't change. only If I resize the window it will be redrawn. 
Am I doing everything right or I miss smth?

**Comment by beto-rodriguez** [comment]
You don't need to raise property changed event, Live charts should detect automatically the changes, there is actually one exmaple included in test project, you can clone the repo to see it, or watch it here:

**XAML**

https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/Pie%20Examples/MvvmPie.xaml

**Code Behind**

https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/Pie%20Examples/MvvmPie.xaml.cs

Hope it helps, if this does not solves your issue please let me know.

**Comment by beto-rodriguez** [comment]
Forgot to mention that VM.Obj.Prop should be an observable collection, otherwise it wont unpdate automatically

**Comment by gregsdennis** [comment]
If you are editing the existing collection, you don't need to raise PropertyChanged.  If you are reassigning the property, you do, and the control needs to respond to it to redraw.

Probably just needs a handler in the dependency property.

**Comment by beto-rodriguez** [comment]
it already has a handler in the dependency property.

**Comment by ruzovvo** [comment]
Hi again. I tried what you've suggested with ObservableCollection. Now it works almost fine. Thank you for it.
But there are still 2 problems I'd like to avoid:
1) each redraw is being processed from initial state but not from the previous state of collection
2) look at pic attached. After redraw I have artifact numbers left from previous collection state. I marked it with arrows
![piechart](https://cloud.githubusercontent.com/assets/4226718/11613752/61baac6c-9c3d-11e5-90d7-13d200274efa.png)

**Comment by beto-rodriguez** [comment]
I will try to force this bug, can you please show me some parts of your code, So it can be easier for me?

**Comment by ruzovvo** [comment]
public ObservableCollection<double> Spectrum
        {
            get { return _spectrum; }
            set
            {
                _spectrum = value;
                RaisePropertyChanged(() => Spectrum);
            }
        }

Modification happens 1 time per second:

Spectrum.Clear();
            Spectrum.Add(val1);
            Spectrum.Add(val2);
            Spectrum.Add(val3);
            Spectrum.Add(val3);

**Comment by ruzovvo** [comment]
Can you say smth about my 1st question regarding redrawing from initial state?

**Comment by beto-rodriguez** [comment]
the easiest solution, since you are updating the chart each second should be to disable animations, Set the DisableAnimation Property to ttue in your Pie Chart, right now pie chart only support full redraw animation, to support animation that starts from current state it is necesary to do an important improvements to PieSerie class, I will open a new issue to add this in a future, by now disable animations please.

**Comment by ruzovvo** [comment]
Beto, I've found 1 more problem. 
this approach does not work: 
<liveCharts:PieChart Name="Spectrum" Grid.Row="0" Grid.Column="0" DisableAnimation="True">
	<liveCharts:PieChart.Series>
		<liveCharts:PieSeries Title="Maria" PrimaryValues="{Binding Obj.Prop}"
				 Labels="{Binding Obj.PropDesc}" />
	</liveCharts:PieChart.Series>
</liveCharts:PieChart>

updates don't come. but if I bing like this:

<liveCharts:PieChart Name="Spectrum" Grid.Row="0" Grid.Column="0" DisableAnimation="True" Series="{Binding PropSeries}"/>

and manually will do:
PropSeries.Add(new PieSeries() { PrimaryValues = Obj.Prop });

then piechart will be updating on collection Obj.Prop changes. Please take a look

**Comment by beto-rodriguez** [comment]
@ruzovvo I will take a look, it seems that the handler is not beeing attached if you initialize it with XAML, I will take a look and let you know as soon as possible, Thanks for reporting

**Comment by ZaJra** [comment]
ruzovvo do you still have the code for realtime pi chart?
