### ISSUE TITLE
LabelPoint on Column Bar

### ISSUE THREAD

**Issue by drdran** [beto-rodriguez/Live-Charts#471]
Instructions: replace text surrounded by '*' with your case, please delete this line.

#### How to reproduce?

There Is a chunck of code:

In the usercontrol:
```
ColumnSeries Stats = new ColumnSeries
 {
  Values = new ChartValues<ObservableValue> { new ObservableValue(0) },
  MaxColumnWidth = 250,
  DataLabels = true,
  LabelPoint = point => point.Y.ToString(),
  Title = "Statistic",
  Fill = Magenta,
};
```
I set a timer that every 5 seconds update the point value, so the Bar Value is updated and painted correctly, but the labelPoint Not. 
The LabelPoint value seems to be freezed on the first value set and is no more update.

#### Extra notes

On Release 0.9.1 The problem don't still exist, it appear on release 0,9.2, 0.9.3, 0.9.3.5

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.3.5</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 7,8,10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Thank you very much for the report.

The referenced commit fixes it and it will be included since version 0.9.5 

This issue was introduced when I added #414, an important feature that was missing.
