### ISSUE TITLE
liveCharts axis labels don'n appear

### ISSUE THREAD

**Issue by aozkul** [beto-rodriguez/Live-Charts#475]
WinForm Application code below

            LineSeries row = new LineSeries()
            {
                DataLabels = true,
                FontSize = 16f,
                Foreground = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(55, 71, 79)),
                Values = new ChartValues<int>(),
                StrokeThickness = 3,
                //Fill = System.Windows.Media.Brushes.Transparent,
                LabelPoint = point => "%" + point.Y.ToString()
            };

            LiveCharts.Wpf.Axis ax = new LiveCharts.Wpf.Axis()
            {
                Title = "Tools",
                FontSize = 8,
                Separator = new Separator { Step = 1, IsEnabled = false },
                ShowLabels = true,
                Labels = new List<string>() {"T11","T12", "T13", "T14", "T15", "T16", "T17", "T18", "T19", "T20", "T21" },
            };

            for (int i = 0; i < Tools.Count-1 ; i++)// Tools.Count-1 = 11
            {
                row.Values.Add((int)ToolPerformance[i]);
            }

            cartesianChart1.Series.Add(row);
            cartesianChart1.AxisX.Add(ax);

i tries this code, and  basicly i did not see all the labels. i have 11 values for this but i just saw 3 values and 2 of them are the same.. Do you have any comments?
thanks for replies.

**Comment by aozkul** [comment]
sorry but i had problems with image so i just try to explain. basicly i did not see all the labels. i have 11 values for this but i just saw 3 values and 2 of them are the same.

**Comment by beto-rodriguez** [comment]
Hello

I just copy pasted your code and its works for me:

Please ensure you are using latest version available on Nuget (0.9.3.5), am I missing something?

![image](https://cloud.githubusercontent.com/assets/10853349/23494079/06e490b2-fed6-11e6-93be-3de9baa9fc41.png)

**Comment by aozkul** [comment]
hello,

i solved the issue. just need to add minValue and maxValue for series. i don't know why but with these 2, i solved the issue.

thanks

**Comment by beto-rodriguez** [comment]
Awesome, I am closing this now.

When you don't specify min and max limits the axis auto scales based on your data, also notice that the labels are mapped directly to the X coordinate value (in this case).

I'll try to explain this better in the site to prevent future issues.
