### ISSUE TITLE
WPF - Section Labels hidden on sections for X axis

### ISSUE THREAD

**Issue by SpiffWilkie** [beto-rodriguez/Live-Charts#479]
When inserting sections on the X axis in a WPF chart, the axis labels are placed below the viewable area.
AxisSection.cs places sets the label top to Model.Chart.DrawMargin.Height, and for sections on the X axis, the label top is not repositioned, leaving it out of the viewable area.

Changing line 244 to `Canvas.SetTop(_label, 0d);` places the label on the top for the X axis and does not impact the placement for Y axis.

**Comment by beto-rodriguez** [comment]
Hello, thanks for the report.

Many things have happened in this library, as I see things now, it is a better idea to use a `VisualElement` they are more flexible than labels.

With the referenced commit I made `Label` property obsolete, it will display a warning in your code and will guide you to update your chart to use a `VisualElement` instead.

**Comment by KWodarczyk** [comment]
So if I just want to put a vertical line on the chart i need to use VisualElement now ?
