### ISSUE TITLE
Candlestick chart

### ISSUE THREAD

**Issue by SkyQuant** [beto-rodriguez/Live-Charts#48]
I'd like to add Candlestick chart with the next values on each point: date, time, open, high, low, close, volume. What steps should I do? Make copy of Series class and swith just doubles to candle class with mentioned properties? Then create CandleSeries class inherited from this Series copy and write a logic in Plot methods?

**Comment by beto-rodriguez** [comment]
Create a CandleStickChart class that inherits from `Chart`, override necesary methods, you can guide in any of already included charts https://github.com/beto-rodriguez/Live-Charts/tree/master/Charts/Charts, then create CandleStickSerie class that inherits from `Serie`, and override necesary methods, you can see examples here https://github.com/beto-rodriguez/Live-Charts/tree/master/Charts/Series, if you have any problems doing it I can help you, it is not that hard, actually after I made the first chart the rest of them were made in a couple of hours.

Wish you luck!

**Comment by beto-rodriguez** [comment]
please if you succed do a pull request and shar that code with us!

**Comment by SkyQuant** [comment]
Is single Candle must be Shape with registred (OHLC) Dependency Properties?

**Comment by SkyQuant** [comment]
Suppose this issue should be keeped open for discussion. What do you  think, beto-rodriguez?

**Comment by beto-rodriguez** [comment]
Sure, here it is

**Comment by SkyQuant** [comment]
So, should I make a candle as class inherited from shape, first?

**Comment by beto-rodriguez** [comment]
It is not necessarily but it might help, for example in the pie chart there is a class called slice, and it helped to draw pie slices, https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/Shapes/PieSlice.cs

**Comment by SkyQuant** [comment]
@beto-rodriguez seems I have some difficulties to build this kind of graphic. If you quick in charts constructing please make an implementation of this data type one day.
```
    public class Candle
    {
        public int Index { get; set; }
        public DateTime DateTime { get; set; }
        public decimal Open { get; set; } 
        public decimal High { get; set; } 
        public decimal Low { get; set; } 
        public decimal Close { get; set; } 
        public int Volume { get; set; }
    }
```

**Comment by beto-rodriguez** [comment]
Sure this can be added in a future, right now the main goal if to fix all the bugs and improve performance for already implemented charts.

**Comment by beto-rodriguez** [comment]
I will close this issue and open a new one to list all the new charts to include, live charts is now much more stable, we can work on adding new charts
