### ISSUE TITLE
Labels are not shown, not all of them

### ISSUE THREAD

**Issue by midthegap** [beto-rodriguez/Live-Charts#481]
#### How to reproduce?

Copying an example from the project, I created a chart with labels, but only a few of them are shown.
I created a minimal project to show the problem:
https://github.com/midthegap/LiveChartsLabelsTest

#### Extra notes

Probably connected to issue #475 
The result is this:

![screenshot from 2017-03-02 16-10-43](https://cloud.githubusercontent.com/assets/18376443/23513766/7e760aea-ff65-11e6-8d35-73d3e265ff03.png)

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>LiveCharts.Wpf 0.9.3.5</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.0 client profile</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Hello, no this is a different issue, the library by default optimizes the number of labels in the axis, imagine a series with 1000 points, then it would not be practical to show all the labels.

but in this case where you are sure you have a few labels, then you must tell the axis to display them all, forcing the step fo the separator to 1


     LiveCharts.Wpf.Axis ax = new LiveCharts.Wpf.Axis()
        {
            Separator = new Separator { Step = 1, IsEnabled = false },
        };


I am closing this for now, let me know if you face any other issue.

**Comment by midthegap** [comment]
Cool! It works like a charm. The only thing I regret is that I have to set Step via code-behind. I understand it correctly that I cannot set it on XAML?

**Comment by midthegap** [comment]
Sorry, the answer was under my nose.
`                        <lvc:Axis>`
`                            <lvc:Axis.Separator>`
`                                <lvc:Separator Step="1" />`
`                            </lvc:Axis.Separator>`
`                        </lvc:Axis>`

Thanks and please keep going with your awesome work.

**Comment by xiongsiyu2018** [comment]
thank you
