### ISSUE TITLE
Axis MinRange does not work with WinForms 

### ISSUE THREAD

**Issue by w3sz** [beto-rodriguez/Live-Charts#482]
#### How to reproduce?
Create CartesianChart with one X axis and 3 Y axes.  Set two Y axes to be fixed ranges, and set third to be automatic with following code:
 dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.LeftBottom,
                Title = "Hz",
                MinRange = 50.0,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    Stroke = brush
                },
                LabelFormatter = value => Math.Round(value).ToString()
            });

When this chart runs, the initial range is 0-1 and then with first data point the range is for example -856.0 to -856.8, then with next data point the range is -840 to -880 all of these having range less than 50. Same is true for positive numbers, first datapoint gives range 3484 to 3484.8, second data point gives range 3480-3520 all range less than 50.

Pertinent code is here: 

        public ChartValues<ObservablePoint> dopplerPt { get; set; }
        public ChartValues<ObservablePoint> headingPt { get; set; }
        public ChartValues<ObservablePoint> speedPt { get; set; }
        public SeriesCollection dopplerPlots { get; set; }
//
.
.
.  non-relevant code between these sections
.
//

        public MainForm()
        {
            InitializeComponent();

            ChartValues<ObservablePoint > dopplerPt = new ChartValues<ObservablePoint>();
            ChartValues<ObservablePoint> headingPt = new ChartValues<ObservablePoint>();
            ChartValues<ObservablePoint> speedPt = new ChartValues<ObservablePoint>();

            System.Windows.Media.BrushConverter converter = new System.Windows.Media.BrushConverter();
            var brush = (System.Windows.Media.Brush)converter.ConvertFromString("#000000");
            Separator separator = new Separator();

            dopplerPlots = new SeriesCollection
            {
                new ScatterSeries
                {
                Title = "Doppler Shift",
                Values = dopplerPt,
                PointGeometry = DefaultGeometries.Diamond,
                MaxPointShapeDiameter =10,
                FontSize = 8,
                ScalesYAt = 0,
                Fill = brush
                },
                new ScatterSeries
                {
                Title = "Heading",
                Values = headingPt,
                PointGeometry = DefaultGeometries.Diamond,
                MaxPointShapeDiameter = 8,
                FontSize = 8,
                ScalesYAt = 1
                },
                new ScatterSeries
                {
                Title = "Speed",
                Values = speedPt,
                PointGeometry = DefaultGeometries.Diamond,
                MaxPointShapeDiameter = 8,
                FontSize = 8,
                ScalesYAt =2
                }
            };

            dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.LeftBottom,
                Title = "Hz",
                MinRange = 50.0,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    Stroke = brush
                },
                LabelFormatter = value => Math.Round(value).ToString()
            });
            dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.RightTop,
                Title = "Degrees",
                ShowLabels = false,
                MaxValue = 360,
                MinValue = 0,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    IsEnabled = false
                },
            });
            dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.RightTop,
                Title = "km/h",
                MaxValue = 1200,
                MinValue = 0,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize =15,
                Separator = new Separator
                {
                    IsEnabled = false
                }
            });
            dopGraph.AxisX.Add(new Axis
            {
                Position = AxisPosition.LeftBottom,
                Title = "Seconds",
                MinValue = 0,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    Stroke = brush
                }
            });

            dopGraph.Series = dopplerPlots;
            dopGraph.LegendLocation = LegendLocation.Top;
            dopGraph.ForeColor = Color.Black;    

*Explain what you expect, feedback, images or anything you consider necessary*

I would like for MinRange=50 to ensure that the range of the Y axis for the axis in question is always 50 or greater. 

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.3.5</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*.NET Framework 4.5</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10 Pro Build 14393.rs1_release.161220-1747</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
The truth is that `Axis.MinRange/Axis.MaxRange` were not designed for this scenario, these properties are evaluated when you zoom in /out, they limit your zooming max/min range.

I saw the description of this property:

> Gets or sets the min range this axis can display, useful to limit user zooming.

Yes, it is ambiguous, I think the way you are trying to use this property has sense, but, it would need to change some really important parts in the library, at this point I don't feel like doing it, to prevent possible new issues, I don't know maybe in a future this will be added, I need to evaluate it.

As an alternative you can also play with your Axis.MinValue and Axis.MaxValue and the Axis.RangeChanged event, to ensure your axis is displaying at least 50 units.

**Comment by w3sz** [comment]
HI Alberto,

Thanks for the  note! You are great!

I can work without a change in the code...I just misunderstood what the
parameter was meant to do. So its another EBCAK (Error Between Chair And
Keyboard) here :)

Sorry for the bandwidth, you are great and Live Charts is great too!

Have a great weekend, and

Thanks Again,

Roger Rehr

**Comment by beto-rodriguez** [comment]
Have a great weekend you too, I am closing this for now then.

thanks to you

**Comment by bugadani** [comment]
This one could deserve a clearer documentation, I just hit this "issue", too.
