### ISSUE TITLE
Potential improvements in Autoscaling of CartesianCharts

### ISSUE THREAD

**Issue by w3sz** [beto-rodriguez/Live-Charts#483]
Issues are:
1.  When bottom limit is a negative number it is often hidden below the bottom of the chart.  Note in the image below that the Black Diamond for Doppler Shift is missing.  It is below the lower limit.  Its value is -1772.89.  In this image I have formatted Left axis to display as integer.  But problem occurs whether or not this is done.

![as_anotherfirstnegpointhiddencut](https://cloud.githubusercontent.com/assets/3195078/23556672/655b8436-fffb-11e6-82ca-2ab58b9b571b.PNG)

2.  When new low value is, say -5500 and previous LowerLimit is -5000, axis will not rescale until a low value of -6000 is obtained, so all values between -5000 and -6000 remain hidden until value of -6000 is obtained.  Note in the image below several missing Black Diamonds for Doppler Shift at the right of the graph.  Minimum datapoint has value of -5496.79.

![as_axisnotresized](https://cloud.githubusercontent.com/assets/3195078/23557192/3142dbc0-fffd-11e6-804e-a6a0b2e21cf6.PNG)
#
3.   Autoscaling choices may leave nearly half of chart empty.  In the image below, note that the axis has scaled so that the right third of the graph is empty.  Better maximum values for the axis would include 750 or 800.

![as_poortimescalingcut](https://cloud.githubusercontent.com/assets/3195078/23556704/7f84372c-fffb-11e6-90f4-7ff31cf1b968.PNG)

#### How to reproduce?

Create CartesianChart with one X axis and 3 Y axes. Set two Y axes to be fixed ranges, and set third to be automatic 

#### Extra notes

Would like to have autoscaling improved as regards the above.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.3.5</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*.NET Framework 4.5</td>
</tr>
<tr>
    <td>Windows</td>
    <td>*Windows 10 Pro Build 14393.rs1_release.161220-1747</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Thank you very much for the report, the referenced commit should improve the series auto scale.

It's being a long way in the library, for some reason this was not updated, thanks for the catch.

this fix will be included in the next version of the library 0.9.4

**Comment by w3sz** [comment]
Thank you very much!
