### ISSUE TITLE
Wordmap Graph

### ISSUE THREAD

**Issue by fagenorn** [beto-rodriguez/Live-Charts#484]
Hey,

Would it be possible to implement a wordmap type of graph 
Similar to this:

![wordmap](http://herdingcats.typepad.com/.a/6a00d8341ca4d953ef00e553a8d1268833-pi)

Perhaps it could be done using a `Dictionary<string,double>` and based on double it would increase the font size. I, however, have no idea how it would rotate the text and make everything fit perfectly.

**Comment by beto-rodriguez** [comment]
I can't find the license, but there seems to be some code working already in C#

https://github.com/whydoidoit/WordCloud

I hope the author @whydoidoit is willing to share his work, I can use his code in a future if he agrees

**Comment by beto-rodriguez** [comment]
I am sorry I am closing this because this seems out of scope.

This would require a full rewrite, this library is complex enough, the truth is that I can't implement this for now.

LiveCharts is DataVisualization, I am not sure if a word is consider data 😟
