### ISSUE TITLE
Stacked bar chart loses bars when shrinking

### ISSUE THREAD

**Issue by lummoj** [beto-rodriguez/Live-Charts#485]
#### How to reproduce?

* Create a stacked bar chart with a dozen or more series having negative values only
* Shrink the control / window vertically and observe that at some sizes some of the bars will disappear leaving a gap (see attached screenshots)

Good:
![image](https://cloud.githubusercontent.com/assets/112391/23598244/251436d6-0274-11e7-9d02-9acaf6cb0eed.png)

Bad:
![image](https://cloud.githubusercontent.com/assets/112391/23598258/3d466e04-0274-11e7-9a3d-a4a121618c0c.png)

#### Extra notes

* I cannot reproduce this issue when the series has positive and negative values
* The issue seems to occur when the zero Y axis grid line disappears as you shrink the control vertically
* Turning data labels off does not fix the issue
* Setting a manual separator (instead of using CleanSeparator) with a step of 1000 **does fix the issue** and seems to ensure that the zero Y axis grid line stays visible

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.3.5 (WinForms)</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.0</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10 Pro (14393.693)</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Thank you very much for the detailed report.

The referenced commit should fix this.

**Comment by beto-rodriguez** [comment]
this will be included since version 0.9.5
