### ISSUE TITLE
Feature Request: Add ability to disable auto-ranging of Weights in HeatSeries

### ISSUE THREAD

**Issue by benpocalypse** [beto-rodriguez/Live-Charts#486]
#### Extra notes

When a HeatSeries contains points with all the same Weights, the Legend will update to show no actual range between values, and thus,  just show blank points in the chart like this: [Heat Series points with all the same Weights](http://imgur.com/a/C4ery)

When the HeatSeries point values are different (have a range) the display appears as one would expect, like this: [HeatSeries points with range of Weights](http://imgur.com/a/9oYpX)

Although it goes against the current design of the LiveCharts library in regards to the *Algorithms structure, it would be nice to be able to specify a range for the HeatSeries colors to respect so that in the case that the values are the same, it doesn't Auto-range and remove the gradient colors. 
In all the chart types, the weight ranges are specified in the X and Y axis' ranges. I tried to work around this by putting dummy points on the HeatSeries that contain the min and max values I'd like, and then move them off the chart by setting their X and Y values to -1, but the chart view automatically expands to include them.

If I have time, I'll fork, attempt to implement the change, and do a PR.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.3.5</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 7 SP1</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Thank you very much for the report, the reference commit prevents this issue.

The interpolation failed because we had an undefined operation 0/0

What I just did is, if weigh = double.NaN then use the first step in the gradient.

I think this should be enough.
