### ISSUE TITLE
Issue Heatmap not Redrawing when resizing

### ISSUE THREAD

**Issue by fagenorn** [beto-rodriguez/Live-Charts#488]
#### Issue

When resizing the window, heat map values will not move until I manually redraw the control.

#### How to reproduce?

Simply resize the window with heat map width set to Auto.

#### Video

![Video Issue](http://i.imgur.com/7XdAfRW.gif)

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.4</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Thank you for the report.

This is fixed with the referenced commit and will be included in the next version of the library (0.9.5)
