### ISSUE TITLE
Binding data to Pie Chart Values not working.

### ISSUE THREAD

**Issue by Guddiny** [beto-rodriguez/Live-Charts#489]
#### How to reproduce?

- Install Caliburn Micro 3.0.3.0.

- Apply Pie chart example from GitHub and insert Binding to "values":
`<lvc:PieChart LegendLocation="Bottom">
            <lvc:PieChart.Series>
                <lvc:PieSeries Title="Maria" Values="{Binding TotalQueries}" DataLabels="True" PushOut="
LabelPoint="{Binding PointLabel}"/>
                <lvc:PieSeries Title="Charles" Values="{Binding TotalQueries1}" DataLabels="True" 
                               LabelPoint="{Binding PointLabel}"/>
                <lvc:PieSeries Title="Frida" Values="{Binding TotalQueries2}" DataLabels="True" 
                               LabelPoint="{Binding PointLabel}"/>
                <lvc:PieSeries Title="Frederic" Values="{Binding TotalQueries3}" DataLabels="True" 
                               LabelPoint="{Binding PointLabel}"/>
            </lvc:PieChart.Series>
        </lvc:PieChart>  `

## Extra notes
When i run this code i have `An unhandled exception of type 'System.NullReferenceException' occurred in WindowsBase.dll`
#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.4.0 (WPF)</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10 x64</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Hello thanks for the report, sadly this seems out of scope.

If the library works well with regular WPF bindings, and you face an issue using Caliburn, then this might be an issue with Caliburn, or an issue with your design.

I believe that it is probable that you are not using correctly Caliburn.

Please verify everything is working properly in your code.
