### ISSUE TITLE
Null reference exception when switching tabs using TabControl

### ISSUE THREAD

**Issue by mneciunas** [beto-rodriguez/Live-Charts#491]
#### How to reproduce?

Select tab with charts, then other tab, then charts again, then other tab again and the exception is thrown.
![livecharts](https://cloud.githubusercontent.com/assets/15345998/23832399/f1dc35e4-073b-11e7-8475-23a0dbe22a1b.gif)

CartesianChart and PieChart throws exception while Gauge doesn't.

#### Extra notes

I've made a simple project to reproduce this bug.
[Link to repository](https://github.com/mneciunas/LiveChartTabControlNullReference)

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.4</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>v4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Hello thanks for the report.

This issue was introduced in 0.9.4, please roll back or wait for 0.9.5, it will be published today.

this was fixed with https://github.com/beto-rodriguez/Live-Charts/commit/eb638c6de4d96a9fad4b7c1df523d0296dd508d7

**Comment by beto-rodriguez** [comment]
I am closing this LiveCharts 0.9.5 is already in nuget

Again thanks!
