### ISSUE TITLE
row series with missing values

### ISSUE THREAD

**Issue by aozkul** [beto-rodriguez/Live-Charts#497]
hello,

i am dealing with row series and i have some series like

[100,98,70]
[null,null,50]

if i draw this values with row series, chart gets the '50' value in the second serie to index 0. and use these series like

[100,98,70]
[50,null,null]

and if i put double.NaN then returns 'NaN' is not a valid value for property 'To'

but if i draw this values with line series and put double,NaN for every null value. everything works fine.

how can i draw this values with row series.

I am using
Live-Charts version 	0.9.5.0
Windows 	Windows 10

**Comment by beto-rodriguez** [comment]
Hello, this is a good question, `double.NaN` feature exists only for `LineSeries`.

Why?

I really don't know, this could be extended also to all the series, feel free to create a PR, but I think this is not a vital feature for the rest of the series, check out in the next snippet how I handle your case, I only explicitly give the point the X coordinate, so I can ignore where I don't need a point:

```xml
    <lvc:CartesianChart>
            <lvc:CartesianChart.Series>
                <lvc:ColumnSeries Values="{Binding V1}" SharesPosition="False" />
                <lvc:ColumnSeries Values="{Binding V2}" SharesPosition="False" />
            </lvc:CartesianChart.Series>
        </lvc:CartesianChart>
```

```c#
public class Vm
    {
        public Vm()
        {
            //case
            //[null,null,50]

            V1 = new ChartValues<ObservablePoint>
            {
                //no point when x = 0
                //no point when x = 1
                new ObservablePoint
                {
                    X = 2,
                    Y = 5
                }
            };

            //case
            //[50,null,null]
            V2 = new ChartValues<ObservablePoint>
            {
                new ObservablePoint
                {
                    X = 0,
                    Y = 3
                }
                //ignore x= 1 and x=2
            };
        }

        public ChartValues<ObservablePoint> V1 { get; set; }
        public ChartValues<ObservablePoint> V2 { get; set; }
    }
```

Let me know if this is enough for your case, then I can close the issue, thanks for the report and good question.

**Comment by beto-rodriguez** [comment]
I am closing this for now, let me know if this was not enough.

**Comment by jamtycle** [comment]
I'm having the same issue at trying to set null (double.NaN) points into a ColumnSeries().
**Winforms Code:**
``` C#
return new ColumnSeries()
{
    Title = _serie.Title,
    Values = _serie.Values,
    SharesPosition = false
}; 
```

this (i think) is the equivalent posted for WPF in this post. But it does not solve the problem i'm still having the "Additional information: 'NaN' is not a valid value for property 'To'." error. Is there any other solution to this? Or ColumnSeries is not able to handle NaN points? :(
