### ISSUE TITLE
HoverPushOut is missing for piechart

### ISSUE THREAD

**Issue by Nightwingg** [beto-rodriguez/Live-Charts#499]
How to reproduce?
First of all, thanks for livechart, it has helped me a lot
I've been working on a piechart, to make a circular menu. However, I have tried to set the distance in which the slides are separated from the graph when the mouse is placed over and I could not. Searching the web, i found the command HoverPushOut, but I could not use it, because I can not find it or is not available.

 I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.95</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>.NET Framework 4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 7 professional</td>
</tr>
</table>

thx, and sorry for my english

**Comment by beto-rodriguez** [comment]
Hello

I am sorry It works for me, am I missing something?

![hoverpushout](https://cloud.githubusercontent.com/assets/10853349/24021449/a41b7756-0a66-11e7-837e-ebcc705090ec.gif)

    <lvc:PieChart LegendLocation="Bottom" HoverPushOut="50">
            <lvc:PieChart.Series>
                <lvc:PieSeries Title="Maria" Values="3" DataLabels="True" PushOut="20" 
                               LabelPoint="{Binding PointLabel}"/>
                <lvc:PieSeries Title="Charles" Values="4" DataLabels="True" 
                               LabelPoint="{Binding PointLabel}"/>
                <lvc:PieSeries Title="Frida" Values="6" DataLabels="True" 
                               LabelPoint="{Binding PointLabel}"/>
                <lvc:PieSeries Title="Frederic" Values="2" DataLabels="True" 
                               LabelPoint="{Binding PointLabel}"/>
            </lvc:PieChart.Series>
        </lvc:PieChart>

**Comment by Nightwingg** [comment]
Hi Beto, sorry, I forgot to mention that it was for winforms not for XML.
However, thanks for defining me that it works for XML, I will program the piechart in XML.
If Hoverpushout works in winforms, let me know
Greetings and thanks

**Comment by beto-rodriguez** [comment]
You were right, this property was not accesible in WinForms, the referenced commit exposes the property, this will be included in the next version of the library (0.9.6) thanks for the report!

**Comment by Nightwingg** [comment]
thanks to you
