### ISSUE TITLE
Sections do not update when DisableAnimations = true

### ISSUE THREAD

**Issue by JoolzCheat** [beto-rodriguez/Live-Charts#504]
#### How to reproduce?

Set a binding value to a section, and update it. The section moves along the chart to the new value. Set the Chart <b>DisableAnimations</b> to <b>True</b>, now change the section value and note it doesn't change until <b>DisabledAnimations</b> is again set to <b>false</b>

#### Extra notes

*I wanted a Mouse Crosshair that snapped to datapoints, so am using a hacky-updating Axis Section to accomplish this. When I zoom out the chart turns off animations to maintain speed.*

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>.WPF 0.9.5<br>Geared 1.2.7</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
This is not an issue with the library, this is how normally animation work in WPF, you cant play like this, it is whether animated or not 😟

**Comment by beto-rodriguez** [comment]
I am closing this for now, since this issue is not with the library, LiveCharts is built in the top of WPF.
