### ISSUE TITLE
UWP: strange behavior on first and last values

### ISSUE THREAD

**Issue by ach00** [beto-rodriguez/Live-Charts#506]
Hi,
with LineSeries I get a vertical line at the beginning and the end of the chart.

http://hpics.li/09d4d93
http://hpics.li/123b82d

Can you please help me with this?
Thanks

**Comment by beto-rodriguez** [comment]
Related to #367 

UWP will have many fixes soon, this issue will be gone once the mentioned issue is fixed.

I am closing this for now since this issue is already reported, thanks
