### ISSUE TITLE
Pie charts over Bubble charts/ Scatter and pies

### ISSUE THREAD

**Issue by NickSavin** [beto-rodriguez/Live-Charts#507]
Hello!

Is there any way to plot Bubble chart with Pie charts as points.

like this:

![image](https://cloud.githubusercontent.com/assets/20172765/24193505/8d39beca-0f03-11e7-828a-591c5552d5d2.png)

**Comment by beto-rodriguez** [comment]
Close enough, you can add any item to a chart, even another chart, that is what I did.

![untitled](https://cloud.githubusercontent.com/assets/10853349/24309950/8654f8a4-1093-11e7-8f8b-f5c05c2bd980.png)

```xml
<lvc:CartesianChart>
            <lvc:CartesianChart.AxisX>
                <lvc:Axis MinValue="0" MaxValue="12" 
                          Labels="Jan, Feb, Mar, Apr, May, Jun, Jul, Agu, Sep, Oct, Nov, Dec"/>
            </lvc:CartesianChart.AxisX>
            <lvc:CartesianChart.AxisY>
                <lvc:Axis MinValue="200" MaxValue="600">
                    <lvc:Axis.Separator>
                        <lvc:Separator Step="50"></lvc:Separator>
                    </lvc:Axis.Separator>
                </lvc:Axis>
            </lvc:CartesianChart.AxisY>
            <lvc:CartesianChart.VisualElements>
                <lvc:VisualElement X="2" Y="250" HorizontalAlignment="Center" VerticalAlignment="Center">
                    <lvc:VisualElement.UIElement>
                        <lvc:PieChart Height="20" Width="20">
                            <lvc:PieChart.Series>
                                <lvc:PieSeries Values="4" />
                                <lvc:PieSeries Values="7" />
                                <lvc:PieSeries Values="2" />
                            </lvc:PieChart.Series>
                        </lvc:PieChart>
                    </lvc:VisualElement.UIElement>
                </lvc:VisualElement>
                <lvc:VisualElement X="9" Y="500" HorizontalAlignment="Center" VerticalAlignment="Center">
                    <lvc:VisualElement.UIElement>
                        <lvc:PieChart Height="60" Width="60" HorizontalAlignment="Center" VerticalAlignment="Center">
                            <lvc:PieChart.Series>
                                <lvc:PieSeries Values="6" />
                                <lvc:PieSeries Values="2" />
                                <lvc:PieSeries Values="1" />
                            </lvc:PieChart.Series>
                        </lvc:PieChart>
                    </lvc:VisualElement.UIElement>
                </lvc:VisualElement>
                <lvc:VisualElement X="5" Y="400" HorizontalAlignment="Center" VerticalAlignment="Center">
                    <lvc:VisualElement.UIElement>
                        <lvc:PieChart Height="80" Width="80" HorizontalAlignment="Center" VerticalAlignment="Center">
                            <lvc:PieChart.Series>
                                <lvc:PieSeries Values="6" />
                                <lvc:PieSeries Values="2" />
                                <lvc:PieSeries Values="1" />
                            </lvc:PieChart.Series>
                        </lvc:PieChart>
                    </lvc:VisualElement.UIElement>
                </lvc:VisualElement>
                <lvc:VisualElement X="6" Y="420" HorizontalAlignment="Center" VerticalAlignment="Center">
                    <lvc:VisualElement.UIElement>
                        <lvc:PieChart Height="100" Width="100" HorizontalAlignment="Center" VerticalAlignment="Center">
                            <lvc:PieChart.Series>
                                <lvc:PieSeries Values="6" />
                                <lvc:PieSeries Values="2" />
                                <lvc:PieSeries Values="1" />
                            </lvc:PieChart.Series>
                        </lvc:PieChart>
                    </lvc:VisualElement.UIElement>
                </lvc:VisualElement>
            </lvc:CartesianChart.VisualElements>
        </lvc:CartesianChart>
```

**Comment by NickSavin** [comment]
Thank you!

**Comment by NickSavin** [comment]
Does not work via Binding:


`<lvc:CartesianChart VisualElements="{Binding VisualElements}"/>`

``

            VisualElements = new VisualElementsCollection()
            {
                 new VisualElement()
            {
                X = 5,
                Y = 3,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Center,
                UIElement = new PieChart()
                {
                    Width = 15,
                    Height = 15,
                    Series = new SeriesCollection()
                    {
                        new PieSeries() { Title = "23", Values = new ChartValues<ObservableValue>() { new ObservableValue(2) }, DataLabels = true },
                        new PieSeries() { Title = "123", Values = new ChartValues<ObservableValue>() { new ObservableValue(2) }, DataLabels = true },
                        new PieSeries() { Title = "11", Values = new ChartValues<ObservableValue>() { new ObservableValue(2) }, DataLabels = true }
                    }

                }
            },
                            new VisualElement()
            {
                X = 6,
                Y = 3,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Center,
                UIElement = new PieChart()
                {
                    Width = 20,
                    Height = 20,
                    Series = new SeriesCollection()
                    {
                        new PieSeries() { Title = "23", Values = new ChartValues<ObservableValue>() { new ObservableValue(2) }, DataLabels = true },
                        new PieSeries() { Title = "123", Values = new ChartValues<ObservableValue>() { new ObservableValue(2) }, DataLabels = true },
                        new PieSeries() { Title = "11", Values = new ChartValues<ObservableValue>() { new ObservableValue(2) }, DataLabels = true }
                    }
                }
            }

            };
``

**Comment by beto-rodriguez** [comment]
I am sure it works from code behind, please verify your binding works properly.
