### ISSUE TITLE
Limit Panning/Zooming to visible chart

### ISSUE THREAD

**Issue by Aichan** [beto-rodriguez/Live-Charts#508]
Hello

Right now, when Panning and Zooming are activated, it lets the user zoom out undefinitely and you can shift the view so that you don't see the values anymore.

Would it be possible to add an option to limit Panning/Zooming to the visible chart?

Keep up the good work, it's awesome ;)

Thank you !

**Comment by beto-rodriguez** [comment]
This was hard to achieve, with the referenced commit I added the new Axis.PreviewRangeChanged event, this even will make it easier for you to control you chart view area, here is a small sample:

    private void Axis_OnPreviewRangeChanged(PreviewRangeChangedEventArgs e)
        {
            //if less than -0.5, cancel
            if (e.PreviewMinValue < -0.5) e.Cancel = true;

            //if greater than the number of items on our array plus a 0.5 offset, stay on max limit
            if (e.PreviewMaxValue > LineSeries.Values.Count - 0.5) e.Cancel = true;

            //finally if the axis range is less than 1, cancel the event
            if (e.PreviewMaxValue - e.PreviewMinValue < 1) e.Cancel = true;
        }


    <lvc:CartesianChart Grid.Row="0" Zoom="X" Pan="X">
            <lvc:CartesianChart.Series>
                <lvc:LineSeries Name="LineSeries" Values="1,6,7,8,8"></lvc:LineSeries>
            </lvc:CartesianChart.Series>
            <lvc:CartesianChart.AxisX>
                <lvc:Axis MinValue="{Binding Min, Mode=TwoWay}" 
                          MaxValue="{Binding Max, Mode=TwoWay}"
                          PreviewRangeChanged="Axis_OnPreviewRangeChanged"/>
            </lvc:CartesianChart.AxisX>
        </lvc:CartesianChart>

**Comment by ysjiang4869** [comment]
@beto-rodriguez 
Actually,I don't think  this method can run success; there is some problem: if you pan the chart to right side or left(not right in center)，then you can't see all values just use zoom, you must pan the chart to center.

Finally I find out another way 
```csharp
private bool limitMin=false, limitMax = false;
private void Ax_PreviewRangeChanged(LiveCharts.Events.PreviewRangeChangedEventArgs e)
{
    // I use begintime and endtime and limited min and max
    limitMax = e.PreviewMaxValue > endtime.Ticks;
    limitMin = e.PreviewMinValue < begintime.Ticks;          
}

private void Ax_RangeChanged(LiveCharts.Events.RangeChangedEventArgs eventArgs)
{
    Axis ax = (Axis)eventArgs.Axis;
    if (limitMax) ax.MaxValue = endtime.Ticks;
    if (limitMin) ax.MinValue = begintime.Ticks;                      
}
```

Bind those two method to your axis. 
Anyway, thanks for @beto-rodriguez 's hint

**Comment by hukjin** [comment]
> @beto-rodriguez Actually,I don't think this method can run success; there is some problem: if you pan the chart to right side or left(not right in center)，then you can't see all values just use zoom, you must pan the chart to center.
> 
> Finally I find out another way
> 
> ```cs
> private bool limitMin=false, limitMax = false;
> private void Ax_PreviewRangeChanged(LiveCharts.Events.PreviewRangeChangedEventArgs e)
> {
>     // I use begintime and endtime and limited min and max
>     limitMax = e.PreviewMaxValue > endtime.Ticks;
>     limitMin = e.PreviewMinValue < begintime.Ticks;          
> }
> 
> private void Ax_RangeChanged(LiveCharts.Events.RangeChangedEventArgs eventArgs)
> {
>     Axis ax = (Axis)eventArgs.Axis;
>     if (limitMax) ax.MaxValue = endtime.Ticks;
>     if (limitMin) ax.MinValue = begintime.Ticks;                      
> }
> ```
> 
> Bind those two method to your axis. Anyway, thanks for @beto-rodriguez 's hint

i have a same issue.
what is endtime.ticks and begintime.ticks? could you explain more detail?
