### ISSUE TITLE
Why 8000 points are very slow

### ISSUE THREAD

**Issue by visualczm** [beto-rodriguez/Live-Charts#509]
using LiveCharts;
using LiveCharts.WinForms;
using LiveCharts.Wpf;
using LiveCharts.Defaults;

Values = new ChartValues<double> { double[]},

**Comment by beto-rodriguez** [comment]
There are many things you can do to improve performance in the library

https://lvcharts.net/App/examples/v1/wpf/Performance%20Tips
https://lvcharts.net/App/examples/v1/wpf/Constant%20Changes%20II

Let me know if this is not enough

**Comment by visualczm** [comment]
Thank you for your help.

var cv = new ChartValues<double>();
cv.AddRange(temporalCv);      this is  invalid...
 

but Install-Package LiveCharts.Geared 
//or you can also
var cv = temporalCv.AsGearedValues(); this is ok. 


Installing the Geared Values package is not free `?

**Comment by enghatmido** [comment]
I want answer of slow data point for 500 point

**Comment by enghatmido** [comment]
add range for observe point is invalid

**Comment by enghatmido** [comment]
@beto-rodriguez could you please help me??? 
the slow data point for 500 point zooming and panning
 I made the following but still slow 
      cartesianChart1.DisableAnimations = true;
            cartesianChart1.Hoverable = false;
            cartesianChart1.DataTooltip = null;
