### ISSUE TITLE
LineSeries fill not used

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#51]
I set the stroke and fill for a line series in a bar chart.

    <lc:BarChart.Series>
        <lc:BarSeries PrimaryValues="{Binding MetricData}" Title="{Binding MetricName}"/>
        <lc:LineSeries PrimaryValues="{Binding GoalData}" Title="{Binding MetricName}"
                       Stroke="Green" Fill="Transparent"/>
    </lc:BarChart.Series>

This is the chart I get:

![croppercapture 2](https://cloud.githubusercontent.com/assets/2676804/11633411/af3946c2-9cd0-11e5-9dce-79883c4273cf.png)

**Comment by beto-rodriguez** [comment]
I will fix this, I just merged your Pull request but I haven't had time to apply it to all charts, by now you can use the AreaOpacity property of a line serie, set it to zero to make it invisible.

**Comment by VictorOdukoya** [comment]
Hi Alberto,

I want to change the areas opacity of a line serie, but there is no such "AreaOpacity" property you mentioned. I know I can change the Fill property, but that would require me to assign colors to each series on my own. I'm trying to get the layout of a [Stacked Area](https://lvcharts.net/App/examples/v1/wpf/Stacked%20Area) just like in the screenshot, but without them actually stacking on top of each other.

**Comment by Blogrammer** [comment]
> Hi Alberto,
> 
> I want to change the areas opacity of a line serie, but there is no such "AreaOpacity" property you mentioned. I know I can change the Fill property, but that would require me to assign colors to each series on my own. I'm trying to get the layout of a [Stacked Area](https://lvcharts.net/App/examples/v1/wpf/Stacked%20Area) just like in the screenshot, but without them actually stacking on top of each other.

You could set the opacity of a `SolidColorBrush` and assign it to the Fill property.

**C#:**  
`Fill = new SolidColorBrush() { Opacity = 0.15, Color = Brushes.Red.Color }`

**XAML:** 
`<lvc:LineSeries.Background>
        <SolidColorBrush 
            Color="{DynamicResource {x:Static SystemColors.HighlightColorKey}}"
            Opacity="0.5" />
 </lvc:LineSeries.Background>`
