### ISSUE TITLE
Hiding Axes [Question]

### ISSUE THREAD

**Issue by rneurink** [beto-rodriguez/Live-Charts#510]
Hi,

First off these charts are amazing and working really well.

I've got a question regarding the visibility of the axes. 
In the object explorer on the site [Link](https://lvcharts.net/App/documentation/beta/wpf/LiveCharts-Wpf-Axis) there's no reference of a visibility property. However in visual studio intellisence has the property listed. This may be because of the inherritance of the UIElement. 

My question is: **Is there a way to hide an Axis?**
This may be with the visibility property or another method.

**Comment by beto-rodriguez** [comment]
Hi

Your guess is right, `Visibility ` property  comes from `FrameworkElement` but the axis is divided in 2 different elements:

Use `Axis.ShowLabels` to hide the labels.
Use Axis.Separator.IsEnabled to hide the separators in the axis.

**Comment by rneurink** [comment]
Thanks for the quick respone.

**Comment by kbehren** [comment]
Hi,

I know this has already been closed but I'm kind of stuck at this point.

I have multiple axes and want to hide one axis completely when it is disabled.
With the tip here I can hide the Labels but not the title.
Is it possible to hide it or do i need some code behind which I'm trying to avoid for mvvm reasons.

Any suggestions welcome.
