### ISSUE TITLE
Need comments in all examples

### ISSUE THREAD

**Issue by TechCowboy** [beto-rodriguez/Live-Charts#513]
#### How to reproduce?

You might think your code examples are obvious and require no comments, but they are not.

Most people would not have hard coded numbers in their programs; why do you think these are good examples? You should be showing best practices.  How to add single and groups of numbers.

```
SeriesCollection = new SeriesCollection
{
    new LineSeries
    {
        Values = new ChartValues<double> { 3, 5, 7, 4 }
    },
    new ColumnSeries                
    {
        Values = new ChartValues<decimal> { 5, 6, 2, 7 }
    }
};
```
#### Extra notes

It's unclear if examples that feature 'LiveCharts.Geared' can only be produced with gears.
Since it says gears is optional.

Performance tips shows how to add a range of numbers, but the code doesn't work.

```
var temporalCv = new double[1000];
 
for (var i = 0; i < 1000; i++){
    temporalCv[i] = 5;
}
 
var cv = new ChartValues<double>();
cv.AddRange(temporalCv);
```

**Comment by beto-rodriguez** [comment]
Thanks for the feed back, the Geared banner will be updated soon to clarify why it exist and what are the diferencies between the regular LiveCharts package.

The geared version doesn't a new way to display series, it only contains a new set of series with a better performance and a points virtualizer (GearedValues).

About documentation, I agree it can be better, time will make this happen, but feel free to contribute and edit the things that you think they could be better, the site provides an easy way to do it

I am closing this for now, I hope this clarifies your issue.

![image](https://cloud.githubusercontent.com/assets/10853349/24690193/2feb62e6-1980-11e7-8514-388a64d44b6b.png)
