### ISSUE TITLE
the AxisX does not update

### ISSUE THREAD

**Issue by a516117636** [beto-rodriguez/Live-Charts#514]
for example,I draw a LineSeries whose AxisX start from 2013-01-01 to 2013-01-08,then I use SeriesCollection.Clear();Chart.AxisX.Clear(). Finally I draw the LineSeries from 2013-01-02 to 2013-01-09,but the AxisX start from 0 to 7,not 2013-01-02 to 2013-01-09.How to update the the AxisX?

**Comment by beto-rodriguez** [comment]
Hi

With the given information I am not sure what could be causing your issue, I created a small test to verify this, and it works properly, notice `Chart.AxisX.Clear() ` should not be necessary

Any input is appreciated.

    public class VieweModel
    {
        private int i;

        public VieweModel()
        {
            ChartValues = GetPoints().AsChartValues();
            Update = new RelayCommand(() =>
            {
                ChartValues.Clear();
                ChartValues.AddRange(GetPoints());
            });
        }

        public ChartValues<ObservablePoint> ChartValues { get; set; }
        public ICommand Update { get; set; }


        public ObservablePoint[] GetPoints()
        {
            var r = new Random();

            var pts = new ObservablePoint[10];

            for (var j = 0; j < 10; j++)
            {
                pts[j] = new ObservablePoint(i++, r.Next(0,10));
            }

            return pts;
        }
    }

    <Grid>
        <wpf:CartesianChart>
            <wpf:CartesianChart.Series>
                <wpf:LineSeries Values="{Binding ChartValues}"></wpf:LineSeries>
            </wpf:CartesianChart.Series>
        </wpf:CartesianChart>
        <Button VerticalAlignment="Top" HorizontalAlignment="Right" Command="{Binding Update}">Update</Button>
    </Grid>
