### ISSUE TITLE
windows 7 Zoom not working? 

### ISSUE THREAD

**Issue by visualczm** [beto-rodriguez/Live-Charts#515]
chart1 =new LiveCharts.WinForms.CartesianChart();//創建對象

chart1.Series = new SeriesCollection()
{
new GLineSeries
 {
   .......
};
};
chart1.Zoom = ZoomingOptions.X;  window10 is OK

**Comment by beto-rodriguez** [comment]
You are right, the focus of the control is lost in Win7, as an alternative for 0.9.5 and lower, you can use the DataClick or MouseEnter event to bring the focus back:

     private void cartesianChart1_DataClick(object sender, ChartPoint chartPoint)
        {
            cartesianChart1.Focus();
        }

**Comment by beto-rodriguez** [comment]
The referenced commit implements this workaround for default, this will be included since version 0.9.6

Thanks for the report

**Comment by visualczm** [comment]
can you  be updated to nuget, easy to work

Thank you very much
