### ISSUE TITLE
hide DataTooltip and labels

### ISSUE THREAD

**Issue by Stakhmi4** [beto-rodriguez/Live-Charts#516]
#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.5</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10/7</td>
</tr>
</table>

Hi. How i can hide DataTooltip and labels  (numbers 8 and 42 in image)?
my code:

        <lvc:PieChart Name="Chart" Grid.Row="1" Series="{Binding SeriesCollection}"
                      StartingRotationAngle="0"
                      HoverPushOut="0"
                      InnerRadius="100" Margin="0 15"
                      lvc:DataClick="Chart_OnDataClick"
                      SeriesColors="{Binding ColorsCollection}"
                      >
            
        </lvc:PieChart>
    

![1](https://cloud.githubusercontent.com/assets/10836966/24603728/a239c5c0-186a-11e7-8234-4c3bb26dce50.png)

Thanks

**Comment by rusanov-vladimir** [comment]
You can set  `DataTooltip = "{x:Null}"` on PieChart and `DataLabels="False"` on PieSeries.

**Comment by beto-rodriguez** [comment]
@rusanov-vladimir is right, this is the way, let us know if this does not fixes your issue.

I am closing this for now, thanks!

**Comment by Stakhmi4** [comment]
Thanks
