### ISSUE TITLE
Hover doesn't work right on mixed charts

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#52]
When adding a line series to a bar chart as the first series in the collection, the mouse-over only works on the line chart.  It doesn't respond to the mouse being over one of the bars.

With the mouse near the line series point on the bar the mouse is over:

![croppercapture 2](https://cloud.githubusercontent.com/assets/2676804/11633593/c6921f96-9cd1-11e5-933d-805cb9829499.png)

With the mouse closer to a line series point for another bar, but still over the same bar:

![croppercapture 3](https://cloud.githubusercontent.com/assets/2676804/11633607/da84f276-9cd1-11e5-9796-00a0e674629b.png)

**Comment by beto-rodriguez** [comment]
Thank you for reporting this issue, when you Apply the AreaOpacity to zero this will work as you want, I already know about this issue but did not reported it,  will fix it as soon as possible, to fix this I will place invisible bars over all series, so this always works

**Comment by beto-rodriguez** [comment]
Last commit should solve both #51 and #52 Thanks @gregsdennis for reporting
