### ISSUE TITLE
GeoMap can not be viewed

### ISSUE THREAD

**Issue by Clarke937** [beto-rodriguez/Live-Charts#528]
![geomap](https://cloud.githubusercontent.com/assets/12832931/25191461/f0349b72-24ec-11e7-8aee-cf8e387dc32f.PNG)
--------------------------------------------------------------
![geomap2](https://cloud.githubusercontent.com/assets/12832931/25191585/51a4d07a-24ed-11e7-9f34-383f10bd9131.PNG)

Hello, I try to use GeoMap Graphic, but only show a blue screen. Only copy and paste the example in the documentation page but not working. Please Help me!

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>Last</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 7 Professional</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Please ensure your file build action is set to content:

![untitled](https://cloud.githubusercontent.com/assets/10853349/25309452/1e0a159c-2793-11e7-8ea9-13535e9ea5ac.png)

**Comment by Clarke937** [comment]
@beto-rodriguez Ok i did the change but it still does not show the map

**Comment by maggima** [comment]
@Clarke937 Hi, I had the same problem and it was caused by a bad path in my XAML.

Double check the folder(s) created at your binaries level. You need to reference the path to your XML map (copied at build) relative to your .exe file in `/bin/Debug` or `/bin/Release`

**Comment by Clarke937** [comment]
@maggima Thank but it was not the route, I was missing the datacontext in the xml

**Comment by kembels** [comment]
Hi, 
I have the same issue. I am trying to display the usercontrol "GeoHeatMap" in my MainWindow:

`<Window x:Class="HeatMap.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:HeatMap"
        mc:Ignorable="d"
        Title="MainWindow" Height="1000" Width="1000">
    <Grid x:Name="PPMRFQGRID" Height="450">
        <StackPanel Name="PPMRFQ" Orientation="Vertical"/>
    </Grid>
</Window>`

My code behind is:

`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace HeatMap
{
    /// <summary>
    /// Interaktionslogik für MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void PPMRFQGRID_Loaded(object sender, RoutedEventArgs e)
        {
            GeoHeatMap geoheat = new GeoHeatMap();
            PPMRFQ.Children.Add(geoheat);
        }
    }
}`

The Usercontrol "GeoHeatMap" is as following:

`<UserControl x:Class="HeatMap.GeoHeatMap"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:HeatMap"
             xmlns:lvc="clr-namespace:LiveCharts.Wpf;assembly=LiveCharts.Wpf"
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300" 
             d:DataContext="{d:DesignInstance local:GeoHeatMap}">
    <Grid>
        <lvc:GeoMap HeatMap="{Binding Values}" Source="Maps/World.xml" LanguagePack="{Binding LanguagePack}" />
    </Grid>
</UserControl>`

However, when starting the app, the only thing that appears is a blank MainWindow, all in white, and nothing else.

Can someone help?

Thank you.
