### ISSUE TITLE
Unable to add text before *Series databinding.

### ISSUE THREAD

**Issue by cglmrfreeman** [beto-rodriguez/Live-Charts#53]
Instead of "Title Value" in the IndexedToolTip, there's no option to add binding text before the Value.

For example:

"High Temp 90 degrees" could be changed to "High Temp Dry 90 degrees", or "Low Temp 30 degrees" could be "Low Temp Frosty 30 degrees".

If there is some kind of overload I can use to add a descriptor before the value, that would be fantastic but I'm not quite sure how to implement it. I'd suffice with the tooltip, but the tooltip doesn't seem to display at all.

**Comment by beto-rodriguez** [comment]
How about this: https://github.com/beto-rodriguez/Live-Charts/wiki/0.4-Labels

```c#
LineChart.PrimaryAxis.LabelFormatter = value => "High Temp Dry " + value + " degrees"
```

**Comment by cglmrfreeman** [comment]
The problem with that is if along the same line the temperature drop from 90 degrees to 30 degrees, the label will be formatted as "High Temp Dry 30 degrees". I'd like to be able to insert my own text with data binding along with the values along the axis.

**Comment by beto-rodriguez** [comment]
I am sorry, but I think I don´t understand what you are trying to do. can you please explain me better so I can help you.

**Comment by cglmrfreeman** [comment]
![graph example](https://cloud.githubusercontent.com/assets/9744201/11844507/001b7e80-a3c4-11e5-8b05-0fe6b3102e0e.png)
Perhaps this graph with my previous charting software will best illustrate what I am trying to do. I want to add text along with the value to specify who/what that value belongs to.

Specifically, in this example, users tip a user, the graph will show how much they were tipped and when they were tipped but can not show who they were tipped by.

**Comment by beto-rodriguez** [comment]
You can add a custom Tooltip, setting the DataToolTip property of a chart, I am not sure if that will be enough to solve your case, I will work on this and some other issues now, another important point I see, is that right now this library does not supports negatives in bar charts,

**Comment by beto-rodriguez** [comment]
I am courious about how did you achive that in the library you plot that, right now the solutions I see are not easy, or I dont like them.

**Comment by cglmrfreeman** [comment]
Currently I use a pointvalueevent with ZedGraph, which basically lets me know what index number the bar I am currently hovering over is and I pull the data from a List of string using that index: http://zedgraph.sourceforge.net/documentation/html/E_ZedGraph_ZedGraphControl_PointValueEvent.htm

**Comment by beto-rodriguez** [comment]
OK, one moment and I will make a commit to solve this.

**Comment by beto-rodriguez** [comment]
I have to say that that I don't really like the solution I committed, I think it is not easy enough, can you please let me know what you think? I will describe the steps to make it work, I also added an example in test project, to Custom Bar Chart example it contains a custom tooltip now.

First of all this is the legend that explains the problem I solved https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/BarExamples/CustomBar.xaml.cs#L17

1) Create a custom tooltip class that inherits from IndexedTooltip

An indexed Tooltip DataContext will be injected when mouse is over a point with an `IndexedTooltipData` Instance (https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/Tooltip/IndexedTooltipData.cs)

It will expouses some useful properties, 

Property  | Description
------------- | -------------
Series  | The Series that Data point belongs to.
Index | The index of the Series in the Series collection of the chart.
Point | The data point values (x,y)
Value | Y value formatted.

here is the XAML https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/BarExamples/CustomTooltip.xaml
here is the Code behind https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/BarExamples/CustomTooltip.xaml.cs

2) Now you need to set that new tooltip to a chart, really simple, just this https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/BarExamples/CustomBar.xaml#L22 and load your extra data to that tooltip https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/BarExamples/CustomBar.xaml.cs#L24


And that's it, The tricky part happens here https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/BarExamples/CustomTooltip.xaml#L34
The multivalue converter injects IndexedTooltipData and ExtraData so you can play with those properties. the corverter just maps them here https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/BarExamples/CustomTooltip.xaml.cs#L30

If I were clear enough this is what you read in this line

```c#
var maxSales = values[0] as decimal[][];
var data = values[1] as IndexedTooltipData;
return maxSales[data.Index][(int) data.Point.X].ToString("C");
//max sales is an array containing the max price sold by Maria, John and Erick.
//maxSales[data.Index]  =>  gets the arraf of Maria, John or Erick according to data.Index
//[(int) data.Point.X]  => data.Point contains the value of the current point, the X property is the index.
```

**Comment by cglmrfreeman** [comment]
Alright, after a little trickiness, I got the example working, and if I understand correctly, I need to handle my strings inside MyConverter? Right now by default through your example it only passes numeric values, correct?

**Comment by beto-rodriguez** [comment]
Yes, this is a tricky solution, it should work, but I am not really happywitht this, does this solves your problem? do you have an idea to make it easier?

**Comment by beto-rodriguez** [comment]
@cglmrfreeman to your question in this example yes, but ExtraData Property is IEnumerable you can pass any object you need.

**Comment by beto-rodriguez** [comment]
@cglmrfreeman I have pulled a lot of code that will make this easy now, here is an example
https://github.com/beto-rodriguez/Live-Charts/tree/master/ChartsTest/Line%20Examples/Mvvm
