### ISSUE TITLE
Tooltip control should have "hovered over series" knowledge

### ISSUE THREAD

**Issue by barbeque** [beto-rodriguez/Live-Charts#532]
The WPF tooltip control base (`IChartTooltip`) does not have a field for exposing the "currently hovered-over" series (the thicker-lined one in CartesianChart).

Right now, I have an elaborate workaround that involves detecting the DataHover event/command and shoving it into a subclass of `IChartTooltip`, but this breaks encapsulation.

If the `IChartTooltip` `TooltipData` exposed the series that is being hovered over this would become a lot easier.

The default LiveCharts tooltip control should also be updated to use this so that the hovered-over series title is displayed in bold.

Again, thanks for the awesome library and for the fast turnaround in gitter on this issue.

**Comment by beto-rodriguez** [comment]
Thanks for the report, since version 0.9.7 you will be able to find which series fired the tooltip at `IChartTooltip.Data.SenderSeries` this should make it easier.

Regards!

**Comment by harshasns** [comment]
Is the SenderSeries label set to FontWeight Bold by default? If so, am not able to see the Bold font. Am I missing something here? Sorry if this is a simple question. Am kind of newbie.
