### ISSUE TITLE
Scrollable Chart (WinForms) BindingAssistant

### ISSUE THREAD

**Issue by lmgoncalves** [beto-rodriguez/Live-Charts#539]
Hi,

I'm having problems to compile the Scrollable Chart (WinForms) example.

Code on https://lvcharts.net/App/examples/v1/wf/Scrollable (WinForms).
Code Behind line 73 BindingAssistant is not found.

Regards,
Luciano

**Comment by beto-rodriguez** [comment]
Hi

Sorry for that, you are right, here is the source code of that sample

https://github.com/Live-Charts/GearedExamples/tree/master/WinForms/ScrollableChart

Documentation will have a full review soon.

**Comment by lmgoncalves** [comment]
Hi,

Thank you for your prompt reply.
It is working fine with the source code.

Thanks.
Luciano
