### ISSUE TITLE
Small amendment to DataLabelViewModel

### ISSUE THREAD

**Issue by Enigmatrix** [beto-rodriguez/Live-Charts#542]
#### The problem

The current [DataLabel](https://github.com/beto-rodriguez/Live-Charts/blob/f61444bfa9eccba53b8113172e2c800e7b4bcb10/Core/DataLabelViewModel.cs) only allows accessing the Instance. While this is mostly sufficient, I was hoping it could store a ChartPoint instead, so that we can get more info such as Participation. The change is minor, mostly changing the code ```point.Instance``` to ```point``` in each of the series and a bit of refactoring. [e.g.](https://github.com/beto-rodriguez/Live-Charts/blob/f61444bfa9eccba53b8113172e2c800e7b4bcb10/WpfView/ColumnSeries.cs#L194) for ColumnSeries.

Thanks,
Enigmatrix

**Comment by beto-rodriguez** [comment]
I like it, previous commit should add this feature and will be included since 0.9.7, plus you can also access the instance from a ChartPoint.
