### ISSUE TITLE
Solid Gauge does not update?

### ISSUE THREAD

**Issue by DBenS** [beto-rodriguez/Live-Charts#543]
#### How to reproduce?

I'm using LiveCharts in a Winforms .NET 4.5 application .

I have a FOR NEXT loop running in few seconds (like 5 to 9 seconds) and I'm trying to update my 360-GAUGE from 0 to 100% - but GAUGE does not update itself during the entire loop, only after the routine ends - in other words, it reflects only the last value.

Even if I put a Thread.Sleep timer to avoid overlap the control, the GAUGE does not update itself.
I put REFRESH, UPDATE and all sort of commands to force its redraw - no success at all.

I tried to simulate it in a button: whenever clicked, I had a random value (0-100) and everything worked ok; the GAUGE reflected all random values on each button.click event.

How can I utilize GAUGE within a loop or any other automated routine to display its evolution?
How can I force GAUGE to update its value and graphics?

I'm using GAUGES 0.9.6 running VB.NET in Visual Studio 2017.

Thanks!

**Comment by briggsyuk** [comment]
Can you provide some code to show your issue?

**Comment by DBenS** [comment]
Thanks for the advise.

You're right: I'm trying to utilize it as a kind of progress bar and to test its functionality I just coded a FOR-NEXT loop as shown below:


**In the Load event of the Winform**

`Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load


        Gauge.Uses360Mode = True
        Gauge.ResumeLayout
        Gauge.Refresh

        Gauge.Uses360Mode = True
        Gauge.To = 100
        Gauge.From = 1
        Gauge.FromColor = System.Windows.Media.Color.FromArgb(255, 255, 0, 0)
        Gauge.FromColor = System.Windows.Media.Color.FromArgb(255, 0, 255, 0)
        Gauge.BackColorTransparent = True

end Sub
`

The above code sets the Gauge control normally...
To simulate the "progress" of any process, I tried the following: 


```
Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click

        For T As Integer = 1 To 100
            Gauge.Value = Int(Rnd(1) * 100)
            Gauge.Refresh
            Threading.Thread.Sleep(500)
            Application.DoEvents
        Next

 End Sub
```

Using this simple code (with OR withou any timer among the FOR-NEXT interactions) the Gauge just show the LAST value.

But, **if I remove the FOR-NEXT, leaving only the Gauge.Value command**, each time I press that button the Gauge responds immediately.

```
Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
            Gauge.Value = Int(Rnd(1) * 100)
            Gauge.Refresh
 End Sub
```

Thank you for any advice about it.

**Comment by briggsyuk** [comment]
Hi DBenS,

You are  putting the UI process to sleep, which will stop the UI from updating!
you will need to use a BackgroundWorker which has progress events.
https://msdn.microsoft.com/en-us/library/system.componentmodel.backgroundworker(v=vs.110).aspx

Best of luck!

**Comment by DBenS** [comment]
Hi briggsyuk!

Thank you for the answer - I will try in some moment of today.
I will keep you in touch.

Have a good day and week. See you soon...

**Comment by DBenS** [comment]
Hi @briggsyuk !

Yes, if I put the entire routine within a Backgroundworker the control functions properly.
But in a real world we cannot run all routines in different, parallel or background Threads... If I even try to call BackgroundWorker just to update the Gauge control (using the e.Percent as the index), I get no success at all.  

See the sample:

```
Private Sub startAsyncButton_Click(ByVal sender As System.Object, _
    ByVal e As System.EventArgs) Handles startAsyncButton.Click

    For T as integer = 1 to 100        
        If backgroundWorker1.IsBusy <> True Then
            backgroundWorker1.RunWorkerAsync(T)
        End If
    Next

End Sub

Private Sub backgroundWorker1_DoWork(ByVal sender As System.Object, _
    ByVal e As DoWorkEventArgs) Handles backgroundWorker1.DoWork

        Dim worker As BackgroundWorker = CType(sender, BackgroundWorker)
        If worker.CancellationPending = True
            e.Cancel = True
            exit for
         Else
            worker.ReportProgress(e.Argument)
        End If

End Sub

Private Sub backgroundWorker1_ProgressChanged(ByVal sender As System.Object, _
    ByVal e As ProgressChangedEventArgs) Handles backgroundWorker1.ProgressChanged

        Gauge.Value= (e.ProgressPercentage)

End Sub


```
In other words: the Gauge needs to have an exclusive thread to run accordingly. Any update performed in the same thread or even in a background thread does not function.

An I saw also that the graphic plot is very delayed in relation to the percentage-text within it.
When I have the 100% percentage text, the chart is ploting almost at 80% ...

**Anyway, thank you very much for efforts in producing these controls and the time spent in my question.**
Kindest regards,
David
