### ISSUE TITLE
Area limit and double.Nan causes a wrong plot

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#553]
#### How to reproduce?

Create a line series that uses both features, double.Nan, to split the points, and set an AreaLimit different to default:

#### Extra notes

![](https://files.gitter.im/beto-rodriguez/Live-Charts/Tmzf/image.png)

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.6</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*</td>
</tr>
<tr>
    <td>Windows</td>
    <td>*</td>
</tr>
</table>

**Comment by PixelHero** [comment]
No, I'm just inept.  No longer an issue in the most recent version.

**Comment by beto-rodriguez** [comment]
@PixelHero confirmed that this is not an issue in the latest nuget version.

Thanks!
