### ISSUE TITLE
How to add legend in code not xaml?

### ISSUE THREAD

**Issue by mazvis00** [beto-rodriguez/Live-Charts#56]
How do I add legend in c# not in xaml into a PieChart? I trying to add it in winforms, any pointers how to do it?

**Comment by beto-rodriguez** [comment]
What do you mean with a legend?

**Comment by mazvis00** [comment]
https://www.google.ie/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=chart%20legend

I got it sorted, I have added another ElementHost:
PieSeriesViewer pieSeriesV = elementHost1.Child as PieSeriesViewer;
and then: 
pieSeriesV.Series = pieChart.Series;

Also I had to put values for pieChart.Labels

**Comment by beto-rodriguez** [comment]
I am glad you find the solution, documentation for Winforms is poor now, I hope to extend it as soon as possible.
