### ISSUE TITLE
Change Color that GLineSeries is Plotted In After it is Created

### ISSUE THREAD

**Issue by jalsck** [beto-rodriguez/Live-Charts#574]
I'd like to be able to change the color that a GLineSeries is plotted in depending on user actions. Apologies if this can already be done. I haven't been able to work out how.

Thanks,

James

**Comment by beto-rodriguez** [comment]
Setting the Stroke property should be enough:

     if (condition) {
         series.Stroke = Brushes.Red;
     }

If you are using WPF, you can also use triggers, then you can have a cleaner layout, check out this sample, it changes the Fill brush according to a condition:

https://lvcharts.net/App/examples/v1/wpf/Constant%20Changes%20II

Let me know if this is not enough, I will close this for now.

**Comment by jalsck** [comment]
Apologies, I thought I had tried casting to a GLineSeries and couldn't do it. The following worked perfectly.

        // Highlights the selected scenario
        private void HighlightScenarioEquityCurve(int prevScenario, int selectedScenario)
        {
            // If the same scenario has been reselected then exit
            if (prevScenario == selectedScenario)
            {
                return;
            }

            // If the previously selected scenario was not the model equity curve
            if (prevScenario != 0)
            {
                // Change the color back to dark gray
                ((GLineSeries)SeriesCollection[prevScenario]).Stroke = Brushes.DarkGray;

                // Reduce the thickness of the line
                ((GLineSeries)SeriesCollection[selectedScenario]).StrokeThickness = 1;

                // Assign the original z-index to the series
                Panel.SetZIndex((GLineSeries)SeriesCollection[prevScenario], prevScenario);
            }

            // If the newly selected scenario is not the scenario for the original model
            if (selectedScenario != 0)
            {
                // Change the color to orange
                ((GLineSeries)SeriesCollection[selectedScenario]).Stroke = Brushes.Orange;

                // Make the selected equity curve a big thicker
                ((GLineSeries)SeriesCollection[selectedScenario]).StrokeThickness = 2;

                // Assign a z-index value higher than any of the other series z-index values
                Panel.SetZIndex((GLineSeries)SeriesCollection[selectedScenario], SeriesCollection.Count + 1);
            }
        }

Thanks,

James
