### ISSUE TITLE
Spelling mistake in error message

### ISSUE THREAD

**Issue by joshnorton** [beto-rodriguez/Live-Charts#577]
The Exception message "One axis has an invalid range, it is or it is tends to zero, please ensure your axis has a valid range" generated by the CartesianChartCore.cs implementation has a spelling mistake. The second instance of the word **is** should be removed.

It should read "One axis has an invalid range, it is or it **~~is~~** tends to zero, please ensure your axis has a valid range".

#### I am using

<table>
<tr>
    <td>LiveCharts WPF</td>
    <td>0.9.6</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Fixed with #578
