### ISSUE TITLE
Labels got hidden when binding values change

### ISSUE THREAD

**Issue by mgth** [beto-rodriguez/Live-Charts#58]
When I try to bind labels for secondary axis, its got hidden at first update.

**Comment by beto-rodriguez** [comment]
Thanks for reporting, Yes, I have not found why this happens, but we are working on this already in #54, I will close this, this will be solved when #54 is done.

Thanks

**Comment by mgth** [comment]
Ok, sorry I did not understand it was the same issue.
Thank you for the fast reply.

Mathieu

**Comment by beto-rodriguez** [comment]
@mgth #54 is already solved.
