### ISSUE TITLE
Issues with MVVM Caliburn Integration

### ISSUE THREAD

**Issue by xanth** [beto-rodriguez/Live-Charts#59]
I love the look of this library but I've had a few issues with it.
So that I could make it pickup my series defined in my view model I had to comment out the [series initialization in the Charts class](https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/Charts/Chart.cs#L103). And now I've come across a new issue where it throws ```"can't set chart property twice."``` when navigating back to a page with a Live-Chart on it, any idea how to solve this?

**Comment by beto-rodriguez** [comment]
I have no experience with Caliburn, I would like to see more of your code, so I can try to help you to use this library, the exception you get I wrote it, and it is just for security reasons, https://github.com/beto-rodriguez/Live-Charts/blob/162da16a499ee538fd70d2c2a2059f456f2de589/Charts/Series/Series.cs#L124

To avoid unexpected bugs I force this exception, it should never be necesary to set Serie.Chart property. 

plase let me know more about your code so we can build a better and easier integreation with mvvm.

Thanks

**Comment by gregsdennis** [comment]
Just as some additional input, we're using a modified Caliburn.Micro for our MVVM framework, and I haven't seen any problems.  We're still playing with an older version though.

I saw this a couple times, too, but it was while I was editing the library code.

To solve the issue presented here, I also suggest a bit of context needs to be shared.

**Comment by xanth** [comment]
Thanks for the speedy response! The Live Chart is within a template like so:
```xaml
<Style TargetType="ItemsControl" x:Key="GraphContainer" BasedOn="{StaticResource GenericTileContainer}">
    <Setter Property="ItemTemplate">
        <Setter.Value>
            <DataTemplate DataType="controls:GraphModel">
                <StackPanel>
                    <TextBlock Text="{Binding Path=Text}"  Style="{StaticResource ConfigHeaderRow}" />
                    <Grid>
                        <Grid.RowDefinitions>
                            <RowDefinition MaxHeight="250" MinHeight="150" Height="150"/>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition MinWidth="250" />
                        </Grid.ColumnDefinitions>

                        <LiveCharts:LineChart Margin="0,0,15,0" Padding="0" Series="{Binding Datasets}" />
                    </Grid>
                </StackPanel>
            </DataTemplate>
        </Setter.Value>
    </Setter>
    <Setter Property="ItemsPanel">
        <Setter.Value>
            <ItemsPanelTemplate>
                <StackPanel Orientation="Vertical" />
            </ItemsPanelTemplate>
        </Setter.Value>
    </Setter>
</Style>
```

The GraphTiles are a ```ObservableCollection<IGraphModel>```

and the template is referenced like so:

```xaml
<ItemsControl x:Name="GraphTiles" Style="{StaticResource GraphContainer}" ></ItemsControl>
```

And the GraphModel looks like so:

```cs
public class GraphModel: PropertyChangedBase, IGraphModel
    {
        private ObservableCollection<Series> datasets;

        public GraphModel(string text, Action<IGraphModel> value)
        {
            Text = text;
            LoadValue = value;        

            Datasets = new ObservableCollection<Series>();
        }

        public string Text { get; }

        public string XAxisLabel { get; }

        public string YAxisLabel { get; }

        public string Subtitle { get; set; }

        public ObservableCollection<Series> Datasets
        {
            get
            {
                return datasets;
            }
            set
            {
                if (Equals(value, datasets)) return;
                datasets = value;
                NotifyOfPropertyChange(() => Datasets);
            }
        }

        public void UpdateDatasets(IReadOnlyList<object> updates)
        {
            var events = updates as IReadOnlyList<EventDto>;
            if (events == null)
                throw new ArgumentException(@"Please supply a IReadOnlyList<EventDto> as a IReadOnlyList<object>", nameof(updates));
            if(Datasets.Count > 0)
                Datasets.Clear();

            Datasets.Add(new LineSeries
            {
                Title = "Datapoints1",
                PrimaryValues = new ObservableCollection<double>(Datapoints.Select(x => (double)x.Datapoints1).ToList())
            });
            Datasets.Add(new LineSeries
            {
                Title = "Datapoints2",
                PrimaryValues = new ObservableCollection<double>(Datapoints.Select(x => (double)x.Datapoints2a).ToList())
            });
        }
    }
```

and is instantiated like so:
```cs
return new GraphModel(x.Title, model =>
  {
      x.RefreshValue();
      model.UpdateDatasets((IReadOnlyList<EventDto>)x.Value);
  });
```

Because the updating the dataset requires a DB call its done in the background like so
```cs
Application.Current.Dispatcher.Invoke(
    DispatcherPriority.Background,
    new Action(() =>
    {
        tile.LoadValue(tile);
        tile.LoadingDone();
    })
);
```

I hope I haven't given you too much context, and again thanks for your time.

**Comment by xanth** [comment]
Also I thought I should add: This is the only line in the library that I've needed to modify:
```cs
protected Chart(){
			...
			//Series = new ObservableCollection<Series>();
			...
}
```

**Comment by beto-rodriguez** [comment]
I will try to reacreate this, so we can fix it

**Comment by beto-rodriguez** [comment]
you are right that line is braking a lot of things, I am working on it now.

**Comment by exally** [comment]
Thanks @beto-rodriguez !!

**Comment by beto-rodriguez** [comment]
Ok, after some undesired bugs, bindings and Mvvm should now work much better, I fixed many bugs, I also added a "complex" Mvvm example so we can always test this in future versions

https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/Line%20Examples/LazyDataLine.xaml.cs

Also for simple charts you will need to change a little bit the sintax. for more info go to

https://github.com/beto-rodriguez/Live-Charts/releases/tag/0.5.9

Plase let me know if this works for you

Thanks

**Comment by beto-rodriguez** [comment]
P.S. starting the library helps to bring more traffic, contributors and also improvements :)
