### ISSUE TITLE
GeoMap does not load into designer in Windows Forms

### ISSUE THREAD

**Issue by mutisama** [beto-rodriguez/Live-Charts#598]
I'm currently using winforms to create my program. I loaded all of the components from .dll file without a problem. I tried using AngularGauge, CartesianChart and the other components , they are working fine but whenever I try to load GeoMap into my form, it gives the error below(but somehow it still load the component). 

![geomap-error](https://user-images.githubusercontent.com/16900879/28105782-ab63a206-66e9-11e7-8bcb-6880add2db84.png)

I might be skipping some step with the installation but I could not figure out how this is specific to geomaps.

![livecharts-components](https://user-images.githubusercontent.com/16900879/28106104-2ab356e0-66eb-11e7-8070-3e94948b3746.png)

The version I currently use can be seen below.

![livecharts-versions](https://user-images.githubusercontent.com/16900879/28106056-ea5d5adc-66ea-11e7-90f6-329f923d6a3c.png)

**Comment by mutisama** [comment]
Although I am still having this problem, geomap is now working after I corrected the path of worldmap.xml.

**Comment by beto-rodriguez** [comment]
Lets keep a track of this issue in #628 

I am closing this for now, feel free to reply this, or create a new issue if necessary.

**Comment by Cerdjee4** [comment]
How exactly do I edit the path of worldmap.xml? I've been trying but I haven't been able to find out where to do it.
