### ISSUE TITLE
Column Series With different color fill in same series?

### ISSUE THREAD

**Issue by twinkle1110** [beto-rodriguez/Live-Charts#602]
Can we provide different colors to columns in a single column series.?

**Comment by bzavaczki** [comment]
I was just about to post about this same thing. Is this already possible? It would be nice to be able to change colors within the same series. I am specifically trying to do it for a RowSeries

**Comment by twinkle1110** [comment]
Any Update??

**Comment by twinkle1110** [comment]
Did you get any solution for the same ?

**Comment by beto-rodriguez** [comment]
You have a couple of options:

1. Use a different series for every point:

```xml
<lvc:CartesianChart>
     <lvc:CartesianChart.Series>
            <lvc:ColumnSeries Fill="Red" />
            <lvc;ColumnSeries Fill="Blue" />
````

You can use set them using a mapper, for example: https://lvcharts.net/App/examples/v1/wpf/Point%20State

**Comment by atjbat** [comment]
I try gantt but i don't undrstand how color different row in rowseries ,anyone have solution?
