### ISSUE TITLE
XY Plotting from List Values

### ISSUE THREAD

**Issue by jordthenord** [beto-rodriguez/Live-Charts#618]
I have four lists (x1List, y1List, x2List, y2List) which hold 1000 values each, i want to plot these lists as x & y values using LiveCharts.
i understand how to plot the y values using;

                var Collection1 = new SeriesCollection

        new LineSeries
        {
            Title = "Series1",
            Values = y1List.AsChartValues(),
            PointGeometry = null
        },

        new LineSeries
        {
            Title = "Series2",
            Values = y2List.AsChartValues(),
            PointGeometry = null
        },
I don't understand how to apply the x values to their respective series.
I'm new to c# so apologies if this is something simple i am overlooking.

**Comment by beto-rodriguez** [comment]
A useful read:

https://lvcharts.net/App/examples/v1/wpf/Types%20and%20Configuration

The code you show is not enough for me to determine what the library is doing, the library sets a mapper according to the type of the value you are plotting.

In the case of a `LineSeries` when you are plotting primitive types, the `Y` coordinate is the value you passed, and the `X` coordinate will be the index of the value in the array, this is by default, if you need to set both values, then try:

    Values = new ChartValues<ObservablePoint>() {
         new ObservablePoint (10, 5) // x = 10, Y = 5
     }

I am closing this for now, feel free to reply this, or create a new issue if necessary.

**Comment by adeshtc** [comment]
HI,

This library development is in progress. Since i can see last release was in 2017 in nuget.
& one more question

How this library is better than OxyPlot library.

**Comment by krrrambambuli** [comment]
> A useful read:
> 
> https://lvcharts.net/App/examples/v1/wpf/Types%20and%20Configuration
> 
> The code you show is not enough for me to determine what the library is doing, the library sets a mapper according to the type of the value you are plotting.
> 
> In the case of a `LineSeries` when you are plotting primitive types, the `Y` coordinate is the value you passed, and the `X` coordinate will be the index of the value in the array, this is by default, if you need to set both values, then try:
> 
> ```
> Values = new ChartValues<ObservablePoint>() {
>      new ObservablePoint (10, 5) // x = 10, Y = 5
>  }

How can I add several thousands of values in an easy way to the series (with X and Y coordinate)? With the solution (new ObservablePoint (10, 5)) it takes a long time to add 100.000 values to the chart with a loop for every point. Is it possible to add two list for x and y values in the series?
