### ISSUE TITLE
shifting origin

### ISSUE THREAD

**Issue by lality-OS** [beto-rodriguez/Live-Charts#620]
how to shift origin to center instead of corner

**Comment by beto-rodriguez** [comment]
Hi

If you mean the X=0 and Y=0 coordinate, then this could be done automatically by the chart when there are positive and negative values in the chart, or when you force the `CartesianChart.AxisY/AxisxX.MinValue`,  and `CartesianChart.AxisY/AxisxX.MaxValue`.

I am closing this for now, feel free to reply this, or create a new issue if necessary.
