### ISSUE TITLE
SerieViewer converting ObservableCollection to IEnumerable

### ISSUE THREAD

**Issue by MaxDeg** [beto-rodriguez/Live-Charts#63]
Hi,

There is a little bug in the SerieConverter used by the SerieViewer. The converter transform the ObservableCollection<Series> to an IEnumerable<SerieStandin> (by the use of Select).

Here is the code
```csharp
var series = value as IEnumerable<Series>;
if (series != null)
    return series.Select(s => new SerieStandin
        {
            Title = s.Title,
            Stroke = s.Stroke,
            Fill = s.Fill
        });

var serie = value as Series;
if (serie != null)
    return new SerieStandin
        {
            Title = serie.Title,
            Stroke = serie.Stroke,
            Fill = serie.Fill
        };

return value;
```

And a quick/dirty fix I used to confirm the issue:
```csharp
var results = new ObservableCollection<SerieStandin>();
(value as ObservableCollection<Series>).CollectionChanged += (s, e) =>
{
    if (e.Action == System.Collections.Specialized.NotifyCollectionChangedAction.Add)
    {
        foreach (Series item in e.NewItems)
            results.Add(new SerieStandin
            {
                Title = item.Title,
                Stroke = item.Stroke,
                Fill = item.Fill
            });
    }
};

return results;
```

By the way your library is really cool. Good job ;)

Max.

**Comment by beto-rodriguez** [comment]
Thank you for reporting I will take a look and fix as soon as possible.

P.S. starting the library helps to bring more traffic, contributors and also improvements :)

**Comment by beto-rodriguez** [comment]
This is already fixed, but instead of suggested solution, now "viewers" are drawn everytime data changes, now instead of creating another object (`SeriesViewer`), you just set the `LegendProperty` to a position here is an example 

https://github.com/beto-rodriguez/Live-Charts/blob/master/ChartsTest/BarExamples/Basic/BasicBar.xaml#L22
