### ISSUE TITLE
Null pointer exception when setting the visibility to Hidden of VerticalStackedAreaSeries.

### ISSUE THREAD

**Issue by stephanusmostert** [beto-rodriguez/Live-Charts#630]
#### How to reproduce?

This crashes with an null pointer exception, on the Visibility setter:
var presentationSeries = new VerticalStackedAreaSeries
                {
                    Title = series.Name,
                    Values = new ChartValues<KeyValuePair<double, double>>(series.Items),                    
                    LineSmoothness = 0,
                    StackMode = StackMode.Percentage,
                    Visibility = System.Windows.Visibility.Hidden
                };

#### Extra notes

My expectation is that it should just hide the series if part of a SeriesCollection and not crash.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
The visibility type is `System.Windows.UIElement.Visibility`

I am closing this for now, feel free to reply this, or create a new issue if necessary.
