### ISSUE TITLE
Adding a big axis MaxValue with a small step makes the app freeze while drawing Separators

### ISSUE THREAD

**Issue by GeorgeTG** [beto-rodriguez/Live-Charts#631]
I am not sure if this is considered a bug.
More like user error, but I think the effect of it could be somehow mitigated.

After downloading the library source and debugging for some hours I found out that
a bug in my code was setting my X axis MaxValue to a big number,
and the whole application became frozen.

#### How to reproduce?
Set MaxValue to a huge number (~6.7 * 10^7), and Separator step to a value like 100000 on some axis.(e.g X)
The code is obviously stuck in the following loop:
`for (var i = l; i <= TopLimit - (EvaluatesUnitWidth ? u : 0); i += S)
                {
                     LastSeparator = i;
                    DrawSeparator(i, tolerance, currentMargin, f, source);
                }`
[Line:318](https://github.com/beto-rodriguez/Live-Charts/blob/master/Core/AxisCore.cs#L318)
Maybe have a hard limit on how many Separators should be drawn or some  way to warn the user since it is known beforehand that millions of separators will be drawn?

#### Extra notes
After 60 seconds I get this exception:
`
Managed Debugging Assistant 'ContextSwitchDeadlock' : 'The CLR has been unable to transition from COM context 0x102e2d0 to COM context 0x102e218 for 60 seconds. The thread that owns the destination context/apartment is most likely either doing a non pumping wait or processing a very long running operation without pumping Windows messages. This situation generally has a negative performance impact and may even lead to the application becoming non responsive or memory usage accumulating continually over time. To avoid this problem, all single threaded apartment (STA) threads should use pumping wait primitives (such as CoWaitForMultipleHandles) and routinely pump messages during long running operations.'
`

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Notice this behavior is documented:

> Warning! Be careful when forcing steps, it could result in horrible performance issues, if not used correctly, for example if your current range of values goes from 0 to 1,000 and you set the step to 1 the chart will draw 1,000 separators too.

At:
https://lvcharts.net/App/examples/v1/wpf/Axes

I am closing this for now, feel free to reply this, or create a new issue if necessary.
