### ISSUE TITLE
how to specify the color of give slice of doughnut chart 

### ISSUE THREAD

**Issue by 1AmAditya** [beto-rodriguez/Live-Charts#633]
I need to chance the color of slices in my doughnut chart but it is picking the random color.

below is my xml

    <lvc:PieChart  Series="{Binding DeviceStateSeriesCollection}" 
                                           LegendLocation="Right"
                                           InnerRadius="{StaticResource InnerRadius}"
                                           Margin="-155,8,0,8"
                                       
                                       >
                            
                            <lvc:PieChart.ChartLegend>
                                <lvc:DefaultLegend 
                                           VerticalAlignment="Center" 
                                           HorizontalAlignment="Center"
                                           Margin="-220,0,0,0"
                                           Foreground="Black" 
                                           BulletSize="{StaticResource BulletSize}" >
                                </lvc:DefaultLegend>
                            </lvc:PieChart.ChartLegend>
                        </lvc:PieChart>

**Comment by jaylange** [comment]
Hi 1AmAditya.... I have just completed this task however you will have to forgive me as my programming skills are low (I am an Engineer that has worked my way through the problem)...  Below is the way I am setting a color to a 'slice' of the pie:

var ps = (PieSeries)seriesCollectionPieA[r];
var mystring = "FF00FF00";
SolidColorBrush myBrush = new SolidColorBrush((Color)ColorConverter.ConvertFromString(mystring));
ps.Fill = myBrush;


Our development is very much in the c# area and not xaml.

I hope that this assists in some way.

**Comment by beto-rodriguez** [comment]
Setting the `Series.Fill`/`Series.Stroke` properties will allows you to customize this.

I am closing this for now, feel free to reply this, or create a new issue if necessary.
