### ISSUE TITLE
Broken cartesianchart

### ISSUE THREAD

**Issue by faststare** [beto-rodriguez/Live-Charts#645]
I cloned your repo and imported to ironpython. But GetDesignerCollection method is not found. I used windows 10

My code is

class FinancialExample(Form):
def __init__(self):
    cc = Livecharts.Winforms.CartesianChart()

Basically i got error in cc variable due to missing method in your library which is GetDesignerCollection method. I tried to trackback in ChartesianChart.cs but I cant find any GetDesignerCollection on it.

**Comment by beto-rodriguez** [comment]
I am not really sure about this issue, this could be caused by IronPyton.

**Comment by beto-rodriguez** [comment]
I am closing this for now, feel free to reply this, or create a new issue if necessary.
