### ISSUE TITLE
Last label on the X Axis is not displaying correctly

### ISSUE THREAD

**Issue by carag-matthew** [beto-rodriguez/Live-Charts#646]
#### How to reproduce?

Suppose the following SeriesCollection:

``` C#
public List<double> DataPoints { get; private set; }
public Func<double, string> XFormatter { get; private set; }
public SeriesCollection SeriesCollection { get; private set; }
...
public SomeConstructor()
{
    SeriesCollection = new SeriesCollection
    {
        new LineSeries
        {
             Title = "My Series",
             Values = new ChartValues<double>(DataPoints),
             PointGeometrySize = 0
        }
    };

    XFormatter = value => (value / DataPoints.Count) * 100 + "%";
}
```
Where the DataPoints is a List<double> containing 10000 points.

The following is an excerpt from the UserControl:
``` xaml
<lvc:CartesianChart Series="{Binding SeriesCollection}" LegendLocation="Right" Name="cartesianChart" Background="#FFF" >
    <lvc:CartesianChart.AxisY>
        <lvc:Axis Title="{Binding YAxisLabel}" />
    </lvc:CartesianChart.AxisY>
    <lvc:CartesianChart.AxisX>
        <!-- THIS AXIS DOES NOT SHOW THE LAST 100% MARK -->
        <lvc:Axis Title="Cumulative Probability" LabelFormatter="{Binding XFormatter}" />
    </lvc:CartesianChart.AxisX>
</lvc:CartesianChart>
```
#### Extra notes

The last "100%" label is not present in the chart. The chart is supposed to be a LineChart.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>v0.9.7 (NuGet)</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10</td>
</tr>
</table>

**Comment by carag-matthew** [comment]
Possible off by one error. May not be an actual bug for Live Charts

**Comment by beto-rodriguez** [comment]
Notice you can customize also the `CartesianChart.AxisX.Separator.Step`, `CartesianChart.AxisX.MinValue` and `CartesianChart.AxisX.MaxValue`, when you don't the library decides this parameters, according to your data in the chart, if you don't agree with the current algorithm, feel free to set this values according to your needs.

I am closing this for now, feel free to reply this, or create a new issue if necessary.
