### ISSUE TITLE
NuGet packages aren't signed

### ISSUE THREAD

**Issue by Trass3r** [beto-rodriguez/Live-Charts#65]
resulting in CS8002 and errors later on.

**Comment by JoelElkhorne** [comment]
First let me say the samples look fantastic :)
Having said that attempting to use the NuGet packages means my WPF project cannot use them :(
This is a shame because they look great - looks like I'm stuck with the hard to work with (let alone understand) Dynamic Data Display :(

**Comment by beto-rodriguez** [comment]
@JoelElkhorne I think the problem you have is that right now examples do not match with 0.5.10 which is the latest nugget package, I am sorry for the inconvenience but right now examples are for 0.6 that will be a much better version but is not in nugget yet, right now I recommend you to wait for 0.6 (maybe today or tomorrow is ready), or see examples in this link that might work for 0.5.10, sorry again this project is in a beta version and right now we are making important improvements.
https://github.com/beto-rodriguez/Live-Charts/tree/46a3b8bcd132c9459c3d17de679d5dee376713a0/ChartsTest

@Trass3r I can´t see this error, and I have not find exactly how to sign this package, I would like to sign it for 0.6 but I am not sure how yet.

**Comment by gregsdennis** [comment]
I think you want this.

https://msdn.microsoft.com/en-us/library/xc31ft41(v=vs.110).aspx

Follow the instructions for Visual Studio.  I did this for my projects.

**Comment by beto-rodriguez** [comment]
@gregsdennis Thank you very much then 0.6 will be signed

**Comment by beto-rodriguez** [comment]
I already signed the package, please let me know if this is not working in 0.6
