### ISSUE TITLE
Element is already the child of another element [UWP] UWP 0.8.0

### ISSUE THREAD

**Issue by Quico20** [beto-rodriguez/Live-Charts#657]
Instructions: replace text surrounded by '*' with your case, please delete this line.

#### How to reproduce?

I'm using template 10 as my ViewModelBase for the MVVM pattern and tried to use your cartesianchart it load great as soon as I navigate to the page where my CartesianChart BasicColumn sample is and it loads great, this is the code I've tried using your sample and then using just xaml:

`<Page.DataContext>
        <vm:BasicColumnViewModel x:Name="ViewModel"/>
    </Page.DataContext>

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
          x:Name="Container">
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"/>
                <RowDefinition Height="*"/>
            </Grid.RowDefinitions>
            <Button x:Name="GoBack"
                    Tapped="{x:Bind ViewModel.GoBack}"
                    Content="GoBack"
                    HorizontalContentAlignment="Center"
                    HorizontalAlignment="Center"/>
            
            <lvc:CartesianChart x:Name="CartesianChart"
                                LegendLocation="Left"
                                Grid.Row="1"
                                Height="600">
                <lvc:CartesianChart.Series>
                    <lvc:ColumnSeries Title="2015"
                                      Values="{x:Bind ViewModel.Values}"/>
                </lvc:CartesianChart.Series>
                <lvc:CartesianChart.AxisX>
                    <lvc:Axis Title="Salesman"
                              Labels="{x:Bind ViewModel.Labels}"/>                    
                </lvc:CartesianChart.AxisX>
                <lvc:CartesianChart.AxisY>
                    <lvc:Axis Title="Sold Apps"
                              LabelFormatter="{x:Bind ViewModel.Formatter}"/>
                </lvc:CartesianChart.AxisY>
            </lvc:CartesianChart>
        </Grid>
    </Grid>`

I do have comments on the line of code that you put on your past sample and tried to add values using xaml code without depending on a series collection but apparently you chart is bound to the page and as soon as I navigate back or to another page the app gets broken.

my view model looks like this:

`public class BasicColumnViewModel : ViewModelBase
    {
        public BasicColumnViewModel()
        {
            //SeriesCollection = new SeriesCollection
            //{
            //    new ColumnSeries
            //    {
            //        Title = "2015",
            //        Values = new ChartValues<double> { 10, 50, 39, 50 }
            //    }
            //};

            //adding series will update and animate the chart automatically
            //SeriesCollection.Add(new ColumnSeries
            //{
            //    Title = "2016",
            //    Values = new ChartValues<double> { 11, 56, 42 }
            //});

            //also adding values updates and animates the chart automatically
            //SeriesCollection[1].Values.Add(48d);

            Labels = new[] { "Maria", "Susan", "Charles", "Frida" };
            Formatter = value => value.ToString("N");
        }

        public SeriesCollection SeriesCollection { get; set; }
        public string[] Labels { get; set; }
        public Func<double, string> Formatter { get; set; }

        public IChartValues Values { get; set; } = new ChartValues<double>(new double[] { 10d, 50d, 39d, 47d });

        public void GoBack()
        {
            NavigationService.NavigateAsync(typeof(Views.MainPage));
        }
    }`

#### Extra notes

This is an important issue because it makes the library unusable while using MVVM Pattern, I dont know if you test this without MVVM but most xaml apps ppl use MVVM pattern for data binding and code reuse.

Hopefully you could correct it soon, I'll keep testing all your charts, so far pircharts and doughnut charts works well.

this Issue has also been reported at #547 Issue.

**Comment by beto-rodriguez** [comment]
The UWP version is not up to date with the WPF version, this issue should be gone in a future update to the UWP package.

**Comment by beto-rodriguez** [comment]
I am closing this, lets track this issue with the issue you referenced.

**Comment by bidasknakayama** [comment]
When will you update / fix this issue ?
v 0.8.0 has still this problem.

**Comment by Dima-dima** [comment]
Hello, use Uwp 0.8.0, and have the same problem (Element is already the child of another element) while Series try bind to SeriesCollection.

<lvc:CartesianChart x:Name="chartPanel"
Visibility="Collapsed"
Series="{x:Bind SeriesCollection,Mode=OneWay}"
HorizontalAlignment="Left">

Please, need any issue
