### ISSUE TITLE
wpf view lines curves

### ISSUE THREAD

**Issue by berjk** [beto-rodriguez/Live-Charts#658]
When cartesian chart creates line serie at graph, it connects dots with curves as polynomial graph. but i want it to do like linear graph. When i zoom the graph, there is a curve between every dot. Instead of curve ,how can i draw linear lines?

**Comment by danieldrm** [comment]
You can set the LineSmoothness property of your LineSeries to 0.

The documentation says this about this property: "Gets or sets line smoothness, this property goes from 0 to 1, use 0 to draw straight lines, 1 really curved lines"

**Comment by beto-rodriguez** [comment]
Yes, as  @danieldrm said use the `LineSmooothness` property, as shown here:

Notice there is a series with straight lines:

https://lvcharts.net/App/examples/v1/wpf/Basic%20Line%20Chart

I am closing this for now, feel free to reply this, or create a new issue if necessary.
