### ISSUE TITLE
Donut PieChart InnerRadius and Resizing

### ISSUE THREAD

**Issue by muffmolch** [beto-rodriguez/Live-Charts#659]
How can I achieve InnerRadius property n % instead f 50% thus the donut scales correctly at resizung the control?

#### How to reproduce?

Create pie chart donut (with inner radius e.g.  50 ) control inside a resizable WinForm, set the *Dock* poperty to *Fill*, start the app and rize the Window. The InnerRadius stays at 50.. 

#### I am using

<table>
<tr>
    <td>Version</td>
    <td>0.9.7</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by Phexyaa** [comment]
You could bind the radius property and then try to calculate it based on actual width and or height of the window or chart. Maybe not the best way, but first thing that came to mind.

**Comment by muffmolch** [comment]
in fact that's what I am doing right now (inside die resize event of tha control). Just wanted to know if there's a more elegant solution

**Comment by Phexyaa** [comment]
I'm not sure that there is, but I suggest doing the math right in the Get{} of the inner radius property instead of an event to help clean things up a bit.
Not sure if that works for you, but other than that not really sure.

**Comment by muffmolch** [comment]
Ok, but how to bind the *InnerRadius* of the chart property to something other?

**Comment by Phexyaa** [comment]
Xaml:
InnerRadius="{Binding InRadius}"

Code behind property:
Public double InRadius 
{
Get { return ( your math) }
}

**Comment by muffmolch** [comment]
ah, I see. But I'm using WinForms... And thus the only way to change the get property is to change the LiveChart sources :-)

**Comment by Phexyaa** [comment]
Oh sorry I should have asked. I haven't done anything in winforms for a while.

**Comment by beto-rodriguez** [comment]
For this there are no plans to support this, I think setting this manually, is easy enough.

I am closing this for now, feel free to reply this, or create a new issue if necessary.

**Comment by Brains** [comment]
I've got it working somehow with this binding:
```xml
InnerRadius="{Binding ActualWidth, RelativeSource={RelativeSource Self}, 
                                        Converter={converters:Reduce Factor=0.3}}"
```
For some charts `ActualWidth` works well, for others `ActualHeight` is better. I guess need to use `MultiBinding` here, will try it later.
