### ISSUE TITLE
I cannot figure out how to enable separtor lines for the x and y axes. There are labels, but no separator lines. How do I put them on my Cartesian Chart?

### ISSUE THREAD

**Issue by sherfey1** [beto-rodriguez/Live-Charts#660]
Instructions: replace text surrounded by '*' with your case, please delete this line.

#### How to reproduce?

*Explain how we can get this issue, if you created a repo with the issue, please add the link, blank if you are submitting a suggestion or improvement*

#### Extra notes

*Explain what you expect, feedback, images or anything you consider necessary*

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>*your Live-Charts version here*</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*your .net version here*</td>
</tr>
<tr>
    <td>Windows</td>
    <td>*your windows version here*</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
There are several samples in the site, and repo.

Check out this one, here I disabled the X separators, while the Y separators are dashed.

https://lvcharts.net/App/examples/v1/wpf/Solid%20Color

    <lvc:CartesianChart Name="Chart" Grid.Row="1" Grid.Column="0" Grid.ColumnSpan="2" Margin="15">
            <lvc:CartesianChart.Series>
                <lvc:LineSeries Values="{Binding Values}" LineSmoothness="1" StrokeThickness="10" 
                                DataLabels="True" FontSize="20" Foreground="#6B303030"
                                Stroke="White" Fill="Transparent" PointGeometrySize="0"/>
            </lvc:CartesianChart.Series>
            <lvc:CartesianChart.AxisX>
                <lvc:Axis IsEnabled="False" ShowLabels="False"/>
            </lvc:CartesianChart.AxisX>
            <lvc:CartesianChart.AxisY>
                <lvc:Axis Foreground="White" FontSize="14">
                    <lvc:Axis.Separator>
                        <lvc:Separator StrokeThickness="1" Stroke="#8EFFFFFF" StrokeDashArray="8" Step="100" />
                    </lvc:Axis.Separator>
                </lvc:Axis>
            </lvc:CartesianChart.AxisY>
        </lvc:CartesianChart>


I am closing this for now, feel free to reply this, or create a new issue if necessary.
