### ISSUE TITLE
Data Tool Tip Null to Enabled

### ISSUE THREAD

**Issue by sherfey1** [beto-rodriguez/Live-Charts#661]
In my cartesian chart, I must set datatooltip to null or else the chart performs too slow. Although I want to add a feature that allows me to pause my chart and enable the data tool tip functions so that I can use my mouse cursor to view the values on my chart. Is there a way to do so?

**Comment by beto-rodriguez** [comment]
The open source library has a slower performance, yes disabling the responsive areas in the chart (tooltips and the DataClick event) allows the chart to behaves better.

This applies form versions < 1.0, the next version of the library should improve this, in this will be no longer necessary.

I'll document it when the release is ready.

I am closing this for now, feel free to reply this, or create a new issue if necessary.
