### ISSUE TITLE
realtime data updates not working

### ISSUE THREAD

**Issue by Trass3r** [beto-rodriguez/Live-Charts#67]
Also using Caliburn like in #59 and a binding similar to the BindingLine example, i.e. directly mapping PrimaryValues="{Binding SomePropertyOfTypeObservableCollection}".
But data updates don't trigger a redraw. One can trigger it "manually" by zooming.

Same thing in the example, it does not update the plot unless you switch to another plot and back:
 ```diff
diff --git a/ChartsTest/Line Examples/Binding/BindingLine.xaml.cs b/ChartsTest/Line Examples/Binding/BindingLine.xaml.cs
index 105510e..6f13e00 100644
--- a/ChartsTest/Line Examples/Binding/BindingLine.xaml.cs	
+++ b/ChartsTest/Line Examples/Binding/BindingLine.xaml.cs	
@@ -1,5 +1,7 @@
-﻿using System.Collections.ObjectModel;
+﻿using System;
+using System.Collections.ObjectModel;
 using System.Windows;
+using System.Windows.Threading;
 
 namespace ChartsTest.Line_Examples
 {
@@ -15,7 +17,16 @@ namespace ChartsTest.Line_Examples
                 SecondSeries = new ObservableCollection<double> { 7, 3, 4, 1, 5, 6, 8, 5, 1, 3 }
             };
             DataContext = this;
-        }
+
+			var rnd = new Random();
+			var dispatcherTimer = new DispatcherTimer();
+			dispatcherTimer.Tick += (sender, eargs) =>
+			{
+				ViewModel.FirstSeries.Add(rnd.NextDouble()*8);
+			};
+			dispatcherTimer.Interval = new TimeSpan(0, 0, 1);
+			dispatcherTimer.Start();
+		}
 
         private void CleanLine_OnLoaded(object sender, RoutedEventArgs e)
         {
```

**Comment by beto-rodriguez** [comment]
taking a look at it, it should be a small bug because of recent big update, one moment please.

**Comment by Trass3r** [comment]
Not sure, I couldn't get realtime display to work before those mvvm changes either.
It looks like it ends up once at https://github.com/beto-rodriguez/Live-Charts/blob/38b8e0d67/Charts/Charts/Chart.cs#L819 during InitializeComponent() call but with an empty PrimaryValues collection as there is no binding yet.

**Comment by beto-rodriguez** [comment]
Thanks for pointing that that helps alot. I am on it now

**Comment by beto-rodriguez** [comment]
Please let me know if this works for you, I am updating all examples so we can test all charts before publishing next release (as soon as I test them all)

**Comment by beto-rodriguez** [comment]
this fixes this issue and opens one more, I am working on it

**Comment by Trass3r** [comment]
Yes now it updates correctly!
Thanks for the quick fix!

**Comment by Trass3r** [comment]
Yes now it updates correctly!
Thanks for the quick fix!

Edit: Though performance doesn't seem to be too good when having multiple line series that update continuously. Need to look into this tomorrow.

**Comment by beto-rodriguez** [comment]
@Trass3r performance will be improved after 0.6, 0.5 was for Mvvm I think we already solved that really good, I got some ideas writen already to improve performance, and they really work, I think we should work on that now. I will close this issue since I already tested it in all charts and is working like a charm, also updated examples, with what you needed in this issue.

Thanks agan!

**Comment by Trass3r** [comment]
I see. One question will be how to efficiently provide sample values for multiple series so it would only do 1 "update" at each time step. Also in that case the time-axis values could be shared in theory.
Saw your comment that it "waits for the data to stop changing within 100ms" which limits the update frequency quite a lot. I think it would be better to let the user deal with this by having something like an ObservableCollection<StructWithAllSeriesValues> instead of multiple separate collections for each line.

**Comment by Trass3r** [comment]
hmm while the LineSeries works ScatterSeries still has problems with realtime updates.

**Comment by beto-rodriguez** [comment]
I will test ScatterSeries, I think I don´t get your idea, I limited the updated frecuency because everytime data changes the current scale of the chart might change so it will need to be drawn atgain, in previous versions this was not implemented and chart used to fired every time you made a change.

**Comment by Trass3r** [comment]
Well I guessed this "waiting" feature is there cause x and y values are distributed among multiple ObservableCollection properties so you would get 2 or more update notifications per time-step.
That could be turned into just 1 by putting everything in a structure. Opened another ticket for that idea.
