### ISSUE TITLE
Primary axis won't top going below 0

### ISSUE THREAD

**Issue by lrmills85** [beto-rodriguez/Live-Charts#7]
I am trying to use a line or bar chart to graph a total number of tickets. In this case it doesn't make sense to plot anything below zero but I am unable to control it.

**Comment by beto-rodriguez** [comment]
Thank you very much for helping, I am just about to comit a fix for this, the idea was to create a nullable double property to set max and min values of an Axis, so the default value will be null and will have the behavior it has now, but if you specify those properties, charts will use the value you stablished. I also edited MainWindows xaml in the test project with this new property, you can find an exmaple in bar chart, or scatter chart. Im clossing this issue. If this does not solves your problem please report the issue and we can work to fix it. Thank you very much!.

**Comment by lrmills85** [comment]
Excellent job man! I love these charts. Some of the best ones I have seen.

Roger
