### ISSUE TITLE
logarithmic axes support

### ISSUE THREAD

**Issue by Trass3r** [beto-rodriguez/Live-Charts#72]
I don't need it yet but should be taken into account when (re-)designing like in #68 I think.
If it already works somehow even better ;)

**Comment by beto-rodriguez** [comment]
this should be done easly with 0.6, will work on it after 0.6 is ready

**Comment by beto-rodriguez** [comment]
with 0.6 this is really easy, here is an example 

https://github.com/beto-rodriguez/Live-Charts/tree/master/ChartsTest/Scatter%20Examples/logarithmicScatter

I will update example as soon as possible to display labels without log, I will use a label formatter for this.
