### ISSUE TITLE
Refresh Static Series, Variable Value

### ISSUE THREAD

**Issue by b1u3w01f** [beto-rodriguez/Live-Charts#74]
Perhaps just something you haven't had time to document or something I'm just not seeing but in my situation I cant find a 'clean' way to refresh my chart.

The simplest chart tracks income and spend as below:

![barchart](https://cloud.githubusercontent.com/assets/13273975/12488527/ec5f1854-c063-11e5-916a-ad74071290f1.PNG)

The data for that is pulled from an sql database and sits in two variables, income and spend. The chart will not increase in bars like the examples in the lvc project, the only thing thing that will change is the variables will increase or decrease.

The Series is set up as:

```C#
public void fillseries()
        {
            IncomeSeries = new SeriesCollection(new SeriesConfiguration<IncSpendData>().Y(data => data.Value))
            {
                new BarSeries
                {
                    Title = "Income",
                    Values = new ChartValues<IncSpendData>
                    {
                        new IncSpendData { Value =  income }
                    }
                },
                new BarSeries
                {
                    Title = "Spend",
                    Values = new ChartValues<IncSpendData>
                    {
                        new IncSpendData { Value =  spend }
                    }
                }
            };
        }
```
And the only way I have been able to figure out to update without errors is:

```C#
public void AddSpend()
        {
            income = income + 1000;
            spend = spend + 1000;
            IncomeSeries.RemoveAt(0);
            IncomeSeries.RemoveAt(0);
            IncomeSeries.Add(new BarSeries
            {
                Title = "Income",
                Values = new ChartValues<IncSpendData>
                {
                    new IncSpendData { Value = income }
                }
            });
            IncomeSeries.Add(new BarSeries
            {
                Title = "Spend",
                Values = new ChartValues<IncSpendData>
                {
                    new IncSpendData { Value = spend }
                }
            });
        }
```

Which is a pretty bad solution all round.

(The +1000 is just a test to demonstrate)

**Comment by beto-rodriguez** [comment]
you are right, for now live charts only redraw when a collection changes, you force the change with this apporach, I need some time to think about this, I am working on a possible solution

**Comment by beto-rodriguez** [comment]
Ok so I think this should be the solution, maybe we can make something to make it smaller, please see https://github.com/beto-rodriguez/Live-Charts/tree/master/ChartsTest/BarExamples/UsingObservableChartPoint
the idea was to keep everything as it is and if you need to notify that a chart point changed then you would implement `IObservableChartPoint` in your `IncSpendData` class this is similar to what you normally do with wpf when using `INotifyPropertyChanged`. what do you think?

**Comment by b1u3w01f** [comment]
I get the IObservableChartPoint logic and that does match with normal WPF principles. The example you wrote seems to be mixing up MVVM principles which I assume you only did for speed but would need to make sure it does fit with MVVM. Theres a lot of additional work at the front end with your Collection = StoresCollection example which unfortunately makes a simpler implementation more dificult for the user to implement which isnt ideal.

The ideal situation, which I appreciate is easy to say, would be to edit/update a listed item in the collection information series and then either using a notify or forcing a chart redraw. Unfortunately how that can be done I do not know.

**Comment by beto-rodriguez** [comment]
I will solve it as soon as possible, I have to say that the image you show at the top of this post is bugged by #75, it is already fixed with last commit but have not published nuget package yet

**Comment by b1u3w01f** [comment]
No worries and cheers for the great work. Yeah I noticed too and saw the bug reference after; minor issue for the moment and assumed it would be picked up down the line; got a stack of my own bugs to sort anyway.

**Comment by AuroraDysis** [comment]
What he said is exactly what I want to say. 

> The example you wrote seems to be mixing up MVVM principles which I assume you only did for speed but would need to make sure it does fit with MVVM.

**Comment by beto-rodriguez** [comment]
@AuroraDysis thats why this issue is still open.

**Comment by AuroraDysis** [comment]
OK, I will close that issue and try to solve this.

**Comment by beto-rodriguez** [comment]
OK now this is clean, in the same link I updated the example, https://github.com/beto-rodriguez/Live-Charts/tree/master/ChartsTest/BarExamples/UsingObservableChartPoint

same logic you implement IObservablePoint, then [LiveCharts detects if T implements IObservablePoint](https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/CoreComponents/ChartValues.cs#L177) if so then LiveCharts attach `ObservableOnValueChanged` to `ValueChanged` and updates your chart.

**Comment by AuroraDysis** [comment]
Sorry, I'm very busy this week. It seemed like Rx.
