### ISSUE TITLE
Nuget Package Download

### ISSUE THREAD

**Issue by serekmt2** [beto-rodriguez/Live-Charts#78]
Hi,

It might not be the case but i can't get the nuget package in visual Studio 2015. Could you let me know is it only an issue i my case or is it something in general? Do you know the solution for that problem?

Thanks,
Michal

**Comment by beto-rodriguez** [comment]
I am using VS 2015, the package has been downloaded close to 1,000 times, can you I can help you but I need more info, what is the error you get and when you get it?

**Comment by serekmt2** [comment]
Just a regular one:


PM> Install-Package LiveCharts
Install-Package : Unable to find package 'LiveCharts'
At line:1 char:1
+ Install-Package LiveCharts
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by serekmt2** [comment]
Do you think it's worth to unzip the nuget and take the dll?

**Comment by beto-rodriguez** [comment]
ensure Package source is nuget.org

![untitled](https://cloud.githubusercontent.com/assets/10853349/12527548/110cd256-c143-11e5-8f42-a774422db6e6.png)

if that is not working then go to solution explorer, right click in references, then Manage NuGet packages then browse for live charts, I am seeing it rigth there here is a print screen 

![image](https://cloud.githubusercontent.com/assets/10853349/12527568/4e070c08-c143-11e5-92e6-1f49d739c16d.png)
