### ISSUE TITLE
Add more charts

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#79]
Live charts is really stable now, fixed many old bugs, it was much easier with 0.6 version. Now it is time to add more charts, if you have a comment or a new chart type please comment this issue.

1) Add negative support to stacked bar, so we can plot this:

![extend stacked bar](https://cloud.githubusercontent.com/assets/10853349/12595224/c0b4a798-c43f-11e5-87e6-a234d74ba8e9.png)

2) Allow scatter chart to add bubbles, if it is not possible then create a new chart type

![extend stacked bar](https://cloud.githubusercontent.com/assets/10853349/12595300/17f1ca0e-c440-11e5-91ee-7c913bfde0f6.png)

3) Gauges

![extend stacked bar](https://cloud.githubusercontent.com/assets/10853349/12595370/7fd12016-c440-11e5-8d7c-08e9837bef8f.png)

4) Spider Web **(Done)**

![extend stacked bar](https://cloud.githubusercontent.com/assets/10853349/12595521/5559fdde-c441-11e5-865a-3d04db8e4402.png)

5) Polar

![extend stacked bar](https://cloud.githubusercontent.com/assets/10853349/12595403/b01ca3d0-c440-11e5-913b-ff0a6ba03ec0.png)

6) Candlestick bar chart

![image](https://cloud.githubusercontent.com/assets/10853349/12595565/9eae0246-c441-11e5-94e6-e890e5d7f396.png)

**Comment by PsykotropyK** [comment]
Hello,

I am very interested by having a candlestick bar chart. If you do so, remember that financial series have gaps between data as financials markets are closed in week ends and out of normal business hours (except the Forex opened 24 hours 5 days a week). Though the representation should ignore those gaps and present it continuously. 

Keep me posted on the implementation :)

Regards,

**Comment by IgorTheRussian** [comment]
@PsykotropyK Totally agreeing with him about the financial series. Really looking forward to it ! Keep up the awesome work !

**Comment by elisechiang** [comment]
candlestick bar chart +1.   Thanks.

**Comment by beto-rodriguez** [comment]
@elisechiang, @PsykotropyK , @IgorTheRussian I am not an expert in financial series, I just added the financial series, I would really like to know your opinion about it, it is already in this repo master

**Comment by elisechiang** [comment]
Has you added the financial series to 0.7.0 alpha ? How do I get it to test ?

**Comment by beto-rodriguez** [comment]
Yes I did, here is a preview(at the end of the gif) you can use 0.7 cloning the repo or downloading the binaries and add the reference to them in your project, but be awere 0.7 is alpha

![0 7 0 series](https://cloud.githubusercontent.com/assets/10853349/15238843/966c5154-18a2-11e6-90ab-2205c67adbb9.gif)

**Comment by elisechiang** [comment]
OK. I see them. But how do I draw the "bar" ? When the close value is more than open value, the "bar" border color and the middle vertical line color maybe is red, and the bar need be filled with light red color. And when the close value is equal to or less than open value, the "bar" border color and the middle vertical line color maybe is green, and the bar need be fill with light green color. If the close value is equal to the open value, there is a "bar" with zero height. These colors are often needed to be customized. Thanks.

**Comment by elisechiang** [comment]
Sorry. I said something wrong before. If the close value is equal to the open value, there is a short horizontal line, not a "bar" with zero height. They are different.

**Comment by rohit3d2003** [comment]
Amazing work! Really like to see the gauges coming through!

**Comment by beto-rodriguez** [comment]
I am closing this issue to release 0.7.0 sooner, the only remaining in this release will be the Polar chart

**Comment by alfarok** [comment]
Hey @beto-rodriguez, did the `Spider Web` ever make it into production?  I see it marked as **done** back in 2016 but don't see any references in the docs.  Great work btw, love LiveCharts!
