### ISSUE TITLE
pie chart

### ISSUE THREAD

**Issue by IGNATIUSLIJO** [beto-rodriguez/Live-Charts#80]
Instead of color is it possible to use image as pie chart filler

**Comment by beto-rodriguez** [comment]
Right now I think this is only possible for all charts but pie chart, I will test commit a solution for this

**Comment by beto-rodriguez** [comment]
This is already supported please see https://github.com/beto-rodriguez/Live-Charts/tree/master/ChartsTest/Pie%20Examples/Custom
