### ISSUE TITLE
Pie chart start angle 

### ISSUE THREAD

**Issue by IGNATIUSLIJO** [beto-rodriguez/Live-Charts#81]
I want pie chart plotting to be started from 90 degree for that i used below code. 

Live:PieSlice RotationAngle="90" 

is it the right way to use. It is not working for me. Kindly guide me to change the starting degree

**Comment by beto-rodriguez** [comment]
No, this is the variable that handles starting angle in a pie series https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/Series/PieSeries.cs#L64 this is not supported right now, as you can see it always starts from the same value. I will improve this as soon as possible.

**Comment by IGNATIUSLIJO** [comment]
Thanks alot for ur kind reply .

**Comment by IGNATIUSLIJO** [comment]
is it possible to override plot method in pieSeries and change the angle? or can you suggest some other solution to make it possible?

**Comment by beto-rodriguez** [comment]
I will add this feature in next release, Right now I am working improving zoom and high perfomance charts, for now you can use Rotate all the control with RotateTranform here is a good example http://www.c-sharpcorner.com/uploadfile/mahesh/rotatetransform-in-wpf/

**Comment by beto-rodriguez** [comment]
you can also override the Plot method meanwhile, but I think its much easier to rotate all the control

**Comment by IGNATIUSLIJO** [comment]
while overriding im not able to access PlotArea ,DataMouseEnter ..how to access those . thank in advance

**Comment by beto-rodriguez** [comment]
You cant because it is internal use Control.ActualHeight and ActualWidth instead, or even better modify it in the same assembly so you can do a pull request and share your code with us :)

**Comment by beto-rodriguez** [comment]
you cant access DataMouseEnter  but you can override the event

**Comment by IGNATIUSLIJO** [comment]
i copied the enitre code and tried to use. but i m getting so many error. I guess i did something wrong. kindly guide me. How can i edit ur code and create assembly . thanks in advance

**Comment by beto-rodriguez** [comment]
1.  Fork this repo, actually you already did.

2. Connect your visual studio to your Fork source and edit directly this file, here you can access PlotArea and DataMouseEnter https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/Series/PieSeries.cs
3. After you have debugged your code, and you are really sure everything is working fine, do a pull request. 

It is actually really simple and that is why gits are amazing.

**Comment by beto-rodriguez** [comment]
Another alternative is to wait for me to add it, Don´t worry I will in 0.6.4 I am already working on it maybe tomorrow is ready

**Comment by IGNATIUSLIJO** [comment]
thanks alot for adding in ur release  ...  :) .. i ll also try from my side

**Comment by IGNATIUSLIJO** [comment]
while debugging i'm always getting \bin\Debug\LiveCharts.dll missing alert . Kindly help me to fix this

**Comment by IGNATIUSLIJO** [comment]
sorry... Now i am able to compile :)  :+1:

**Comment by beto-rodriguez** [comment]
This is already supported with the new property for `PieChart `class `PieRotation`, follow this link for an example

https://github.com/beto-rodriguez/Live-Charts/tree/master/WPFExamples/Pie%20Examples/Custom

P.S. it will be available when I publis 0.6.4 it is almost ready

**Comment by IGNATIUSLIJO** [comment]
i tried the below code for binding colors in pie chart..but chart is always coming with default color.It is working fine with static colors  

xmal:
<LiveCharts:PieSeries Title="Donut1" Values="{Binding ViewModel.FirstSeries}" 
                    				   Brushes="{Binding ViewModel.ColorSeries}">
cs:
  ViewModel = new BindingPieViewModel
            {
                 ColorSeries = new ChartValues<String>{color1,color2 }
            };
