### ISSUE TITLE
Can't draw chart immediately when navigating

### ISSUE THREAD

**Issue by AuroraDysis** [beto-rodriguez/Live-Charts#82]
When I navigate to(use content control)  a usercontrol it can't draw immediately, when I change the window size it will be drawed.

**Comment by beto-rodriguez** [comment]
Hello, Thanks for reporting, I am not able to force this bug with this information can you please show me a part of your code so I can see what is going on, Thanks

**Comment by AuroraDysis** [comment]
I try to make a sample for you, but I failed, it works well. If I success tommorrow, I will reopen this.

**Comment by beto-rodriguez** [comment]
Right now I am building better examples, the problem now is that last weak I made huge changes and I think examples are not clear enough now, I hope in a couple of hours we have better examples

**Comment by AuroraDysis** [comment]
Yes, I agree. And I think the api can be easier to use. Series must be built in STA and I must use the dispather to handle data, it's terrible. Like https://github.com/ailon/amCharts-Quick-Charts, it doesn't have any document and sample, but I can only use five minutes to start, for example
```Xml
 <amq:PieChart Margin="40" DataSource="{Binding Series}" 
                                      TitleMemberPath="Name" 
                                      ValueMemberPath="Total">
                            <amq:PieChart.Brushes>
                                <Brush>GreenYellow</Brush>
                                <Brush>OrangeRed</Brush>
                            </amq:PieChart.Brushes>
</amq:PieChart>
```
I read the sample again and again, use a long time to finish the same effect by LiveCharts. 
I think there are a lot of choices. For instance
```C#
[TitlePropertyAttribute]
public string Title {get;set;}
```
or MemberPath via Reflection or others. I don't know what is best, but I think it should be improve.

**Comment by beto-rodriguez** [comment]
LiveCharts used to be that easy, but then this request came #68, And I everything is more complex now, I love the solution we Implemented but now I need to make that easy again, I am working on it.

**Comment by beto-rodriguez** [comment]
@AuroraDysis please see new examples and update to 0.6.2, thanks for reporting again, this might help a lot. please let me know your opinion
