### ISSUE TITLE
Transparent Background on PieChart

### ISSUE THREAD

**Issue by thomasjoscht** [beto-rodriguez/Live-Charts#85]
Hey, I'm using PieChart with Transparent Background. In this case the slice padding/border will not work. I've encountered that the reason lies on the transparent painting of the slice border which will be then invissible. Is it possible to separate Background and slice border color in a future release? Maybe this requires an enhanced implementation of painting padding/border.

**Comment by beto-rodriguez** [comment]
Hello, thanks for reporting, I am working on pie charts today and will concider this

**Comment by beto-rodriguez** [comment]
You were right this was wrong, now Pie Background is transparent by default and PieSlice stroke is taken from Series.Stroke, default is White

**Comment by beto-rodriguez** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10853349/12801295/2c75192e-caa1-11e5-9610-3fb49acbcd62.png)
