### ISSUE TITLE
pie chart dynamic color

### ISSUE THREAD

**Issue by IGNATIUSLIJO** [beto-rodriguez/Live-Charts#87]
I tried the below code for binding colors in pie chart..but chart is always coming with default colors. It is working fine with static colors. It is failing in below case

xmal:
Brushes="{Binding ViewModel.ColorSeries}">

cs:
String color1 = "#24B6B5";
String color2 = "#26DB7D";
ViewModel = new BindingPieViewModel
{
ColorSeries = new ChartValues<String> { color1,color2 }
};

**Comment by beto-rodriguez** [comment]
Thanks fo reporting wil be supported in 0.6.5

**Comment by beto-rodriguez** [comment]
**Aha!** I see what is going on you are using a wrong syntax I will build an example for this case in a future, Brushes are **not** chart values it is just an array with custom colors (I know pie chart is kind of confusing it jumps from the logic of all the charts, but it is a really different chart) instead try:

```c#
SolidColorBrush color1 = (SolidColorBrush)(new BrushConverter().ConvertFrom("#24B6B5"));
SolidColorBrush color2 = (SolidColorBrush)(new BrushConverter().ConvertFrom("#26DB7D"));
ViewModel = new BindingPieViewModel
{
ColorSeries = new Brush[] { color1,color2 }
};
```

**Comment by beto-rodriguez** [comment]
Please let me know if it wrks for you

**Comment by IGNATIUSLIJO** [comment]
ya it is working fine. Thanks for your support. I have a doubt regarding real time data display on chart 

https://github.com/beto-rodriguez/Live-Charts/issues/47

in the above link you have given one sample prgm for real time data display. But the link is expired can you post that again.
Thanks alot for your inputs .

**Comment by beto-rodriguez** [comment]
That link does not exist any more, MVVM pie is not currenctly build because of major changes in previous versions, PieChart.Series works exactly as all series in any chart, so any other example could guide you. I recommend you to see spexially theese ones:

the last 3 ones included in wiki

https://github.com/beto-rodriguez/Live-Charts/wiki/91-Live-Data
https://github.com/beto-rodriguez/Live-Charts/wiki/92-Filtered-Data
https://github.com/beto-rodriguez/Live-Charts/wiki/93-IObservableChartPoint

but for now as you can see in #49 animations needs a complete redraw, so even it will work it is not the expected behavior, I am working on it as you can see that issue is in progess I hope today I can update all series t suppor this

**Comment by IGNATIUSLIJO** [comment]
thanks for sharing  example. I have one more doubt on that.Is it possible to change pie chart colour depends upon real time data.

I tried below syntax 

` SolidColorBrush pink = (SolidColorBrush)(new BrushConverter().ConvertFrom("#F630A3"));
  SolidColorBrush shade = (SolidColorBrush)(new BrushConverter().ConvertFrom("#E6E6E6"));
  pieseries1 = new SeriesCollection(config);
   pieseries1.Add(new PieSeries
            {
                Values = new ChartValues<StoreViewModel>
                {
                    new StoreViewModel {Income = 29},
                    new StoreViewModel {Income = 35},
                },
                Brushes = new ChartValues<StoreColorModel>
                {
                    new StoreColorModel {Clr = pink},
                    new StoreColorModel {Clr = shade},
                },
            }
               );
`
`  public class StoreColorModel : IObservableChartPoint
    {
        private SolidColorBrush _clr;
        public SolidColorBrush Clr
        {
            get { return _clr; }
            set
            {
                _clr = value;
                if (ValueChanged != null) ValueChanged.Invoke();
            }
        }
        public event Action ValueChanged;
    }`


Kindly guide me

**Comment by beto-rodriguez** [comment]
I will try to update with an example, but right now I am really bussy with #49 I will as soon as possible and let you know

**Comment by IGNATIUSLIJO** [comment]
thanks for the quick reply .. :+1:

**Comment by IGNATIUSLIJO** [comment]
when can you post the example . Thanks in advance .

**Comment by beto-rodriguez** [comment]
@IGNATIUSLIJO I have been really bussy with #49, I will when 0.6.5 is realeased, it was a really hard issue. thank for your patience

**Comment by beto-rodriguez** [comment]
@IGNATIUSLIJO for now you can call Chart.Update everytime you change your colors set.

**Comment by IGNATIUSLIJO** [comment]
thanks @beto-rodriguez  for kind reply :+1:

**Comment by IGNATIUSLIJO** [comment]
kindly respond if have time .. my scenario is button click has to change my piechart series colour i used below code it is not working

            `pieseries1[0].Fill = (SolidColorBrush)(new BrushConverter().ConvertFrom("#29C2C0"));
            ch.Redraw();`

(I am not able to access brush)

**Comment by beto-rodriguez** [comment]
instead set a colors set in PieSeries.Brushes Property then change the desired color, for now it wont update unless you call ch.Redraw, I will fix that in a next release.

**Comment by beto-rodriguez** [comment]
@IGNATIUSLIJO Now with 0.6.5 it should be much easier, since PieChart now uses a different and easier logic, you can bind the fill property now and should update as any other wpf element.

http://lvcharts.net/#/examples/v1/series-colors-wpf?path=WPF-Components-Series
