### ISSUE TITLE
Smarter Zoom

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#9]
Zooming works well, but it always zooms according to 0,0 chart point, it would be more user friendly if we move on X and Y according to user position on chart.

**Comment by lrmills85** [comment]
I agree with this. Thanks!

**Comment by gregsdennis** [comment]
In my experience, the best zoom was implemented in SolidWorks.  It would zoom in to the mouse cursor, but out from the center.  Other implementations (like in & out from cursor) seems clunky after working with SolidWorks.

**Comment by beto-rodriguez** [comment]
Now zoom follows your mose position, should display data much better, and works better for High performance algoriths, Also you can customize which axis to zoom, Changed Chart.Zooming (bool) property to ZoomingAxis (value is a enum X, Y or None).

**Comment by gregsdennis** [comment]
Questions:

- Does the "zoom out" zoom from center?
- Why is the default `X`?  Shouldn't it be `X | Y`?  (This would imply that the enum needs to be a flags enum or offer a `Both` option.)

**Comment by beto-rodriguez** [comment]
> Does the "zoom out" zoom from center? 

Yes, why? actually there is no a clear why, but I find it useful because you have a clear view when you zoom out.

> Why is the default X? Shouldn't it be X | Y? (This would imply that the enum needs to be a flags enum or offer a Both option.)

This is actually really interesting, as I said data displays much better now when zooming, what it does now, for example if ZoomingAxis = X, then it will crop the data and display "a new chart" only containing the zoomed data, similar too HighCharts http://www.highcharts.com/demo/line-time-series, the Zooming Y property will be used when you invert axis in a chart for example, or when we implement row charts (inverted bar charts)

**Comment by gregsdennis** [comment]
Good.  That implementation always made more sense once you've worked with it.

So it sounds like we'll always have a zoom level that respects the aspect ratio of the graph add it was originally laid out.  Is that correct?  If so, why split to an X/Y? Seems like the zoom is with respect to the primary data, regardless of whether the plot is inverted?  The `bool` should be sufficient.

**Comment by beto-rodriguez** [comment]
> it sounds like we'll always have a zoom level that respects the aspect ratio of the graph add it was originally laid out. Is that correct

No, I will try to explain with a simple diagram

![untitled](https://cloud.githubusercontent.com/assets/10853349/12569063/0ab5f7b6-c391-11e5-9996-1a7ddca9e822.png)

**Comment by gregsdennis** [comment]
What I'm talking about is that the x/y ratio is the same.  So using the example on the left, the slope (angle) from (1,2) to (2,5) will remain the same regardless of zoom level.  If that's the case, x and y are zooming together (by the same factor), and there's no reason to distinguish between them.  Otherwise, the graph will distort as you zoom in.

**Comment by beto-rodriguez** [comment]
The slope will be totally diferent, and this is totaly intentional to display data as big as possible, here is again the diagram, notice how orange line redices its distance dratically, this will of course change the slope of both line

![untitled](https://cloud.githubusercontent.com/assets/10853349/12569268/cd3de57c-c392-11e5-81cd-a0dd08f6f5c4.png)

**Comment by gregsdennis** [comment]
That's going to feel weird when zooming in with the mouse wheel, where you have incremental and successive zooms.

If I zoom in on an area, I want to see a portion of the same graph in finer detail, not a new graph.

Perhaps an alternate way to do this is by taking advantage of render transform combined with render masks.

**Comment by gregsdennis** [comment]
Maybe it can simply be another zooming mode...

**Comment by beto-rodriguez** [comment]
I really don´t know what to say, this method has really good benefits for example:

it will allow us to have millions of points in a chart and zoom in/out, for example http://www.highcharts.com/demo/line-time-series it has a high number fo points and you can easly see them all, for all kind of charts, imagine to have 10 years of data in a bar chart, when you zoom in you can then see how bars range change from year to moth or from month to day, according to zoom.

 > If I zoom in on an area, I want to see a portion of the same graph in finer detail, not a new graph.

this is exactly what it does, but it is not just a finer detail, it is a high definition detail, optimized to zoom as much as possible.

 > Perhaps an alternate way to do this is by taking advantage of render transform combined with render masks.

the old method worked something similar, and I got to say that it was good for low amounths of data, but I was mocking you, you were never seeing a finer detail of the data, I was just making it bigger, now with this method we are able to draw high quality charts, actually the new high performance algorithms that I am working with have a property to set the quality (low, medium, high, highest).

 > Maybe it can simply be another zooming mode...

this actually seems really good, to have both options, this option for charts where precision is really important, and you dont only want to see an aproximation, for example an exchange rate chart http://www.highcharts.com/demo/line-time-series and another zooming type where you only need to make a bigger draw, similar to the old method.

What do you think?

**Comment by gregsdennis** [comment]
Let me play with what you have before you go on a coding frenzy. :)

**Comment by beto-rodriguez** [comment]
I think I get your point, this library right now seems much harder than how it was in early versions, and it is, but just for a moment, right now you can configure a lot of things, and that is awesome as I said before 0.6 is much more scalable, but be patient I am working solving all the new issues, I am working with this "hard setup" to make it easy for users.

**Comment by gregsdennis** [comment]
Totally understand.

**Comment by beto-rodriguez** [comment]
just for the record, I dropped down 

> Changed Chart.Zooming (bool) property to ZoomingAxis (value is a enum X, Y or None, default is X).

for simplicity charts will only have a boolean Zoom property as it was before, and LiveCharts will internally decide if zoom on X or Y

**Comment by beto-rodriguez** [comment]
Now, I am testing HighPerformance charts, and this zooming mode could be better as you said @gregsdennis, I am testing and working on it, HighPerformance example is not available for everyone yet, since it depend on a new package LiveCharts.Optimizations that is not in Nuget yet

**Comment by beto-rodriguez** [comment]
I improved zooming, it is a combination of both methods, you can configure x, y or xy, will build an example when next patch is ready, now you dont get lost while zooming like with the old method
