### ISSUE TITLE
Live changes failing sometimes (not sure when already)

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#91]
![undolvedbug](https://cloud.githubusercontent.com/assets/10853349/13210819/94497bca-d8f8-11e5-9646-6ec8e317e4ec.gif)

I hope any of you using 0.6.5 or greater can identify exactly when this happens, so it can be fixed.

if you have been using this library in the last months you will notice how 0.6.5 is a big release, the logic of all series changed, they have better and natural animations, here are some gifs of the new version:

**Comment by beto-rodriguez** [comment]
To help tracking this bug, it also happens sometimes when resizing the chart.

![bug](https://cloud.githubusercontent.com/assets/10853349/14160965/329be256-f69d-11e5-89e0-a6512ff534f0.gif)

**Comment by beto-rodriguez** [comment]
This should happen when you remove a point and add points when the chart is being animated, because the animation is async, the position of the point is messing up....

I keep investigating.

**Comment by beto-rodriguez** [comment]
This was fixed with many commits, now there is a much cleaner algorithm, and this does not happens anymore

**Comment by TwoPintMatty** [comment]
Hi Beto, do you have the source code for this graph? It runs very smoothly and I am trying to get mine to do the same.

Thank you
