### ISSUE TITLE
Unknown point (Double.Nan) and line charts fails when you change a point from double.nan to double

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#92]
As title says double.nan is supported for line charts, it means an unknown point, but if you change the value it could not display correctly. this explains the issue better: (this bug is for 0.6.5, not released yet, just wating for some issues with hosting company)
![doublenanbug](https://cloud.githubusercontent.com/assets/10853349/13238592/cd2bf7aa-d999-11e5-983d-fdb00b7c2c4c.gif)

**Comment by beto-rodriguez** [comment]
double.nan is making `LineSeries` kind of messy, I think the best solution to keep `LineSeries` is to create a double.nan wrapper class it will just take some `ChartValues` and return as many `LineSeries` as requiered, I mean one LineSeries per division generated by a double.nan

**Comment by gregsdennis** [comment]
Would it be possible to devise a few behaviors for when this happens and let the client decide?  It seems like the responsibility to verify the data is valid.  Even so, the library should handle when the data is invalid in some expected way.

**Comment by beto-rodriguez** [comment]
@gregsdennis when you were working this code, there were some double.nan bugs that you and I were not really sure when it happend, and then you implemented `EnsureDouble()` I think I already fixed those double.nan generated by livecharts, when I added unit testring project I could identify when this unexpected Nans where created and I fixed that, actually I deleted your method and everything runs fine now, I ment double.nan values that you as a user need, for example when you don´t know the value of a point you could say that to livecharts and pass a double.nan value (means no data) and chart wont plot anything in that point.

I wish new website was here :( this library has too many new features now that are hard to document on github.

**Comment by gregsdennis** [comment]
Okay, that seems like a good feature.  I'd be careful about introducing new complexity.  You've done a good job of making the library simple so far.

**Comment by beto-rodriguez** [comment]
I will concider what you say, I will let this open and won't fix this untill I have a really solid and easy idea, thanks again for your help
