### ISSUE TITLE
Is it possible to set a max. Chartpoint Count ?

### ISSUE THREAD

**Issue by dastom** [beto-rodriguez/Live-Charts#93]
If gather very large amounts of data and only want to show the last 50 entries in an Live Chart.

Is there any possibility to set a max Count. I already tried to remove the Point out of the binded Collection but it seems as if the Chart only finds the new entries but didn`t remove the deleted ones.

**Comment by beto-rodriguez** [comment]
There is the axis.max and axis.min properties
http://lvcharts.net/#/documentation/0.6.5/axis?search=max
http://lvcharts.net/#/documentation/0.6.5/axis?search=min

You can move this properties according to your needs, please let me know if this solves your issue

**Comment by beto-rodriguez** [comment]
A chart will only plot all the points inside min-max range according to an axis

**Comment by dastom** [comment]
My Problem is not the max Value, it is the max Count :)

I want to Show only the last 50 entries in an Line Chart. Perhabs i can also do this with the maxValue Property but i don`t get how to do this.

**Comment by beto-rodriguez** [comment]
I don't understand what you mean with Max count,  I mean let say you have 150 points, if you use min 0 and Max 50 the you are showing only the first 50, min 50 max 100 second 50, min 100 max 150 will show the last 50

**Comment by dastom** [comment]
I am collecting pings values. Every few seconds i add one ping result to the Collection that*s binded to the Chart.
I only want to show the last 50 results in the Chart. With the Axis.MaxValue i can Show only results above or under a specific value. But the value is equal for me. I only want to show the last results.

So for example. I have an ping result that has an value of 50ms. If i set the axis.maxvalue to 50 it doesn`t Show the result in the Chart. But that isn`t what i am looking for. I want to Show only the last 50 results/ entries i got.

**Comment by beto-rodriguez** [comment]
I see, now I can help you better, you have a few options I think the easier one is to remove the first  point if you are already showing 50 pts 

`if(series.Values.Count > 50 ) series.Values.RemoveAt(0);`

You could also use linq `Skip()` and `Take()` to get only the last 50 pts, but with the info you gave me I am not able to build an example

This should solve your issue, please let me know if it doesnt.
